import type { Question } from '@/types'

// ─────────────────────────────────────────────────────────────────────────────
// Seed question bank — aligned to the Australian Curriculum v9.0
// Expand each array as content grows. Questions are seeded into Supabase
// via /supabase/seed.sql or the admin panel.
// ─────────────────────────────────────────────────────────────────────────────

export const QUESTION_BANK: Omit<Question, 'id' | 'created_at'>[] = [

  // ── NUMBER & OPERATIONS — Grade 3–4 ─────────────────────────────────────

  {
    topic: 'number_operations',
    year_level: 'grade_3',
    difficulty: 'foundation',
    question_text: 'What is 47 + 36?',
    options: ['73', '83', '81', '93'],
    correct_index: 1,
    explanation: 'Add the ones: 7 + 6 = 13. Write 3, carry 1. Add the tens: 4 + 3 + 1 = 8. Answer: 83.',
    curriculum_code: 'AC9M3N04',
  },
  {
    topic: 'number_operations',
    year_level: 'grade_4',
    difficulty: 'developing',
    question_text: 'What is 248 + 375?',
    options: ['613', '623', '533', '600'],
    correct_index: 1,
    explanation: 'Adding column by column: ones 8+5=13 (carry 1), tens 4+7+1=12 (carry 1), hundreds 2+3+1=6. Answer: 623.',
    curriculum_code: 'AC9M4N04',
  },
  {
    topic: 'number_operations',
    year_level: 'grade_5',
    difficulty: 'developing',
    question_text: 'Calculate 15 × 24',
    options: ['340', '360', '380', '350'],
    correct_index: 1,
    explanation: '15 × 24 = 15 × 20 + 15 × 4 = 300 + 60 = 360.',
    curriculum_code: 'AC9M5N04',
  },
  {
    topic: 'number_operations',
    year_level: 'grade_6',
    difficulty: 'developing',
    question_text: 'What is ¾ + ½?',
    options: ['1', '1¼', '1½', '¾'],
    correct_index: 1,
    explanation: 'Convert to common denominator: ¾ + 2⁄4 = 5⁄4 = 1¼.',
    curriculum_code: 'AC9M6N04',
  },
  {
    topic: 'number_operations',
    year_level: 'grade_6',
    difficulty: 'proficient',
    question_text: 'What is 20% of 450?',
    options: ['80', '90', '100', '85'],
    correct_index: 1,
    explanation: '20% = 20/100 = 1/5. 450 ÷ 5 = 90.',
    curriculum_code: 'AC9M6N05',
  },
  {
    topic: 'number_operations',
    year_level: 'year_7',
    difficulty: 'developing',
    question_text: 'Express 0.35 as a fraction in simplest form',
    options: ['3/5', '7/20', '35/100', '7/10'],
    correct_index: 1,
    explanation: '0.35 = 35/100. Simplify by dividing by 5: 7/20.',
    curriculum_code: 'AC9M7N03',
  },
  {
    topic: 'number_operations',
    year_level: 'year_8',
    difficulty: 'proficient',
    question_text: 'Calculate: −3 × (−4) + 2',
    options: ['10', '14', '−10', '−14'],
    correct_index: 1,
    explanation: '−3 × −4 = +12. Then 12 + 2 = 14.',
    curriculum_code: 'AC9M8N03',
  },

  // ── ALGEBRA & FUNCTIONS — Year 7–10 ──────────────────────────────────────

  {
    topic: 'algebra_functions',
    year_level: 'year_7',
    difficulty: 'foundation',
    question_text: 'Solve: x + 7 = 15',
    options: ['x = 7', 'x = 8', 'x = 9', 'x = 22'],
    correct_index: 1,
    explanation: 'Subtract 7 from both sides: x = 15 − 7 = 8.',
    curriculum_code: 'AC9M7A02',
  },
  {
    topic: 'algebra_functions',
    year_level: 'year_7',
    difficulty: 'developing',
    question_text: 'What is the next term in the sequence: 3, 7, 11, 15, ___?',
    options: ['17', '18', '19', '20'],
    correct_index: 2,
    explanation: 'The common difference is +4. 15 + 4 = 19.',
    curriculum_code: 'AC9M7A01',
  },
  {
    topic: 'algebra_functions',
    year_level: 'year_8',
    difficulty: 'developing',
    question_text: 'Simplify: 4x + 3x − 2x',
    options: ['5x', '9x', '7x', 'x'],
    correct_index: 0,
    explanation: 'Collect like terms: (4 + 3 − 2)x = 5x.',
    curriculum_code: 'AC9M8A01',
  },
  {
    topic: 'algebra_functions',
    year_level: 'year_9',
    difficulty: 'proficient',
    question_text: 'Factorise: x² − 9',
    options: ['(x+3)(x+3)', '(x−3)(x+3)', '(x−9)(x+1)', '(x+9)(x−1)'],
    correct_index: 1,
    explanation: 'Difference of two squares: a² − b² = (a−b)(a+b). So x² − 9 = (x−3)(x+3).',
    curriculum_code: 'AC9M9A01',
  },
  {
    topic: 'algebra_functions',
    year_level: 'year_10',
    difficulty: 'proficient',
    question_text: 'If f(x) = 2x² − 3, what is f(−2)?',
    options: ['5', '−11', '−5', '11'],
    correct_index: 0,
    explanation: 'f(−2) = 2(−2)² − 3 = 2(4) − 3 = 8 − 3 = 5.',
    curriculum_code: 'AC9M10A02',
  },

  // ── GEOMETRY & MEASUREMENT — Grade 4–Year 9 ──────────────────────────────

  {
    topic: 'geometry_measurement',
    year_level: 'grade_4',
    difficulty: 'foundation',
    question_text: 'What is the perimeter of a square with side length 7 cm?',
    options: ['14 cm', '21 cm', '28 cm', '49 cm'],
    correct_index: 2,
    explanation: 'Perimeter of a square = 4 × side = 4 × 7 = 28 cm.',
    curriculum_code: 'AC9M4M02',
  },
  {
    topic: 'geometry_measurement',
    year_level: 'grade_5',
    difficulty: 'developing',
    question_text: 'Area of a rectangle: length 8 cm, width 5 cm',
    options: ['26 cm²', '40 cm²', '13 cm²', '45 cm²'],
    correct_index: 1,
    explanation: 'Area = length × width = 8 × 5 = 40 cm².',
    curriculum_code: 'AC9M5M02',
  },
  {
    topic: 'geometry_measurement',
    year_level: 'grade_6',
    difficulty: 'proficient',
    question_text: 'Volume of a cube with side length 4 cm?',
    options: ['16 cm³', '48 cm³', '64 cm³', '12 cm³'],
    correct_index: 2,
    explanation: 'Volume of a cube = side³ = 4³ = 64 cm³.',
    curriculum_code: 'AC9M6M02',
  },
  {
    topic: 'geometry_measurement',
    year_level: 'year_7',
    difficulty: 'developing',
    question_text: 'Area of a circle with radius 5 cm? (use π ≈ 3.14)',
    options: ['78.5 cm²', '31.4 cm²', '15.7 cm²', '157 cm²'],
    correct_index: 0,
    explanation: 'A = πr² = 3.14 × 5² = 3.14 × 25 = 78.5 cm².',
    curriculum_code: 'AC9M7M02',
  },
  {
    topic: 'geometry_measurement',
    year_level: 'year_9',
    difficulty: 'proficient',
    question_text: 'In a right triangle, legs are 6 cm and 8 cm. What is the hypotenuse?',
    options: ['10 cm', '12 cm', '14 cm', '7 cm'],
    correct_index: 0,
    explanation: 'Pythagoras: c² = 6² + 8² = 36 + 64 = 100. c = √100 = 10 cm.',
    curriculum_code: 'AC9M9M03',
  },

  // ── STATISTICS & PROBABILITY — Grade 4–Year 10 ───────────────────────────

  {
    topic: 'statistics_probability',
    year_level: 'grade_4',
    difficulty: 'foundation',
    question_text: 'What is the mode of: 2, 4, 4, 5, 6, 4, 7?',
    options: ['2', '4', '5', '6'],
    correct_index: 1,
    explanation: 'The mode is the most frequent value. 4 appears 3 times.',
    curriculum_code: 'AC9M4ST01',
  },
  {
    topic: 'statistics_probability',
    year_level: 'grade_5',
    difficulty: 'developing',
    question_text: 'Mean of: 4, 7, 9, 10, 5',
    options: ['6', '7', '8', '9'],
    correct_index: 1,
    explanation: 'Sum = 4+7+9+10+5 = 35. Mean = 35 ÷ 5 = 7.',
    curriculum_code: 'AC9M5ST01',
  },
  {
    topic: 'statistics_probability',
    year_level: 'grade_6',
    difficulty: 'developing',
    question_text: 'Median of: 3, 5, 7, 9, 11',
    options: ['5', '7', '9', '6'],
    correct_index: 1,
    explanation: 'Data is already ordered. Middle value (3rd of 5) = 7.',
    curriculum_code: 'AC9M6ST01',
  },
  {
    topic: 'statistics_probability',
    year_level: 'year_7',
    difficulty: 'developing',
    question_text: 'What is the probability of rolling a 6 on a fair die?',
    options: ['1/3', '1/4', '1/6', '1/2'],
    correct_index: 2,
    explanation: 'There are 6 equally likely outcomes. P(6) = 1/6.',
    curriculum_code: 'AC9M7P01',
  },
  {
    topic: 'statistics_probability',
    year_level: 'year_8',
    difficulty: 'proficient',
    question_text: 'Range of: 12, 7, 19, 3, 15',
    options: ['12', '16', '7', '19'],
    correct_index: 1,
    explanation: 'Range = max − min = 19 − 3 = 16.',
    curriculum_code: 'AC9M8ST01',
  },

  // ── READING COMPREHENSION — Grade 3–Year 9 ───────────────────────────────

  {
    topic: 'reading_comprehension',
    year_level: 'grade_3',
    difficulty: 'foundation',
    question_text: "Read: \"Tom packed his bag and ran to catch the bus. He was late for school.\" Why did Tom run?",
    options: ['He wanted exercise', 'He was late for school', 'He lost his bag', 'He missed the bus'],
    correct_index: 1,
    explanation: "The passage says Tom 'was late for school,' which is why he ran to catch the bus.",
    curriculum_code: 'AC9E3LY06',
  },
  {
    topic: 'reading_comprehension',
    year_level: 'grade_5',
    difficulty: 'developing',
    question_text: "Read: \"Although it was raining, Maya decided to go for a walk because she loved the smell of wet earth.\" What is Maya's motivation for going outside?",
    options: ['She had to walk the dog', 'She loved the smell of rain', 'She was late', 'She wanted to get wet'],
    correct_index: 1,
    explanation: "The word 'because' signals her reason: she loved the smell of wet earth.",
    curriculum_code: 'AC9E5LY07',
  },
  {
    topic: 'reading_comprehension',
    year_level: 'grade_6',
    difficulty: 'developing',
    question_text: 'In a story, a character who changes and grows over time is called a:',
    options: ['Static character', 'Dynamic character', 'Narrator', 'Antagonist'],
    correct_index: 1,
    explanation: 'A dynamic character undergoes meaningful internal change during the story.',
    curriculum_code: 'AC9E6LE07',
  },
  {
    topic: 'reading_comprehension',
    year_level: 'year_7',
    difficulty: 'proficient',
    question_text: "Read: \"The old bridge groaned under the weight of the truck, its timbers creaking like tired bones.\" This sentence mainly uses which literary device?",
    options: ['Simile', 'Metaphor', 'Onomatopoeia', 'Hyperbole'],
    correct_index: 0,
    explanation: "'Creaking like tired bones' compares the bridge's sound to bones using 'like' — a simile.",
    curriculum_code: 'AC9E7LE05',
  },
  {
    topic: 'reading_comprehension',
    year_level: 'year_9',
    difficulty: 'advanced',
    question_text: 'An author who writes with a critical or mocking tone about the flaws of society is using:',
    options: ['Satire', 'Elegy', 'Parody', 'Soliloquy'],
    correct_index: 0,
    explanation: "Satire uses irony, humour, and exaggeration to criticise society's flaws.",
    curriculum_code: 'AC9E9LE04',
  },

  // ── GRAMMAR & PUNCTUATION — Grade 3–Year 8 ───────────────────────────────

  {
    topic: 'grammar_punctuation',
    year_level: 'grade_3',
    difficulty: 'foundation',
    question_text: 'Which sentence uses the correct punctuation?',
    options: ['Where is my hat', 'Where is my hat.', 'Where is my hat?', 'where is my hat?'],
    correct_index: 2,
    explanation: 'Questions must end with a question mark and start with a capital letter.',
    curriculum_code: 'AC9E3LA05',
  },
  {
    topic: 'grammar_punctuation',
    year_level: 'grade_4',
    difficulty: 'developing',
    question_text: 'Choose the correctly punctuated sentence.',
    options: ['Its a sunny day.', "It's a sunny day.", "Its' a sunny day.", 'Its a sunny day'],
    correct_index: 1,
    explanation: "'It's' is the contraction of 'it is'. 'Its' (no apostrophe) shows possession.",
    curriculum_code: 'AC9E4LA06',
  },
  {
    topic: 'grammar_punctuation',
    year_level: 'grade_6',
    difficulty: 'proficient',
    question_text: 'Identify the sentence with correct subject-verb agreement.',
    options: ['The team are winning.', 'The team is winning.', 'The team am winning.', 'The team be winning.'],
    correct_index: 1,
    explanation: "'Team' is a collective noun treated as singular in Australian English, so it takes 'is'.",
    curriculum_code: 'AC9E6LA07',
  },
  {
    topic: 'grammar_punctuation',
    year_level: 'year_7',
    difficulty: 'developing',
    question_text: "Which word correctly completes: 'Neither the students nor the teacher ___ ready.'",
    options: ['was', 'were', 'is', 'are'],
    correct_index: 0,
    explanation: "With 'neither/nor', the verb agrees with the nearer subject — 'teacher' (singular), so 'was'.",
    curriculum_code: 'AC9E7LA05',
  },
  {
    topic: 'grammar_punctuation',
    year_level: 'year_8',
    difficulty: 'proficient',
    question_text: 'Which sentence correctly uses a semicolon?',
    options: ['I like tea; however, I prefer coffee.', 'I like tea, however I prefer coffee.', 'I like tea; and coffee.', 'I like tea however; I prefer coffee.'],
    correct_index: 0,
    explanation: "A semicolon can join two related independent clauses, often before a conjunctive adverb like 'however'.",
    curriculum_code: 'AC9E8LA06',
  },

  // ── VOCABULARY — Grade 3–Year 9 ──────────────────────────────────────────

  {
    topic: 'vocabulary',
    year_level: 'grade_3',
    difficulty: 'foundation',
    question_text: "Which word means the same as 'happy'?",
    options: ['Glad', 'Sad', 'Angry', 'Tired'],
    correct_index: 0,
    explanation: "'Glad' is a synonym for 'happy' — both describe feeling pleased.",
    curriculum_code: 'AC9E3LA09',
  },
  {
    topic: 'vocabulary',
    year_level: 'grade_5',
    difficulty: 'developing',
    question_text: "What is the antonym (opposite) of 'generous'?",
    options: ['Kind', 'Selfish', 'Wealthy', 'Helpful'],
    correct_index: 1,
    explanation: "'Selfish' means the opposite of 'generous', which means willing to give.",
    curriculum_code: 'AC9E5LA10',
  },
  {
    topic: 'vocabulary',
    year_level: 'grade_6',
    difficulty: 'developing',
    question_text: "The prefix 'un-' in the word 'unhappy' means:",
    options: ['Very', 'Again', 'Not', 'Before'],
    correct_index: 2,
    explanation: "The prefix 'un-' means 'not', so 'unhappy' means 'not happy'.",
    curriculum_code: 'AC9E6LA09',
  },
  {
    topic: 'vocabulary',
    year_level: 'year_7',
    difficulty: 'proficient',
    question_text: "Which word best fits: 'The detective's ___ observation solved the case.'",
    options: ['meticulous', 'careless', 'hasty', 'vague'],
    correct_index: 0,
    explanation: "'Meticulous' means very careful and precise, fitting a detective solving a case.",
    curriculum_code: 'AC9E7LA10',
  },
  {
    topic: 'vocabulary',
    year_level: 'year_9',
    difficulty: 'advanced',
    question_text: "'Ubiquitous' most nearly means:",
    options: ['Rare', 'Present everywhere', 'Ancient', 'Loud'],
    correct_index: 1,
    explanation: "'Ubiquitous' describes something found everywhere or very common.",
    curriculum_code: 'AC9E9LA08',
  },

  // ── LIFE SCIENCE — Grade 3–Year 9 ────────────────────────────────────────

  {
    topic: 'life_science',
    year_level: 'grade_3',
    difficulty: 'foundation',
    question_text: 'Which of these is a living thing?',
    options: ['Rock', 'Tree', 'Chair', 'Cloud'],
    correct_index: 1,
    explanation: 'Living things grow, reproduce, and need energy — a tree is alive; rocks, chairs and clouds are not.',
    curriculum_code: 'AC9S3U01',
  },
  {
    topic: 'life_science',
    year_level: 'grade_5',
    difficulty: 'developing',
    question_text: "What is the main function of a plant's roots?",
    options: ['Make food using sunlight', 'Absorb water and nutrients', 'Produce seeds', 'Release oxygen'],
    correct_index: 1,
    explanation: 'Roots anchor the plant and absorb water and nutrients from the soil.',
    curriculum_code: 'AC9S5U01',
  },
  {
    topic: 'life_science',
    year_level: 'grade_6',
    difficulty: 'developing',
    question_text: 'Which organ pumps blood around the human body?',
    options: ['Lungs', 'Liver', 'Heart', 'Stomach'],
    correct_index: 2,
    explanation: 'The heart is a muscular organ that pumps blood through the circulatory system.',
    curriculum_code: 'AC9S6U02',
  },
  {
    topic: 'life_science',
    year_level: 'year_7',
    difficulty: 'proficient',
    question_text: 'In a food chain, what is the primary role of a producer?',
    options: ['Eats other animals', 'Makes its own food using sunlight', 'Decomposes dead matter', 'Hunts prey'],
    correct_index: 1,
    explanation: 'Producers, like plants, make their own food through photosynthesis.',
    curriculum_code: 'AC9S7U03',
  },
  {
    topic: 'life_science',
    year_level: 'year_9',
    difficulty: 'advanced',
    question_text: 'Which process allows cells to divide and produce two genetically identical daughter cells?',
    options: ['Meiosis', 'Mitosis', 'Fertilisation', 'Osmosis'],
    correct_index: 1,
    explanation: 'Mitosis produces two genetically identical daughter cells for growth and repair.',
    curriculum_code: 'AC9S9U03',
  },

  // ── PHYSICAL SCIENCE — Grade 4–Year 10 ───────────────────────────────────

  {
    topic: 'physical_science',
    year_level: 'grade_4',
    difficulty: 'foundation',
    question_text: 'What happens to water when it is heated to boiling point?',
    options: ['It freezes', 'It turns into gas', 'It turns into rock', 'It disappears forever'],
    correct_index: 1,
    explanation: 'At boiling point, water changes from a liquid to a gas (water vapour).',
    curriculum_code: 'AC9S4U01',
  },
  {
    topic: 'physical_science',
    year_level: 'grade_6',
    difficulty: 'developing',
    question_text: 'Which of these is a force that slows down moving objects?',
    options: ['Gravity', 'Friction', 'Magnetism', 'Light'],
    correct_index: 1,
    explanation: 'Friction acts opposite to motion between surfaces, slowing objects down.',
    curriculum_code: 'AC9S6U01',
  },
  {
    topic: 'physical_science',
    year_level: 'year_7',
    difficulty: 'developing',
    question_text: 'What is the unit used to measure electric current?',
    options: ['Volt', 'Watt', 'Ampere', 'Ohm'],
    correct_index: 2,
    explanation: 'Electric current is measured in amperes (amps), symbol A.',
    curriculum_code: 'AC9S7U01',
  },
  {
    topic: 'physical_science',
    year_level: 'year_8',
    difficulty: 'proficient',
    question_text: 'Which state of matter has a fixed volume but no fixed shape?',
    options: ['Solid', 'Liquid', 'Gas', 'Plasma'],
    correct_index: 1,
    explanation: 'A liquid takes the shape of its container but keeps a fixed volume.',
    curriculum_code: 'AC9S8U01',
  },
  {
    topic: 'physical_science',
    year_level: 'year_10',
    difficulty: 'advanced',
    question_text: "According to Newton's second law, force equals:",
    options: ['mass ÷ acceleration', 'mass × acceleration', 'mass + acceleration', 'acceleration ÷ mass'],
    correct_index: 1,
    explanation: "Newton's second law states F = m × a (force equals mass times acceleration).",
    curriculum_code: 'AC9S10U03',
  },

  // ── EARTH & SPACE — Grade 3–Year 9 ───────────────────────────────────────

  {
    topic: 'earth_space',
    year_level: 'grade_3',
    difficulty: 'foundation',
    question_text: 'What causes day and night on Earth?',
    options: ['The Moon orbiting Earth', 'Earth spinning on its axis', 'The Sun moving around Earth', 'Clouds covering the Sun'],
    correct_index: 1,
    explanation: 'Earth rotates on its axis once every 24 hours, causing day and night.',
    curriculum_code: 'AC9S3U02',
  },
  {
    topic: 'earth_space',
    year_level: 'grade_5',
    difficulty: 'developing',
    question_text: 'Which layer of the Earth is the hottest?',
    options: ['Crust', 'Mantle', 'Outer core', 'Inner core'],
    correct_index: 3,
    explanation: "The inner core is the hottest layer, reaching temperatures similar to the Sun's surface.",
    curriculum_code: 'AC9S5U02',
  },
  {
    topic: 'earth_space',
    year_level: 'grade_6',
    difficulty: 'developing',
    question_text: 'What is the main cause of the seasons on Earth?',
    options: ['Distance from the Sun changing a lot', "The tilt of Earth's axis", "The Moon's gravity", 'Ocean currents'],
    correct_index: 1,
    explanation: "Earth's axial tilt means different hemispheres receive more or less direct sunlight through the year, causing seasons.",
    curriculum_code: 'AC9S6U03',
  },
  {
    topic: 'earth_space',
    year_level: 'year_8',
    difficulty: 'proficient',
    question_text: 'Which type of rock forms from cooled magma or lava?',
    options: ['Sedimentary', 'Metamorphic', 'Igneous', 'Fossil'],
    correct_index: 2,
    explanation: 'Igneous rock forms when magma or lava cools and solidifies.',
    curriculum_code: 'AC9S8U02',
  },
  {
    topic: 'earth_space',
    year_level: 'year_9',
    difficulty: 'advanced',
    question_text: 'What is the primary evidence used to support the theory of plate tectonics?',
    options: ['Fossil records only', 'Matching coastlines, fossils, and rock strata across continents', 'Ocean temperature', 'Moon phases'],
    correct_index: 1,
    explanation: 'Matching coastlines, fossil distributions, and rock strata across continents provide strong evidence for plate tectonics.',
    curriculum_code: 'AC9S9U04',
  },
]
