import type { Question } from '@/types'

// ─────────────────────────────────────────────────────────────────────────────
// Seed question bank — aligned to the Australian Curriculum v9.0
// Expand each array as content grows. Questions are seeded into Supabase
// via /supabase/seed.sql or the admin panel.
// ─────────────────────────────────────────────────────────────────────────────

export const QUESTION_BANK: Omit<Question, 'created_at'>[] = [

  // ── NUMBER & OPERATIONS — Grade 3–4 ─────────────────────────────────────

  {
    id: 'c23dbf3e-78db-42f3-bd2b-03a47ef52aae',
    topic: 'number_operations',
    year_level: 'grade_3',
    difficulty: 'foundation',
    question_text: 'What is 47 + 36?',
    options: ['73', '83', '81', '93'],
    correct_index: 1,
    explanation: 'Add the ones: 7 + 6 = 13. Write 3, carry 1. Add the tens: 4 + 3 + 1 = 8. Answer: 83.',
    curriculum_code: 'AC9M3N04',
  },
  {
    id: '39e52f17-8622-49bc-b73a-5cdecc3668ae',
    topic: 'number_operations',
    year_level: 'grade_4',
    difficulty: 'developing',
    question_text: 'What is 248 + 375?',
    options: ['613', '623', '533', '600'],
    correct_index: 1,
    explanation: 'Adding column by column: ones 8+5=13 (carry 1), tens 4+7+1=12 (carry 1), hundreds 2+3+1=6. Answer: 623.',
    curriculum_code: 'AC9M4N04',
  },
  {
    id: '458f66e7-5d18-40f3-af46-16ff171e225f',
    topic: 'number_operations',
    year_level: 'grade_5',
    difficulty: 'developing',
    question_text: 'Calculate 15 × 24',
    options: ['340', '360', '380', '350'],
    correct_index: 1,
    explanation: '15 × 24 = 15 × 20 + 15 × 4 = 300 + 60 = 360.',
    curriculum_code: 'AC9M5N04',
  },
  {
    id: '6c56f7ea-0f72-407b-a5b7-6cf68fe4ce6c',
    topic: 'number_operations',
    year_level: 'grade_6',
    difficulty: 'developing',
    question_text: 'What is ¾ + ½?',
    options: ['1', '1¼', '1½', '¾'],
    correct_index: 1,
    explanation: 'Convert to common denominator: ¾ + 2⁄4 = 5⁄4 = 1¼.',
    curriculum_code: 'AC9M6N04',
  },
  {
    id: '96262ed4-eb11-4c6a-a91d-fe6a373063c9',
    topic: 'number_operations',
    year_level: 'grade_6',
    difficulty: 'proficient',
    question_text: 'What is 20% of 450?',
    options: ['80', '90', '100', '85'],
    correct_index: 1,
    explanation: '20% = 20/100 = 1/5. 450 ÷ 5 = 90.',
    curriculum_code: 'AC9M6N05',
  },
  {
    id: '617d183d-8898-4592-9695-72582b0109bb',
    topic: 'number_operations',
    year_level: 'year_7',
    difficulty: 'developing',
    question_text: 'Express 0.35 as a fraction in simplest form',
    options: ['3/5', '7/20', '35/100', '7/10'],
    correct_index: 1,
    explanation: '0.35 = 35/100. Simplify by dividing by 5: 7/20.',
    curriculum_code: 'AC9M7N03',
  },
  {
    id: 'ac08bd38-3a7d-4b96-b583-ff63e763bb9c',
    topic: 'number_operations',
    year_level: 'year_8',
    difficulty: 'proficient',
    question_text: 'Calculate: −3 × (−4) + 2',
    options: ['10', '14', '−10', '−14'],
    correct_index: 1,
    explanation: '−3 × −4 = +12. Then 12 + 2 = 14.',
    curriculum_code: 'AC9M8N03',
  },

  // ── ALGEBRA & FUNCTIONS — Year 7–10 ──────────────────────────────────────

  {
    id: '61a7eacb-c722-480d-92b1-edd7865d8250',
    topic: 'algebra_functions',
    year_level: 'year_7',
    difficulty: 'foundation',
    question_text: 'Solve: x + 7 = 15',
    options: ['x = 7', 'x = 8', 'x = 9', 'x = 22'],
    correct_index: 1,
    explanation: 'Subtract 7 from both sides: x = 15 − 7 = 8.',
    curriculum_code: 'AC9M7A02',
  },
  {
    id: '2d67f5a7-047c-4453-98f5-13a4a897d540',
    topic: 'algebra_functions',
    year_level: 'year_7',
    difficulty: 'developing',
    question_text: 'What is the next term in the sequence: 3, 7, 11, 15, ___?',
    options: ['17', '18', '19', '20'],
    correct_index: 2,
    explanation: 'The common difference is +4. 15 + 4 = 19.',
    curriculum_code: 'AC9M7A01',
  },
  {
    id: 'c8d6e78d-84e3-48e8-8778-634f0db174a4',
    topic: 'algebra_functions',
    year_level: 'year_8',
    difficulty: 'developing',
    question_text: 'Simplify: 4x + 3x − 2x',
    options: ['5x', '9x', '7x', 'x'],
    correct_index: 0,
    explanation: 'Collect like terms: (4 + 3 − 2)x = 5x.',
    curriculum_code: 'AC9M8A01',
  },
  {
    id: 'f21ff070-d3d8-4e69-b9d1-cc965b53e1ff',
    topic: 'algebra_functions',
    year_level: 'year_9',
    difficulty: 'proficient',
    question_text: 'Factorise: x² − 9',
    options: ['(x+3)(x+3)', '(x−3)(x+3)', '(x−9)(x+1)', '(x+9)(x−1)'],
    correct_index: 1,
    explanation: 'Difference of two squares: a² − b² = (a−b)(a+b). So x² − 9 = (x−3)(x+3).',
    curriculum_code: 'AC9M9A01',
  },
  {
    id: '98490cd9-b9c1-4b78-a692-4636eea71cbc',
    topic: 'algebra_functions',
    year_level: 'year_10',
    difficulty: 'proficient',
    question_text: 'If f(x) = 2x² − 3, what is f(−2)?',
    options: ['5', '−11', '−5', '11'],
    correct_index: 0,
    explanation: 'f(−2) = 2(−2)² − 3 = 2(4) − 3 = 8 − 3 = 5.',
    curriculum_code: 'AC9M10A02',
  },

  // ── GEOMETRY & MEASUREMENT — Grade 4–Year 9 ──────────────────────────────

  {
    id: 'a3227722-463c-4d3a-953e-dedf94ffa757',
    topic: 'geometry_measurement',
    year_level: 'grade_4',
    difficulty: 'foundation',
    question_text: 'What is the perimeter of a square with side length 7 cm?',
    options: ['14 cm', '21 cm', '28 cm', '49 cm'],
    correct_index: 2,
    explanation: 'Perimeter of a square = 4 × side = 4 × 7 = 28 cm.',
    curriculum_code: 'AC9M4M02',
  },
  {
    id: 'a3bcde8a-e33d-4304-9c05-59101e339834',
    topic: 'geometry_measurement',
    year_level: 'grade_5',
    difficulty: 'developing',
    question_text: 'Area of a rectangle: length 8 cm, width 5 cm',
    options: ['26 cm²', '40 cm²', '13 cm²', '45 cm²'],
    correct_index: 1,
    explanation: 'Area = length × width = 8 × 5 = 40 cm².',
    curriculum_code: 'AC9M5M02',
  },
  {
    id: 'bca5ead2-f1bb-40ef-a116-8b77635e58ab',
    topic: 'geometry_measurement',
    year_level: 'grade_6',
    difficulty: 'proficient',
    question_text: 'Volume of a cube with side length 4 cm?',
    options: ['16 cm³', '48 cm³', '64 cm³', '12 cm³'],
    correct_index: 2,
    explanation: 'Volume of a cube = side³ = 4³ = 64 cm³.',
    curriculum_code: 'AC9M6M02',
  },
  {
    id: 'fe66cdd3-5735-4593-893d-149840de519b',
    topic: 'geometry_measurement',
    year_level: 'year_7',
    difficulty: 'developing',
    question_text: 'Area of a circle with radius 5 cm? (use π ≈ 3.14)',
    options: ['78.5 cm²', '31.4 cm²', '15.7 cm²', '157 cm²'],
    correct_index: 0,
    explanation: 'A = πr² = 3.14 × 5² = 3.14 × 25 = 78.5 cm².',
    curriculum_code: 'AC9M7M02',
  },
  {
    id: '248a22df-0128-4c1b-ae8c-b6c48148eeba',
    topic: 'geometry_measurement',
    year_level: 'year_9',
    difficulty: 'proficient',
    question_text: 'In a right triangle, legs are 6 cm and 8 cm. What is the hypotenuse?',
    options: ['10 cm', '12 cm', '14 cm', '7 cm'],
    correct_index: 0,
    explanation: 'Pythagoras: c² = 6² + 8² = 36 + 64 = 100. c = √100 = 10 cm.',
    curriculum_code: 'AC9M9M03',
  },

  // ── STATISTICS & PROBABILITY — Grade 4–Year 10 ───────────────────────────

  {
    id: '7fe9cb1e-c2f8-4b27-a07d-159bc4219368',
    topic: 'statistics_probability',
    year_level: 'grade_4',
    difficulty: 'foundation',
    question_text: 'What is the mode of: 2, 4, 4, 5, 6, 4, 7?',
    options: ['2', '4', '5', '6'],
    correct_index: 1,
    explanation: 'The mode is the most frequent value. 4 appears 3 times.',
    curriculum_code: 'AC9M4ST01',
  },
  {
    id: 'c2bbbfe9-28fb-4857-861d-f5050375b792',
    topic: 'statistics_probability',
    year_level: 'grade_5',
    difficulty: 'developing',
    question_text: 'Mean of: 4, 7, 9, 10, 5',
    options: ['6', '7', '8', '9'],
    correct_index: 1,
    explanation: 'Sum = 4+7+9+10+5 = 35. Mean = 35 ÷ 5 = 7.',
    curriculum_code: 'AC9M5ST01',
  },
  {
    id: '0b6ec697-94fb-42c6-959f-6e7abc8cb892',
    topic: 'statistics_probability',
    year_level: 'grade_6',
    difficulty: 'developing',
    question_text: 'Median of: 3, 5, 7, 9, 11',
    options: ['5', '7', '9', '6'],
    correct_index: 1,
    explanation: 'Data is already ordered. Middle value (3rd of 5) = 7.',
    curriculum_code: 'AC9M6ST01',
  },
  {
    id: 'df773e2f-c2be-4735-bdef-ae4030e187a0',
    topic: 'statistics_probability',
    year_level: 'year_7',
    difficulty: 'developing',
    question_text: 'What is the probability of rolling a 6 on a fair die?',
    options: ['1/3', '1/4', '1/6', '1/2'],
    correct_index: 2,
    explanation: 'There are 6 equally likely outcomes. P(6) = 1/6.',
    curriculum_code: 'AC9M7P01',
  },
  {
    id: 'fb70f0b9-45af-44ca-a7d5-379f78d6917b',
    topic: 'statistics_probability',
    year_level: 'year_8',
    difficulty: 'proficient',
    question_text: 'Range of: 12, 7, 19, 3, 15',
    options: ['12', '16', '7', '19'],
    correct_index: 1,
    explanation: 'Range = max − min = 19 − 3 = 16.',
    curriculum_code: 'AC9M8ST01',
  },

  // ── READING COMPREHENSION — Grade 3–Year 9 ───────────────────────────────

  {
    id: '4c9c48fc-ba92-47c2-b8e7-d85eee10b828',
    topic: 'reading_comprehension',
    year_level: 'grade_3',
    difficulty: 'foundation',
    question_text: "Read: \"Tom packed his bag and ran to catch the bus. He was late for school.\" Why did Tom run?",
    options: ['He wanted exercise', 'He was late for school', 'He lost his bag', 'He missed the bus'],
    correct_index: 1,
    explanation: "The passage says Tom 'was late for school,' which is why he ran to catch the bus.",
    curriculum_code: 'AC9E3LY06',
  },
  {
    id: '88176768-82e6-40f6-a4b6-e2a8449adfe7',
    topic: 'reading_comprehension',
    year_level: 'grade_5',
    difficulty: 'developing',
    question_text: "Read: \"Although it was raining, Maya decided to go for a walk because she loved the smell of wet earth.\" What is Maya's motivation for going outside?",
    options: ['She had to walk the dog', 'She loved the smell of rain', 'She was late', 'She wanted to get wet'],
    correct_index: 1,
    explanation: "The word 'because' signals her reason: she loved the smell of wet earth.",
    curriculum_code: 'AC9E5LY07',
  },
  {
    id: 'f32db62e-cfd9-4ce9-a39e-0bf06cb95bc2',
    topic: 'reading_comprehension',
    year_level: 'grade_6',
    difficulty: 'developing',
    question_text: 'In a story, a character who changes and grows over time is called a:',
    options: ['Static character', 'Dynamic character', 'Narrator', 'Antagonist'],
    correct_index: 1,
    explanation: 'A dynamic character undergoes meaningful internal change during the story.',
    curriculum_code: 'AC9E6LE07',
  },
  {
    id: '57e7176d-1784-41e5-b934-b008fe956f1a',
    topic: 'reading_comprehension',
    year_level: 'year_7',
    difficulty: 'proficient',
    question_text: "Read: \"The old bridge groaned under the weight of the truck, its timbers creaking like tired bones.\" This sentence mainly uses which literary device?",
    options: ['Simile', 'Metaphor', 'Onomatopoeia', 'Hyperbole'],
    correct_index: 0,
    explanation: "'Creaking like tired bones' compares the bridge's sound to bones using 'like', which makes it a simile.",
    curriculum_code: 'AC9E7LE05',
  },
  {
    id: 'f8f0d371-501c-4e1e-8a34-ba7636d6558d',
    topic: 'reading_comprehension',
    year_level: 'year_9',
    difficulty: 'advanced',
    question_text: 'An author who writes with a critical or mocking tone about the flaws of society is using:',
    options: ['Satire', 'Elegy', 'Parody', 'Soliloquy'],
    correct_index: 0,
    explanation: "Satire uses irony, humour, and exaggeration to criticise society's flaws.",
    curriculum_code: 'AC9E9LE04',
  },

  // ── GRAMMAR & PUNCTUATION — Grade 3–Year 8 ───────────────────────────────

  {
    id: '13289b3d-55d7-4388-8289-12e944e75a28',
    topic: 'grammar_punctuation',
    year_level: 'grade_3',
    difficulty: 'foundation',
    question_text: 'Which sentence uses the correct punctuation?',
    options: ['Where is my hat', 'Where is my hat.', 'Where is my hat?', 'where is my hat?'],
    correct_index: 2,
    explanation: 'Questions must end with a question mark and start with a capital letter.',
    curriculum_code: 'AC9E3LA05',
  },
  {
    id: 'b4e8d10c-3038-4248-acbf-99c71fe7dd11',
    topic: 'grammar_punctuation',
    year_level: 'grade_4',
    difficulty: 'developing',
    question_text: 'Choose the correctly punctuated sentence.',
    options: ['Its a sunny day.', "It's a sunny day.", "Its' a sunny day.", 'Its a sunny day'],
    correct_index: 1,
    explanation: "'It's' is the contraction of 'it is'. 'Its' (no apostrophe) shows possession.",
    curriculum_code: 'AC9E4LA06',
  },
  {
    id: '50d57618-b6ac-4a40-9414-11fc145bebcb',
    topic: 'grammar_punctuation',
    year_level: 'grade_6',
    difficulty: 'proficient',
    question_text: 'Identify the sentence with correct subject-verb agreement.',
    options: ['The team are winning.', 'The team is winning.', 'The team am winning.', 'The team be winning.'],
    correct_index: 1,
    explanation: "'Team' is a collective noun treated as singular in Australian English, so it takes 'is'.",
    curriculum_code: 'AC9E6LA07',
  },
  {
    id: '44031c53-3fe9-401e-be48-ed1ff2ccc2bc',
    topic: 'grammar_punctuation',
    year_level: 'year_7',
    difficulty: 'developing',
    question_text: "Which word correctly completes: 'Neither the students nor the teacher ___ ready.'",
    options: ['was', 'were', 'is', 'are'],
    correct_index: 0,
    explanation: "With 'neither/nor', the verb agrees with the nearer subject, 'teacher' (singular), so 'was'.",
    curriculum_code: 'AC9E7LA05',
  },
  {
    id: '06ae62bf-37df-4c5e-a56e-ed9c1cf7512c',
    topic: 'grammar_punctuation',
    year_level: 'year_8',
    difficulty: 'proficient',
    question_text: 'Which sentence correctly uses a semicolon?',
    options: ['I like tea; however, I prefer coffee.', 'I like tea, however I prefer coffee.', 'I like tea; and coffee.', 'I like tea however; I prefer coffee.'],
    correct_index: 0,
    explanation: "A semicolon can join two related independent clauses, often before a conjunctive adverb like 'however'.",
    curriculum_code: 'AC9E8LA06',
  },

  // ── VOCABULARY — Grade 3–Year 9 ──────────────────────────────────────────

  {
    id: 'd0787f9d-fc16-4824-bd33-9b5a9ce48d10',
    topic: 'vocabulary',
    year_level: 'grade_3',
    difficulty: 'foundation',
    question_text: "Which word means the same as 'happy'?",
    options: ['Glad', 'Sad', 'Angry', 'Tired'],
    correct_index: 0,
    explanation: "'Glad' is a synonym for 'happy'; both describe feeling pleased.",
    curriculum_code: 'AC9E3LA09',
  },
  {
    id: '38223913-5840-4bd4-8f9d-1bbea56a700f',
    topic: 'vocabulary',
    year_level: 'grade_5',
    difficulty: 'developing',
    question_text: "What is the antonym (opposite) of 'generous'?",
    options: ['Kind', 'Selfish', 'Wealthy', 'Helpful'],
    correct_index: 1,
    explanation: "'Selfish' means the opposite of 'generous', which means willing to give.",
    curriculum_code: 'AC9E5LA10',
  },
  {
    id: 'ef89ac55-5590-45b9-8ca7-8a935961c8a9',
    topic: 'vocabulary',
    year_level: 'grade_6',
    difficulty: 'developing',
    question_text: "The prefix 'un-' in the word 'unhappy' means:",
    options: ['Very', 'Again', 'Not', 'Before'],
    correct_index: 2,
    explanation: "The prefix 'un-' means 'not', so 'unhappy' means 'not happy'.",
    curriculum_code: 'AC9E6LA09',
  },
  {
    id: '96962a07-d84a-4489-b4b4-4324f88b2b26',
    topic: 'vocabulary',
    year_level: 'year_7',
    difficulty: 'proficient',
    question_text: "Which word best fits: 'The detective's ___ observation solved the case.'",
    options: ['meticulous', 'careless', 'hasty', 'vague'],
    correct_index: 0,
    explanation: "'Meticulous' means very careful and precise, fitting a detective solving a case.",
    curriculum_code: 'AC9E7LA10',
  },
  {
    id: 'bf750551-cf5e-491e-9e3c-eac4f1057ee0',
    topic: 'vocabulary',
    year_level: 'year_9',
    difficulty: 'advanced',
    question_text: "'Ubiquitous' most nearly means:",
    options: ['Rare', 'Present everywhere', 'Ancient', 'Loud'],
    correct_index: 1,
    explanation: "'Ubiquitous' describes something found everywhere or very common.",
    curriculum_code: 'AC9E9LA08',
  },

  // ── LIFE SCIENCE — Grade 3–Year 9 ────────────────────────────────────────

  {
    id: '5ca913e1-318e-47f6-b043-4719b7bb1540',
    topic: 'life_science',
    year_level: 'grade_3',
    difficulty: 'foundation',
    question_text: 'Which of these is a living thing?',
    options: ['Rock', 'Tree', 'Chair', 'Cloud'],
    correct_index: 1,
    explanation: 'Living things grow, reproduce, and need energy, so a tree is alive, while rocks, chairs and clouds are not.',
    curriculum_code: 'AC9S3U01',
  },
  {
    id: '9bf731e1-fa29-4479-92ed-ba7882e1b692',
    topic: 'life_science',
    year_level: 'grade_5',
    difficulty: 'developing',
    question_text: "What is the main function of a plant's roots?",
    options: ['Make food using sunlight', 'Absorb water and nutrients', 'Produce seeds', 'Release oxygen'],
    correct_index: 1,
    explanation: 'Roots anchor the plant and absorb water and nutrients from the soil.',
    curriculum_code: 'AC9S5U01',
  },
  {
    id: '12310b4f-6289-41b5-8379-2d52e086a163',
    topic: 'life_science',
    year_level: 'grade_6',
    difficulty: 'developing',
    question_text: 'Which organ pumps blood around the human body?',
    options: ['Lungs', 'Liver', 'Heart', 'Stomach'],
    correct_index: 2,
    explanation: 'The heart is a muscular organ that pumps blood through the circulatory system.',
    curriculum_code: 'AC9S6U02',
  },
  {
    id: 'a7543b7a-a68d-4973-bed4-370427f0228d',
    topic: 'life_science',
    year_level: 'year_7',
    difficulty: 'proficient',
    question_text: 'In a food chain, what is the primary role of a producer?',
    options: ['Eats other animals', 'Makes its own food using sunlight', 'Decomposes dead matter', 'Hunts prey'],
    correct_index: 1,
    explanation: 'Producers, like plants, make their own food through photosynthesis.',
    curriculum_code: 'AC9S7U03',
  },
  {
    id: '75a77b8c-543b-4772-a94b-1f700d4c4f3f',
    topic: 'life_science',
    year_level: 'year_9',
    difficulty: 'advanced',
    question_text: 'Which process allows cells to divide and produce two genetically identical daughter cells?',
    options: ['Meiosis', 'Mitosis', 'Fertilisation', 'Osmosis'],
    correct_index: 1,
    explanation: 'Mitosis produces two genetically identical daughter cells for growth and repair.',
    curriculum_code: 'AC9S9U03',
  },

  // ── PHYSICAL SCIENCE — Grade 4–Year 10 ───────────────────────────────────

  {
    id: '2f9423e0-9e64-47f0-ba90-f0e31d32a1ff',
    topic: 'physical_science',
    year_level: 'grade_4',
    difficulty: 'foundation',
    question_text: 'What happens to water when it is heated to boiling point?',
    options: ['It freezes', 'It turns into gas', 'It turns into rock', 'It disappears forever'],
    correct_index: 1,
    explanation: 'At boiling point, water changes from a liquid to a gas (water vapour).',
    curriculum_code: 'AC9S4U01',
  },
  {
    id: 'd7c1d9c5-c9de-4188-851b-fb10521c436b',
    topic: 'physical_science',
    year_level: 'grade_6',
    difficulty: 'developing',
    question_text: 'Which of these is a force that slows down moving objects?',
    options: ['Gravity', 'Friction', 'Magnetism', 'Light'],
    correct_index: 1,
    explanation: 'Friction acts opposite to motion between surfaces, slowing objects down.',
    curriculum_code: 'AC9S6U01',
  },
  {
    id: 'b4135d64-f9bb-403b-8899-464791404fae',
    topic: 'physical_science',
    year_level: 'year_7',
    difficulty: 'developing',
    question_text: 'What is the unit used to measure electric current?',
    options: ['Volt', 'Watt', 'Ampere', 'Ohm'],
    correct_index: 2,
    explanation: 'Electric current is measured in amperes (amps), symbol A.',
    curriculum_code: 'AC9S7U01',
  },
  {
    id: '08c4487d-e0de-45dd-a475-9b23f8d3b6ee',
    topic: 'physical_science',
    year_level: 'year_8',
    difficulty: 'proficient',
    question_text: 'Which state of matter has a fixed volume but no fixed shape?',
    options: ['Solid', 'Liquid', 'Gas', 'Plasma'],
    correct_index: 1,
    explanation: 'A liquid takes the shape of its container but keeps a fixed volume.',
    curriculum_code: 'AC9S8U01',
  },
  {
    id: 'fa75ee6b-7411-4dc0-8f24-9db75d523b3e',
    topic: 'physical_science',
    year_level: 'year_10',
    difficulty: 'advanced',
    question_text: "According to Newton's second law, force equals:",
    options: ['mass ÷ acceleration', 'mass × acceleration', 'mass + acceleration', 'acceleration ÷ mass'],
    correct_index: 1,
    explanation: "Newton's second law states F = m × a (force equals mass times acceleration).",
    curriculum_code: 'AC9S10U03',
  },

  // ── EARTH & SPACE — Grade 3–Year 9 ───────────────────────────────────────

  {
    id: '5955cdef-1a18-49bc-867e-83772e0bb443',
    topic: 'earth_space',
    year_level: 'grade_3',
    difficulty: 'foundation',
    question_text: 'What causes day and night on Earth?',
    options: ['The Moon orbiting Earth', 'Earth spinning on its axis', 'The Sun moving around Earth', 'Clouds covering the Sun'],
    correct_index: 1,
    explanation: 'Earth rotates on its axis once every 24 hours, causing day and night.',
    curriculum_code: 'AC9S3U02',
  },
  {
    id: 'c6fb52e0-4bff-4659-bb3d-5374d17ab882',
    topic: 'earth_space',
    year_level: 'grade_5',
    difficulty: 'developing',
    question_text: 'Which layer of the Earth is the hottest?',
    options: ['Crust', 'Mantle', 'Outer core', 'Inner core'],
    correct_index: 3,
    explanation: "The inner core is the hottest layer, reaching temperatures similar to the Sun's surface.",
    curriculum_code: 'AC9S5U02',
  },
  {
    id: '6eec1bb8-817f-4d8a-9cfe-f1fea7cc875b',
    topic: 'earth_space',
    year_level: 'grade_6',
    difficulty: 'developing',
    question_text: 'What is the main cause of the seasons on Earth?',
    options: ['Distance from the Sun changing a lot', "The tilt of Earth's axis", "The Moon's gravity", 'Ocean currents'],
    correct_index: 1,
    explanation: "Earth's axial tilt means different hemispheres receive more or less direct sunlight through the year, causing seasons.",
    curriculum_code: 'AC9S6U03',
  },
  {
    id: '5327c5a5-d566-472a-9c20-46d7b7130175',
    topic: 'earth_space',
    year_level: 'year_8',
    difficulty: 'proficient',
    question_text: 'Which type of rock forms from cooled magma or lava?',
    options: ['Sedimentary', 'Metamorphic', 'Igneous', 'Fossil'],
    correct_index: 2,
    explanation: 'Igneous rock forms when magma or lava cools and solidifies.',
    curriculum_code: 'AC9S8U02',
  },
  {
    id: '2a50a3c3-40ff-4e56-947a-394adc7cab21',
    topic: 'earth_space',
    year_level: 'year_9',
    difficulty: 'advanced',
    question_text: 'What is the primary evidence used to support the theory of plate tectonics?',
    options: ['Fossil records only', 'Matching coastlines, fossils, and rock strata across continents', 'Ocean temperature', 'Moon phases'],
    correct_index: 1,
    explanation: 'Matching coastlines, fossil distributions, and rock strata across continents provide strong evidence for plate tectonics.',
    curriculum_code: 'AC9S9U04',
  },

  // ── CHEMISTRY (VCE selective) — Year 11 ──────────────────────────────────

  {
    id: '3b42d2be-fbd4-4d3b-8827-22a090d39f3e',
    topic: 'chem_atomic_structure',
    year_level: 'year_11',
    difficulty: 'foundation',
    question_text: 'How many electrons can the first electron shell (n = 1) hold at maximum?',
    options: ['2', '8', '18', '6'],
    correct_index: 0,
    explanation: 'The first shell (n = 1) holds a maximum of 2 electrons.',
  },
  {
    id: '065e91db-0de0-4986-9df8-b9511054b68a',
    topic: 'chem_atomic_structure',
    year_level: 'year_11',
    difficulty: 'foundation',
    question_text: 'What does the atomic number of an element tell you?',
    options: ['The number of neutrons', 'The number of protons', 'The number of protons plus neutrons', 'The number of outer-shell electrons'],
    correct_index: 1,
    explanation: 'The atomic number is the number of protons in the nucleus, which also equals the number of electrons in a neutral atom.',
  },
  {
    id: '0ddf4f17-0812-4cdd-aa13-f4aaad38b896',
    topic: 'chem_reactions',
    year_level: 'year_11',
    difficulty: 'developing',
    question_text: 'In the reaction Mg + 2HCl → MgCl₂ + H₂, what type of reaction is this?',
    options: ['Combustion', 'Displacement', 'Neutralisation', 'Decomposition'],
    correct_index: 1,
    explanation: 'Magnesium displaces hydrogen from hydrochloric acid, making this a displacement reaction.',
  },
  {
    id: '557bbb2b-67b7-4b2b-9f4b-47b80434436d',
    topic: 'chem_reactions',
    year_level: 'year_11',
    difficulty: 'developing',
    question_text: 'What are the correct coefficients to balance: __H₂ + __O₂ → __H₂O?',
    options: ['1, 1, 1', '2, 1, 2', '2, 2, 2', '1, 2, 1'],
    correct_index: 1,
    explanation: '2H₂ + O₂ → 2H₂O balances both hydrogen (4 atoms) and oxygen (2 atoms) on each side.',
  },

  // ── PHYSICS (VCE selective) — Year 11 ────────────────────────────────────

  {
    id: '0a07ed7f-3495-412f-843c-c967b7394a2b',
    topic: 'phys_mechanics',
    year_level: 'year_11',
    difficulty: 'developing',
    question_text: 'A car accelerates from rest at 2 m/s² for 5 seconds. What is its final velocity?',
    options: ['5 m/s', '10 m/s', '15 m/s', '20 m/s'],
    correct_index: 1,
    explanation: 'v = u + at = 0 + (2 × 5) = 10 m/s.',
  },
  {
    id: '6c48df1d-33ae-4d32-91b5-6e353d6e176d',
    topic: 'phys_mechanics',
    year_level: 'year_11',
    difficulty: 'foundation',
    question_text: 'Which formula gives the kinetic energy of a moving object?',
    options: ['mgh', '½mv²', 'mv', 'ma'],
    correct_index: 1,
    explanation: 'Kinetic energy is calculated as ½mv², where m is mass and v is velocity.',
  },
  {
    id: 'f7de488d-5e3b-4931-b68a-5db63687a461',
    topic: 'phys_electricity',
    year_level: 'year_11',
    difficulty: 'developing',
    question_text: "Using Ohm's law, what is the current through a 10 Ω resistor with 20 V across it?",
    options: ['0.5 A', '2 A', '10 A', '200 A'],
    correct_index: 1,
    explanation: 'I = V / R = 20 / 10 = 2 A.',
  },
  {
    id: '044beb53-783a-4caf-a5b7-26d10f2e1650',
    topic: 'phys_electricity',
    year_level: 'year_11',
    difficulty: 'foundation',
    question_text: 'Which particle carries negative charge and flows to create a typical electric current in a wire?',
    options: ['Proton', 'Neutron', 'Electron', 'Positron'],
    correct_index: 2,
    explanation: 'Electrons carry negative charge and are the particles that flow through a conductor.',
  },

  // ── MATHS METHODS (VCE selective) — Year 11 ──────────────────────────────

  {
    id: 'c2a82f32-e1b5-4a7e-82e3-5843a6d0f39a',
    topic: 'mm_calculus',
    year_level: 'year_11',
    difficulty: 'developing',
    question_text: 'Differentiate f(x) = 3x² + 2x.',
    options: ["f'(x) = 6x + 2", "f'(x) = 3x + 2", "f'(x) = 6x", "f'(x) = 6x² + 2"],
    correct_index: 0,
    explanation: 'Using the power rule: d/dx(3x²) = 6x and d/dx(2x) = 2, giving 6x + 2.',
  },
  {
    id: '2bd3853a-b67a-4cc7-baf4-227f343c1874',
    topic: 'mm_calculus',
    year_level: 'year_11',
    difficulty: 'foundation',
    question_text: 'What is the derivative of a constant, such as f(x) = 7?',
    options: ['7', '1', '0', 'x'],
    correct_index: 2,
    explanation: 'The derivative of any constant is 0, since a constant does not change as x changes.',
  },
  {
    id: '8205de0f-8534-4eb8-8199-371a67bc7156',
    topic: 'mm_probability',
    year_level: 'year_11',
    difficulty: 'developing',
    question_text: 'A fair coin is tossed twice. What is the probability of getting exactly one head?',
    options: ['1/4', '1/2', '3/4', '1'],
    correct_index: 1,
    explanation: 'Of the four equally likely outcomes (HH, HT, TH, TT), two have exactly one head, giving 2/4 = 1/2.',
  },
  {
    id: '26ca60d4-2c6d-4f9e-b97c-c0f37655220c',
    topic: 'mm_probability',
    year_level: 'year_11',
    difficulty: 'developing',
    question_text: 'If P(A) = 0.3 and P(B) = 0.4 and A and B are independent, what is P(A and B)?',
    options: ['0.7', '0.12', '0.1', '0.34'],
    correct_index: 1,
    explanation: 'For independent events, P(A and B) = P(A) × P(B) = 0.3 × 0.4 = 0.12.',
  },

  // ── FURTHER MATHEMATICS (VCE selective) — Year 11 ────────────────────────

  {
    id: '91dd8c91-8f1f-491f-96b8-e2610b41fe99',
    topic: 'fm_data_analysis',
    year_level: 'year_11',
    difficulty: 'foundation',
    question_text: 'What does the median of a data set represent?',
    options: ['The most frequent value', 'The middle value when the data is ordered', 'The average of all values', 'The range of the values'],
    correct_index: 1,
    explanation: 'The median is the middle value once the data set is arranged in order.',
  },
  {
    id: '91c45557-dbe3-465b-9fd5-3be3080e9dc9',
    topic: 'fm_data_analysis',
    year_level: 'year_11',
    difficulty: 'developing',
    question_text: 'A data set has Q1 = 10 and Q3 = 18. What is the interquartile range (IQR)?',
    options: ['8', '18', '28', '10'],
    correct_index: 0,
    explanation: 'IQR = Q3 − Q1 = 18 − 10 = 8.',
  },
  {
    id: '23d8c575-deee-4f27-b355-ce6a665086d3',
    topic: 'fm_financial',
    year_level: 'year_11',
    difficulty: 'developing',
    question_text: '$1000 is invested at 5% simple interest per year. How much interest is earned after 3 years?',
    options: ['$50', '$150', '$1050', '$1150'],
    correct_index: 1,
    explanation: 'Simple interest = P × r × t = 1000 × 0.05 × 3 = $150.',
  },
  {
    id: '181fa7ab-86e6-4dde-b712-b5d3351df455',
    topic: 'fm_financial',
    year_level: 'year_11',
    difficulty: 'foundation',
    question_text: 'What does "principal" mean in the context of a loan or investment?',
    options: ['The interest earned', 'The original amount borrowed or invested', 'The final balance', 'The interest rate'],
    correct_index: 1,
    explanation: 'The principal is the original sum of money borrowed or invested, before interest is applied.',
  },

  // ── SPECIALIST MATHEMATICS (VCE selective) — Year 11 ─────────────────────

  {
    id: '3cad9f55-12a8-4c1a-86bb-c1aa38995a9d',
    topic: 'sm_complex_numbers',
    year_level: 'year_11',
    difficulty: 'foundation',
    question_text: 'Simplify i², where i is the imaginary unit.',
    options: ['1', '−1', 'i', '−i'],
    correct_index: 1,
    explanation: 'By definition, i² = −1.',
  },
  {
    id: '265515d5-2037-4970-afd7-2def26515b11',
    topic: 'sm_complex_numbers',
    year_level: 'year_11',
    difficulty: 'developing',
    question_text: 'What is the modulus of the complex number 3 + 4i?',
    options: ['5', '7', '25', '12'],
    correct_index: 0,
    explanation: 'The modulus is √(3² + 4²) = √(9 + 16) = √25 = 5.',
  },
  {
    id: '82f2daa3-b0b0-4c9f-be83-ca7d3b56b0c9',
    topic: 'sm_vectors',
    year_level: 'year_11',
    difficulty: 'developing',
    question_text: 'What is the magnitude of the vector (6, 8)?',
    options: ['10', '14', '48', '100'],
    correct_index: 0,
    explanation: 'Magnitude = √(6² + 8²) = √(36 + 64) = √100 = 10.',
  },
  {
    id: 'e1a9f16e-7ff7-4bbd-9f4b-599e364ceb21',
    topic: 'sm_vectors',
    year_level: 'year_11',
    difficulty: 'foundation',
    question_text: 'Two vectors are perpendicular to each other. What is their dot product?',
    options: ['1', '−1', '0', 'Undefined'],
    correct_index: 2,
    explanation: 'Perpendicular vectors always have a dot product of 0.',
  },
]
