// ─────────────────────────────────────────────────────────────────────────────
// Auto-generated by scripts/gen-coverage.mjs — do not hand-edit.
// Regenerate after bank.ts changes with: npm run gen
//
// How many questions the free quiz can serve for each topic at each year level,
// plus the size of the whole bank. This is the ONLY
// question-bank-derived data that may be imported by a client component: it
// tells the practice builder which combinations have content without shipping
// any question text, answers or explanations to the browser. Actual questions
// are served by /api/practice/quiz, which returns only the handful selected for
// one quiz.
// ─────────────────────────────────────────────────────────────────────────────

import type { TopicSlug, YearLevel } from '@/types'

export type TopicCoverage = Partial<Record<TopicSlug, Partial<Record<YearLevel, number>>>>

export const TOPIC_COVERAGE: TopicCoverage = {
  algebra_equations: { year_10: 26, year_7: 18, year_8: 10, year_9: 25 },
  chem_atomic_structure: { year_11: 22 },
  chem_reactions: { year_11: 21 },
  earth_space: { grade_3: 7, grade_4: 7, grade_5: 7, grade_6: 8, year_10: 7, year_7: 6, year_8: 7, year_9: 7 },
  geometry_measurement: { grade_3: 2, grade_4: 1, grade_5: 10, grade_6: 1, year_10: 20, year_7: 16, year_8: 3, year_9: 24 },
  gm_data_analysis: { year_11: 27, year_12: 11 },
  gm_financial: { year_11: 26, year_12: 8 },
  gm_matrices: { year_12: 3 },
  gm_networks: { year_12: 2 },
  grammar_punctuation: { grade_3: 31, grade_4: 30, grade_5: 30, grade_6: 30, year_10: 30, year_7: 31, year_8: 30, year_9: 30 },
  life_science: { grade_3: 9, grade_4: 9, grade_5: 9, grade_6: 9, year_10: 8, year_7: 9, year_8: 8, year_9: 9 },
  mm_algebra: { year_12: 2 },
  mm_calculus: { year_11: 29, year_12: 5 },
  mm_functions: { year_12: 6 },
  mm_probability: { year_11: 26, year_12: 5 },
  number_operations: { grade_3: 11, grade_4: 13, grade_5: 32, grade_6: 17, year_10: 26, year_7: 60, year_8: 17, year_9: 60 },
  number_patterns: { grade_3: 3, grade_4: 5, grade_5: 9, grade_6: 5 },
  phys_electricity: { year_11: 23 },
  phys_mechanics: { year_11: 26 },
  physical_science: { grade_3: 8, grade_4: 8, grade_5: 8, grade_6: 9, year_10: 9, year_7: 9, year_8: 9, year_9: 8 },
  reading_comprehension: { grade_3: 7, grade_4: 6, grade_5: 7, grade_6: 8 },
  reading_literary_analysis: { year_10: 7, year_7: 8, year_8: 7, year_9: 8 },
  sm_complex_numbers: { year_11: 24 },
  sm_vectors: { year_11: 22 },
  statistics_probability: { grade_3: 1, grade_4: 2, grade_5: 3, grade_6: 3, year_10: 15, year_7: 7, year_8: 6, year_9: 13 },
  vocabulary: { grade_3: 12, grade_4: 11, grade_5: 12, grade_6: 12, year_10: 11, year_7: 12, year_8: 11, year_9: 12 },
}

/** Every question in the bank, including those only on the printable papers. */
export const QUESTION_TOTAL = 1917

/** Total questions available for a topic, across every year level. */
export function topicTotal(topic: TopicSlug): number {
  return Object.values(TOPIC_COVERAGE[topic] ?? {}).reduce((a, b) => a + b, 0)
}

/** Questions available for a topic at one year level. */
export function topicCountAt(topic: TopicSlug, yearLevel: YearLevel): number {
  return TOPIC_COVERAGE[topic]?.[yearLevel] ?? 0
}
