import type { ReadingMagazine } from '@/types/reading'

// ─────────────────────────────────────────────────────────────────────────────
// Reading magazines — the colour booklet a student reads before answering the
// Reading paper, in the shape of the real NAPLAN Reading Magazine: one text per
// page, a mix of text types (story, report, explanation, persuasive, verse,
// procedure, notice), and a picture or diagram on most pages.
//
// Every text here is original. Structure, length and spread of text types
// follow the published NAPLAN papers (Years 3, 5, 7 and 9, 2012-2016): Year 3
// and 5 magazines run 6-7 texts over 8 pages with 38 questions, Years 7 and 9
// run 8 texts over 12 pages with 50. Length scales with the year level, from
// about 90 words at Year 3 to 480 at Year 9.
//
// Magazine 1 at each year level is the free sample; later sets are paid.
// Questions live in bank.ts and point at a text through `stimulus_id`.
// ─────────────────────────────────────────────────────────────────────────────

export const MAGAZINES: ReadingMagazine[] = [
  {
    id: 'reading-grade_3-1',
    yearLevel: 'grade_3',
    set: 1,
    texts: [
      {
        id: 'e7398d81-aed9-4d75-85ee-f3229bd264ee',
        page: 2,
        title: 'The sandwich thief',
        type: 'story',
        blocks: [
          { kind: 'para', text: 'Every lunchtime, Ravi put his lunchbox on the low wall near the bike racks. Every lunchtime, one half of his sandwich disappeared.' },
          { kind: 'para', text: '“Someone is taking my lunch,” Ravi told his friend Amina. “It is always the half with the cheese.”' },
          { kind: 'para', text: 'Amina looked at the wall. She looked at the tree above the wall. Then she smiled.' },
          { kind: 'para', text: '“Tomorrow,” she said, “we will watch from the library window.”' },
          { kind: 'para', text: 'The next day the two friends knelt at the window and waited. Ravi’s lunchbox sat on the wall in the sun. Nothing happened for a long time.' },
          { kind: 'para', text: 'Then a grey bird with a black head landed on the wall. It tipped its head to one side, hopped twice, and lifted the lid with its beak.' },
          { kind: 'para', text: '“A currawong!” whispered Ravi.' },
          { kind: 'para', text: 'The bird took the cheese half in its beak and flew up into the tree. Ravi laughed so loudly that the librarian looked up.' },
          { kind: 'para', text: 'After that, Ravi kept his lunchbox in his bag. He still left one small crust on the wall, because the currawong had made him laugh, and that was worth a crust.' },
        ],
      },
      {
        id: '69ea2036-e7ed-4a68-9e0c-f01afce52cf2',
        page: 3,
        title: 'Wombats',
        type: 'report',
        columns: 2,
        blocks: [
          { kind: 'para', text: 'Wombats are short, strong animals that live in Australia. A wombat is about as long as a school ruler and two hand spans wide. It has thick grey or brown fur.' },
          { kind: 'para', text: 'Wombats dig burrows under the ground with their strong front legs and flat claws. A burrow can be longer than a classroom. Inside the burrow it stays cool in summer and warm in winter.' },
          { kind: 'para', text: 'A wombat is a marsupial, so a wombat mother carries her baby in a pouch. Her pouch faces backwards. This means the pouch does not fill with soil while she digs.' },
          { kind: 'para', text: 'Wombats eat grass, roots and bark. They come out to feed at night when the air is cool. During the hot part of the day they sleep in the burrow.' },
          { kind: 'factbox', title: 'Wombat facts', items: ['A baby wombat is called a joey.', 'Wombat droppings are shaped like little cubes.', 'A wombat can run as fast as a person for a short way.'] },
        ],
      },
      {
        id: 'f1c56d83-40b7-49cc-9f8d-f7ba4b48df01',
        page: 4,
        title: 'Where does rain come from?',
        type: 'explanation',
        blocks: [
          { kind: 'para', text: 'Rain has been falling on Earth for a very long time. The same water goes around and around. This is called the water cycle.' },
          { kind: 'para', text: 'The sun warms the sea. Some of the water turns into a gas called water vapour and rises into the sky. You cannot see water vapour.' },
          { kind: 'para', text: 'High in the sky the air is cold. The water vapour cools and turns back into tiny drops. Millions of these drops together make a cloud.' },
          { kind: 'para', text: 'The drops bump into each other and join up. When a drop is too heavy to float, it falls as rain. The rain runs into creeks and rivers, and the rivers carry it back to the sea. Then the cycle starts again.' },
        ],
        figure: {
          kind: 'flow',
          cycle: true,
          steps: [
            { text: 'Sea', then: 'water rises' },
            { text: 'Cloud', then: 'drops join' },
            { text: 'Rain', then: 'rivers carry it back to the sea' },
          ],
        },
        figureCaption: 'The water cycle',
      },
      {
        id: '82c87b63-2028-405a-8484-80ecf332f671',
        page: 5,
        title: 'A garden for our school',
        type: 'letter',
        blocks: [
          { kind: 'note', text: 'Dear Mrs Patel' },
          { kind: 'para', text: 'I am writing because I think our school should grow a vegetable garden in the empty corner near the hall.' },
          { kind: 'para', text: 'At the moment that corner has nothing in it but weeds and one old bench. Nobody plays there. A garden would make it the nicest part of the school.' },
          { kind: 'para', text: 'A garden would also help us learn. In Year 3 we are learning about living things. It is easier to understand how a plant grows when you water it yourself and watch it every week.' },
          { kind: 'para', text: 'My grandfather says that beans and carrots are easy to grow, and that a garden costs very little to start. Our class could look after it at lunchtime. When the vegetables are ready, the canteen could use them in the salads.' },
          { kind: 'para', text: 'Please think about my idea. I would be very happy to show you the corner and where the beds could go.' },
          { kind: 'note', text: 'From Sophie Nguyen, Year 3B' },
        ],
      },
      {
        id: 'e588b40c-a1e6-436f-be14-14e40251fc4b',
        page: 6,
        title: 'Tiny visitor',
        type: 'poem',
        blocks: [
          { kind: 'verse', lines: [
            'A green tree frog is on the glass,',
            'flat feet spread like sticky stars.',
            'He watches every moth that comes',
            'to dance around our kitchen lamp.',
            '',
            'He does not hurry. Frogs can wait.',
            'He sits so still he looks asleep,',
            'then — quick as blinking — out it goes,',
            'that long pink ribbon of a tongue.',
            '',
            'By morning he has slipped away',
            'to somewhere cool and dark and damp,',
            'but on the window, small and round,',
            'he leaves five footprints and a smudge.',
          ] },
        ],
      },
      {
        id: '4abb2bb3-7679-48b9-aac2-160e1b6c1310',
        page: 7,
        title: 'Make a paper boat',
        type: 'procedure',
        blocks: [
          { kind: 'para', text: 'You will need one sheet of paper. Thin paper folds best. Do each fold carefully and press it flat.' },
          { kind: 'steps', items: [
            'Fold the paper in half so the short edges meet. Press the fold flat.',
            'Fold the two top corners down to the middle so they make a point.',
            'Fold the strip at the bottom up on each side to make a hat shape.',
            'Open the hat and push the two side points together to make a square.',
            'Fold the bottom corners of the square up to the top point.',
            'Hold the middle of the square and pull the two top points apart until a boat appears.',
          ] },
          { kind: 'factbox', title: 'Before you sail', items: ['Rub a candle over the paper to help the boat last longer in water.', 'Test the boat in a sink or a bucket, never in a creek or a pool on your own.'] },
        ],
      },
      {
        id: '4096bfb7-d979-4517-b9cf-2afadc3d7b53',
        page: 8,
        title: 'Junior Fun Run',
        type: 'persuasive',
        blocks: [
          { kind: 'quote', text: 'Run, jog or walk — every finisher gets a medal!' },
          { kind: 'para', text: 'The Riverside Junior Fun Run is on Sunday 14 June at Riverside Park. Money raised will buy new sports equipment for local primary schools.' },
          { kind: 'bullets', items: ['Bring a water bottle and wear a hat.', 'Every runner needs a grown-up with them at the park.', 'Entry is $5. Pay at the tent near the gate.'] },
          { kind: 'para', text: 'Come early to collect your number. Runners who arrive after their start time can still run, but they will not be timed.' },
        ],
        figure: {
          kind: 'data_table',
          title: 'Start times',
          columns: ['Race', 'Age', 'Starts'],
          rows: [['Dash', '5 to 7 years', '9:00 am'], ['1 km', '8 to 10 years', '9:30 am'], ['2 km', '11 to 13 years', '10:15 am']],
        },
      },
    ],
  },
  {
    id: 'reading-grade_3-2',
    yearLevel: 'grade_3',
    set: 2,
    texts: [
      {
        id: 'c8a4ee6c-b1f7-4380-8bb7-92fd46ea6597',
        page: 2,
        title: 'The blue ribbon',
        type: 'story',
        blocks: [
          { kind: 'para', text: 'Max had never liked the deep end. At swimming lessons he always stayed near the steps, where his feet could touch the bottom.' },
          { kind: 'para', text: '“The school swimming carnival is in two weeks,” said Mr Tran, the swimming coach. “Everyone in Year 3 can swim one lap.”' },
          { kind: 'para', text: 'Max’s stomach felt as if it were full of fish.' },
          { kind: 'para', text: 'That night he told his big sister, Lena. She did not laugh. “Then we practice,” she said. “Every afternoon.”' },
          { kind: 'para', text: 'So they did. On Monday Max floated on his back. On Wednesday he kicked across the pool holding a board. By Friday he could swim half a lap without stopping.' },
          { kind: 'para', text: 'On the day of the carnival, Max stood on the edge with five other swimmers. The whistle blew. He pushed off and swam, and swam, and swam. His arms ached. He could hear people shouting, but he did not look up.' },
          { kind: 'para', text: 'When his hand touched the wall, the other swimmers were already out of the pool. Max had come last.' },
          { kind: 'para', text: 'Then he saw Lena in the crowd, jumping up and down and waving. Mr Tran walked over and pinned a blue ribbon to his towel. It said Best Effort.' },
          { kind: 'para', text: 'Max had come last, but he had swum the whole lap. He did not stop smiling all day.' },
        ],
      },
      {
        id: 'c7359999-7442-4cef-9807-80f0de90a21b',
        page: 3,
        title: 'Pelican saved at Bellbird Lake',
        type: 'news',
        blocks: [
          { kind: 'note', text: 'By Sam Okafor, Bellbird News' },
          { kind: 'para', text: 'A pelican that was tangled in fishing line was rescued at Bellbird Lake on Sunday morning.' },
          { kind: 'para', text: 'Nine-year-old Chloe Martin saw the bird while she was walking her dog along the jetty. “One of its wings was stuck to its side,” Chloe said. “It kept trying to fly, but it just flapped in a circle.”' },
          { kind: 'para', text: 'Chloe’s mother called a wildlife rescue group. Two volunteers arrived in a small boat. They gently wrapped the pelican in a towel and cut away the line with special scissors.' },
          { kind: 'para', text: '“The towel keeps the bird calm,” said volunteer Priya Das. “If it cannot see, it is not so frightened.”' },
          { kind: 'para', text: 'The pelican has been taken to a wildlife hospital. Vets say it should be back on the lake in about two weeks.' },
          { kind: 'factbox', title: 'How you can help', items: ['Put old fishing line in the bins at the jetty.', 'If you see a hurt animal, do not touch it. Tell an adult.', 'Ask an adult to call a wildlife rescue group.'] },
        ],
      },
      {
        id: 'a8ae90e9-18f6-4128-bed3-fdaa5b98a66d',
        page: 4,
        title: 'Octopuses',
        type: 'report',
        columns: 2,
        blocks: [
          { kind: 'para', text: 'Octopuses are sea animals with soft bodies and eight arms. They have no bones at all, so they can squeeze through a gap not much bigger than a coin.' },
          { kind: 'para', text: 'Each arm is covered in suckers. The suckers can grip rocks and hold food. They can even taste whatever they touch.' },
          { kind: 'para', text: 'An octopus can change colour in less than a second. It turns brown, red or white to match the rocks and weed around it. This helps it hide from sharks and seals, and it helps it sneak up on crabs.' },
          { kind: 'para', text: 'If an octopus is in danger, it squirts a cloud of dark ink into the water. While the enemy cannot see, the octopus swims away.' },
          { kind: 'para', text: 'Octopuses are clever. Scientists have watched them open jars, solve puzzles and carry shells to use as shelters.' },
          { kind: 'factbox', title: 'Octopus facts', items: ['An octopus has three hearts.', 'Its blood is blue.', 'Most octopuses live for only one or two years.'] },
        ],
      },
      {
        id: '73b62823-6354-447e-a996-0cdcc2f7bf97',
        page: 5,
        title: 'Rainbow fruit sticks',
        type: 'procedure',
        blocks: [
          { kind: 'para', text: 'A cool, healthy snack for a hot day. Makes 6 sticks.' },
          { kind: 'heading', text: 'You will need' },
          { kind: 'bullets', items: ['6 strawberries', '1 small pineapple', '2 kiwi fruit', '18 blueberries', '6 wooden skewers', 'a chopping board and a knife'] },
          { kind: 'heading', text: 'What to do' },
          { kind: 'steps', items: [
            'Wash your hands and the fruit.',
            'Ask an adult to peel the pineapple and kiwi fruit and cut them into small cubes.',
            'Push a strawberry onto each skewer, then a piece of pineapple.',
            'Add a piece of kiwi fruit, then three blueberries.',
            'Keep going until each stick is full.',
            'Put the sticks in the fridge for 20 minutes so they are nice and cold.',
          ] },
          { kind: 'factbox', title: 'Safety tip', items: ['Skewers are sharp. Hold them by the flat end and point them away from your face.'] },
        ],
      },
      {
        id: '57195d86-97f2-44e1-b460-9c5e709b2751',
        page: 6,
        title: 'Wind',
        type: 'poem',
        blocks: [
          { kind: 'verse', lines: [
            'The wind came running down our street,',
            'it rattled every gate,',
            'it stole a hat from Mr Pike',
            'and made the washing wave.',
            '',
            'It whistled through the letterbox,',
            'it pushed the bins around,',
            'it tossed the autumn leaves up high',
            'then dropped them on the ground.',
            '',
            'At bedtime it was tired out,',
            'it curled up by the door,',
            'and all night long I heard it breathe',
            'a soft and sleepy snore.',
          ] },
        ],
      },
      {
        id: '4019abd7-43dc-4caf-ae43-2825fdf2a399',
        page: 7,
        title: 'Pip and the Quiet Roar',
        type: 'review',
        blocks: [
          { kind: 'note', text: 'Book review by Jack, Year 3' },
          { kind: 'para', text: 'Pip and the Quiet Roar by Elsa Moon is about a young dragon called Pip. All the other dragons can roar so loudly that the mountains shake, but when Pip tries, only a tiny squeak comes out.' },
          { kind: 'para', text: 'The other dragons laugh at Pip, so she runs away into the forest. There she meets a lost baby owl that is being chased by a fox. Pip cannot scare the fox away by roaring, so she has to think of another plan. I will not tell you what she does, because that would spoil the ending!' },
          { kind: 'para', text: 'My favourite part is when Pip sings to the baby owl to help it sleep. The pictures are bright and funny, and the words are easy to read.' },
          { kind: 'para', text: 'The only thing I did not like was that the book was too short. I wanted it to keep going.' },
          { kind: 'para', text: 'I think this book would be great for kids aged 5 to 9, and especially for anyone who feels different from everyone else.' },
          { kind: 'quote', text: 'My rating: 4 out of 5 stars' },
        ],
      },
      {
        id: '904ca47d-4a96-4342-ad39-89c459dcc928',
        page: 8,
        title: 'Holiday fun at Greenfield Library',
        type: 'web',
        blocks: [
          { kind: 'para', text: 'These school holidays, Greenfield Library has activities for children aged 5 to 12. Most activities are indoors, so they will go ahead even if it rains. The science show is outside in Greenfield Park, so wear a hat.' },
          { kind: 'bullets', items: ['All activities are free.', 'Book a place at the front desk or on this website.', 'Children under 8 must bring an adult.'] },
          { kind: 'para', text: 'Places fill up fast, so book early! If you cannot come, please tell us so that someone else can have your place.' },
        ],
        figure: {
          kind: 'data_table',
          title: 'Activities',
          columns: ['Activity', 'Day', 'Time'],
          rows: [['Lego building', 'Monday', '10:00 am'], ['Story time', 'Tuesday', '11:00 am'], ['Make a comic', 'Wednesday', '2:00 pm'], ['Science show', 'Thursday', '10:30 am'], ['Movie morning', 'Friday', '9:30 am']],
        },
      },
    ],
  },
  {
    id: 'reading-grade_3-3',
    yearLevel: 'grade_3',
    set: 3,
    texts: [
      {
        id: '7de6fc03-fd8b-4b9a-aef0-864da5ad96a5',
        page: 2,
        title: 'Grandma’s new phone',
        type: 'story',
        blocks: [
          { kind: 'para', text: 'Grandma bought her first mobile phone on a Tuesday. By Wednesday, Zoe had eleven messages from her.' },
          { kind: 'para', text: 'The first message was a photo of Grandma’s ear. The second was a photo of her thumb. The third just said HELLO ZOE IS THIS WORKING.' },
          { kind: 'para', text: '“Why is Grandma shouting?” asked Zoe’s little brother, Ben.' },
          { kind: 'para', text: '“She isn’t shouting,” laughed Zoe. “She just doesn’t know how to turn off the capital letters.”' },
          { kind: 'para', text: 'On Saturday, Zoe rode her bike to Grandma’s flat. She showed Grandma how to hold the phone the right way round for a photo, how to make the letters small and how to send a smiling face.' },
          { kind: 'para', text: 'Grandma practiced all afternoon. She took photos of her tea cup, her cat and the geraniums on the balcony.' },
          { kind: 'para', text: 'That night Zoe’s phone buzzed. It was a photo of the sunset over the sea, sharp and bright. Under it, Grandma had written: Thank you, my clever girl. Now it is my turn to teach you something. Bring your knitting needles next Saturday!' },
          { kind: 'para', text: 'Zoe smiled. She had never knitted anything in her life.' },
        ],
      },
      {
        id: '1a943783-ffb7-4d18-b084-b671b0f203bf',
        page: 3,
        title: 'How do bees make honey?',
        type: 'explanation',
        blocks: [
          { kind: 'para', text: 'Honey is made by honeybees. It takes a lot of hard work, and a whole hive of bees working together.' },
          { kind: 'para', text: 'A worker bee flies from flower to flower, drinking a sweet liquid called nectar. She stores the nectar in a special part of her body called a honey stomach.' },
          { kind: 'para', text: 'Back at the hive, she passes the nectar to a younger bee. That bee chews it and passes it on again. Each time, the nectar gets a little thicker.' },
          { kind: 'para', text: 'Next, the bees spread the nectar into the small six-sided rooms of the honeycomb, called cells. They fan it with their wings to dry out the water. Slowly, the runny nectar turns into thick, sticky honey.' },
          { kind: 'para', text: 'Finally, the bees cover each full cell with a lid of wax. The honey keeps there for months, ready to feed the hive through winter.' },
        ],
        figure: {
          kind: 'flow',
          steps: [
            { text: 'A bee drinks nectar' },
            { text: 'Bees pass it from bee to bee' },
            { text: 'Bees fan it dry in the cells' },
            { text: 'Cells are covered with wax' },
          ],
        },
        figureCaption: 'How nectar becomes honey',
      },
      {
        id: '93aefda4-7c41-4b9c-83af-ee542a613174',
        page: 4,
        title: 'Every class needs a pet',
        type: 'persuasive',
        blocks: [
          { kind: 'note', text: 'A speech by Aiden, Year 3' },
          { kind: 'para', text: 'Good morning, everyone. Today I am going to tell you why every class in our school should have a pet.' },
          { kind: 'para', text: 'First, a pet teaches us to be responsible. If our class had a guinea pig, we would take turns to feed it, give it fresh water and clean its cage. Nobody would want it to go hungry.' },
          { kind: 'para', text: 'Second, a pet makes a classroom calmer. When I stroke my dog at home, I feel relaxed. I think a class pet would help children who feel worried or upset.' },
          { kind: 'para', text: 'Third, a pet helps us learn. We could measure how much our guinea pig grows, write stories about it and find out what it needs to stay healthy.' },
          { kind: 'para', text: 'Some people say pets are noisy or messy. But a guinea pig is small and quiet, and if we clean its cage every Friday it will not be messy at all.' },
          { kind: 'para', text: 'So please vote yes for class pets. Our classrooms will be happier, calmer and smarter places. Thank you.' },
        ],
      },
      {
        id: 'b6867e34-7ef0-4e37-aaf0-d6b959d56c89',
        page: 5,
        title: 'Thank you, Ranger Kim',
        type: 'letter',
        blocks: [
          { kind: 'note', text: 'Dear Ranger Kim' },
          { kind: 'para', text: 'Thank you for showing Class 3K around Blue Gum National Park last Thursday. We had the best day.' },
          { kind: 'para', text: 'Our favourite part was the night walk. We never knew that sugar gliders could glide further than the length of a netball court! When you shone the red torch into the trees, we saw two of them eating. You told us that red light does not frighten animals the way white light does.' },
          { kind: 'para', text: 'We also learned why we must stay on the track. If people walk off the track, they crush small plants and the homes of lizards and insects.' },
          { kind: 'para', text: 'When we got back to school, we made posters about looking after the bush. We have put them up in the library so the whole school can see them.' },
          { kind: 'para', text: 'We hope we can visit again next year.' },
          { kind: 'note', text: 'From Class 3K, Wattle Hill Primary School' },
        ],
      },
      {
        id: '4f3b68de-ab63-479a-b1af-819b5e43efc5',
        page: 6,
        title: 'Night market',
        type: 'poem',
        blocks: [
          { kind: 'verse', lines: [
            'Lanterns hang like paper moons,',
            'the smoky grill goes hiss,',
            'a man is spinning sugar clouds —',
            'I’ve never tasted this!',
            '',
            'The noodles curl like yellow string,',
            'the dumplings steam and pop,',
            'a drummer taps a happy beat',
            'that makes my feet go hop.',
            '',
            'We walk home slowly, full and warm,',
            'the stars come out to see,',
            'and in my pocket, wrapped in foil,',
            'a dumpling just for me.',
          ] },
        ],
      },
      {
        id: '8ee4f2de-bd09-4db8-b3da-7a08824f2e5b',
        page: 7,
        title: 'Emus',
        type: 'report',
        columns: 2,
        blocks: [
          { kind: 'para', text: 'The emu is Australia’s largest bird. An adult emu can be taller than a grown-up person and weigh as much as a big dog.' },
          { kind: 'para', text: 'Emus cannot fly. Their wings are tiny, only about as long as a pencil. Instead of flying, emus run. They have long, strong legs and can run faster than a car in a school zone.' },
          { kind: 'para', text: 'Emus eat seeds, fruit, flowers and insects. When they eat fruit, the seeds pass through their bodies and are dropped in new places, where they can grow into new plants.' },
          { kind: 'para', text: 'The female emu lays the eggs, but the male does the rest. He sits on the eggs for about eight weeks and hardly eats or drinks the whole time. After the chicks hatch, he looks after them for many months.' },
          { kind: 'factbox', title: 'Emu facts', items: ['Emu eggs are dark green.', 'Emu chicks have stripes, which help them hide in the grass.', 'The emu is on Australia’s coat of arms.'] },
        ],
      },
      {
        id: 'f00df197-ee7e-4ffa-834a-a7957f1642b2',
        page: 8,
        title: 'Lost dog',
        type: 'notice',
        blocks: [
          { kind: 'quote', text: 'Please help us find Biscuit!' },
          { kind: 'para', text: 'Biscuit went missing from Acacia Street on Sunday afternoon when our gate was left open. He is friendly but shy, and he may hide if you call him loudly.' },
          { kind: 'heading', text: 'What Biscuit looks like' },
          { kind: 'bullets', items: ['small brown dog with one white ear', 'red collar with a silver bell', 'very fluffy tail'] },
          { kind: 'heading', text: 'If you see him' },
          { kind: 'bullets', items: ['Do not chase him. Sit down and hold out your hand.', 'Knock on the door of 14 Acacia Street, or tell a grown-up.'] },
          { kind: 'para', text: 'A reward of $50 will be given to the person who brings Biscuit home.' },
          { kind: 'note', text: 'Thank you! From Hana and Leo' },
        ],
      },
    ],
  },
]

/** Every magazine text, by id — the lookup the exam builder and the PDF use. */
export const READING_TEXTS = new Map(MAGAZINES.flatMap(m => m.texts.map(t => [t.id, { ...t, magazine: m }] as const)))
