import type { ReadingMagazine } from '@/types/reading'

// ─────────────────────────────────────────────────────────────────────────────
// Reading magazines — the colour booklet a student reads before answering the
// Reading paper, in the shape of the real NAPLAN Reading Magazine: one text per
// page, a mix of text types (story, report, explanation, persuasive, verse,
// procedure, notice), and a picture or diagram on most pages.
//
// Every text here is original. Structure, length and spread of text types
// follow the published NAPLAN papers (Years 3, 5, 7 and 9, 2012-2016): Year 3
// and 5 magazines run 6-7 texts over 8 pages with 38 questions, Years 7 and 9
// run 8 texts over 12 pages with 50. Length scales with the year level, from
// about 90 words at Year 3 to 480 at Year 9.
//
// Magazine 1 at each year level is the free sample; later sets are paid.
// Questions live in bank.ts and point at a text through `stimulus_id`.
// ─────────────────────────────────────────────────────────────────────────────

export const MAGAZINES: ReadingMagazine[] = [
  {
    id: 'reading-grade_3-1',
    yearLevel: 'grade_3',
    set: 1,
    texts: [
      {
        id: 'e7398d81-aed9-4d75-85ee-f3229bd264ee',
        page: 2,
        title: 'The sandwich thief',
        type: 'story',
        blocks: [
          { kind: 'para', text: 'Every lunchtime, Ravi put his lunchbox on the low wall near the bike racks. Every lunchtime, one half of his sandwich disappeared.' },
          { kind: 'para', text: '“Someone is taking my lunch,” Ravi told his friend Amina. “It is always the half with the cheese.”' },
          { kind: 'para', text: 'Amina looked at the wall. She looked at the tree above the wall. Then she smiled.' },
          { kind: 'para', text: '“Tomorrow,” she said, “we will watch from the library window.”' },
          { kind: 'para', text: 'The next day the two friends knelt at the window and waited. Ravi’s lunchbox sat on the wall in the sun. Nothing happened for a long time.' },
          { kind: 'para', text: 'Then a grey bird with a black head landed on the wall. It tipped its head to one side, hopped twice, and lifted the lid with its beak.' },
          { kind: 'para', text: '“A currawong!” whispered Ravi.' },
          { kind: 'para', text: 'The bird took the cheese half in its beak and flew up into the tree. Ravi laughed so loudly that the librarian looked up.' },
          { kind: 'para', text: 'After that, Ravi kept his lunchbox in his bag. He still left one small crust on the wall, because the currawong had made him laugh, and that was worth a crust.' },
        ],
      },
      {
        id: '69ea2036-e7ed-4a68-9e0c-f01afce52cf2',
        page: 3,
        title: 'Wombats',
        type: 'report',
        columns: 2,
        blocks: [
          { kind: 'para', text: 'Wombats are short, strong animals that live in Australia. A wombat is about as long as a school ruler and two hand spans wide. It has thick grey or brown fur.' },
          { kind: 'para', text: 'Wombats dig burrows under the ground with their strong front legs and flat claws. A burrow can be longer than a classroom. Inside the burrow it stays cool in summer and warm in winter.' },
          { kind: 'para', text: 'A wombat is a marsupial, so a wombat mother carries her baby in a pouch. Her pouch faces backwards. This means the pouch does not fill with soil while she digs.' },
          { kind: 'para', text: 'Wombats eat grass, roots and bark. They come out to feed at night when the air is cool. During the hot part of the day they sleep in the burrow.' },
          { kind: 'factbox', title: 'Wombat facts', items: ['A baby wombat is called a joey.', 'Wombat droppings are shaped like little cubes.', 'A wombat can run as fast as a person for a short way.'] },
        ],
      },
      {
        id: 'f1c56d83-40b7-49cc-9f8d-f7ba4b48df01',
        page: 4,
        title: 'Where does rain come from?',
        type: 'explanation',
        blocks: [
          { kind: 'para', text: 'Rain has been falling on Earth for a very long time. The same water goes around and around. This is called the water cycle.' },
          { kind: 'para', text: 'The sun warms the sea. Some of the water turns into a gas called water vapour and rises into the sky. You cannot see water vapour.' },
          { kind: 'para', text: 'High in the sky the air is cold. The water vapour cools and turns back into tiny drops. Millions of these drops together make a cloud.' },
          { kind: 'para', text: 'The drops bump into each other and join up. When a drop is too heavy to float, it falls as rain. The rain runs into creeks and rivers, and the rivers carry it back to the sea. Then the cycle starts again.' },
        ],
        figure: {
          kind: 'flow',
          cycle: true,
          steps: [
            { text: 'Sea', then: 'water rises' },
            { text: 'Cloud', then: 'drops join' },
            { text: 'Rain', then: 'rivers carry it back to the sea' },
          ],
        },
        figureCaption: 'The water cycle',
      },
      {
        id: '82c87b63-2028-405a-8484-80ecf332f671',
        page: 5,
        title: 'A garden for our school',
        type: 'letter',
        blocks: [
          { kind: 'note', text: 'Dear Mrs Patel' },
          { kind: 'para', text: 'I am writing because I think our school should grow a vegetable garden in the empty corner near the hall.' },
          { kind: 'para', text: 'At the moment that corner has nothing in it but weeds and one old bench. Nobody plays there. A garden would make it the nicest part of the school.' },
          { kind: 'para', text: 'A garden would also help us learn. In Year 3 we are learning about living things. It is easier to understand how a plant grows when you water it yourself and watch it every week.' },
          { kind: 'para', text: 'My grandfather says that beans and carrots are easy to grow, and that a garden costs very little to start. Our class could look after it at lunchtime. When the vegetables are ready, the canteen could use them in the salads.' },
          { kind: 'para', text: 'Please think about my idea. I would be very happy to show you the corner and where the beds could go.' },
          { kind: 'note', text: 'From Sophie Nguyen, Year 3B' },
        ],
      },
      {
        id: 'e588b40c-a1e6-436f-be14-14e40251fc4b',
        page: 6,
        title: 'Tiny visitor',
        type: 'poem',
        blocks: [
          { kind: 'verse', lines: [
            'A green tree frog is on the glass,',
            'flat feet spread like sticky stars.',
            'He watches every moth that comes',
            'to dance around our kitchen lamp.',
            '',
            'He does not hurry. Frogs can wait.',
            'He sits so still he looks asleep,',
            'then — quick as blinking — out it goes,',
            'that long pink ribbon of a tongue.',
            '',
            'By morning he has slipped away',
            'to somewhere cool and dark and damp,',
            'but on the window, small and round,',
            'he leaves five footprints and a smudge.',
          ] },
        ],
      },
      {
        id: '4abb2bb3-7679-48b9-aac2-160e1b6c1310',
        page: 7,
        title: 'Make a paper boat',
        type: 'procedure',
        blocks: [
          { kind: 'para', text: 'You will need one sheet of paper. Thin paper folds best. Do each fold carefully and press it flat.' },
          { kind: 'steps', items: [
            'Fold the paper in half so the short edges meet. Press the fold flat.',
            'Fold the two top corners down to the middle so they make a point.',
            'Fold the strip at the bottom up on each side to make a hat shape.',
            'Open the hat and push the two side points together to make a square.',
            'Fold the bottom corners of the square up to the top point.',
            'Hold the middle of the square and pull the two top points apart until a boat appears.',
          ] },
          { kind: 'factbox', title: 'Before you sail', items: ['Rub a candle over the paper to help the boat last longer in water.', 'Test the boat in a sink or a bucket, never in a creek or a pool on your own.'] },
        ],
      },
      {
        id: '4096bfb7-d979-4517-b9cf-2afadc3d7b53',
        page: 8,
        title: 'Junior Fun Run',
        type: 'persuasive',
        blocks: [
          { kind: 'quote', text: 'Run, jog or walk — every finisher gets a medal!' },
          { kind: 'para', text: 'The Riverside Junior Fun Run is on Sunday 14 June at Riverside Park. Money raised will buy new sports equipment for local primary schools.' },
          { kind: 'bullets', items: ['Bring a water bottle and wear a hat.', 'Every runner needs a grown-up with them at the park.', 'Entry is $5. Pay at the tent near the gate.'] },
          { kind: 'para', text: 'Come early to collect your number. Runners who arrive after their start time can still run, but they will not be timed.' },
        ],
        figure: {
          kind: 'data_table',
          title: 'Start times',
          columns: ['Race', 'Age', 'Starts'],
          rows: [['Dash', '5 to 7 years', '9:00 am'], ['1 km', '8 to 10 years', '9:30 am'], ['2 km', '11 to 13 years', '10:15 am']],
        },
      },
    ],
  },
  {
    id: 'reading-grade_3-2',
    yearLevel: 'grade_3',
    set: 2,
    texts: [
      {
        id: 'c8a4ee6c-b1f7-4380-8bb7-92fd46ea6597',
        page: 2,
        title: 'The blue ribbon',
        type: 'story',
        blocks: [
          { kind: 'para', text: 'Max had never liked the deep end. At swimming lessons he always stayed near the steps, where his feet could touch the bottom.' },
          { kind: 'para', text: '“The school swimming carnival is in two weeks,” said Mr Tran, the swimming coach. “Everyone in Year 3 can swim one lap.”' },
          { kind: 'para', text: 'Max’s stomach felt as if it were full of fish.' },
          { kind: 'para', text: 'That night he told his big sister, Lena. She did not laugh. “Then we practice,” she said. “Every afternoon.”' },
          { kind: 'para', text: 'So they did. On Monday Max floated on his back. On Wednesday he kicked across the pool holding a board. By Friday he could swim half a lap without stopping.' },
          { kind: 'para', text: 'On the day of the carnival, Max stood on the edge with five other swimmers. The whistle blew. He pushed off and swam, and swam, and swam. His arms ached. He could hear people shouting, but he did not look up.' },
          { kind: 'para', text: 'When his hand touched the wall, the other swimmers were already out of the pool. Max had come last.' },
          { kind: 'para', text: 'Then he saw Lena in the crowd, jumping up and down and waving. Mr Tran walked over and pinned a blue ribbon to his towel. It said Best Effort.' },
          { kind: 'para', text: 'Max had come last, but he had swum the whole lap. He did not stop smiling all day.' },
        ],
      },
      {
        id: 'c7359999-7442-4cef-9807-80f0de90a21b',
        page: 3,
        title: 'Pelican saved at Bellbird Lake',
        type: 'news',
        blocks: [
          { kind: 'note', text: 'By Sam Okafor, Bellbird News' },
          { kind: 'para', text: 'A pelican that was tangled in fishing line was rescued at Bellbird Lake on Sunday morning.' },
          { kind: 'para', text: 'Nine-year-old Chloe Martin saw the bird while she was walking her dog along the jetty. “One of its wings was stuck to its side,” Chloe said. “It kept trying to fly, but it just flapped in a circle.”' },
          { kind: 'para', text: 'Chloe’s mother called a wildlife rescue group. Two volunteers arrived in a small boat. They gently wrapped the pelican in a towel and cut away the line with special scissors.' },
          { kind: 'para', text: '“The towel keeps the bird calm,” said volunteer Priya Das. “If it cannot see, it is not so frightened.”' },
          { kind: 'para', text: 'The pelican has been taken to a wildlife hospital. Vets say it should be back on the lake in about two weeks.' },
          { kind: 'factbox', title: 'How you can help', items: ['Put old fishing line in the bins at the jetty.', 'If you see a hurt animal, do not touch it. Tell an adult.', 'Ask an adult to call a wildlife rescue group.'] },
        ],
      },
      {
        id: 'a8ae90e9-18f6-4128-bed3-fdaa5b98a66d',
        page: 4,
        title: 'Octopuses',
        type: 'report',
        columns: 2,
        blocks: [
          { kind: 'para', text: 'Octopuses are sea animals with soft bodies and eight arms. They have no bones at all, so they can squeeze through a gap not much bigger than a coin.' },
          { kind: 'para', text: 'Each arm is covered in suckers. The suckers can grip rocks and hold food. They can even taste whatever they touch.' },
          { kind: 'para', text: 'An octopus can change colour in less than a second. It turns brown, red or white to match the rocks and weed around it. This helps it hide from sharks and seals, and it helps it sneak up on crabs.' },
          { kind: 'para', text: 'If an octopus is in danger, it squirts a cloud of dark ink into the water. While the enemy cannot see, the octopus swims away.' },
          { kind: 'para', text: 'Octopuses are clever. Scientists have watched them open jars, solve puzzles and carry shells to use as shelters.' },
          { kind: 'factbox', title: 'Octopus facts', items: ['An octopus has three hearts.', 'Its blood is blue.', 'Most octopuses live for only one or two years.'] },
        ],
      },
      {
        id: '73b62823-6354-447e-a996-0cdcc2f7bf97',
        page: 5,
        title: 'Rainbow fruit sticks',
        type: 'procedure',
        blocks: [
          { kind: 'para', text: 'A cool, healthy snack for a hot day. Makes 6 sticks.' },
          { kind: 'heading', text: 'You will need' },
          { kind: 'bullets', items: ['6 strawberries', '1 small pineapple', '2 kiwi fruit', '18 blueberries', '6 wooden skewers', 'a chopping board and a knife'] },
          { kind: 'heading', text: 'What to do' },
          { kind: 'steps', items: [
            'Wash your hands and the fruit.',
            'Ask an adult to peel the pineapple and kiwi fruit and cut them into small cubes.',
            'Push a strawberry onto each skewer, then a piece of pineapple.',
            'Add a piece of kiwi fruit, then three blueberries.',
            'Keep going until each stick is full.',
            'Put the sticks in the fridge for 20 minutes so they are nice and cold.',
          ] },
          { kind: 'factbox', title: 'Safety tip', items: ['Skewers are sharp. Hold them by the flat end and point them away from your face.'] },
        ],
      },
      {
        id: '57195d86-97f2-44e1-b460-9c5e709b2751',
        page: 6,
        title: 'Wind',
        type: 'poem',
        blocks: [
          { kind: 'verse', lines: [
            'The wind came running down our street,',
            'it rattled every gate,',
            'it stole a hat from Mr Pike',
            'and made the washing wave.',
            '',
            'It whistled through the letterbox,',
            'it pushed the bins around,',
            'it tossed the autumn leaves up high',
            'then dropped them on the ground.',
            '',
            'At bedtime it was tired out,',
            'it curled up by the door,',
            'and all night long I heard it breathe',
            'a soft and sleepy snore.',
          ] },
        ],
      },
      {
        id: '4019abd7-43dc-4caf-ae43-2825fdf2a399',
        page: 7,
        title: 'Pip and the Quiet Roar',
        type: 'review',
        blocks: [
          { kind: 'note', text: 'Book review by Jack, Year 3' },
          { kind: 'para', text: 'Pip and the Quiet Roar by Elsa Moon is about a young dragon called Pip. All the other dragons can roar so loudly that the mountains shake, but when Pip tries, only a tiny squeak comes out.' },
          { kind: 'para', text: 'The other dragons laugh at Pip, so she runs away into the forest. There she meets a lost baby owl that is being chased by a fox. Pip cannot scare the fox away by roaring, so she has to think of another plan. I will not tell you what she does, because that would spoil the ending!' },
          { kind: 'para', text: 'My favourite part is when Pip sings to the baby owl to help it sleep. The pictures are bright and funny, and the words are easy to read.' },
          { kind: 'para', text: 'The only thing I did not like was that the book was too short. I wanted it to keep going.' },
          { kind: 'para', text: 'I think this book would be great for kids aged 5 to 9, and especially for anyone who feels different from everyone else.' },
          { kind: 'quote', text: 'My rating: 4 out of 5 stars' },
        ],
      },
      {
        id: '904ca47d-4a96-4342-ad39-89c459dcc928',
        page: 8,
        title: 'Holiday fun at Greenfield Library',
        type: 'web',
        blocks: [
          { kind: 'para', text: 'These school holidays, Greenfield Library has activities for children aged 5 to 12. Most activities are indoors, so they will go ahead even if it rains. The science show is outside in Greenfield Park, so wear a hat.' },
          { kind: 'bullets', items: ['All activities are free.', 'Book a place at the front desk or on this website.', 'Children under 8 must bring an adult.'] },
          { kind: 'para', text: 'Places fill up fast, so book early! If you cannot come, please tell us so that someone else can have your place.' },
        ],
        figure: {
          kind: 'data_table',
          title: 'Activities',
          columns: ['Activity', 'Day', 'Time'],
          rows: [['Lego building', 'Monday', '10:00 am'], ['Story time', 'Tuesday', '11:00 am'], ['Make a comic', 'Wednesday', '2:00 pm'], ['Science show', 'Thursday', '10:30 am'], ['Movie morning', 'Friday', '9:30 am']],
        },
      },
    ],
  },
  {
    id: 'reading-grade_3-3',
    yearLevel: 'grade_3',
    set: 3,
    texts: [
      {
        id: '7de6fc03-fd8b-4b9a-aef0-864da5ad96a5',
        page: 2,
        title: 'Grandma’s new phone',
        type: 'story',
        blocks: [
          { kind: 'para', text: 'Grandma bought her first mobile phone on a Tuesday. By Wednesday, Zoe had eleven messages from her.' },
          { kind: 'para', text: 'The first message was a photo of Grandma’s ear. The second was a photo of her thumb. The third just said HELLO ZOE IS THIS WORKING.' },
          { kind: 'para', text: '“Why is Grandma shouting?” asked Zoe’s little brother, Ben.' },
          { kind: 'para', text: '“She isn’t shouting,” laughed Zoe. “She just doesn’t know how to turn off the capital letters.”' },
          { kind: 'para', text: 'On Saturday, Zoe rode her bike to Grandma’s flat. She showed Grandma how to hold the phone the right way round for a photo, how to make the letters small and how to send a smiling face.' },
          { kind: 'para', text: 'Grandma practiced all afternoon. She took photos of her tea cup, her cat and the geraniums on the balcony.' },
          { kind: 'para', text: 'That night Zoe’s phone buzzed. It was a photo of the sunset over the sea, sharp and bright. Under it, Grandma had written: Thank you, my clever girl. Now it is my turn to teach you something. Bring your knitting needles next Saturday!' },
          { kind: 'para', text: 'Zoe smiled. She had never knitted anything in her life.' },
        ],
      },
      {
        id: '1a943783-ffb7-4d18-b084-b671b0f203bf',
        page: 3,
        title: 'How do bees make honey?',
        type: 'explanation',
        blocks: [
          { kind: 'para', text: 'Honey is made by honeybees. It takes a lot of hard work, and a whole hive of bees working together.' },
          { kind: 'para', text: 'A worker bee flies from flower to flower, drinking a sweet liquid called nectar. She stores the nectar in a special part of her body called a honey stomach.' },
          { kind: 'para', text: 'Back at the hive, she passes the nectar to a younger bee. That bee chews it and passes it on again. Each time, the nectar gets a little thicker.' },
          { kind: 'para', text: 'Next, the bees spread the nectar into the small six-sided rooms of the honeycomb, called cells. They fan it with their wings to dry out the water. Slowly, the runny nectar turns into thick, sticky honey.' },
          { kind: 'para', text: 'Finally, the bees cover each full cell with a lid of wax. The honey keeps there for months, ready to feed the hive through winter.' },
        ],
        figure: {
          kind: 'flow',
          steps: [
            { text: 'A bee drinks nectar' },
            { text: 'Bees pass it from bee to bee' },
            { text: 'Bees fan it dry in the cells' },
            { text: 'Cells are covered with wax' },
          ],
        },
        figureCaption: 'How nectar becomes honey',
      },
      {
        id: '93aefda4-7c41-4b9c-83af-ee542a613174',
        page: 4,
        title: 'Every class needs a pet',
        type: 'persuasive',
        blocks: [
          { kind: 'note', text: 'A speech by Aiden, Year 3' },
          { kind: 'para', text: 'Good morning, everyone. Today I am going to tell you why every class in our school should have a pet.' },
          { kind: 'para', text: 'First, a pet teaches us to be responsible. If our class had a guinea pig, we would take turns to feed it, give it fresh water and clean its cage. Nobody would want it to go hungry.' },
          { kind: 'para', text: 'Second, a pet makes a classroom calmer. When I stroke my dog at home, I feel relaxed. I think a class pet would help children who feel worried or upset.' },
          { kind: 'para', text: 'Third, a pet helps us learn. We could measure how much our guinea pig grows, write stories about it and find out what it needs to stay healthy.' },
          { kind: 'para', text: 'Some people say pets are noisy or messy. But a guinea pig is small and quiet, and if we clean its cage every Friday it will not be messy at all.' },
          { kind: 'para', text: 'So please vote yes for class pets. Our classrooms will be happier, calmer and smarter places. Thank you.' },
        ],
      },
      {
        id: 'b6867e34-7ef0-4e37-aaf0-d6b959d56c89',
        page: 5,
        title: 'Thank you, Ranger Kim',
        type: 'letter',
        blocks: [
          { kind: 'note', text: 'Dear Ranger Kim' },
          { kind: 'para', text: 'Thank you for showing Class 3K around Blue Gum National Park last Thursday. We had the best day.' },
          { kind: 'para', text: 'Our favourite part was the night walk. We never knew that sugar gliders could glide further than the length of a netball court! When you shone the red torch into the trees, we saw two of them eating. You told us that red light does not frighten animals the way white light does.' },
          { kind: 'para', text: 'We also learned why we must stay on the track. If people walk off the track, they crush small plants and the homes of lizards and insects.' },
          { kind: 'para', text: 'When we got back to school, we made posters about looking after the bush. We have put them up in the library so the whole school can see them.' },
          { kind: 'para', text: 'We hope we can visit again next year.' },
          { kind: 'note', text: 'From Class 3K, Wattle Hill Primary School' },
        ],
      },
      {
        id: '4f3b68de-ab63-479a-b1af-819b5e43efc5',
        page: 6,
        title: 'Night market',
        type: 'poem',
        blocks: [
          { kind: 'verse', lines: [
            'Lanterns hang like paper moons,',
            'the smoky grill goes hiss,',
            'a man is spinning sugar clouds —',
            'I’ve never tasted this!',
            '',
            'The noodles curl like yellow string,',
            'the dumplings steam and pop,',
            'a drummer taps a happy beat',
            'that makes my feet go hop.',
            '',
            'We walk home slowly, full and warm,',
            'the stars come out to see,',
            'and in my pocket, wrapped in foil,',
            'a dumpling just for me.',
          ] },
        ],
      },
      {
        id: '8ee4f2de-bd09-4db8-b3da-7a08824f2e5b',
        page: 7,
        title: 'Emus',
        type: 'report',
        columns: 2,
        blocks: [
          { kind: 'para', text: 'The emu is Australia’s largest bird. An adult emu can be taller than a grown-up person and weigh as much as a big dog.' },
          { kind: 'para', text: 'Emus cannot fly. Their wings are tiny, only about as long as a pencil. Instead of flying, emus run. They have long, strong legs and can run faster than a car in a school zone.' },
          { kind: 'para', text: 'Emus eat seeds, fruit, flowers and insects. When they eat fruit, the seeds pass through their bodies and are dropped in new places, where they can grow into new plants.' },
          { kind: 'para', text: 'The female emu lays the eggs, but the male does the rest. He sits on the eggs for about eight weeks and hardly eats or drinks the whole time. After the chicks hatch, he looks after them for many months.' },
          { kind: 'factbox', title: 'Emu facts', items: ['Emu eggs are dark green.', 'Emu chicks have stripes, which help them hide in the grass.', 'The emu is on Australia’s coat of arms.'] },
        ],
      },
      {
        id: 'f00df197-ee7e-4ffa-834a-a7957f1642b2',
        page: 8,
        title: 'Lost dog',
        type: 'notice',
        blocks: [
          { kind: 'quote', text: 'Please help us find Biscuit!' },
          { kind: 'para', text: 'Biscuit went missing from Acacia Street on Sunday afternoon when our gate was left open. He is friendly but shy, and he may hide if you call him loudly.' },
          { kind: 'heading', text: 'What Biscuit looks like' },
          { kind: 'bullets', items: ['small brown dog with one white ear', 'red collar with a silver bell', 'very fluffy tail'] },
          { kind: 'heading', text: 'If you see him' },
          { kind: 'bullets', items: ['Do not chase him. Sit down and hold out your hand.', 'Knock on the door of 14 Acacia Street, or tell a grown-up.'] },
          { kind: 'para', text: 'A reward of $50 will be given to the person who brings Biscuit home.' },
          { kind: 'note', text: 'Thank you! From Hana and Leo' },
        ],
      },
    ],
  },
  {
    id: 'reading-grade_5-1',
    yearLevel: 'grade_5',
    set: 1,
    texts: [
      {
        id: '56ba0211-7562-4b33-8c35-945f034a5122',
        page: 2,
        title: 'The violin',
        type: 'story',
        blocks: [
          { kind: 'para', text: 'Anika’s grandfather kept his violin in a case under his bed. The case was black and scratched, and the clasps squeaked when you opened them.' },
          { kind: 'para', text: '“I played this on the ship that brought me to Australia,” Dadu told her. “Every night, for six weeks. It was the only thing that stopped me feeling homesick.”' },
          { kind: 'para', text: 'When Anika was nine, he put the case in her arms. “It is yours now,” he said. “My fingers are too stiff to play, but yours are not.”' },
          { kind: 'para', text: 'Anika was delighted — until she tried to play it. The bow screeched across the strings like a cat whose tail had been stepped on. Her dog, Pepper, got up and left the room.' },
          { kind: 'para', text: 'For weeks, every note came out wrong. Her fingers ached. Twice she put the violin back in its case and announced that she was giving up. Both times, the next afternoon, she opened the squeaky clasps again.' },
          { kind: 'para', text: 'Slowly, the screeches turned into notes, and the notes turned into tunes. By winter she could play the song Dadu used to hum while he cooked, a gentle, rocking tune from the village where he grew up. Her teacher helped her write it down, because nobody had ever written it down before.' },
          { kind: 'para', text: 'On Dadu’s eightieth birthday, the family squeezed into his small lounge room. Anika lifted the violin to her chin. Her hands were shaking. She took a deep breath and began to play.' },
          { kind: 'para', text: 'Halfway through, she looked up. Dadu’s eyes were closed and there were tears on his cheeks. Anika almost stopped, but her mother gave a tiny nod, so she kept going.' },
          { kind: 'para', text: 'When the last note faded, Dadu opened his eyes. “For sixty years that song lived only in my head,” he said quietly. “Now it lives in yours.”' },
        ],
      },
      {
        id: 'a197b8e8-7adc-4afa-b574-01481abf3891',
        page: 3,
        title: 'Antarctica',
        type: 'report',
        columns: 2,
        blocks: [
          { kind: 'para', text: 'Antarctica is the continent at the very bottom of the world. It is the coldest, windiest and driest continent on Earth. Almost all of it is covered by a sheet of ice that is, in places, more than four kilometres thick.' },
          { kind: 'heading', text: 'A frozen desert' },
          { kind: 'para', text: 'Although Antarctica is covered in ice, very little new snow falls there each year. Because it gets so little rain or snow, scientists call it a desert. In winter, the temperature can drop below minus 80 degrees Celsius.' },
          { kind: 'heading', text: 'Who lives there?' },
          { kind: 'para', text: 'No people live in Antarctica permanently. About a thousand scientists and support staff stay through the winter, and several thousand more arrive in summer. They study the ice, the weather and the animals.' },
          { kind: 'para', text: 'The animals that live there are suited to the cold. Emperor penguins huddle together in groups of thousands to keep warm. Seals have a thick layer of fat, called blubber, under their skin.' },
          { kind: 'heading', text: 'Protecting Antarctica' },
          { kind: 'para', text: 'In 1959, twelve countries signed an agreement called the Antarctic Treaty. They agreed that Antarctica would be used only for peaceful purposes and for science. Today more than fifty countries have signed it, and mining is not allowed.' },
          { kind: 'factbox', title: 'Antarctica at a glance', items: ['Size: almost twice as big as Australia', 'Lowest temperature recorded: minus 89 degrees Celsius', 'Its ice holds about 70 per cent of the world’s fresh water'] },
        ],
      },
      {
        id: '253c0ea2-49d6-4d30-acaf-36310338ebeb',
        page: 4,
        title: 'Should homework be banned?',
        type: 'persuasive',
        blocks: [
          { kind: 'note', text: 'Two readers wrote to the Hillview Gazette.' },
          { kind: 'heading', text: 'Yes — let kids be kids' },
          { kind: 'para', text: 'After six hours at school, children need time to play, rest and be with their families. Many nights my son spends an hour on homework sheets that he could finish in ten minutes if they were not so boring. By the time he is done, it is dark, and he has missed his chance to kick a ball in the park.' },
          { kind: 'para', text: 'Some people say homework teaches children to work on their own. But children can learn that at school, with a teacher there to help. Let’s ban homework and give childhood back to our kids.' },
          { kind: 'note', text: 'Maria Costa, parent' },
          { kind: 'heading', text: 'No — practice makes progress' },
          { kind: 'para', text: 'I am in Year 5 and I think homework is useful. When I practice my times tables at home, I remember them better in class the next day. Homework also shows my parents what I am learning, so they can help me.' },
          { kind: 'para', text: 'I agree that homework should not be boring or take too long. Twenty minutes a night is plenty. But banning it completely would be like a soccer team that only trains on game day.' },
          { kind: 'note', text: 'Tom Nguyen, age 10' },
        ],
      },
      {
        id: '7cff2b63-6079-49ec-ad16-eb62805f33e6',
        page: 5,
        title: 'Make a floating compass',
        type: 'procedure',
        blocks: [
          { kind: 'para', text: 'Long before phones and GPS, travellers used compasses to find their way. You can make a simple compass with things from around the house.' },
          { kind: 'heading', text: 'You will need' },
          { kind: 'bullets', items: ['a sewing needle', 'a small magnet (a fridge magnet will do)', 'a slice of cork, or a small piece of foam', 'a shallow bowl of water'] },
          { kind: 'heading', text: 'What to do' },
          { kind: 'steps', items: [
            'Hold the needle by its eye. Stroke the magnet along the needle from the eye to the point about 30 times. Always stroke in the same direction, and lift the magnet away at the end of each stroke.',
            'Carefully push the needle through the cork, or lay it on top of the foam.',
            'Float the cork in the middle of the bowl of water, away from any metal.',
            'Watch as the needle slowly turns and settles. One end now points north.',
          ] },
          { kind: 'factbox', title: 'How does it work?', items: ['Stroking the needle with a magnet turns the needle into a weak magnet.', 'The Earth acts like a giant magnet, so a magnet that is free to turn lines up north to south.', 'Metal objects can pull the needle the wrong way, so keep them away from your compass.'] },
        ],
      },
      {
        id: '268428c5-2156-411b-a7d7-f9f0915431de',
        page: 6,
        title: 'When the rain came',
        type: 'poem',
        blocks: [
          { kind: 'verse', lines: [
            'All summer long the paddocks cracked',
            'like crusts of burnt-brown bread;',
            'the creek became a dusty track,',
            'the gum leaves hung like lead.',
            '',
            'Each evening Dad would watch the west,',
            'his hat pulled low and still;',
            'the clouds rolled in, then rolled away',
            'and left the empty hill.',
            '',
            'Then late one night the thunder rolled,',
            'the tin roof drummed and rang;',
            'we ran outside into the cold',
            'and splashed and laughed and sang.',
            '',
            'By morning, green was creeping back',
            'where only dust had been,',
            'and Dad was smiling by the creek —',
            'the first in months I’d seen.',
          ] },
        ],
      },
      {
        id: '3a5e0eef-465a-4b83-8bd7-4fbd04d5f1cd',
        page: 7,
        title: 'Meet a volcano scientist',
        type: 'interview',
        blocks: [
          { kind: 'para', text: 'Dr Lena Park studies volcanoes. Year 5 reporter Kai Thompson asked her about her job.' },
          { kind: 'heading', text: 'What does a volcano scientist do?' },
          { kind: 'para', text: 'We try to work out when a volcano might erupt, so that people living nearby can get to safety in time. We measure tiny earthquakes, changes in the shape of the ground and the gases coming out of the volcano.' },
          { kind: 'heading', text: 'Have you ever been close to an eruption?' },
          { kind: 'para', text: 'Yes, in Hawaii. I stood about a hundred metres from a river of lava. The heat on my face felt like opening an oven door. It was the most amazing thing I have ever seen, but we never go closer than it is safe to be.' },
          { kind: 'heading', text: 'Can scientists tell exactly when a volcano will erupt?' },
          { kind: 'para', text: 'Not exactly, not yet. It is a bit like a weather forecast. We can say that an eruption is likely soon, but not the exact day or hour. That is why we watch our volcanoes all day, every day.' },
          { kind: 'heading', text: 'What advice would you give a kid who wants to do your job?' },
          { kind: 'para', text: 'Be curious and ask lots of questions. Work hard at maths and science, and get outside! Rocks are everywhere, and every one of them has a story.' },
        ],
      },
      {
        id: '2d762d85-01ef-42bc-900d-0ee2dd76186a',
        page: 8,
        title: 'Ask Dr Paws',
        type: 'web',
        blocks: [
          { kind: 'para', text: 'Every week, vet Dr Sam Ahmed answers readers’ questions about their pets.' },
          { kind: 'heading', text: 'My dog ate a chocolate biscuit. Should I be worried?' },
          { kind: 'para', text: 'Chocolate contains a chemical that is poisonous to dogs, and dark chocolate is the most dangerous kind. One biscuit may not harm a big dog, but it could make a small dog very sick. Call your vet straight away and tell them what your dog ate, how much it ate and how big your dog is.' },
          { kind: 'heading', text: 'How often should I wash my cat?' },
          { kind: 'para', text: 'Almost never! Cats keep themselves clean with their rough tongues. Only wash a cat if it has rolled in something sticky or smelly, and use a shampoo made for cats.' },
          { kind: 'heading', text: 'Why does my rabbit chew everything?' },
          { kind: 'para', text: 'A rabbit’s teeth never stop growing. Chewing wears them down, so give your rabbit plenty of hay and safe wooden toys, and keep electrical cords out of reach.' },
        ],
      },
    ],
  },
  {
    id: 'reading-grade_5-2',
    yearLevel: 'grade_5',
    set: 2,
    texts: [
      {
        id: 'd8ca2412-921b-4b65-95a6-7a0388bb1a44',
        page: 2,
        title: 'The map behind the wallpaper',
        type: 'story',
        blocks: [
          { kind: 'para', text: 'Grandma’s house was ninety years old, and Mum said it was falling apart. So in the summer holidays, the whole family came to help fix it up.' },
          { kind: 'para', text: 'Rosa and her cousin Sam were given the worst job: scraping the old wallpaper off the walls of the back bedroom. It was covered in faded pink roses, and it came off in tiny, stubborn strips.' },
          { kind: 'para', text: '“This is taking forever,” Sam groaned, flicking a curl of paper off his scraper.' },
          { kind: 'para', text: 'Rosa didn’t answer. Behind the roses, something was drawn on the plaster in pencil. She scraped more carefully, and slowly a picture appeared: a wobbly outline of the backyard, the big lemon tree, the shed — and a small, dark X beside the back fence.' },
          { kind: 'para', text: 'Underneath, in round, careful letters, someone had written: M.B. aged 10. Do not dig until 2025.' },
          { kind: 'para', text: '“M.B.,” whispered Sam. “Margaret Bell. That’s Grandma!”' },
          { kind: 'para', text: 'They ran to find her. Grandma was on the veranda with a cup of tea. When they told her about the map, she put the cup down so quickly that it rattled.' },
          { kind: 'para', text: '“I had forgotten all about that,” she said slowly. “I buried a tin the summer I turned ten. I wanted to see what the future would be like when I opened it.”' },
          { kind: 'para', text: 'It took an hour of digging beside the fence before Sam’s spade hit metal. Inside the rusty tin were six glass marbles, a black-and-white photo of a girl on a bicycle and a letter folded very small.' },
          { kind: 'para', text: 'Grandma unfolded the letter and read it aloud. “Dear future me, do people still ride bikes? Do you still like lemons? I hope you have had lots of adventures.”' },
          { kind: 'para', text: 'Grandma laughed until her eyes were wet. Then she picked a lemon from the tree and took a big bite.' },
        ],
      },
      {
        id: 'fa17b047-9b4f-44c7-8def-cfe9002e733f',
        page: 3,
        title: 'How does a submarine dive?',
        type: 'explanation',
        blocks: [
          { kind: 'para', text: 'A submarine is a ship that can travel under the water as well as on top of it. To dive and to rise again, it changes how heavy it is.' },
          { kind: 'para', text: 'A submarine has large spaces called ballast tanks between its inner and outer walls. When the submarine is floating on the surface, these tanks are full of air. Air is much lighter than water, so the submarine floats, just as a plastic bottle full of air bobs on the surface of a bath.' },
          { kind: 'para', text: 'To dive, the crew open valves that let seawater rush into the tanks. The water pushes the air out. Now the submarine is heavier, and it begins to sink.' },
          { kind: 'para', text: 'To rise again, the crew blow air from high-pressure tanks into the ballast tanks. The air pushes the water out through the bottom. The submarine becomes lighter and floats back up to the surface.' },
          { kind: 'para', text: 'By letting in just the right amount of water, the crew can make the submarine hover at any depth, neither rising nor sinking. Small fins called hydroplanes help steer it up or down as it moves forward.' },
        ],
        figure: {
          kind: 'flow',
          cycle: true,
          steps: [
            { text: 'Tanks full of air: it floats', then: 'let seawater in' },
            { text: 'Tanks full of water: it sinks', then: 'blow air in' },
            { text: 'Air pushes water out: it rises', then: 'back at the surface' },
          ],
        },
        figureCaption: 'How a submarine dives and rises',
      },
      {
        id: '0507006b-b26c-4335-87cd-7582355617a6',
        page: 4,
        title: 'Students clear 212 kilograms of rubbish from creek',
        type: 'news',
        blocks: [
          { kind: 'note', text: 'Bayside Herald' },
          { kind: 'para', text: 'More than sixty students from Bayside Primary School spent Saturday morning pulling rubbish out of Mangrove Creek, and what they found shocked them.' },
          { kind: 'para', text: 'In just three hours, the students and their families collected 212 kilograms of rubbish from the banks and shallow water of the creek. They found a shopping trolley, two car tyres and a garden chair, but most of what they picked up was much smaller.' },
          { kind: 'para', text: '“We thought we would find big things,” said Year 5 student Jarrah Collins, who organised the event with his class. “But the worst part was the thousands of tiny pieces of plastic. Birds and fish think they are food.”' },
          { kind: 'para', text: 'Council officer Deb Nguyen said the clean-up had made a real difference. “Rubbish from the streets washes down the drains and into the creek every time it rains,” she said. “This creek flows into the bay, so what these students did will help the whole bay.”' },
          { kind: 'para', text: 'The students plan to hold another clean-up in autumn. They are also asking shops near the creek to stop giving out plastic straws.' },
        ],
        figure: {
          kind: 'data_table',
          title: 'What the students collected',
          columns: ['Type of rubbish', 'Number of pieces'],
          rows: [['Plastic bottles', '430'], ['Food wrappers', '615'], ['Plastic straws', '288'], ['Cans', '174'], ['Large items', '6']],
        },
      },
      {
        id: 'ebff407c-ab33-479f-9383-b5658039d02f',
        page: 5,
        title: 'Wildwood Adventure Park',
        type: 'persuasive',
        blocks: [
          { kind: 'quote', text: 'Wildwood — where every day is an adventure!' },
          { kind: 'para', text: 'Bored of the same old weekend? Swap the couch for the trees at Wildwood Adventure Park, just 40 minutes from the city!' },
          { kind: 'bullets', items: ['Fly through the forest on our giant flying fox*', 'Climb the Giant’s Ladder, 20 metres above the ground*', 'Cool off on the Rapids Ride — you will get wet!', 'Feed the goats and alpacas at Wildwood Farm'] },
          { kind: 'para', text: 'Thousands of happy families visit every year. Don’t miss out — the best adventures fill up fast!' },
          { kind: 'note', text: '*Riders on the flying fox and the Giant’s Ladder must be at least 120 cm tall. All tickets must be booked online.' },
        ],
        figure: {
          kind: 'data_table',
          title: 'Ticket prices',
          columns: ['Ticket', 'Price'],
          rows: [['Child (5 to 15)', '$29'], ['Adult', '$39'], ['Family (2 adults, 2 children)', '$110'], ['Under 5', 'Free']],
        },
      },
      {
        id: '02026c54-f707-469a-aef8-09b6c2674484',
        page: 6,
        title: 'What’s in my pocket?',
        type: 'poem',
        blocks: [
          { kind: 'verse', lines: [
            'A stone that looks a bit like Mum,',
            'a rubber band, a lump of gum,',
            'a magpie feather, black and white,',
            'a bottle top I found last night.',
            '',
            'A ticket from the Easter show,',
            'a note from Jess that says HELLO,',
            'a shell with sand still in its curl,',
            'a marble with a milky swirl.',
            '',
            'A key that doesn’t fit our door,',
            'a crayon worn down to the core —',
            'and something wriggling. Oh, no, Fred!',
            '“So that’s where your frog went,” I said.',
          ] },
        ],
      },
      {
        id: 'd983081e-5f2f-43eb-89fa-817155ccc094',
        page: 7,
        title: 'Mary Anning, fossil hunter',
        type: 'report',
        blocks: [
          { kind: 'para', text: 'Mary Anning was born in 1799 in Lyme Regis, a small town on the south coast of England. The cliffs near her home were crumbling and full of fossils — the stony remains of animals that lived millions of years ago.' },
          { kind: 'para', text: 'Mary’s family was poor. Her father collected fossils and sold them to tourists, and he taught Mary and her brother Joseph how to find them. After he died, when Mary was only eleven, fossil hunting helped the family survive.' },
          { kind: 'para', text: 'Around 1811, Joseph found the skull of a strange creature in the cliffs. Mary searched for months and dug out the rest of its skeleton. It was an ichthyosaur, a sea reptile that looked a little like a dolphin. Few scientists had ever seen such a complete one.' },
          { kind: 'para', text: 'In 1823, Mary found the first complete skeleton of a plesiosaur, a sea reptile with a very long neck. Some experts did not believe it was real until they had examined it for themselves.' },
          { kind: 'para', text: 'Many scientists bought her fossils and asked for her advice, but Mary was not allowed to join the Geological Society of London, because it did not accept women. Often, the men who bought her fossils took the credit for her discoveries.' },
          { kind: 'para', text: 'Mary Anning died in 1847. Today she is remembered as one of the most important fossil hunters in history.' },
        ],
      },
      {
        id: '683d9c6f-9fed-4db0-89aa-a3ca62da6143',
        page: 8,
        title: 'How to play Four Square',
        type: 'procedure',
        blocks: [
          { kind: 'para', text: 'Four Square is a fast ball game played on a court divided into four squares. You need four players at a time, a bouncy ball, and anyone else waiting in a line.' },
          { kind: 'heading', text: 'The court' },
          { kind: 'para', text: 'Draw a large square on the ground, about three metres on each side, and divide it into four smaller squares. Number them 1 to 4. The player in square 4 is the King, and the King serves.' },
          { kind: 'heading', text: 'How to play' },
          { kind: 'steps', items: [
            'The King bounces the ball once in their own square, then hits it into another player’s square.',
            'The player in that square must let the ball bounce once, then hit it with their hands into any other square.',
            'Play continues until someone breaks a rule.',
            'The player who breaks a rule leaves the court. Everyone in a lower square moves up one, and the first person in the line joins in square 1.',
          ] },
          { kind: 'factbox', title: 'You are out if', items: ['the ball bounces twice in your square', 'you hit the ball before it bounces', 'you hit the ball outside the court', 'you catch or carry the ball'] },
        ],
      },
    ],
  },
  {
    id: 'reading-grade_5-3',
    yearLevel: 'grade_5',
    set: 3,
    texts: [
      {
        id: '6761590d-a1be-43ff-b1ae-35fd3b0285b5',
        page: 2,
        title: 'The new kid',
        type: 'story',
        blocks: [
          { kind: 'para', text: 'On the first day of Term 2, a new boy stood at the front of Class 5P, holding his bag in front of him like a shield.' },
          { kind: 'para', text: '“This is Yusuf,” said Mr Peters. “He has just moved here, and he is still learning English. I know you will all make him welcome.”' },
          { kind: 'para', text: 'Yusuf sat at the desk next to Priya. He did not say a word all morning. At lunch he ate by himself on the bench near the canteen, and Priya felt a small, uncomfortable ache in her chest every time she looked over.' },
          { kind: 'para', text: 'The next day, Priya noticed that Yusuf was drawing in the back of his maths book. She leaned over to look. It was a comic: a cat in a spacesuit, floating past the moon, chasing a fish-shaped rocket. The drawings were so good that Priya forgot she was supposed to be doing long division.' },
          { kind: 'para', text: '“Wow,” she whispered. Yusuf looked up, worried, and closed the book.' },
          { kind: 'para', text: 'That night Priya dug out her own comic from under her bed. It was about a superhero chicken called Captain Cluck. The drawings were not nearly as good, but the jokes were funny.' },
          { kind: 'para', text: 'In the morning she slid it onto Yusuf’s desk. He turned the pages slowly. When he reached the part where Captain Cluck sneezed and blew a bank robber into a pond, his shoulders began to shake. He was laughing.' },
          { kind: 'para', text: 'He pointed at the chicken, then at his cat. Then he drew a small box on a fresh page and, inside it, a cat in a spacesuit shaking hands with a chicken in a cape.' },
          { kind: 'para', text: 'For the rest of the term, Priya wrote the stories and Yusuf drew the pictures. Their comic, The Space Cat and Captain Cluck, grew to thirty pages. At the school fete they sold fifty copies and gave the money to the library.' },
          { kind: 'para', text: 'On the last day of term, Yusuf handed Priya a folded piece of paper. Inside was a drawing of the two of them, and underneath, in careful English letters, he had written one word: Friends.' },
        ],
      },
      {
        id: 'bd16eb98-9aad-4581-9a8b-e587ae6a28af',
        page: 3,
        title: 'The platypus',
        type: 'report',
        columns: 2,
        blocks: [
          { kind: 'para', text: 'The platypus is one of the strangest animals in the world. It has a bill like a duck, a flat tail like a beaver and webbed feet like an otter. When the first platypus skin was sent from Australia to England in 1798, some scientists thought it was a joke — a duck’s bill sewn onto a furry body.' },
          { kind: 'heading', text: 'A mammal that lays eggs' },
          { kind: 'para', text: 'The platypus is a mammal. It has fur and feeds its babies milk. But unlike almost every other mammal, the platypus lays eggs. The only other mammals that lay eggs are echidnas. The mother lays one or two soft, leathery eggs in a burrow and curls around them to keep them warm.' },
          { kind: 'heading', text: 'Hunting with its bill' },
          { kind: 'para', text: 'A platypus hunts in creeks and rivers, mostly at night. When it dives, it closes its eyes, ears and nose. It finds food with its bill, which can sense the tiny electric signals made by shrimps, worms and insect larvae as they move.' },
          { kind: 'heading', text: 'Watch out!' },
          { kind: 'para', text: 'The male platypus has a sharp spur on each back ankle. The spur can deliver venom strong enough to kill a dog, and it causes terrible pain to people.' },
          { kind: 'factbox', title: 'Platypus facts', items: ['Lives only in eastern Australia, including Tasmania', 'Length: about 50 centimetres, including the tail', 'Stores fat in its tail for times when food is hard to find'] },
        ],
      },
      {
        id: '8def7d66-519c-4a96-b99b-b9914a7cf2ed',
        page: 4,
        title: 'Our playground needs fixing',
        type: 'letter',
        blocks: [
          { kind: 'note', text: 'To the Mayor, Riverside Council' },
          { kind: 'para', text: 'We are writing to ask the council to fix the playground in Hollis Park. The slide has a crack down the middle, two swings are missing their seats, and the soft rubber under the climbing frame has worn away, so the ground underneath is hard concrete.' },
          { kind: 'para', text: 'Last month, a boy in Year 2 fell off the climbing frame and broke his wrist. We think that if the soft rubber had been there, he might not have been hurt so badly.' },
          { kind: 'para', text: 'Lots of families use Hollis Park every day. It is the only playground in our suburb. Please fix it before someone else gets hurt.' },
          { kind: 'note', text: 'Year 5 students, Hollis Primary School' },
          { kind: 'heading', text: 'The council’s reply' },
          { kind: 'para', text: 'Dear students, thank you for your letter. You are right that the playground needs work, and we are sorry to hear about the student who was injured.' },
          { kind: 'para', text: 'Our workers inspected the playground the day after your letter arrived. The slide and the climbing frame have been fenced off so that no one uses them until they are safe. New swing seats will be fitted next week, and the whole playground will be rebuilt in March, with new soft rubber under every piece of equipment.' },
          { kind: 'para', text: 'We would like to invite your class to help choose the new equipment. Your teacher will receive an invitation soon.' },
          { kind: 'note', text: 'Councillor Anna Lee, Riverside Council' },
        ],
      },
      {
        id: '0aa97b0b-ad12-4a7b-8a1b-031827d60f5c',
        page: 5,
        title: 'Grow a bean in a jar',
        type: 'procedure',
        blocks: [
          { kind: 'para', text: 'Have you ever wondered what happens under the soil when a seed starts to grow? In this experiment, you can watch it happen.' },
          { kind: 'heading', text: 'You will need' },
          { kind: 'bullets', items: ['a clear glass jar', 'paper towel', 'three dried broad beans', 'water'] },
          { kind: 'heading', text: 'What to do' },
          { kind: 'steps', items: [
            'Fold two sheets of paper towel and line the inside of the jar with them.',
            'Push the beans between the paper towel and the glass, about halfway down, so you can see them from outside.',
            'Pour a little water into the bottom of the jar so the paper towel is damp but not dripping.',
            'Put the jar somewhere warm and bright, but out of direct sunlight.',
            'Check the jar every day. Add a little water if the paper towel starts to dry out, and write down what you see.',
          ] },
          { kind: 'para', text: 'Here is what one student recorded.' },
        ],
        figure: {
          kind: 'data_table',
          title: 'Observations',
          columns: ['Day', 'What I saw'],
          rows: [['Day 1', 'The beans are hard and dry.'], ['Day 3', 'The beans are bigger and their skins are wrinkly.'], ['Day 5', 'A small white root is growing down.'], ['Day 8', 'A green shoot is growing up towards the light.'], ['Day 12', 'The shoot has two leaves.']],
        },
      },
      {
        id: '33518661-b1e7-4be9-bd51-25a771135cee',
        page: 6,
        title: 'Fishing with Pop',
        type: 'poem',
        blocks: [
          { kind: 'verse', lines: [
            'We’re on the jetty before the sun,',
            'my grandpa, me and a bucket of bait,',
            'the water flat as a sheet of glass,',
            'the gulls already lined up to wait.',
            '',
            'Pop doesn’t talk much. He shows me how',
            'to thread the hook and cast out wide,',
            'then hands me a thermos cup of tea',
            'and we sit there, watching the turning tide.',
            '',
            'We don’t catch much — one tiny bream',
            'we slip back in to grow some more —',
            'but I come home with a sunburnt nose',
            'and a feeling I can’t find words for.',
          ] },
        ],
      },
      {
        id: '653bdd09-078a-4ca1-a560-483371401147',
        page: 7,
        title: 'How is a rainbow made?',
        type: 'explanation',
        blocks: [
          { kind: 'para', text: 'A rainbow is one of the most beautiful sights in nature, but it is really just sunlight and water working together.' },
          { kind: 'para', text: 'Sunlight looks white, but it is actually made of many colours mixed together: red, orange, yellow, green, blue, indigo and violet.' },
          { kind: 'para', text: 'When sunlight shines into a raindrop, the light bends as it passes from the air into the water. Each colour bends by a slightly different amount, so the white light spreads out into its colours, like a fan opening.' },
          { kind: 'para', text: 'The light then bounces off the back of the raindrop and bends again as it comes out. Millions of raindrops do this at once. Each drop sends one colour towards your eyes, depending on where it is in the sky, and together they make the arc of a rainbow.' },
          { kind: 'para', text: 'To see a rainbow, you need the sun behind you and rain in front of you. That is why rainbows often appear in the late afternoon, when the sun is low and a shower is passing.' },
        ],
        figure: {
          kind: 'flow',
          steps: [
            { text: 'Sunlight enters a raindrop' },
            { text: 'Light bends and splits into colours' },
            { text: 'Light bounces off the back of the drop' },
            { text: 'Colours come out towards your eyes' },
          ],
        },
        figureCaption: 'Inside one raindrop',
      },
      {
        id: '830a4251-31f5-4ba7-8a6f-ac4cbe2fb292',
        page: 8,
        title: 'Stay safe online',
        type: 'web',
        blocks: [
          { kind: 'para', text: 'The internet is a great place to learn, play and talk with friends. But just like crossing a road, it is safer when you know the rules.' },
          { kind: 'heading', text: 'Keep private things private' },
          { kind: 'para', text: 'Never share your full name, address, school, phone number or passwords online. A password is like the key to your house: you would not give it to a stranger.' },
          { kind: 'heading', text: 'Think before you post' },
          { kind: 'para', text: 'Anything you put online can be copied and shared, even if you delete it later. Before you post a photo or a comment, ask yourself: would I be happy for my teacher or my grandparent to see this?' },
          { kind: 'heading', text: 'Be kind' },
          { kind: 'para', text: 'Treat people online the way you would treat them face to face. If someone is being unkind to you or to someone else, do not reply. Take a screenshot and tell an adult you trust.' },
          { kind: 'heading', text: 'If something feels wrong, tell someone' },
          { kind: 'para', text: 'If anything online makes you feel scared, confused or uncomfortable, close it and talk to a parent, carer or teacher. You will not be in trouble for telling.' },
        ],
      },
    ],
  },
]

/** Every magazine text, by id — the lookup the exam builder and the PDF use. */
export const READING_TEXTS = new Map(MAGAZINES.flatMap(m => m.texts.map(t => [t.id, { ...t, magazine: m }] as const)))
