// Types for static image imports (`import page from '@/assets/samples/x.webp'`).
//
// Next normally provides these through next-env.d.ts, but that file is
// generated by `next dev`/`next build` and is gitignored, so on a clean
// checkout — which is what CI type-checks, before it builds — there is no
// declaration for *.webp and every sample-page import fails with TS2307.
// Referencing Next's own declarations here keeps them present either way;
// TypeScript includes the file once even when next-env.d.ts also exists.
/// <reference types="next/image-types/global" />
