#!/usr/bin/env node
// Builds src/lib/questions/exams.ts — fixed, pre-composed practice exams
// (as opposed to the custom exam builder on /practice, which mixes topics
// on demand). 3 exams per subject+grade for the general subjects, 5 for
// Further Mathematics and Maths Methods (their Unit 1&2 pool is deliberately
// sized for that). Each question is reused at most twice across a subject's
// exams, picked greedily by least-used-first so usage stays balanced.
//
// Safe to re-run whenever bank.ts changes — regenerates the whole file.
// Usage: node scripts/gen-exams.mjs

import { readFileSync, writeFileSync, unlinkSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(__dirname, '..')
const bankPath = join(repoRoot, 'src/lib/questions/bank.ts')
const examsPath = join(repoRoot, 'src/lib/questions/exams.ts')

const src = readFileSync(bankPath, 'utf8')
const jsSrc = src
  .replace(/^import type .+\n/m, '')
  .replace(/export const QUESTION_BANK:[^=]+=\s*\[/, 'export const QUESTION_BANK = [')
const tmpPath = join(repoRoot, '.bank-tmp2.mjs')
writeFileSync(tmpPath, jsSrc)
const { QUESTION_BANK } = await import('file://' + tmpPath)
unlinkSync(tmpPath)

const TOPIC_TO_SUBJECT = {
  number_operations: 'math', algebra_functions: 'math', geometry_measurement: 'math', statistics_probability: 'math',
  reading_comprehension: 'english', grammar_punctuation: 'english', vocabulary: 'english',
  life_science: 'science', physical_science: 'science', earth_space: 'science',
  chem_atomic_structure: 'chemistry', chem_reactions: 'chemistry',
  phys_mechanics: 'physics', phys_electricity: 'physics',
  mm_calculus: 'maths_methods', mm_probability: 'maths_methods',
  fm_data_analysis: 'further_maths', fm_financial: 'further_maths',
  sm_complex_numbers: 'specialist_maths', sm_vectors: 'specialist_maths',
}
const SELECTIVE_SUBJECTS = new Set(['chemistry', 'physics', 'maths_methods', 'further_maths', 'specialist_maths'])
const SUBJECT_LABEL = {
  math: 'Maths', english: 'English', science: 'Science',
  chemistry: 'Chemistry', physics: 'Physics', maths_methods: 'Maths Methods',
  further_maths: 'Further Mathematics', specialist_maths: 'Specialist Mathematics',
}
const GRADE_LABEL = {
  grade_3: 'Grade 3', grade_4: 'Grade 4', grade_5: 'Grade 5', grade_6: 'Grade 6',
  year_7: 'Year 7', year_8: 'Year 8', year_9: 'Year 9', year_10: 'Year 10',
  year_11: 'Unit 1 & 2',
}
const EXAM_SIZE = 10
const EXAM_COUNT = { further_maths: 5, maths_methods: 5 } // default 3 otherwise

// Group questions: general subjects by subject+grade, selective subjects by subject alone.
const groups = new Map() // key -> { subject, yearLevel, questions: [] }
for (const question of QUESTION_BANK) {
  const subject = TOPIC_TO_SUBJECT[question.topic]
  if (!subject) continue
  const key = SELECTIVE_SUBJECTS.has(subject) ? subject : `${subject}__${question.year_level}`
  if (!groups.has(key)) {
    groups.set(key, { subject, yearLevel: question.year_level, questions: [] })
  }
  groups.get(key).questions.push(question)
}

function buildExams(questions, examCount, examSize) {
  const usage = new Array(questions.length).fill(0)
  const exams = []
  for (let e = 0; e < examCount; e++) {
    const candidates = questions.map((_, i) => i).filter(i => usage[i] < 2)
    candidates.sort((a, b) => usage[a] - usage[b] || a - b)
    const chosen = candidates.slice(0, examSize)
    if (chosen.length < examSize) {
      throw new Error(`Not enough distinct questions to build exam ${e + 1} (need ${examSize}, pool has ${questions.length}).`)
    }
    chosen.forEach(i => usage[i]++)
    exams.push(chosen.map(i => questions[i].id))
  }
  return exams
}

const practiceExams = []
for (const { subject, yearLevel, questions } of groups.values()) {
  const examCount = EXAM_COUNT[subject] ?? 3
  const examSize = Math.min(EXAM_SIZE, questions.length)
  const exams = buildExams(questions, examCount, examSize)
  exams.forEach((questionIds, i) => {
    const gradeLabel = GRADE_LABEL[yearLevel] ?? yearLevel
    practiceExams.push({
      id: `${subject}-${yearLevel}-${i + 1}`,
      subject,
      yearLevel,
      title: `${SUBJECT_LABEL[subject]} ${gradeLabel} — Practice Exam ${i + 1}`,
      questionIds,
    })
  })
}

const ts = `// ─────────────────────────────────────────────────────────────────────────────
// Auto-generated by scripts/gen-exams.mjs — do not hand-edit.
// Fixed, pre-composed practice exams (as opposed to the custom exam builder
// on /practice, which mixes topics on demand). Regenerate after bank.ts
// changes with: node scripts/gen-exams.mjs
// ─────────────────────────────────────────────────────────────────────────────

import type { SubjectSlug, YearLevel } from '@/types'

export interface PracticeExam {
  id: string
  subject: SubjectSlug
  yearLevel: YearLevel
  title: string
  questionIds: string[]
}

export const PRACTICE_EXAMS: PracticeExam[] = ${JSON.stringify(practiceExams, null, 2)}
`

writeFileSync(examsPath, ts)
console.log(`Wrote ${practiceExams.length} practice exams to src/lib/questions/exams.ts.`)
const bySubject = {}
practiceExams.forEach(e => { bySubject[e.subject] = (bySubject[e.subject] || 0) + 1 })
console.log(bySubject)
