#!/usr/bin/env node
/**
 * Splits supabase/seed.sql into chunks small enough to paste into the Supabase
 * SQL editor.
 *
 * seed.sql is ~890 KB in two enormous statements. The editor is a browser text
 * area, and pasting that much into it is slow at best and drops the tail at
 * worst — a truncated paste still parses as valid SQL, so it succeeds while
 * loading only part of the bank, which is exactly the kind of silent partial
 * failure this project keeps getting bitten by.
 *
 * Each chunk is a complete, standalone, idempotent upsert: same column list,
 * same `on conflict` clause, a subset of the rows. Run them in any order, or
 * re-run one that failed. Output goes to supabase/seed-parts/ (gitignored).
 *
 *   node scripts/split-seed.mjs [--max-bytes 150000]
 */
import { readFileSync, writeFileSync, mkdirSync, rmSync, readdirSync } from 'node:fs'
import { join } from 'node:path'

const argv = process.argv.slice(2)
const maxBytesArg = argv.indexOf('--max-bytes')
const MAX_BYTES = maxBytesArg === -1 ? 150_000 : Number(argv[maxBytesArg + 1])

const ROOT = new URL('..', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')
const SEED = join(ROOT, 'supabase', 'seed.sql')
const OUT_DIR = join(ROOT, 'supabase', 'seed-parts')

const sql = readFileSync(SEED, 'utf8').replace(/\r\n/g, '\n')

/**
 * Pulls apart one `insert ... values (row), (row) ... on conflict ...;`.
 *
 * Split by scanning rather than by line or by regex: a row's text contains
 * newlines, commas, parentheses and escaped quotes (reading passages are
 * stored inline), so anything simpler cuts a row in half.
 */
function parseStatement(text, startIndex) {
  const valuesAt = text.indexOf('\nvalues\n', startIndex)
  if (valuesAt === -1) return null
  const header = text.slice(startIndex, valuesAt + '\nvalues\n'.length)

  const rows = []
  let i = valuesAt + '\nvalues\n'.length
  let rowStart = -1
  let depth = 0
  let inString = false

  while (i < text.length) {
    const c = text[i]

    if (inString) {
      // '' is an escaped quote inside a string, not the end of one.
      if (c === "'" && text[i + 1] === "'") i += 2
      else if (c === "'") { inString = false; i++ }
      else i++
      continue
    }

    if (c === "'") { inString = true; i++; continue }

    if (c === '(') {
      if (depth === 0) rowStart = i
      depth++
      i++
      continue
    }

    if (c === ')') {
      depth--
      if (depth === 0) {
        rows.push(text.slice(rowStart, i + 1))
        rowStart = -1
      }
      i++
      continue
    }

    if (depth === 0 && text.startsWith('on conflict', i)) break

    i++
  }

  const semicolon = text.indexOf(';', i)
  const tail = text.slice(i, semicolon + 1)
  return { header, rows, tail, endIndex: semicolon + 1 }
}

const statements = []
let cursor = 0
while (true) {
  const next = sql.indexOf('insert into ', cursor)
  if (next === -1) break
  const parsed = parseStatement(sql, next)
  if (!parsed) break
  const table = sql.slice(next + 'insert into '.length).split(/[\s(]/)[0]
  statements.push({ table, ...parsed })
  cursor = parsed.endIndex
}

if (statements.length === 0) {
  console.error('Found no insert statements in supabase/seed.sql — has its shape changed?')
  process.exit(1)
}

// Rewritten from scratch each run, so a stale chunk from an older bank cannot
// be pasted by mistake.
rmSync(OUT_DIR, { recursive: true, force: true })
mkdirSync(OUT_DIR, { recursive: true })

const NOTE = (table, part, total, rowCount) =>
  `-- PrepNest seed — ${table}, part ${part} of ${total} (${rowCount} rows).\n` +
  `-- Generated by scripts/split-seed.mjs. Do not hand-edit; re-run the script.\n` +
  `-- Paste this whole file as ONE query in the Supabase SQL editor.\n` +
  `-- Idempotent: safe to re-run, and safe to run the parts in any order.\n\n`

let fileIndex = 0
let totalRows = 0

for (const stmt of statements) {
  // Group rows into chunks under the byte budget. A single row larger than the
  // budget still gets its own chunk rather than being split.
  const chunks = []
  let current = []
  let size = 0
  for (const row of stmt.rows) {
    if (current.length > 0 && size + row.length > MAX_BYTES) {
      chunks.push(current)
      current = []
      size = 0
    }
    current.push(row)
    size += row.length
  }
  if (current.length) chunks.push(current)

  chunks.forEach((rows, i) => {
    fileIndex++
    totalRows += rows.length
    const body =
      NOTE(stmt.table, i + 1, chunks.length, rows.length) +
      stmt.header.trimStart() +
      rows.join(',\n') +
      '\n' +
      stmt.tail +
      '\n'
    const name = `${String(fileIndex).padStart(2, '0')}-${stmt.table}-${i + 1}.sql`
    writeFileSync(join(OUT_DIR, name), body, 'utf8')
  })

  console.log(`${stmt.table}: ${stmt.rows.length} rows → ${chunks.length} file(s)`)
}

const written = readdirSync(OUT_DIR).sort()
const largest = Math.max(
  ...written.map(f => readFileSync(join(OUT_DIR, f), 'utf8').length)
)
console.log(`\nWrote ${written.length} files to supabase/seed-parts/ (${totalRows} rows total)`)
console.log(`Largest is ${Math.round(largest / 1024)} KB.\n`)
written.forEach(f => console.log(`  ${f}`))
console.log('\nPaste them into the Supabase SQL editor in filename order.\n')
