// VCE General Mathematics Unit 3 & 4 — Practice set 3.
// Examination 1: 40 multiple choice (16 / 8 / 8 / 8). Examination 2: 60 marks (24 / 12 / 12 / 12).
// Numeric answers are checked in scripts/authoring/vce/check-gm-set3.mjs.
const DA = 'gm_data_analysis', RF = 'gm_financial', MX = 'gm_matrices', NW = 'gm_networks'
const S = 3
const code = { [DA]: 'VCE-GM-U34-AOS1', [RF]: 'VCE-GM-U34-AOS2', [MX]: 'VCE-GM-U34-AOS3', [NW]: 'VCE-GM-U34-AOS4' }
const mc = (t, d, q, o, e, extra = {}) => ({ t, s: S, d, calc: true, q, o, e, code: code[t], ...extra })
const ext = (t, d, q, p, extra = {}) => ({ t, s: S, d, calc: true, q, p, code: code[t], ...extra })

const roadNetwork = {
  kind: 'network_graph',
  title: 'Walking tracks (distances in km)',
  vertices: [
    { id: 'P', x: 5, y: 50 }, { id: 'Q', x: 30, y: 85 }, { id: 'R', x: 30, y: 15 },
    { id: 'S', x: 62, y: 62 }, { id: 'T', x: 62, y: 20 }, { id: 'U', x: 94, y: 42 },
  ],
  edges: [
    { from: 'P', to: 'Q', weight: 6 }, { from: 'P', to: 'R', weight: 4 }, { from: 'Q', to: 'R', weight: 3 },
    { from: 'Q', to: 'S', weight: 7 }, { from: 'R', to: 'S', weight: 5 }, { from: 'R', to: 'T', weight: 8 },
    { from: 'S', to: 'T', weight: 2 }, { from: 'S', to: 'U', weight: 6 }, { from: 'T', to: 'U', weight: 5 },
  ],
}

const projectTable = {
  kind: 'data_table',
  title: 'Activities for fitting out a shop',
  columns: ['Activity', 'Duration (days)', 'Immediate predecessor(s)'],
  rowHeader: true,
  rows: [['A', 4, '–'], ['B', 6, '–'], ['C', 3, 'A'], ['D', 5, 'A'], ['E', 2, 'B, C'], ['F', 4, 'D, E']],
}

const transition3 = {
  kind: 'matrix',
  name: 'T =',
  rows: [[0.7, 0.2, 0.1], [0.2, 0.6, 0.3], [0.1, 0.2, 0.6]],
  colLabels: ['A', 'B', 'C'],
  rowLabels: ['A', 'B', 'C'],
}

export const ITEMS = [
  // ════════════════ Examination 1 — Data analysis (16) ════════════════
  mc(DA, 'developing',
    'A café records, for each customer, the size of coffee ordered (small, medium or large) and the time spent waiting for it, in minutes. These two variables are, respectively,',
    ['categorical ordinal and numerical continuous', 'categorical nominal and numerical continuous', 'categorical ordinal and numerical discrete', 'numerical discrete and numerical continuous', 'categorical nominal and categorical ordinal'],
    'Coffee size is a category with a natural order (small < medium < large), so it is ordinal. Waiting time is measured, not counted, so it is numerical continuous.'),
  mc(DA, 'developing',
    'The number of minutes that seven customers waited in a queue were 3, 5, 5, 6, 8, 9 and 13. The standard deviation of these waiting times, correct to two decimal places, is',
    ['3.32', '3.07', '7.00', '9.43', '11.00'],
    'The mean is 49 ÷ 7 = 7. The squared deviations are 16, 4, 4, 1, 1, 4 and 36, which sum to 66. The sample standard deviation is √(66 ÷ 6) = √11 = 3.32. Dividing by 7 instead of 6 gives 3.07, the population value, which is not what a CAS reports as sₓ.'),
  mc(DA, 'proficient',
    'The box plot below displays the ages of the members of a rowing club. Which one of the following statements is true?',
    ['The distribution is positively skewed.', 'The maximum age is an outlier.', 'The interquartile range is 28 years.', 'About 50% of members are aged between 15 and 17 years.', 'The distribution is approximately symmetric.'],
    'The median (17) sits close to Q1 (15) and the upper whisker is long, so the distribution is positively skewed. The upper fence is Q3 + 1.5 × IQR = 25 + 1.5 × 10 = 40, and a value must be greater than the fence to be an outlier, so 40 is not one. The IQR is 25 − 15 = 10, and only about 25% of members lie between Q1 and the median.',
    { diagram: { kind: 'box_plot', title: 'Ages of rowing club members (years)', axisLabel: 'age (years)', min: 10, max: 45, step: 5, boxes: [{ min: 12, q1: 15, median: 17, q3: 25, max: 40 }] } }),
  mc(DA, 'developing',
    'The heights of adult female emus are approximately normally distributed with a mean of 1.6 m and a standard deviation of 0.1 m. Using the 68–95–99.7% rule, the percentage of adult female emus taller than 1.5 m is closest to',
    ['84%', '16%', '34%', '50%', '68%'],
    '1.5 m is one standard deviation below the mean. 50% of heights lie above the mean and 34% lie between one standard deviation below and the mean, so 50% + 34% = 84% are taller than 1.5 m.'),
  mc(DA, 'proficient',
    'The table below shows the test scores of five students in different classes, with each class’s mean and standard deviation. Relative to their own class, the student who performed best was',
    ['Dev', 'Aria', 'Ben', 'Chloe', 'Eli'],
    'Compare standardised scores: Aria (74 − 68) ÷ 4 = 1.5; Ben (81 − 75) ÷ 5 = 1.2; Chloe (66 − 58) ÷ 6 = 1.33; Dev (90 − 84) ÷ 3 = 2.0; Eli (70 − 60) ÷ 8 = 1.25. Dev has the highest z-score, even though Eli’s raw score is further above the mean.',
    { diagram: { kind: 'data_table', title: 'Test scores', columns: ['Student', 'Score', 'Class mean', 'Class standard deviation'], rowHeader: true, rows: [['Aria', 74, 68, 4], ['Ben', 81, 75, 5], ['Chloe', 66, 58, 6], ['Dev', 90, 84, 3], ['Eli', 70, 60, 8]] } }),
  mc(DA, 'developing',
    'A researcher wants to investigate the association between age group (under 30, 30 to 50, over 50) and preferred streaming service. The most appropriate display is',
    ['a segmented bar chart', 'a scatterplot', 'a back-to-back stem plot', 'parallel box plots', 'a time series plot'],
    'Both variables are categorical, and a segmented bar chart shows the percentage preferring each service within each age group. Scatterplots, stem plots and box plots need at least one numerical variable.'),
  mc(DA, 'developing',
    'Over one year, the correlation coefficient between the daily number of ice creams sold at a beach kiosk and the daily number of rescues made by lifeguards at that beach was r = 0.91. The best explanation for this association is that',
    ['hot weather increases both ice cream sales and the number of people swimming', 'eating ice cream causes swimmers to get into difficulty', 'lifeguard rescues cause people to buy ice cream', 'the association must be a coincidence because r is not equal to 1', 'the association is weak because the variables are unrelated'],
    'A strong correlation does not establish causation. Both variables rise on hot days, when more people buy ice cream and more people swim — a common response to a third variable.'),
  mc(DA, 'proficient',
    'The table below shows the hours of practice and the score out of 25 for six students. Using a CAS, the equation of the least squares line for predicting score from hours of practice, with coefficients correct to two decimal places, is',
    ['score = 1.19 + 1.89 × hours', 'score = 1.89 + 1.19 × hours', 'score = 13.17 + 1.89 × hours', 'score = 1.19 + 0.53 × hours', 'score = −0.60 + 0.53 × hours'],
    'With hours as the explanatory variable, the CAS gives slope 1.89 and intercept 1.19. The value 0.53 is the slope of hours on score, which is what you get by entering the variables the wrong way round.',
    { diagram: { kind: 'data_table', title: 'Practice and score', columns: ['Hours of practice', '2', '4', '5', '7', '9', '11'], rowHeader: true, rows: [['Score (out of 25)', 5, 9, 10, 15, 18, 22]] } }),
  mc(DA, 'developing',
    'For a delivery company, the least squares line predicted time = 4.5 + 0.35 × distance is fitted to delivery times, in minutes, and distances, in kilometres. For one delivery the residual is −1.2. This means that',
    ['the actual time was 1.2 minutes less than the time predicted by the line', 'the actual time was 1.2 minutes more than the time predicted by the line', 'the predicted time for this delivery was 1.2 minutes', 'the distance was 1.2 km less than predicted', 'the line overestimates every delivery time by 1.2 minutes'],
    'A residual is actual value − predicted value. A residual of −1.2 means the actual time was 1.2 minutes below the line’s prediction for that distance.'),
  mc(DA, 'proficient',
    'A scatterplot of the time, y hours, taken to complete a job against the number of workers, x, suggests that y is approximately proportional to 1/x. The plot that is most likely to be linear is',
    ['y against 1/x', 'y against x²', 'log(y) against x', 'y² against x', 'y against log(x)'],
    'If y = k × (1/x), then plotting y against 1/x gives a straight line through the origin with slope k. This is the reciprocal transformation of the explanatory variable.'),
  mc(DA, 'developing',
    'For a group of adults, the coefficient of determination between arm span and height is 0.81. Which one of the following is a correct interpretation?',
    ['81% of the variation in height can be explained by the variation in arm span.', '81% of adults have an arm span equal to their height.', 'Height increases by 0.81 cm for each 1 cm increase in arm span.', 'The correlation coefficient is 0.81.', '19% of the variation in height can be explained by the variation in arm span.'],
    'The coefficient of determination r² gives the percentage of variation in the response variable explained by the explanatory variable. Here r = √0.81 = 0.9 (positive for this context), not 0.81.'),
  mc(DA, 'proficient',
    'The table below shows the daily number of visitors, in hundreds, to a museum over seven days. The five-mean smoothed number of visitors, in hundreds, for day 4 is',
    ['29.4', '28', '30', '30.6', '31'],
    'The five-mean smoothed value for day 4 averages days 2 to 6: (27 + 25 + 31 + 34 + 30) ÷ 5 = 147 ÷ 5 = 29.4. The value 30 is the three-mean smoothed value for day 4, and 28 is the five-mean value for day 3.',
    { diagram: { kind: 'data_table', title: 'Visitors (hundreds)', columns: ['Day', '1', '2', '3', '4', '5', '6', '7'], rowHeader: true, rows: [['Visitors', 23, 27, 25, 31, 34, 30, 36]] } }),
  mc(DA, 'proficient',
    'The table below shows a shop’s sales, in thousands of dollars, for each quarter of one year. The seasonal index for Quarter 3, correct to two decimal places, is',
    ['0.72', '0.28', '0.78', '0.90', '1.39'],
    'The mean quarterly sales are (120 + 150 + 90 + 140) ÷ 4 = 500 ÷ 4 = 125. The seasonal index for Quarter 3 is 90 ÷ 125 = 0.72.',
    { diagram: { kind: 'data_table', title: 'Quarterly sales ($ thousands)', columns: ['Quarter', '1', '2', '3', '4'], rowHeader: true, rows: [['Sales', 120, 150, 90, 140]] } }),
  mc(DA, 'developing',
    'The main purpose of deseasonalising a time series is to',
    ['remove the seasonal pattern so that the underlying trend can be seen more clearly', 'remove any outliers from the data', 'make every season’s figures equal to the yearly mean', 'forecast future values without a trend line', 'smooth out random variation using moving averages'],
    'Deseasonalising divides each value by its seasonal index, which removes the regular seasonal pattern and leaves the trend (and random variation) visible. Smoothing is a different technique.'),
  mc(DA, 'proficient',
    'The scores of 800 students on a test are approximately normally distributed. Using the 68–95–99.7% rule, the number of students expected to score more than two standard deviations below the mean is closest to',
    ['20', '40', '128', '400', '780'],
    'About 5% of scores lie more than two standard deviations from the mean, half of them below it, so about 2.5% score more than two standard deviations below the mean: 0.025 × 800 = 20 students. 780 is the number scoring above that value.'),
  mc(DA, 'developing',
    'The mean of ten numbers is 12. One number, 30, is removed from the set. The mean of the remaining nine numbers is',
    ['10', '9', '11', '12', '13.33'],
    'The ten numbers sum to 10 × 12 = 120. Removing 30 leaves a sum of 90 across nine numbers, so the new mean is 90 ÷ 9 = 10.'),

  // ════════════════ Examination 1 — Recursion and financial modelling (8) ════════════════
  mc(RF, 'developing',
    'A sequence is generated by the recurrence relation T₀ = 40, Tₙ₊₁ = 0.5Tₙ + 12. The value of T₃ is',
    ['26', '24', '25', '28', '32'],
    'T₁ = 0.5 × 40 + 12 = 32, T₂ = 0.5 × 32 + 12 = 28 and T₃ = 0.5 × 28 + 12 = 26. The sequence approaches 24 in the long run, which is a common wrong answer.'),
  mc(RF, 'proficient',
    'A laptop purchased for $2400 is depreciated using the reducing balance method. After two years its value is $1536. The annual rate of depreciation is',
    ['20%', '16%', '18%', '32%', '36%'],
    'After two years the value is 1536 ÷ 2400 = 0.64 of the purchase price. The yearly multiplier is √0.64 = 0.8, so the value falls by 20% each year. 36% is the total fall over two years.'),
  mc(RF, 'proficient',
    'A tool purchased for $3600 is depreciated using the flat rate method at 12.5% of the purchase price per year. The value of the tool first falls below $1000 after',
    ['6 years', '4 years', '5 years', '7 years', '8 years'],
    'The tool loses 0.125 × 3600 = $450 each year. After 5 years it is worth 3600 − 2250 = $1350 and after 6 years it is worth 3600 − 2700 = $900, so it first falls below $1000 after 6 years.'),
  mc(RF, 'proficient',
    'An amount of $7500 is invested at 3.8% per annum, compounding weekly. Assuming 52 weeks in a year, the total interest earned after two years is closest to',
    ['$592', '$570', '$581', '$8092', '$285'],
    'The value after 104 weeks is 7500 × (1 + 0.038 ÷ 52)¹⁰⁴ ≈ $8091.99, so the interest is about $592. $570 is simple interest and $581 is annual compounding; $8092 is the final value, not the interest.'),
  mc(RF, 'proficient',
    'A loan of $420 000 is charged interest at 6.3% per annum, compounding monthly. It is to be repaid with equal monthly repayments over 30 years. Using a financial solver, the monthly repayment, correct to the nearest cent, is',
    ['$2599.69', '$1166.67', '$2205.00', '$2750.00', '$3371.67'],
    'With N = 360, I% = 6.3, PV = 420 000, FV = 0 and 12 payments per year, the solver gives PMT = −2599.69. $2205.00 is the interest-only repayment (0.525% of 420 000) and $1166.67 ignores interest.'),
  mc(RF, 'proficient',
    'An investment is to act as a perpetuity, paying $2500 at the end of each month indefinitely. Interest is earned at 4.2% per annum, compounding monthly. The amount that must be invested is closest to',
    ['$714 285.71', '$59 523.81', '$71 428.57', '$595 238.10', '$1 050 000.00'],
    'The monthly interest rate is 4.2% ÷ 12 = 0.35%. A perpetuity pays exactly the interest each month, so the principal is 2500 ÷ 0.0035 = $714 285.71.'),
  mc(RF, 'proficient',
    'Ari deposits $300 at the end of each month into a new account that pays interest at 4.8% per annum, compounding monthly. The balance of the account after ten years is closest to',
    ['$46 090', '$36 000', '$38 420', '$53 280', '$57 600'],
    'This is an annuity investment with PV = 0, PMT = −300, N = 120 and I% = 4.8. The solver gives FV ≈ $46 089.59. $36 000 is the total deposited without interest.'),
  mc(RF, 'developing',
    'A car purchased for $12 500 is depreciated using the flat rate method at 8% of the purchase price each year. A recurrence relation for the value Vₙ of the car, in dollars, after n years is',
    ['V₀ = 12 500, Vₙ₊₁ = Vₙ − 1000', 'V₀ = 12 500, Vₙ₊₁ = 0.92Vₙ', 'V₀ = 12 500, Vₙ₊₁ = Vₙ − 920', 'V₀ = 12 500, Vₙ₊₁ = 1.08Vₙ − 1000', 'V₀ = 12 500, Vₙ₊₁ = Vₙ − 0.08'],
    'Flat rate depreciation removes the same amount each year: 8% of $12 500 is $1000. Vₙ₊₁ = 0.92Vₙ describes reducing balance depreciation instead.'),

  // ════════════════ Examination 1 — Matrices (8) ════════════════
  mc(MX, 'developing',
    'For matrix A below, the order of A and the element a₂₃ are, respectively,',
    ['2 × 4 and 1', '4 × 2 and 1', '2 × 4 and 4', '4 × 2 and 0', '2 × 4 and 0'],
    'A has 2 rows and 4 columns, so its order is 2 × 4. The element a₂₃ is in row 2, column 3, which is 1.',
    { diagram: { kind: 'matrix', name: 'A =', rows: [[3, -1, 0, 2], [5, 4, 1, 6]] } }),
  mc(MX, 'proficient',
    'Let A be the matrix below, and let B be the matrix with first row 2, 1 and second row 1, 4. The matrix AB − BA is',
    ['first row −1, 5 and second row −7, 1', 'first row 0, 0 and second row 0, 0', 'first row 1, −5 and second row 7, −1', 'first row 4, 9 and second row 6, 3', 'first row −1, 3 and second row 5, 1'],
    'AB = [1×2 + 2×1, 1×1 + 2×4; 3×2 + 0×1, 3×1 + 0×4], which has first row 4, 9 and second row 6, 3. BA = [2×1 + 1×3, 2×2 + 1×0; 1×1 + 4×3, 1×2 + 4×0], which has first row 5, 4 and second row 13, 2. So AB − BA has first row −1, 5 and second row −7, 1 — matrix multiplication is not commutative.',
    { diagram: { kind: 'matrix', name: 'A =', rows: [[1, 2], [3, 0]] } }),
  mc(MX, 'proficient',
    'The determinant of matrix A below is 2. The determinant of the matrix 3A is',
    ['18', '2', '6', '12', '54'],
    'Multiplying a 2 × 2 matrix by 3 multiplies every element by 3, so the determinant is multiplied by 3 × 3 = 9. Check: 3A has first row 12, 9 and second row 6, 6, and 12 × 6 − 9 × 6 = 72 − 54 = 18.',
    { diagram: { kind: 'matrix', name: 'A =', rows: [[4, 3], [2, 2]] } }),
  mc(MX, 'proficient',
    'In the communication matrix below, a 1 in row i and column j means that person i can send a message directly to person j. The number of different ways that P can send a message to S using exactly one other person as an intermediary is',
    ['2', '0', '1', '3', '4'],
    'P can send directly to Q and to R. Q can send directly to S, and R can send directly to S, so there are two two-step links: P → Q → S and P → R → S. This is the element in row P, column S of the square of the matrix.',
    { diagram: { kind: 'matrix', name: 'C =', rows: [[0, 1, 1, 0], [0, 0, 1, 1], [1, 0, 0, 1], [0, 1, 0, 0]], rowLabels: ['P', 'Q', 'R', 'S'], colLabels: ['P', 'Q', 'R', 'S'] } }),
  mc(MX, 'developing',
    'Customers choose between three supermarkets, A, B and C, each week according to the transition matrix T below, where the columns show this week and the rows show next week. The percentage of customers who shop at B this week and switch to C next week is',
    ['20%', '2%', '10%', '30%', '60%'],
    'Read down the "B" column (this week) to the "C" row (next week): 0.2, or 20%. The value 0.3 in row B, column C is the percentage moving from C to B.',
    { diagram: transition3 }),
  mc(MX, 'proficient',
    'Using the transition matrix T below, where the columns show this week and the rows show next week, there are 400 customers at A, 300 at B and 300 at C this week. The number of customers expected at A next week is',
    ['370', '300', '330', '360', '400'],
    'Next week at A = 0.7 × 400 + 0.2 × 300 + 0.1 × 300 = 280 + 60 + 30 = 370.',
    { diagram: transition3 }),
  mc(MX, 'proficient',
    'Matrix A is shown below. If AB = I, where I is the 2 × 2 identity matrix, then B is',
    ['first row 3, −5 and second row −1, 2', 'first row 3, 5 and second row 1, 2', 'first row −3, 5 and second row 1, −2', 'first row 2, 1 and second row 5, 3', 'first row 2, −5 and second row −1, 3'],
    'B must be the inverse of A. The determinant is 2 × 3 − 5 × 1 = 1, so A⁻¹ = (1/1) × [3, −5; −1, 2]: swap the leading diagonal, negate the other two elements and divide by the determinant.',
    { diagram: { kind: 'matrix', name: 'A =', rows: [[2, 5], [1, 3]] } }),
  mc(MX, 'developing',
    'Matrix L, of order 3 × 2, records the numbers of adult and child tickets sold at each of three cinema sessions. Matrix P, of order 2 × 1, records the prices of an adult ticket and a child ticket. The total ticket revenue from each session is given by the matrix',
    ['LP', 'PL', 'L + P', 'L × L', 'P × P'],
    'LP is (3 × 2)(2 × 1), which is defined and has order 3 × 1: one revenue figure per session. PL is (2 × 1)(3 × 2), which is not defined, and L + P needs matrices of the same order.'),

  // ════════════════ Examination 1 — Networks and decision mathematics (8) ════════════════
  mc(NW, 'proficient',
    'A connected graph has five vertices. Four of the vertices have degrees 1, 2, 2 and 3. The smallest possible degree of the fifth vertex is',
    ['2', '0', '1', '3', '4'],
    'The sum of the degrees must be even (it is twice the number of edges). 1 + 2 + 2 + 3 = 8, so the fifth degree must be even, and it cannot be 0 in a connected graph. The smallest possible value is 2.'),
  mc(NW, 'developing',
    'A connected planar graph has 10 edges and 6 faces. The number of vertices is',
    ['6', '2', '4', '14', '18'],
    'Euler’s formula v − e + f = 2 gives v = 2 + e − f = 2 + 10 − 6 = 6.'),
  mc(NW, 'developing',
    'A route through a connected graph that visits every vertex exactly once and returns to its starting vertex is called',
    ['a Hamiltonian cycle', 'an Eulerian circuit', 'an Eulerian trail', 'a Hamiltonian path', 'a spanning tree'],
    'A Hamiltonian cycle visits every vertex exactly once and finishes where it started. An Eulerian circuit uses every edge exactly once, and a Hamiltonian path does not return to its start.'),
  mc(NW, 'proficient',
    'The weighted graph below shows the walking tracks, with distances in kilometres, between six huts. The total length of the minimum spanning tree, in kilometres, is',
    ['19', '17', '20', '21', '24'],
    'Using Kruskal’s algorithm: ST (2), QR (3), PR (4), then RS (5) and TU (5) connect the remaining components. PQ, QS, SU and RT would each create a cycle. The total is 2 + 3 + 4 + 5 + 5 = 19 km.',
    { diagram: roadNetwork }),
  mc(NW, 'proficient',
    'The weighted graph below shows the walking tracks, with distances in kilometres, between six huts. The length of the shortest path from P to U, in kilometres, is',
    ['15', '14', '16', '17', '19'],
    'The shortest route is P–R–S–U = 4 + 5 + 6 = 15 km. Alternatives are longer: P–R–S–T–U = 16, P–R–T–U = 17 and P–Q–S–U = 19.',
    { diagram: roadNetwork }),
  mc(NW, 'advanced',
    'The directed network below shows the capacity, in litres per minute, of each pipe from a source S to a sink T. A cut separates the vertices {S, A} from the vertices {B, T}. The capacity of this cut, in litres per minute, is',
    ['19', '14', '15', '23', '24'],
    'Only edges that flow from the source side {S, A} to the sink side {B, T} count: S→B (10) and A→T (9), giving 19. The edge B→A (5) flows from the sink side back to the source side, so it is not included.',
    { diagram: { kind: 'network_graph', title: 'Pipe capacities (litres per minute)', directed: true, vertices: [{ id: 'S', x: 6, y: 50 }, { id: 'A', x: 46, y: 86 }, { id: 'B', x: 46, y: 14 }, { id: 'T', x: 92, y: 50 }], edges: [{ from: 'S', to: 'A', weight: 8 }, { from: 'S', to: 'B', weight: 10 }, { from: 'B', to: 'A', weight: 5 }, { from: 'A', to: 'T', weight: 9 }, { from: 'B', to: 'T', weight: 6 }] } }),
  mc(NW, 'advanced',
    'The table below shows the activities in a project, their durations and their immediate predecessors. The only activity that is not on a critical path is',
    ['B', 'A', 'C', 'D', 'E'],
    'The earliest finish is 13 days. Two paths take 13 days: A–D–F (4 + 5 + 4) and A–C–E–F (4 + 3 + 2 + 4), so A, C, D, E and F are all critical. B–E–F takes only 6 + 2 + 4 = 12 days, so B has one day of float.',
    { diagram: projectTable }),
  mc(NW, 'advanced',
    'For the project in the table below, the latest start time for activity B, in days, is',
    ['1', '0', '2', '6', '7'],
    'Activity E is critical and must start on day 7 at the latest. B takes 6 days and must finish before E starts, so B must start by day 7 − 6 = 1.',
    { diagram: projectTable }),

  // ════════════════ Examination 2 — Data analysis (24 marks) ════════════════
  ext(DA, 'proficient',
    'The number of minutes late for 12 trains arriving at a city station on one morning is shown in the table below.',
    [
      ['a', 'Find the median number of minutes late.', 1, '7.5 minutes', 'In order: 2, 4, 5, 5, 6, 7, 8, 9, 10, 12, 13, 29. With 12 values, the median is the mean of the 6th and 7th: (7 + 8) ÷ 2 = 7.5.'],
      ['b', 'Find the first quartile, the third quartile and the interquartile range.', 2, 'Q₁ = 5, Q₃ = 11, IQR = 6', 'The lower half is 2, 4, 5, 5, 6, 7, so Q₁ = (5 + 5) ÷ 2 = 5. The upper half is 8, 9, 10, 12, 13, 29, so Q₃ = (10 + 12) ÷ 2 = 11. IQR = 11 − 5 = 6. One mark for both quartiles, one for the IQR.'],
      ['c', 'Show that the value 29 is an outlier.', 2, 'Upper fence = 11 + 1.5 × 6 = 20; 29 > 20, so it is an outlier.', 'Upper fence = Q₃ + 1.5 × IQR = 11 + 9 = 20. Since 29 is greater than 20, it is an outlier. One mark for the fence, one for the comparison.'],
      ['d', 'Describe the shape of the distribution.', 1, 'Positively skewed, with an outlier at 29 minutes.', 'Most trains were a few minutes late and the values tail off to the right, with one extreme value.'],
    ],
    { d: 'developing', diagram: { kind: 'data_table', title: 'Minutes late', columns: ['Train', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'], rowHeader: true, rows: [['Minutes late', 8, 2, 13, 5, 29, 7, 10, 4, 12, 6, 9, 5]] } }),
  ext(DA, 'proficient',
    'The hours of practice and the score out of 25 on a skills test for six students are shown in the table below. Score is to be predicted from hours of practice.',
    [
      ['a', 'Name the explanatory variable.', 1, 'Hours of practice', 'The variable used to make the prediction is the explanatory variable.'],
      ['b', 'Find the equation of the least squares line. Write the coefficients correct to two decimal places.', 2, 'score = 1.19 + 1.89 × hours', 'Using a CAS with hours as x and score as y: slope 1.8916, intercept 1.1867. One mark for each coefficient.'],
      ['c', 'Interpret the slope of the least squares line in the context of this data.', 1, 'On average, score increases by 1.89 points for each additional hour of practice.', 'The slope is the average change in the response variable for a one-unit increase in the explanatory variable.'],
      ['d', 'Find the correlation coefficient r, correct to three decimal places.', 1, 'r = 0.998', 'From the CAS, r = 0.9979, which rounds to 0.998: a very strong positive linear association.'],
      ['e', 'Use the least squares line to predict the score of a student who practises for 6 hours, correct to one decimal place, and state whether this prediction is an interpolation or an extrapolation.', 1, 'score ≈ 12.5; interpolation', '1.1867 + 1.8916 × 6 = 12.54, which is 12.5. Six hours lies within the data range of 2 to 11 hours, so this is interpolation.'],
    ],
    { diagram: { kind: 'data_table', title: 'Practice and score', columns: ['Hours of practice', '2', '4', '5', '7', '9', '11'], rowHeader: true, rows: [['Score (out of 25)', 5, 9, 10, 15, 18, 22]] } }),
  ext(DA, 'proficient',
    'The masses of apples from an orchard are approximately normally distributed with a mean of 150 g and a standard deviation of 12 g.',
    [
      ['a', 'Using the 68–95–99.7% rule, find the percentage of apples with a mass between 126 g and 174 g.', 1, '95%', '126 and 174 are two standard deviations either side of the mean, which contains about 95% of values.'],
      ['b', 'Using the 68–95–99.7% rule, find the percentage of apples with a mass greater than 162 g.', 1, '16%', '162 g is one standard deviation above the mean. 34% lie between the mean and 162 g, so 50% − 34% = 16% lie above it.'],
      ['c', 'Find the standardised score of an apple with a mass of 141 g.', 1, 'z = −0.75', 'z = (141 − 150) ÷ 12 = −0.75.'],
      ['d', 'A crate holds 2000 apples from this orchard. Using the 68–95–99.7% rule, find the number of apples expected to have a mass less than 126 g.', 1, '50 apples', 'About 2.5% of apples are more than two standard deviations below the mean: 0.025 × 2000 = 50.'],
      ['e', 'An apple has a standardised score of 1.5. Find its mass.', 1, '168 g', 'mass = 150 + 1.5 × 12 = 168 g.'],
      ['f', 'An apple with a mass of 200 g is found. Explain, with a calculation, whether this apple is unusual.', 1, 'z = (200 − 150) ÷ 12 ≈ 4.17, more than three standard deviations above the mean, so it is very unusual.', 'Fewer than 0.15% of apples are expected more than three standard deviations above the mean.'],
    ]),
  ext(DA, 'advanced',
    'The table below shows the quarterly sales, in thousands of dollars, of a garden supply business over two years. The seasonal indices, correct to two decimal places, are 0.95 for Quarter 1, 1.10 for Quarter 3 and 0.70 for Quarter 4.',
    [
      ['a', 'Find the mean quarterly sales, in thousands of dollars, for Year 1.', 1, '50', '(48 + 62 + 55 + 35) ÷ 4 = 200 ÷ 4 = 50.'],
      ['b', 'Show that the seasonal index for Quarter 2 is 1.26, correct to two decimal places.', 1, '(62 ÷ 50 + 70 ÷ 55) ÷ 2 = (1.24 + 1.2727) ÷ 2 = 1.26', 'The Year 2 mean is 220 ÷ 4 = 55. Average the Quarter 2 ratios for the two years: (1.24 + 1.2727) ÷ 2 = 1.2564, which is 1.26. (Check: the four indices sum to 4.)'],
      ['c', 'Deseasonalise the Quarter 4 sales for Year 2. Give your answer in thousands of dollars, correct to two decimal places.', 1, '54.29', '38 ÷ 0.70 = 54.29.'],
      ['d', 'Interpret the seasonal index for Quarter 4.', 1, 'Quarter 4 sales are typically 30% below the quarterly average.', 'A seasonal index of 0.70 means sales in that quarter are 70% of an average quarter.'],
      ['e', 'A least squares line fitted to the deseasonalised data is deseasonalised sales = 45 + 1.5t, where t = 1 is Quarter 1 of Year 1. Use this line and the seasonal index for Quarter 2 to forecast the actual sales for Quarter 2 of Year 3, in thousands of dollars.', 2, '75.6', 'Quarter 2 of Year 3 is t = 10. Deseasonalised forecast = 45 + 1.5 × 10 = 60. Actual forecast = 60 × 1.26 = 75.6. One mark for t = 10 and the trend value, one for reseasonalising.'],
    ],
    { diagram: { kind: 'data_table', title: 'Quarterly sales ($ thousands)', columns: ['', 'Quarter 1', 'Quarter 2', 'Quarter 3', 'Quarter 4'], rowHeader: true, rows: [['Year 1', 48, 62, 55, 35], ['Year 2', 52, 70, 60, 38]] } }),

  // ════════════════ Examination 2 — Recursion and financial modelling (12 marks) ════════════════
  ext(RF, 'proficient',
    'Jo buys a food truck for $68 000 and is comparing two depreciation methods: flat rate depreciation of $6120 per year, or reducing balance depreciation at 12% per year.',
    [
      ['a', 'Write down a recurrence relation that models the value Vₙ, in dollars, of the food truck after n years using flat rate depreciation.', 1, 'V₀ = 68 000, Vₙ₊₁ = Vₙ − 6120', 'Flat rate depreciation subtracts the same amount each year.'],
      ['b', 'Find the value of the food truck after five years using flat rate depreciation.', 1, '$37 400', '68 000 − 5 × 6120 = 68 000 − 30 600 = $37 400.'],
      ['c', 'Find the value of the food truck after five years using reducing balance depreciation, correct to the nearest cent.', 1, '$35 885.77', '68 000 × 0.88⁵ = $35 885.77.'],
      ['d', 'After how many years is the value under flat rate depreciation first lower than the value under reducing balance depreciation?', 1, '6 years', 'After 5 years: flat rate $37 400, reducing balance $35 885.77. After 6 years: flat rate $31 280, reducing balance 68 000 × 0.88⁶ = $31 579.48, so the flat rate value is now lower.'],
    ]),
  ext(RF, 'advanced',
    'Kai borrows $36 000 to buy a car. Interest is charged at 8.4% per annum, compounding monthly, and Kai repays $900 at the end of each month.',
    [
      ['a', 'Find the monthly interest rate.', 1, '0.7%', '8.4% ÷ 12 = 0.7% per month.'],
      ['b', 'Write down a recurrence relation that models the balance Bₙ, in dollars, of the loan after n months.', 1, 'B₀ = 36 000, Bₙ₊₁ = 1.007Bₙ − 900', 'Each month the balance grows by 0.7% interest, then the $900 repayment is subtracted.'],
      ['c', 'Find the balance of the loan after two years, correct to the nearest dollar.', 1, '$19 129', 'Financial solver: N = 24, I% = 8.4, PV = 36 000, PMT = −900 gives FV = −19 129.37, so the balance is $19 129.'],
      ['d', 'Find the number of monthly repayments needed to repay the loan in full. (The final repayment may be less than $900.)', 1, '48', 'Solving for N with FV = 0 gives N = 47.09, so 47 full repayments are followed by a smaller 48th repayment.'],
    ]),
  ext(RF, 'advanced',
    'Mei’s retirement fund has a balance of $480 000 and earns interest at 5.1% per annum, compounding monthly. She withdraws $4000 at the end of each month.',
    [
      ['a', 'Find the interest earned in the first month.', 1, '$2040', 'The monthly rate is 5.1% ÷ 12 = 0.425%, and 0.00425 × 480 000 = $2040.'],
      ['b', 'Find the balance of the fund after the first withdrawal.', 1, '$478 040', '480 000 + 2040 − 4000 = $478 040.'],
      ['c', 'Find the monthly withdrawal that Mei could make if she wanted the fund to act as a perpetuity.', 1, '$2040', 'A perpetuity withdraws only the interest, so the balance never changes: $2040 per month.'],
      ['d', 'Find the number of full $4000 withdrawals that Mei can make before the fund runs out.', 1, '168', 'Solving for N with PV = 480 000, PMT = 4000 and FV = 0 gives N = 168.2, so 168 full withdrawals can be made.'],
    ]),

  // ════════════════ Examination 2 — Matrices (12 marks) ════════════════
  ext(MX, 'advanced',
    'Five teams, A to E, play each other once in a netball round robin. In the dominance matrix D below, a 1 in row i and column j means team i defeated team j.',
    [
      ['a', 'Which teams did team E defeat?', 1, 'A and C', 'Row E has 1s in columns A and C.'],
      ['b', 'Find the two-step dominance total for team D.', 1, '4', 'D defeated A and E. A has 2 wins and E has 2 wins, so D has 2 + 2 = 4 two-step dominances (row D of D² sums to 4).'],
      ['c', 'The teams are ranked using the sum of their one-step and two-step dominances. Which team is ranked first, and which two teams have the same total?', 2, 'B is first (total 8); A and D tie on 6.', 'One-step totals: A 2, B 3, C 1, D 2, E 2. Two-step totals: A 4, B 5, C 2, D 4, E 3. Sums: A 6, B 8, C 3, D 6, E 5. One mark for B first, one for A and D tying.'],
    ],
    { diagram: { kind: 'matrix', name: 'D =', rows: [[0, 1, 1, 0, 0], [0, 0, 1, 1, 1], [0, 0, 0, 1, 0], [1, 0, 0, 0, 1], [1, 0, 1, 0, 0]], rowLabels: ['A', 'B', 'C', 'D', 'E'], colLabels: ['A', 'B', 'C', 'D', 'E'] } }),
  ext(MX, 'advanced',
    'A bike-share scheme has 500 bikes at three stations, X, Y and Z. The transition matrix T below shows how bikes move from one day (columns) to the next (rows). On Monday there are 200 bikes at X, 150 at Y and 150 at Z.',
    [
      ['a', 'What percentage of the bikes at Y on one day are at Z the next day?', 1, '10%', 'Column Y, row Z: 0.1.'],
      ['b', 'Find the number of bikes at each station on Tuesday.', 1, 'X 165, Y 210, Z 125', 'X: 0.6 × 200 + 0.1 × 150 + 0.2 × 150 = 165. Y: 0.3 × 200 + 0.8 × 150 + 0.2 × 150 = 210. Z: 0.1 × 200 + 0.1 × 150 + 0.6 × 150 = 125.'],
      ['c', 'Find the number of bikes at X on Wednesday.', 1, '145', '0.6 × 165 + 0.1 × 210 + 0.2 × 125 = 99 + 21 + 25 = 145.'],
      ['d', 'In the long run, how many bikes will be at station Y each day?', 1, '280', 'The steady state satisfies TS = S with a total of 500. Solving gives X 120, Y 280, Z 100 (check: 0.3 × 120 + 0.8 × 280 + 0.2 × 100 = 36 + 224 + 20 = 280).'],
    ],
    { diagram: { kind: 'matrix', name: 'T =', rows: [[0.6, 0.1, 0.2], [0.3, 0.8, 0.2], [0.1, 0.1, 0.6]], colLabels: ['X', 'Y', 'Z'], rowLabels: ['X', 'Y', 'Z'] } }),
  ext(MX, 'advanced',
    'Two wildlife parks, A and B, exchange animals each year according to the transition matrix T below (columns: this year, rows: next year). Each year 30 new animals are also released into park A and 10 into park B, so Sₙ₊₁ = TSₙ + R, where R is the column matrix with elements 30 (top) and 10 (bottom). Initially there are 500 animals in park A and 300 in park B.',
    [
      ['a', 'Explain the meaning of the element 0.2 in matrix T.', 1, 'Each year, 20% of the animals in park B move to park A.', 'The element is in column B (this year) and row A (next year).'],
      ['b', 'Find S₁.', 1, 'A 540, B 300', 'A: 0.9 × 500 + 0.2 × 300 + 30 = 540. B: 0.1 × 500 + 0.8 × 300 + 10 = 300.'],
      ['c', 'Find the number of animals in park A after two years.', 1, '576', '0.9 × 540 + 0.2 × 300 + 30 = 486 + 60 + 30 = 576.'],
      ['d', 'Find the total number of animals in the two parks after two years.', 1, '880', 'Park B after two years: 0.1 × 540 + 0.8 × 300 + 10 = 304. Total 576 + 304 = 880: the total rises by the 40 animals released each year.'],
    ],
    { diagram: { kind: 'matrix', name: 'T =', rows: [[0.9, 0.2], [0.1, 0.8]], colLabels: ['A', 'B'], rowLabels: ['A', 'B'] } }),

  // ════════════════ Examination 2 — Networks and decision mathematics (12 marks) ════════════════
  ext(NW, 'proficient',
    'The graph below shows the bike paths between six lookouts, A to F.',
    [
      ['a', 'Write down the degree of vertex D.', 1, '3', 'D is joined to B, E and F.'],
      ['b', 'Explain why it is not possible to ride along every path exactly once.', 1, 'There are four vertices of odd degree (B, C, D and E); an Eulerian trail needs zero or two.', 'Degrees: A 2, B 3, C 3, D 3, E 3, F 2.'],
      ['c', 'Find the minimum number of paths that would need to be added so that a ride could use every path exactly once and return to its start.', 1, '2', 'Adding two paths, such as B–C and D–E, makes every degree even, which gives an Eulerian circuit.'],
      ['d', 'Write down a Hamiltonian cycle that starts and finishes at A.', 1, 'A–B–D–F–E–C–A', 'Each vertex is visited once: A–B, B–D, D–F, F–E, E–C and C–A are all paths.'],
    ],
    { diagram: { kind: 'network_graph', title: 'Bike paths', vertices: [{ id: 'A', x: 5, y: 50 }, { id: 'B', x: 30, y: 86 }, { id: 'C', x: 30, y: 14 }, { id: 'D', x: 66, y: 86 }, { id: 'E', x: 66, y: 14 }, { id: 'F', x: 95, y: 50 }], edges: [{ from: 'A', to: 'B' }, { from: 'A', to: 'C' }, { from: 'B', to: 'C' }, { from: 'B', to: 'D' }, { from: 'C', to: 'E' }, { from: 'D', to: 'E' }, { from: 'D', to: 'F' }, { from: 'E', to: 'F' }] } }),
  ext(NW, 'advanced',
    'The table below shows the activities needed to renovate a kitchen, their durations in days and their immediate predecessors.',
    [
      ['a', 'Find the earliest start time for activity E.', 1, 'Day 7', 'E needs B (finishes day 5) and C (finishes day 3 + 4 = 7), so it starts on day 7.'],
      ['b', 'Find the minimum time, in days, to complete the renovation.', 1, '15 days', 'The critical path is A–D–F–G: 3 + 6 + 2 + 4 = 15 days.'],
      ['c', 'Find the float time for activity B.', 1, '3 days', 'E’s latest start is day 8 (G’s latest start 11 − 3). B must finish by day 8, so its latest start is 8 − 5 = 3, and its float is 3 − 0 = 3 days.'],
      ['d', 'The duration of activity D can be reduced by up to 3 days. If it is reduced by 2 days, find the new minimum completion time.', 1, '14 days', 'A–D–F–G becomes 3 + 4 + 2 + 4 = 13 days, but A–C–E–G is 3 + 4 + 3 + 4 = 14 days, which is now critical. Only one day is saved.'],
    ],
    { diagram: { kind: 'data_table', title: 'Kitchen renovation', columns: ['Activity', 'Duration (days)', 'Immediate predecessor(s)'], rowHeader: true, rows: [['A', 3, '–'], ['B', 5, '–'], ['C', 4, 'A'], ['D', 6, 'A'], ['E', 3, 'B, C'], ['F', 2, 'D'], ['G', 4, 'E, F']] } }),
  ext(NW, 'advanced',
    'The weighted graph below shows the roads, with distances in kilometres, between a depot S, four towns A, B, C and D, and a terminal T.',
    [
      ['a', 'Find the length of the shortest path from S to T.', 1, '17 km', 'Using Dijkstra’s algorithm: B 4, A 6 (via B), D 10, C 11 (via A), T 17 (via C).'],
      ['b', 'Write down the route of this shortest path.', 1, 'S–B–A–C–T', '4 + 2 + 5 + 6 = 17 km.'],
      ['c', 'Find the total length of the minimum spanning tree.', 1, '20 km', 'Kruskal: AB (2), CD (3), SB (4), AC (5), then CT (6); BD (6) would form a cycle. Total 2 + 3 + 4 + 5 + 6 = 20 km.'],
      ['d', 'The road between A and C is closed. Find the new length of the shortest path from S to T.', 1, '18 km', 'Without A–C the best route is S–B–C–T = 4 + 8 + 6 = 18 km (S–B–D–C–T and S–B–D–T are both 19 km).'],
    ],
    { diagram: { kind: 'network_graph', title: 'Road distances (km)', vertices: [{ id: 'S', x: 5, y: 50 }, { id: 'A', x: 33, y: 86 }, { id: 'B', x: 33, y: 14 }, { id: 'C', x: 66, y: 80 }, { id: 'D', x: 66, y: 20 }, { id: 'T', x: 95, y: 50 }], edges: [{ from: 'S', to: 'A', weight: 7 }, { from: 'S', to: 'B', weight: 4 }, { from: 'A', to: 'B', weight: 2 }, { from: 'A', to: 'C', weight: 5 }, { from: 'B', to: 'C', weight: 8 }, { from: 'B', to: 'D', weight: 6 }, { from: 'C', to: 'D', weight: 3 }, { from: 'C', to: 'T', weight: 6 }, { from: 'D', to: 'T', weight: 9 }] } }),
]
