// VCE General Mathematics Unit 3 & 4 — Practice set 4.
// Examination 1: 40 multiple choice (16 / 8 / 8 / 8). Examination 2: 60 marks (24 / 12 / 12 / 12).
const DA = 'gm_data_analysis', RF = 'gm_financial', MX = 'gm_matrices', NW = 'gm_networks'
const S = 4
const code = { [DA]: 'VCE-GM-U34-AOS1', [RF]: 'VCE-GM-U34-AOS2', [MX]: 'VCE-GM-U34-AOS3', [NW]: 'VCE-GM-U34-AOS4' }
const mc = (t, d, q, o, e, extra = {}) => ({ t, s: S, d, calc: true, q, o, e, code: code[t], ...extra })
const ext = (t, d, q, p, extra = {}) => ({ t, s: S, d, calc: true, q, p, code: code[t], ...extra })

const drinkTable = {
  kind: 'data_table',
  title: 'Temperature and cold drink sales',
  columns: ['Maximum temperature (°C)', '18', '21', '24', '26', '29', '31', '34'],
  rowHeader: true,
  rows: [['Drinks sold', 120, 138, 151, 165, 178, 192, 204]],
}

const trackNetwork = {
  kind: 'network_graph',
  title: 'Road distances (km)',
  vertices: [
    { id: 'A', x: 5, y: 50 }, { id: 'B', x: 28, y: 86 }, { id: 'C', x: 28, y: 14 }, { id: 'D', x: 56, y: 56 },
    { id: 'E', x: 56, y: 10 }, { id: 'F', x: 80, y: 88 }, { id: 'G', x: 95, y: 40 },
  ],
  edges: [
    { from: 'A', to: 'B', weight: 5 }, { from: 'A', to: 'C', weight: 3 }, { from: 'B', to: 'C', weight: 4 },
    { from: 'B', to: 'D', weight: 6 }, { from: 'C', to: 'D', weight: 7 }, { from: 'C', to: 'E', weight: 9 },
    { from: 'D', to: 'E', weight: 4 }, { from: 'D', to: 'F', weight: 5 }, { from: 'E', to: 'G', weight: 7 },
    { from: 'F', to: 'G', weight: 3 }, { from: 'D', to: 'G', weight: 9 },
  ],
}

const fitoutTable = {
  kind: 'data_table',
  title: 'Activities for building a deck',
  columns: ['Activity', 'Duration (days)', 'Immediate predecessor(s)'],
  rowHeader: true,
  rows: [['A', 3, '–'], ['B', 4, '–'], ['C', 2, 'A'], ['D', 5, 'A'], ['E', 3, 'B, C'], ['F', 4, 'D'], ['G', 2, 'E, F']],
}

export const ITEMS = [
  // ════════════════ Examination 1 — Data analysis (16) ════════════════
  mc(DA, 'developing',
    'The numbers on the jerseys worn by the players in a football team are an example of',
    ['a categorical nominal variable', 'a categorical ordinal variable', 'a numerical discrete variable', 'a numerical continuous variable', 'a bivariate numerical variable'],
    'Jersey numbers are labels. They have no meaningful order or size — a player wearing 20 is not "twice" a player wearing 10 — so the variable is categorical nominal.'),
  mc(DA, 'developing',
    'The stem plot below shows the scores of 15 students on a quiz marked out of 50. The interquartile range of the scores is',
    ['15', '13', '17', '27', '31'],
    'In order: 15, 18, 19, 21, 23, 24, 24, 27, 30, 32, 35, 36, 38, 41, 46. The median is the 8th value, 27. Q₁ is the median of the lower seven values, 21, and Q₃ is the median of the upper seven, 36. IQR = 36 − 21 = 15. The range is 31.',
    { diagram: { kind: 'stem_leaf', title: 'Quiz scores', rows: [{ stem: '1', leaves: '5 8 9' }, { stem: '2', leaves: '1 3 4 4 7' }, { stem: '3', leaves: '0 2 5 6 8' }, { stem: '4', leaves: '1 6' }], keyText: '1 | 5 means 15' } }),
  mc(DA, 'developing',
    'The box plot below shows the battery life, in hours, of 200 phones. The number of phones with a battery life of more than 14 hours is closest to',
    ['50', '14', '25', '100', '150'],
    '14 hours is the third quartile, so about 25% of the phones lie above it: 0.25 × 200 = 50.',
    { diagram: { kind: 'box_plot', title: 'Battery life of 200 phones', axisLabel: 'battery life (hours)', min: 4, max: 22, step: 2, boxes: [{ min: 6, q1: 9, median: 11, q3: 14, max: 21 }] } }),
  mc(DA, 'developing',
    'The time taken to assemble a desk is approximately normally distributed with a mean of 45 minutes and a standard deviation of 6 minutes. Using the 68–95–99.7% rule, the percentage of desks assembled in between 39 and 57 minutes is',
    ['81.5%', '47.5%', '68%', '83.85%', '95%'],
    '39 is one standard deviation below the mean and 57 is two above. That is 34% + 47.5% = 81.5%.'),
  mc(DA, 'proficient',
    'The resting heart rates of adults are approximately normally distributed with a mean of 72 beats per minute and a standard deviation of 8 beats per minute. For an adult with a resting heart rate of 56 beats per minute, the standardised score, and the approximate percentage of adults with a lower resting heart rate, are',
    ['z = −2 and 2.5%', 'z = −2 and 5%', 'z = 2 and 2.5%', 'z = −2 and 16%', 'z = −1.6 and 5.5%'],
    'z = (56 − 72) ÷ 8 = −2. By the 68–95–99.7% rule, 95% lie within two standard deviations, so 2.5% lie below z = −2.'),
  mc(DA, 'proficient',
    'The table below shows, as column percentages, the preferred type of holiday of people in three age groups. Which one of the following statements supports the view that preferred type of holiday is associated with age group?',
    ['The percentage preferring a beach holiday decreases as age increases, from 52% to 38% to 25%.', 'The percentage preferring a city holiday is about the same in every age group.', 'Most people aged over 50 prefer a beach holiday.', 'A nature holiday is the most popular type in every age group.', 'Because 30% of two age groups prefer city holidays, there is no association.'],
    'An association exists when the percentages in a category change across the groups. Beach and nature preferences both change markedly with age; the city percentages alone would not show an association.',
    { diagram: { kind: 'data_table', title: 'Preferred holiday (column %)', columns: ['Holiday type', 'Under 30', '30 to 50', 'Over 50'], rowHeader: true, rows: [['Beach', '52%', '38%', '25%'], ['City', '30%', '32%', '30%'], ['Nature', '18%', '30%', '45%'], ['Total', '100%', '100%', '100%']] } }),
  mc(DA, 'developing',
    'For a group of teenagers, the correlation coefficient between daily hours of screen time and nightly hours of sleep is r = −0.84. The association between these variables is best described as',
    ['strong, negative and linear', 'moderate, negative and linear', 'strong, positive and linear', 'weak, negative and linear', 'strong and negative, with screen time causing less sleep'],
    'r = −0.84 lies between −0.75 and −1, which is conventionally strong and negative. Correlation alone does not establish that one variable causes the other.'),
  mc(DA, 'developing',
    'For a sample of used cars of one model, the least squares line price = 28 500 − 2100 × age is fitted, where price is in dollars and age is in years. The best interpretation of the intercept is that',
    ['a car of this model aged 0 years is predicted to be worth $28 500', 'the price falls by $28 500 each year', 'the price falls by $2100 each year', 'every car in the sample cost $28 500', 'a car of this model aged 1 year is predicted to be worth $28 500'],
    'The intercept is the predicted value of the response variable when the explanatory variable is zero, here a new car.'),
  mc(DA, 'proficient',
    'A reciprocal transformation is applied to a set of bivariate data, and the least squares line y = 2.5 + 40 × (1/x) is fitted. The value of y predicted when x = 8 is',
    ['7.5', '2.81', '5.0', '42.5', '322.5'],
    '1/x = 1/8 = 0.125, so y = 2.5 + 40 × 0.125 = 7.5. Using x instead of 1/x gives 322.5.'),
  mc(DA, 'proficient',
    'A scatterplot shows that y decreases as x increases, and that the rate of decrease slows as x increases. A transformation that could linearise this association is',
    ['log₁₀(x)', 'x²', 'y²', 'x² together with y²', 'none — a straight line should be fitted without a transformation'],
    'For data that decrease and flatten out, the circle of transformations suggests log x, 1/x, log y or 1/y. Squaring x or y would increase the curvature.'),
  mc(DA, 'developing',
    'The time series plot below shows the quarterly number of visitors, in thousands, to a regional museum over three years. The plot shows',
    ['an increasing trend with seasonality', 'seasonality with no trend', 'a decreasing trend with seasonality', 'an increasing trend with an outlier', 'irregular fluctuations only'],
    'The peaks and troughs repeat every four quarters (seasonality), and the level of each year is higher than the year before (increasing trend).',
    { diagram: { kind: 'line_graph', title: 'Museum visitors each quarter', xLabels: ['Q1', 'Q2', 'Q3', 'Q4', 'Q1', 'Q2', 'Q3', 'Q4', 'Q1', 'Q2', 'Q3', 'Q4'], series: [{ values: [42, 58, 50, 36, 46, 63, 55, 39, 51, 68, 59, 44] }], yMin: 30, yMax: 70, yStep: 10, xLabel: 'quarter (years 1 to 3)', yLabel: 'visitors (000s)' } }),
  mc(DA, 'proficient',
    'The table below shows the number of bikes hired from a stand each week for seven weeks. The five-median smoothed value for week 4 is',
    ['18', '17', '19.4', '20', '22'],
    'The five values centred on week 4 are 18, 15, 22, 17 and 25. In order: 15, 17, 18, 22, 25, so the median is 18. The mean, 19.4, gives the five-mean smoothed value instead.',
    { diagram: { kind: 'data_table', title: 'Weekly bike hire', columns: ['Week', '1', '2', '3', '4', '5', '6', '7'], rowHeader: true, rows: [['Bikes hired', 12, 18, 15, 22, 17, 25, 20]] } }),
  mc(DA, 'developing',
    'The deseasonalised sales of a business for Quarter 3 were $64 000, and the seasonal index for Quarter 3 is 1.15. The actual sales for Quarter 3 were',
    ['$73 600', '$55 652', '$64 000', '$9600', '$65 150'],
    'Actual = deseasonalised × seasonal index = 64 000 × 1.15 = $73 600. Dividing by the index gives $55 652, which reverses the calculation.'),
  mc(DA, 'proficient',
    'The seasonal index for Quarter 2 sales at a shop is 0.8. To correct Quarter 2 sales for seasonality, they must be',
    ['increased by 25%', 'decreased by 20%', 'increased by 20%', 'decreased by 25%', 'left unchanged'],
    'Deseasonalised = actual ÷ 0.8 = actual × 1.25, an increase of 25%.'),
  mc(DA, 'proficient',
    'The table below shows the maximum temperature and the number of cold drinks sold at a kiosk on seven days. Drinks sold is to be predicted from temperature. Using a CAS, the equation of the least squares line, with coefficients correct to two decimal places, is',
    ['drinks sold = 25.65 + 5.29 × temperature', 'drinks sold = 5.29 + 25.65 × temperature', 'drinks sold = 25.65 + 0.19 × temperature', 'temperature = −4.75 + 0.19 × drinks sold', 'drinks sold = 164.00 + 5.29 × temperature'],
    'With temperature as x and drinks sold as y: slope 5.2919 and intercept 25.6542. Swapping the variables gives temperature = −4.75 + 0.19 × drinks sold, which predicts the wrong variable.',
    { diagram: drinkTable }),
  mc(DA, 'proficient',
    'For the data in the table below, the percentage of the variation in the number of drinks sold that is explained by the variation in temperature, correct to one decimal place, is',
    ['99.7%', '0.3%', '5.3%', '84.0%', '99.8%'],
    'r = 0.9984, so r² = 0.9968, which is 99.7%. 99.8% is r written as a percentage, a common error.',
    { diagram: drinkTable }),

  // ════════════════ Examination 1 — Recursion and financial modelling (8) ════════════════
  mc(RF, 'developing',
    'A sequence is generated by the recurrence relation V₀ = 2000, Vₙ₊₁ = Vₙ − 150. The smallest value of n for which Vₙ < 1000 is',
    ['7', '3', '4', '5', '6'],
    'Vₙ = 2000 − 150n. V₆ = 1100 and V₇ = 950.'),
  mc(RF, 'developing',
    'A water tank holding 5000 L loses 4% of the water in it each day. The volume of water in the tank after three days, in litres, is',
    ['4423.68', '4247.54', '4400.00', '4608.00', '5624.32'],
    '5000 × 0.96³ = 4423.68. Subtracting 4% of 5000 each day gives 4400, which treats the loss as linear.'),
  mc(RF, 'proficient',
    'An investment earns interest at 6% per annum, compounding quarterly, and $500 is added to it at the end of every quarter. A recurrence relation for the value Vₙ of the investment after n quarters is',
    ['Vₙ₊₁ = 1.015Vₙ + 500', 'Vₙ₊₁ = 1.06Vₙ + 500', 'Vₙ₊₁ = 1.015(Vₙ + 500)', 'Vₙ₊₁ = 0.985Vₙ + 500', 'Vₙ₊₁ = 1.5Vₙ + 500'],
    'The quarterly rate is 6% ÷ 4 = 1.5%, so each quarter the value is multiplied by 1.015, and then the deposit is added.'),
  mc(RF, 'proficient',
    'A loan of $18 000 is charged interest at 9.6% per annum, compounding monthly, and is repaid with equal monthly repayments over three years. The monthly repayment, correct to the nearest cent, is',
    ['$577.43', '$144.00', '$500.00', '$598.93', '$644.00'],
    'Financial solver: N = 36, I% = 9.6, PV = 18 000, FV = 0, P/Y = C/Y = 12 gives PMT = −577.43. $500 ignores interest, $644 uses simple interest, and $144 is the interest-only repayment.'),
  mc(RF, 'advanced',
    'Leila invests $5000 in an account paying 4.16% per annum, compounding fortnightly, and adds $150 at the end of every fortnight. Assuming 26 fortnights in a year, the balance after two years, correct to the nearest cent, is',
    ['$13 560.33', '$12 800.00', '$13 233.43', '$13 573.33', '$14 017.65'],
    'Financial solver: N = 52, I% = 4.16, PV = −5000, PMT = −150, P/Y = C/Y = 26 gives FV = 13 560.33. $12 800 ignores interest, and $13 573.33 treats the deposits as made at the start of each fortnight.'),
  mc(RF, 'developing',
    'An amount is to be invested at 4.8% per annum, compounding monthly, so that it acts as a perpetuity paying $1800 at the end of every month. The amount that must be invested is',
    ['$450 000', '$37 500', '$45 000', '$432 000', '$540 000'],
    'The monthly rate is 0.4%, and a perpetuity pays only the interest: 1800 ÷ 0.004 = $450 000. Dividing by the annual rate gives $37 500.'),
  mc(RF, 'proficient',
    'Part of the amortisation table for a loan charged interest at 6% per annum, compounding monthly, is shown below. The value of X, the interest charged in payment 3, correct to the nearest cent, is',
    ['$193.48', '$190.20', '$196.75', '$200.00', '$656.52'],
    'The monthly rate is 0.5%, and interest is charged on the balance after payment 2: 0.005 × 38 696.75 = $193.48.',
    { diagram: { kind: 'data_table', title: 'Amortisation table', columns: ['Payment number', 'Payment ($)', 'Interest ($)', 'Principal reduction ($)', 'Balance ($)'], rowHeader: true, rows: [['0', '0.00', '0.00', '0.00', '40 000.00'], ['1', '850.00', '200.00', '650.00', '39 350.00'], ['2', '850.00', '196.75', '653.25', '38 696.75'], ['3', '850.00', 'X', '', '']] } }),
  mc(RF, 'developing',
    'An amount of $8000 is invested at 5% per annum, compounding annually. The number of years it takes for the investment to first exceed $16 000 is',
    ['15', '10', '12', '13', '14'],
    '1.05¹⁴ = 1.980 and 1.05¹⁵ = 2.079, so the value first exceeds double after 15 years. After 14 years it is still just under $16 000.'),

  // ════════════════ Examination 1 — Matrices (8) ════════════════
  mc(MX, 'developing',
    'The matrix product AB has order 3 × 4. If matrix A has order 3 × 5, then matrix B has order',
    ['5 × 4', '4 × 5', '3 × 4', '5 × 3', '4 × 3'],
    'For AB to exist, B must have 5 rows. The product has the rows of A and the columns of B, so B has 4 columns.'),
  mc(MX, 'proficient',
    'The elements of the 3 × 3 matrix A are given by aᵢⱼ = 2i − j. The sum of the elements in row 3 of A is',
    ['12', '0', '3', '5', '6'],
    'Row 3 has a₃₁ = 5, a₃₂ = 4 and a₃₃ = 3, which sum to 12. Row 1 sums to 0 and row 2 to 6.'),
  mc(MX, 'proficient',
    'The inverse of matrix A below is the matrix with',
    ['first row 1, −1.5 and second row −1, 2', 'first row 2, −3 and second row −2, 4', 'first row 1, −1 and second row −1.5, 2', 'first row −1, 1.5 and second row 1, −2', 'first row 0.25, 0.33 and second row 0.5, 0.5'],
    'det(A) = 4 × 2 − 3 × 2 = 2. Swap the leading diagonal, negate the other elements and divide by 2: (1/2) × (first row 2, −3; second row −2, 4).',
    { diagram: { kind: 'matrix', name: 'A =', rows: [[4, 3], [2, 2]] } }),
  mc(MX, 'developing',
    'The simultaneous equations 2x − y = 7 and x + 3y = 0 are solved using matrices. The solution is',
    ['x = 3, y = −1', 'x = −1, y = 3', 'x = 3, y = 1', 'x = 7, y = 0', 'x = 21/5, y = −7/5'],
    'The coefficient matrix has determinant 2 × 3 − (−1) × 1 = 7. Solving gives x = 3 and y = −1. Check: 6 + 1 = 7 and 3 − 3 = 0.'),
  mc(MX, 'proficient',
    'In the communication matrix C below, a 1 in row i and column j means that person i can send a message directly to person j. The number of ways person 1 can send a message to person 4 through exactly one other person is',
    ['2', '3', '4', '6', '8'],
    'The element in row 1, column 4 of C² is 2: the routes are 1 → 2 → 4 and 1 → 3 → 4.',
    { diagram: { kind: 'matrix', name: 'C =', rows: [[0, 1, 1, 0], [1, 0, 1, 1], [0, 1, 0, 1], [1, 0, 1, 0]], rowLabels: ['1', '2', '3', '4'], colLabels: ['1', '2', '3', '4'] } }),
  mc(MX, 'proficient',
    'The transition matrix T below (columns: this week, rows: next week) shows how 1000 members of a club move between three activities, A, B and C. This week 300 members are in A, 400 in B and 300 in C. The number in C next week is',
    ['280', '210', '250', '300', '310'],
    'Row C of T multiplied by the state matrix: 0.1 × 300 + 0.1 × 400 + 0.7 × 300 = 30 + 40 + 210 = 280.',
    { diagram: { kind: 'matrix', name: 'T =', rows: [[0.7, 0.1, 0.2], [0.2, 0.8, 0.1], [0.1, 0.1, 0.7]], colLabels: ['A', 'B', 'C'], rowLabels: ['A', 'B', 'C'] } }),
  mc(MX, 'proficient',
    'For matrix A below, the matrix A² is the matrix with',
    ['first row 7, 2 and second row 3, 6', 'first row 1, 4 and second row 9, 0', 'first row 2, 4 and second row 6, 0', 'first row 7, 3 and second row 2, 6', 'first row 1, 6 and second row 6, 0'],
    'A² = A × A: row 1 gives 1 × 1 + 2 × 3 = 7 and 1 × 2 + 2 × 0 = 2; row 2 gives 3 × 1 + 0 × 3 = 3 and 3 × 2 + 0 × 0 = 6. Squaring each element gives the wrong matrix.',
    { diagram: { kind: 'matrix', name: 'A =', rows: [[1, 2], [3, 0]] } }),
  mc(MX, 'developing',
    'In the transition matrix T below, the columns show this year and the rows show next year. The element 0.15 means that',
    ['each year, 15% of those in A move to B', 'each year, 15% of those in B move to A', 'each year, 15% of those in A stay in A', 'in the long run, 15% will be in B', 'each year, 15% of the total population moves'],
    '0.15 is in column A (this year) and row B (next year).',
    { diagram: { kind: 'matrix', name: 'T =', rows: [[0.85, 0.4], [0.15, 0.6]], colLabels: ['A', 'B'], rowLabels: ['A', 'B'] } }),

  // ════════════════ Examination 1 — Networks and decision mathematics (8) ════════════════
  mc(NW, 'developing',
    'The weighted graph below shows the roads between seven towns, with distances in kilometres. The length of the shortest path from A to G, in kilometres, is',
    ['18', '17', '19', '20', '22'],
    'Dijkstra’s algorithm: C 3, B 5, D 10 (via C), E 12 (via C), F 15 (via D), G 18 (via F). The route is A–C–D–F–G.',
    { diagram: trackNetwork }),
  mc(NW, 'proficient',
    'For the weighted graph below, the total length of the minimum spanning tree, in kilometres, is',
    ['25', '19', '21', '22', '24'],
    'Kruskal’s algorithm: AC 3, FG 3, BC 4, DE 4, then AB 5 is rejected (cycle), DF 5, BD 6. Total 3 + 3 + 4 + 4 + 5 + 6 = 25 km.',
    { diagram: trackNetwork }),
  mc(NW, 'advanced',
    'For the graph below, removing which one of the following edges would leave a graph that has an Eulerian trail?',
    ['B–D', 'A–B', 'C–E', 'F–G', 'A–C'],
    'The odd-degree vertices are B (3), D (5), E (3) and G (3). Removing B–D makes B and D even, leaving exactly two odd vertices, E and G. Each other option leaves four or six odd vertices.',
    { diagram: trackNetwork }),
  mc(NW, 'proficient',
    'The directed network below shows the capacity, in litres per minute, of each pipe from a source S to a sink T. The maximum flow from S to T, in litres per minute, is',
    ['20', '19', '21', '22', '23'],
    'The minimum cut crosses the three pipes into T: 7 + 9 + 4 = 20. This flow is achievable, for example with 4 from A to C and 5 from B to C.',
    { diagram: { kind: 'network_graph', title: 'Pipe capacities (L/min)', directed: true, vertices: [{ id: 'S', x: 5, y: 50 }, { id: 'A', x: 35, y: 86 }, { id: 'B', x: 35, y: 14 }, { id: 'C', x: 62, y: 50 }, { id: 'T', x: 95, y: 50 }], edges: [{ from: 'S', to: 'A', weight: 12 }, { from: 'S', to: 'B', weight: 10 }, { from: 'A', to: 'C', weight: 6 }, { from: 'A', to: 'T', weight: 7 }, { from: 'B', to: 'C', weight: 5 }, { from: 'C', to: 'T', weight: 9 }, { from: 'B', to: 'T', weight: 4 }] } }),
  mc(NW, 'advanced',
    'Four swimmers, W, X, Y and Z, are each to swim one leg of a medley relay. The table below shows each swimmer’s time, in seconds, for each stroke. The minimum total time for the relay, in seconds, is',
    ['127', '120', '129', '130', '133'],
    'The Hungarian algorithm gives W freestyle (29), X breaststroke (35), Y backstroke (33) and Z butterfly (30): 127 seconds. 120 is the sum of each swimmer’s best time, which would need two swimmers on freestyle.',
    { diagram: { kind: 'data_table', title: 'Times (seconds)', columns: ['Swimmer', 'Backstroke', 'Breaststroke', 'Butterfly', 'Freestyle'], rowHeader: true, rows: [['W', 34, 38, 31, 29], ['X', 36, 35, 33, 30], ['Y', 33, 39, 32, 31], ['Z', 37, 36, 30, 32]] } }),
  mc(NW, 'developing',
    'The table below shows the activities in a project, their durations and their immediate predecessors. The critical path is',
    ['A, D, F, G', 'A, C, E, G', 'B, E, G', 'A, D, F', 'A, C, D, F, G'],
    'Earliest start times: C 3, D 3, E 5, F 8, G 12, so the project takes 14 days. A–D–F–G takes 3 + 5 + 4 + 2 = 14 days, and every activity on it has zero float.',
    { diagram: fitoutTable }),
  mc(NW, 'proficient',
    'For the project in the table below, the duration of activity D is reduced by 2 days. The new minimum time to complete the project, in days, is',
    ['12', '9', '10', '11', '14'],
    'A–D–F–G becomes 3 + 3 + 4 + 2 = 12 days. The other paths, A–C–E–G (10 days) and B–E–G (9 days), are shorter, so the project takes 12 days.',
    { diagram: fitoutTable }),
  mc(NW, 'developing',
    'A graph has 7 vertices, and every vertex has degree 4. The number of edges in the graph is',
    ['14', '7', '11', '21', '28'],
    'The sum of the degrees is 7 × 4 = 28, which is twice the number of edges.'),

  // ════════════════ Examination 2 — Data analysis (24 marks) ════════════════
  ext(DA, 'proficient',
    'The stem plot below shows the daily maximum temperature, in degrees Celsius, in a country town over 15 days in March.',
    [
      ['a', 'Find the median temperature.', 1, '25 °C', 'With 15 values, the median is the 8th: 25.'],
      ['b', 'Find the interquartile range.', 1, '9 °C', 'Q₁ is the median of the lower seven values, 21, and Q₃ is the median of the upper seven, 30. IQR = 30 − 21 = 9.'],
      ['c', 'Show that the temperature of 41 °C is not an outlier.', 2, 'Upper fence = 30 + 1.5 × 9 = 43.5; 41 < 43.5, so it is not an outlier.', 'One mark for the upper fence, one for the comparison.'],
      ['d', 'Find the mean and standard deviation of the temperatures, correct to one decimal place.', 1, 'Mean 25.8 °C; standard deviation 6.2 °C', 'Using a CAS: x̄ = 25.8 and sₓ = 6.155.'],
      ['e', 'Find the percentage of these days on which the maximum temperature was higher than 30 °C.', 1, '20%', 'Three days (31, 33 and 41) out of 15.'],
    ],
    { diagram: { kind: 'stem_leaf', title: 'Daily maximum temperature (°C)', rows: [{ stem: '1', leaves: '8 9' }, { stem: '2', leaves: '0 1 2 2 4 5 6 7 8' }, { stem: '3', leaves: '0 1 3' }, { stem: '4', leaves: '1' }], keyText: '1 | 8 means 18 °C' } }),
  ext(DA, 'proficient',
    'The table below shows the hours of sunshine and the energy, in kilowatt-hours (kWh), generated by a household’s solar panels on eight days. Energy generated is to be predicted from hours of sunshine.',
    [
      ['a', 'Name the explanatory variable.', 1, 'Hours of sunshine', 'The variable used to make the prediction.'],
      ['b', 'Find the equation of the least squares line. Write the coefficients correct to two decimal places.', 2, 'energy = 0.30 + 1.86 × sunshine', 'Using a CAS: intercept 0.3036, slope 1.8585. One mark for each coefficient.'],
      ['c', 'Interpret the slope of the least squares line.', 1, 'On average, energy generated increases by 1.86 kWh for each additional hour of sunshine.', 'The slope is the average change in the response per unit change in the explanatory variable.'],
      ['d', 'Find the coefficient of determination, correct to three decimal places, and interpret it.', 1, 'r² = 0.998: 99.8% of the variation in energy generated is explained by the variation in hours of sunshine.', 'r = 0.9992.'],
      ['e', 'Find the residual for the day with 7.5 hours of sunshine, correct to two decimal places.', 1, '0.26 kWh', 'Predicted = 0.3036 + 1.8585 × 7.5 = 14.24, and 14.5 − 14.24 = 0.26. Using the rounded coefficients gives 0.25, which is also accepted.'],
    ],
    { diagram: { kind: 'data_table', title: 'Sunshine and solar energy', columns: ['Sunshine (hours)', '2', '3.5', '5', '6', '7.5', '8', '9.5', '11'], rowHeader: true, rows: [['Energy (kWh)', 4.1, 6.8, 9.6, 11.2, 14.5, 14.9, 18.3, 20.6]] } }),
  ext(DA, 'advanced',
    'The scatterplot below shows the stopping distance, in metres, of a car at different speeds, in km/h. The speeds 40, 50, 60, 70, 80, 90 and 100 km/h gave stopping distances of 17, 24, 32, 42, 53, 65 and 78 m.',
    [
      ['a', 'A least squares line is fitted to the data, and its residual plot shows a clear U-shaped pattern. What does this indicate?', 1, 'The association is not linear, so a linear model is not appropriate even though r is high.', 'A random scatter of residuals is needed to support linearity.'],
      ['b', 'A squared transformation is applied to speed. Find the equation of the least squares line for stopping distance against speed². Write the coefficients correct to four significant figures.', 2, 'distance = 5.849 + 0.007279 × speed²', 'Using a CAS with speed² as x: intercept 5.8485, slope 0.0072793. One mark for each coefficient.'],
      ['c', 'Find the coefficient of determination for the transformed data, correct to four decimal places.', 1, '0.9996', 'r = 0.99979.'],
      ['d', 'Use the transformed model to predict the stopping distance at 110 km/h, correct to one decimal place.', 1, '93.9 m', '5.8485 + 0.0072793 × 12 100 = 93.93.'],
      ['e', 'Explain why this prediction may be unreliable.', 1, 'It is an extrapolation: 110 km/h lies outside the range of speeds in the data (40 to 100 km/h).', 'The model has not been tested beyond the data.'],
    ],
    { diagram: { kind: 'function_graph', title: 'Stopping distance against speed', xMin: 30, xMax: 110, yMin: 0, yMax: 90, xStep: 10, yStep: 10, xLabel: 'speed (km/h)', yLabel: 'distance (m)', curves: [], points: [{ x: 40, y: 17 }, { x: 50, y: 24 }, { x: 60, y: 32 }, { x: 70, y: 42 }, { x: 80, y: 53 }, { x: 90, y: 65 }, { x: 100, y: 78 }] } }),
  ext(DA, 'proficient',
    'The time series plot below shows the number of visitors to a swimming pool on ten consecutive days. The numbers were 142, 156, 149, 171, 165, 188, 176, 195, 190 and 212.',
    [
      ['a', 'Describe the features of the time series.', 1, 'An increasing trend with irregular fluctuations.', 'Visitor numbers rise over the ten days, with ups and downs from day to day.'],
      ['b', 'Find the three-point moving average for day 5, correct to one decimal place.', 1, '174.7', '(171 + 165 + 188) ÷ 3 = 174.67.'],
      ['c', 'Find the four-point moving average with centring for day 5, correct to one decimal place.', 2, '171.6', 'Days 3 to 6 average (149 + 171 + 165 + 188) ÷ 4 = 168.25 and days 4 to 7 average (171 + 165 + 188 + 176) ÷ 4 = 175. Centring: (168.25 + 175) ÷ 2 = 171.625. One mark for the two averages, one for centring.'],
      ['d', 'A least squares line fitted to the data is visitors = 136.5 + 6.88 × day. Use it to predict the number of visitors on day 14, to the nearest whole number.', 1, '233', '136.5 + 6.88 × 14 = 232.8.'],
      ['e', 'Interpret the slope of this least squares line.', 1, 'On average, the number of visitors increases by about 6.9 each day.', 'The slope is the average daily change.'],
    ],
    { diagram: { kind: 'line_graph', title: 'Daily visitors to a swimming pool', xLabels: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], series: [{ values: [142, 156, 149, 171, 165, 188, 176, 195, 190, 212] }], yMin: 130, yMax: 220, yStep: 10, xLabel: 'day', yLabel: 'visitors' } }),

  // ════════════════ Examination 2 — Recursion and financial modelling (12 marks) ════════════════
  ext(RF, 'proficient',
    'A farm buys a crop-spraying drone for $9600. It can be depreciated by the unit cost method at $0.80 per kilometre flown, and it is expected to fly 1500 km each year. Alternatively, it can be depreciated by the reducing balance method at 18% per year.',
    [
      ['a', 'Write down a recurrence relation for the value Vₙ, in dollars, of the drone after n years using unit cost depreciation.', 1, 'V₀ = 9600, Vₙ₊₁ = Vₙ − 1200', '1500 × 0.80 = $1200 per year.'],
      ['b', 'Using unit cost depreciation, after how many years is the value of the drone first less than $3000?', 1, '6 years', 'After 5 years the value is 9600 − 6000 = $3600; after 6 years it is $2400.'],
      ['c', 'Find the value of the drone after four years using reducing balance depreciation, correct to the nearest cent.', 1, '$4340.37', '9600 × 0.82⁴ = 4340.37.'],
      ['d', 'Which method gives the higher value after five years, and by how much?', 1, 'Unit cost, by $40.90', 'Unit cost: $3600. Reducing balance: 9600 × 0.82⁵ = $3559.10.'],
    ]),
  ext(RF, 'advanced',
    'Ari borrows $520 000 to buy a house. Interest is charged at 5.88% per annum, compounding monthly, and the loan is to be repaid with equal monthly repayments over 25 years.',
    [
      ['a', 'Find the monthly repayment, correct to the nearest cent.', 1, '$3312.33', 'Financial solver: N = 300, I% = 5.88, PV = 520 000, FV = 0 gives PMT = −3312.33.'],
      ['b', 'Find the balance of the loan after five years, correct to the nearest dollar.', 1, '$466 837', 'N = 60 with PMT = −3312.33 gives FV = −466 837.'],
      ['c', 'Assuming all 300 repayments are $3312.33, find the total interest paid over the life of the loan.', 1, '$473 699', '300 × 3312.33 − 520 000 = 473 699.'],
      ['d', 'After five years the interest rate rises to 6.6% per annum, compounding monthly. Find the new monthly repayment, correct to the nearest cent, that would still repay the loan in 25 years in total.', 1, '$3508.15', 'N = 240, I% = 6.6, PV = 466 836.99, FV = 0 gives PMT = −3508.15.'],
    ]),
  ext(RF, 'proficient',
    'Noah opens a savings account with $2000. The account pays interest at 4.2% per annum, compounding monthly, and Noah deposits $400 at the end of every month.',
    [
      ['a', 'Write down a recurrence relation for the balance Vₙ, in dollars, after n months.', 1, 'V₀ = 2000, Vₙ₊₁ = 1.0035Vₙ + 400', 'The monthly rate is 4.2% ÷ 12 = 0.35%.'],
      ['b', 'Find the balance after three years, correct to the nearest cent.', 1, '$17 586.08', 'Financial solver: N = 36, I% = 4.2, PV = −2000, PMT = −400 gives FV = 17 586.08.'],
      ['c', 'Find the total interest earned over the three years.', 1, '$1186.08', '17 586.08 − 2000 − 36 × 400 = 1186.08.'],
      ['d', 'Find the monthly deposit, correct to the nearest cent, that would give a balance of $30 000 after four years.', 1, '$529.72', 'N = 48, I% = 4.2, PV = −2000, FV = 30 000 gives PMT = −529.72.'],
    ]),

  // ════════════════ Examination 2 — Matrices (12 marks) ════════════════
  ext(MX, 'advanced',
    'Each school day, the 500 students at a school either buy lunch at the canteen (C), bring lunch from home (H) or skip lunch (S). The transition matrix T below shows how their choices change from one day (columns) to the next (rows). On Monday, 200 students buy lunch at the canteen, 200 bring lunch from home and 100 skip lunch.',
    [
      ['a', 'Explain the meaning of the element 0.3 in row H and column C.', 1, '30% of the students who buy lunch at the canteen on one day bring lunch from home the next day.', 'Column C is today; row H is the next day.'],
      ['b', 'Find the number of students making each choice on Tuesday.', 1, 'C 190, H 230, S 80', 'C: 0.6 × 200 + 0.2 × 200 + 0.3 × 100 = 190. H: 0.3 × 200 + 0.7 × 200 + 0.3 × 100 = 230. S: 0.1 × 200 + 0.1 × 200 + 0.4 × 100 = 80.'],
      ['c', 'Find the number of students who bring lunch from home on Wednesday.', 1, '242', '0.3 × 190 + 0.7 × 230 + 0.3 × 80 = 57 + 161 + 24 = 242.'],
      ['d', 'In the long run, how many students will bring lunch from home each day?', 1, '250', 'Raising T to a high power, or solving TS = S with a total of 500, gives about 178.6, 250 and 71.4.'],
    ],
    { diagram: { kind: 'matrix', name: 'T =', rows: [[0.6, 0.2, 0.3], [0.3, 0.7, 0.3], [0.1, 0.1, 0.4]], colLabels: ['C', 'H', 'S'], rowLabels: ['C', 'H', 'S'] } }),
  ext(MX, 'advanced',
    'A florist makes three bouquets from roses, lilies and daisies. Bouquet A uses 6 roses, 4 lilies and 5 daisies and costs $48 in flowers. Bouquet B uses 3 roses, 6 lilies and 8 daisies and costs $49. Bouquet C uses 10 roses, 2 lilies and 4 daisies and costs $55. Let r, l and d be the cost, in dollars, of one rose, one lily and one daisy.',
    [
      ['a', 'Write this information as a matrix equation of the form AX = B.', 1, 'A has rows 6, 4, 5; 3, 6, 8; 10, 2, 4. X is the column r, l, d and B is the column 48, 49, 55.', 'Each row of A lists the flowers in one bouquet.'],
      ['b', 'Find the determinant of A, and explain why the equations have a unique solution.', 1, 'det(A) = 50; since it is not zero, A⁻¹ exists and X = A⁻¹B is unique.', '6(24 − 16) − 4(12 − 80) + 5(6 − 60) = 48 + 272 − 270 = 50.'],
      ['c', 'Find the cost of each type of flower.', 1, 'Rose $4.00, lily $3.50, daisy $2.00', 'X = A⁻¹B, found with a CAS.'],
      ['d', 'Find the cost of the flowers in a bouquet of 5 roses, 5 lilies and 5 daisies.', 1, '$47.50', '5 × (4 + 3.5 + 2) = 47.50.'],
    ]),
  ext(MX, 'advanced',
    'An airline flies between five cities, A to E. In matrix R below, a 1 in row i and column j means there is a direct flight from city i to city j. Every route is flown in both directions.',
    [
      ['a', 'How many cities have a direct flight from city B?', 1, '3', 'Row B has 1s in columns A, C and D.'],
      ['b', 'The element in row A and column D of R² is 1. Explain what this means.', 1, 'There is one way to fly from A to D using exactly two flights: A → B → D.', 'R² counts the two-step routes.'],
      ['c', 'Explain why the element in row B and column B of R² is 3.', 1, 'B has three direct connections, and each gives a two-flight route from B and back to B.', 'For example B → A → B.'],
      ['d', 'Which two pairs of cities cannot be connected using at most two flights?', 1, 'A and E; C and E', 'These are the zero elements (off the leading diagonal) of R + R². Each pair needs three flights, via B and D.'],
    ],
    { diagram: { kind: 'matrix', name: 'R =', rows: [[0, 1, 1, 0, 0], [1, 0, 1, 1, 0], [1, 1, 0, 0, 0], [0, 1, 0, 0, 1], [0, 0, 0, 1, 0]], rowLabels: ['A', 'B', 'C', 'D', 'E'], colLabels: ['A', 'B', 'C', 'D', 'E'] } }),

  // ════════════════ Examination 2 — Networks and decision mathematics (12 marks) ════════════════
  ext(NW, 'proficient',
    'The graph below shows the walking tracks between six lookouts, P to U, in a national park.',
    [
      ['a', 'Explain why a walker can use every track exactly once, and state the lookouts at which such a walk must start and finish.', 1, 'Exactly two vertices, R and S, have odd degree (3), so an Eulerian trail exists. It must start at one of R and S and finish at the other.', 'Degrees: P 2, Q 4, R 3, S 3, T 4, U 2.'],
      ['b', 'Write down such a walk.', 1, 'For example R–P–Q–R–T–Q–S–T–U–S', 'Any trail that uses all nine tracks once, from R to S or from S to R.'],
      ['c', 'Write down a Hamiltonian cycle that starts and finishes at P.', 1, 'P–Q–S–U–T–R–P', 'Each lookout is visited once before returning to P.'],
      ['d', 'The graph is planar. Use Euler’s formula to find the number of faces.', 1, '5', 'v − e + f = 2 gives 6 − 9 + f = 2, so f = 5.'],
    ],
    { diagram: { kind: 'network_graph', title: 'Walking tracks', vertices: [{ id: 'P', x: 5, y: 50 }, { id: 'Q', x: 35, y: 86 }, { id: 'R', x: 35, y: 14 }, { id: 'S', x: 68, y: 86 }, { id: 'T', x: 68, y: 14 }, { id: 'U', x: 95, y: 50 }], edges: [{ from: 'P', to: 'Q' }, { from: 'P', to: 'R' }, { from: 'Q', to: 'R' }, { from: 'Q', to: 'S' }, { from: 'R', to: 'T' }, { from: 'S', to: 'T' }, { from: 'S', to: 'U' }, { from: 'T', to: 'U' }, { from: 'Q', to: 'T' }] } }),
  ext(NW, 'advanced',
    'The table below shows the activities needed to set up a market stall business, their durations in days and their immediate predecessors.',
    [
      ['a', 'Find the earliest start time for activity D.', 1, 'Day 4', 'D needs A (finishes on day 4) and B (finishes on day 3).'],
      ['b', 'Find the minimum time to complete the project, and write down the critical path.', 1, '18 days; A–C–E–G', '4 + 5 + 6 + 3 = 18.'],
      ['c', 'Find the float time for activity F.', 1, '5 days', 'F’s earliest start is day 6. G’s latest start is day 15, so F’s latest start is 15 − 4 = 11. Float = 11 − 6 = 5.'],
      ['d', 'Activity C can be reduced by up to 2 days at a cost of $500 per day, and activity E can be reduced by up to 2 days at a cost of $800 per day. Find the minimum cost of reducing the completion time to 15 days.', 1, '$1800', 'Reduce C by 2 days ($1000) and E by 1 day ($800). The other paths, A–D–F–G (13 days) and B–D–F–G (12 days), stay within 15 days.'],
    ],
    { diagram: { kind: 'data_table', title: 'Setting up a market stall', columns: ['Activity', 'Duration (days)', 'Immediate predecessor(s)'], rowHeader: true, rows: [['A', 4, '–'], ['B', 3, '–'], ['C', 5, 'A'], ['D', 2, 'A, B'], ['E', 6, 'C'], ['F', 4, 'D'], ['G', 3, 'E, F']] } }),
  ext(NW, 'advanced',
    'Four tradespeople, Ada, Ben, Cai and Dee, are each to be given one job on a building site: painting, tiling, wiring or plumbing. The table below shows the time, in hours, each person would take for each job.',
    [
      ['a', 'The Hungarian algorithm begins by subtracting the smallest element in each row from every element in that row. Write down the new row for Ada.', 1, '0, 3, 1, 2', 'Ada’s smallest time is 6 hours.'],
      ['b', 'Find the allocation of jobs that minimises the total time.', 2, 'Ada painting, Ben plumbing, Cai wiring, Dee tiling', 'Completing the Hungarian algorithm gives a unique optimal allocation. One mark for any two correct, two marks for all four.'],
      ['c', 'Find the minimum total time.', 1, '23 hours', '6 + 6 + 5 + 6 = 23.'],
    ],
    { diagram: { kind: 'data_table', title: 'Time for each job (hours)', columns: ['Person', 'Painting', 'Tiling', 'Wiring', 'Plumbing'], rowHeader: true, rows: [['Ada', 6, 9, 7, 8], ['Ben', 8, 7, 9, 6], ['Cai', 7, 8, 5, 9], ['Dee', 9, 6, 8, 7]] } }),
]
