// VCE General Mathematics Unit 3 & 4 — Practice set 5.
// Examination 1: 40 multiple choice (16 / 8 / 8 / 8). Examination 2: 60 marks (24 / 12 / 12 / 12).
const DA = 'gm_data_analysis', RF = 'gm_financial', MX = 'gm_matrices', NW = 'gm_networks'
const S = 5
const code = { [DA]: 'VCE-GM-U34-AOS1', [RF]: 'VCE-GM-U34-AOS2', [MX]: 'VCE-GM-U34-AOS3', [NW]: 'VCE-GM-U34-AOS4' }
const mc = (t, d, q, o, e, extra = {}) => ({ t, s: S, d, calc: true, q, o, e, code: code[t], ...extra })
const ext = (t, d, q, p, extra = {}) => ({ t, s: S, d, calc: true, q, p, code: code[t], ...extra })

const yieldTable = {
  kind: 'data_table',
  title: 'Rainfall and wheat yield',
  columns: ['Growing-season rainfall (mm)', '250', '300', '340', '380', '420', '470', '510', '560'],
  rowHeader: true,
  rows: [['Yield (tonnes per hectare)', 1.6, 2.0, 2.3, 2.5, 2.9, 3.2, 3.4, 3.9]],
}

const routeNetwork = {
  kind: 'network_graph',
  title: 'Cycle paths (distances in km)',
  vertices: [
    { id: 'S', x: 5, y: 50 }, { id: 'A', x: 28, y: 86 }, { id: 'B', x: 28, y: 14 }, { id: 'C', x: 56, y: 66 },
    { id: 'D', x: 56, y: 20 }, { id: 'E', x: 80, y: 86 }, { id: 'T', x: 95, y: 40 },
  ],
  edges: [
    { from: 'S', to: 'A', weight: 4 }, { from: 'S', to: 'B', weight: 6 }, { from: 'A', to: 'B', weight: 3 },
    { from: 'A', to: 'C', weight: 7 }, { from: 'B', to: 'C', weight: 5 }, { from: 'B', to: 'D', weight: 8 },
    { from: 'C', to: 'D', weight: 2 }, { from: 'C', to: 'E', weight: 6 }, { from: 'D', to: 'E', weight: 4 },
    { from: 'D', to: 'T', weight: 7 }, { from: 'E', to: 'T', weight: 3 },
  ],
}

const gardenTable = {
  kind: 'data_table',
  title: 'Activities for landscaping a garden',
  columns: ['Activity', 'Duration (days)', 'Immediate predecessor(s)'],
  rowHeader: true,
  rows: [['A', 5, '–'], ['B', 3, '–'], ['C', 4, 'A'], ['D', 6, 'B'], ['E', 2, 'C, D'], ['F', 3, 'C'], ['G', 4, 'E, F']],
}

const ferryMatrix = { kind: 'matrix', name: 'T =', rows: [[0.9, 0.3], [0.1, 0.7]], colLabels: ['A', 'B'], rowLabels: ['A', 'B'] }

export const ITEMS = [
  // ════════════════ Examination 1 — Data analysis (16) ════════════════
  mc(DA, 'developing',
    'A hospital records each patient’s blood type (A, B, AB or O) and the number of nights they stay in hospital. These two variables are, respectively,',
    ['categorical nominal and numerical discrete', 'categorical ordinal and numerical discrete', 'categorical nominal and numerical continuous', 'numerical discrete and numerical continuous', 'categorical ordinal and categorical nominal'],
    'Blood types are labels with no natural order, so blood type is nominal. Nights are counted, so the number of nights is numerical discrete.'),
  mc(DA, 'developing',
    'The histogram below shows the ages of the 40 people in a yoga class. The percentage of the class aged 40 years or older is',
    ['55%', '22%', '35%', '45%', '57.5%'],
    '14 + 5 + 3 = 22 people are in the classes from 40 upwards, and 22 ÷ 40 = 55%.',
    { diagram: { kind: 'bar_chart', title: 'Ages of yoga class members', bars: [{ label: '20–<30', value: 6 }, { label: '30–<40', value: 12 }, { label: '40–<50', value: 14 }, { label: '50–<60', value: 5 }, { label: '60–<70', value: 3 }], yMax: 16, yStep: 2, yLabel: 'frequency', xLabel: 'age (years)' } }),
  mc(DA, 'proficient',
    'The box plot below shows the times, in minutes, that customers spent in a hardware store. Which one of the following statements is true?',
    ['The interquartile range is 8 minutes and the value of 45 minutes lies beyond the upper fence of 38 minutes.', 'The range is 22 minutes.', 'The median is 26 minutes.', 'About 25% of customers spent between 12 and 22 minutes in the store.', 'The distribution is negatively skewed.'],
    'IQR = 26 − 18 = 8, so the upper fence is 26 + 1.5 × 8 = 38, and 45 is an outlier. The range is 45 − 12 = 33, the median is 22, and about 50% of customers lie between the minimum and the median.',
    { diagram: { kind: 'box_plot', title: 'Time spent in store', axisLabel: 'time (minutes)', min: 10, max: 50, step: 5, boxes: [{ min: 12, q1: 18, median: 22, q3: 26, max: 34, outliers: [45] }] } }),
  mc(DA, 'developing',
    'The lengths of 1200 fish in a pond are approximately normally distributed with a mean of 30 cm and a standard deviation of 4 cm. Using the 68–95–99.7% rule, the number of fish expected to be longer than 38 cm is',
    ['30', '3', '18', '60', '192'],
    '38 cm is two standard deviations above the mean, and 2.5% of values lie above that: 0.025 × 1200 = 30.'),
  mc(DA, 'proficient',
    'Scores on an aptitude test are approximately normally distributed with a mean of 70 and a standard deviation of 6. Using the 68–95–99.7% rule, the score at the 84th percentile is',
    ['76', '64', '75', '82', '84'],
    '50% of scores lie below the mean and 34% lie between the mean and one standard deviation above it, so the 84th percentile is 70 + 6 = 76.'),
  mc(DA, 'proficient',
    'The two-way frequency table below shows the smoking status of 250 adults by gender. Of the non-smokers, the percentage who are female, correct to one decimal place, is',
    ['51.2%', '44.0%', '48.8%', '86.0%', '88.0%'],
    'There are 105 + 110 = 215 non-smokers, of whom 110 are female: 110 ÷ 215 = 51.2%. 88.0% is the percentage of females who are non-smokers, which answers a different question.',
    { diagram: { kind: 'data_table', title: 'Smoking status by gender', columns: ['', 'Male', 'Female', 'Total'], rowHeader: true, rows: [['Smoker', 20, 15, 35], ['Non-smoker', 105, 110, 215], ['Total', 125, 125, 250]] } }),
  mc(DA, 'developing',
    'The scatterplot below shows, for ten apartment blocks, the age of the block in years and the monthly strata fee in hundreds of dollars. The correlation coefficient is r = −0.60. The association is best described as',
    ['moderate, negative and linear', 'strong, negative and linear', 'weak, negative and linear', 'moderate, positive and linear', 'strong, negative and non-linear'],
    'r between −0.5 and −0.75 is conventionally described as moderate. The points drift downward in a roughly straight band, so the association is negative and linear.',
    { diagram: { kind: 'function_graph', title: 'Strata fee against age of block', xMin: 0, xMax: 12, yMin: 10, yMax: 35, xStep: 2, yStep: 5, xLabel: 'age (years)', yLabel: 'fee ($00)', curves: [], points: [{ x: 2, y: 30 }, { x: 3, y: 25 }, { x: 4, y: 31 }, { x: 5, y: 22 }, { x: 6, y: 27 }, { x: 7, y: 29 }, { x: 8, y: 20 }, { x: 9, y: 26 }, { x: 10, y: 17 }, { x: 11, y: 23 }] } }),
  mc(DA, 'developing',
    'For a set of bivariate data, the correlation coefficient is r = 0.8. The percentage of the variation in the response variable that is not explained by the variation in the explanatory variable is',
    ['36%', '10.6%', '20%', '64%', '80%'],
    'r² = 0.64, so 64% of the variation is explained and 100% − 64% = 36% is not.'),
  mc(DA, 'developing',
    'The least squares line time = 12.4 + 1.8 × distance is used to predict delivery time, in minutes, from distance, in kilometres. A delivery of 15 km took 36 minutes. The residual for this delivery, in minutes, is',
    ['−3.4', '−2.6', '3.4', '36', '39.4'],
    'Predicted time = 12.4 + 1.8 × 15 = 39.4. Residual = actual − predicted = 36 − 39.4 = −3.4.'),
  mc(DA, 'proficient',
    'A log transformation is applied to the response variable, and the least squares line log₁₀(y) = 0.5 + 0.3x is fitted. The value of y predicted when x = 5 is',
    ['100', '2', '3.16', '20', '1000'],
    'log₁₀(y) = 0.5 + 0.3 × 5 = 2, so y = 10² = 100. Stopping at 2 forgets to reverse the transformation.'),
  mc(DA, 'developing',
    'A least squares line is fitted to the heights of children aged 2 to 10 years. Using the line to predict the height of a 30-year-old is unreliable because',
    ['it is an extrapolation beyond the ages in the data', 'the correlation between age and height is negative', 'height is a categorical variable', 'the residuals must all be zero', 'it is an interpolation within the ages in the data'],
    'Age 30 lies well outside the range 2 to 10, and children’s growth does not continue linearly into adulthood.'),
  mc(DA, 'proficient',
    'When a four-point moving average is used to smooth a time series, the result is centred because',
    ['otherwise the average would sit between two time periods', 'otherwise the average would be too large', 'centring removes the seasonal component', 'centring is needed only when the data contain outliers', 'an odd number of points must never be used'],
    'The mean of four consecutive points belongs halfway between the 2nd and 3rd points. Averaging two consecutive four-point means realigns the result with an actual time period.'),
  mc(DA, 'developing',
    'A business calculates monthly seasonal indices. The indices for eleven of the months sum to 11.12. The seasonal index for the remaining month is',
    ['0.88', '0.12', '1.00', '1.12', '11.12'],
    'Monthly seasonal indices sum to 12, so the remaining index is 12 − 11.12 = 0.88.'),
  mc(DA, 'developing',
    'The time series plot below shows the monthly number of complaints received by a council over 14 months. The most noticeable feature of the plot is',
    ['a structural change', 'seasonality', 'an increasing trend', 'an outlier', 'cycles with a period of about three months'],
    'The level of the series drops suddenly between months 7 and 8 and stays at the new, lower level, which is a structural change.',
    { diagram: { kind: 'line_graph', title: 'Monthly complaints', xLabels: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14'], series: [{ values: [52, 49, 54, 51, 53, 50, 52, 33, 30, 34, 31, 32, 29, 33] }], yMin: 20, yMax: 60, yStep: 10, xLabel: 'month', yLabel: 'complaints' } }),
  mc(DA, 'proficient',
    'Wheat yield is to be predicted from growing-season rainfall using the data in the table below. Using a CAS, the equation of the least squares line, with coefficients correct to four significant figures, is',
    ['yield = −0.1752 + 0.007183 × rainfall', 'yield = 0.007183 − 0.1752 × rainfall', 'yield = −0.1752 + 0.07183 × rainfall', 'rainfall = 26.12 + 138.6 × yield', 'yield = 2.725 + 0.007183 × rainfall'],
    'With rainfall as x and yield as y: slope 0.0071831 and intercept −0.17519. The option with rainfall as the response predicts the wrong variable.',
    { diagram: yieldTable }),
  mc(DA, 'proficient',
    'For the data in the table below, the correlation coefficient between rainfall and wheat yield, correct to three decimal places, is',
    ['0.998', '0.995', '0.007', '0.958', '−0.998'],
    'Using a CAS, r = 0.9977. The coefficient of determination is 0.995, which is r², not r.',
    { diagram: yieldTable }),

  // ════════════════ Examination 1 — Recursion and financial modelling (8) ════════════════
  mc(RF, 'developing',
    'An amount of $4000 is invested at 3.5% per annum simple interest. A recurrence relation for the value Vₙ of the investment after n years is',
    ['V₀ = 4000, Vₙ₊₁ = Vₙ + 140', 'V₀ = 4000, Vₙ₊₁ = 1.035Vₙ', 'V₀ = 4000, Vₙ₊₁ = Vₙ + 3.5', 'V₀ = 4000, Vₙ₊₁ = 1.035Vₙ + 140', 'V₀ = 4000, Vₙ₊₁ = 0.035Vₙ'],
    'Simple interest adds the same amount each year: 3.5% of 4000 = $140. Multiplying by 1.035 would model compound interest.'),
  mc(RF, 'developing',
    'The value of a machine is modelled by V₀ = 20 000, Vₙ₊₁ = 0.85Vₙ, where n is the number of years. The value first falls below half of its purchase price after',
    ['5 years', '3 years', '4 years', '6 years', '7 years'],
    '0.85⁴ = 0.522 and 0.85⁵ = 0.444, so the value first drops below $10 000 after 5 years.'),
  mc(RF, 'advanced',
    'Which one of the following investments has the highest effective annual interest rate?',
    ['4.95% per annum, compounding quarterly', '5.00% per annum, compounding annually', '4.90% per annum, compounding monthly', '4.85% per annum, compounding daily', '4.80% per annum, compounding weekly'],
    'Effective rates: quarterly 4.95% gives 5.043%; annual 5.00% gives 5.000%; monthly 4.90% gives 5.012%; daily 4.85% gives 4.969%; weekly 4.80% gives 4.914%.'),
  mc(RF, 'proficient',
    'A loan of $25 000 is charged interest at 7.8% per annum, compounding monthly, and is repaid at $600 per month. The number of monthly repayments needed to repay the loan in full is',
    ['49', '41', '42', '48', '50'],
    'Financial solver: I% = 7.8, PV = 25 000, PMT = −600, FV = 0 gives N = 48.75, so 48 full repayments and a smaller 49th are needed. 25 000 ÷ 600 = 41.7 ignores interest.'),
  mc(RF, 'proficient',
    'A loan of $60 000 is charged interest at 6.6% per annum, compounding monthly, and is repaid at $1200 per month. The balance of the loan after two years, correct to the nearest cent, is',
    ['$37 744.50', '$31 200.00', '$36 950.28', '$39 022.63', '$42 136.40'],
    'Financial solver: N = 24, I% = 6.6, PV = 60 000, PMT = −1200 gives FV = −37 744.50. $31 200 ignores interest.'),
  mc(RF, 'proficient',
    'An annuity of $300 000 earns interest at 5.4% per annum, compounding monthly, and pays $2500 at the end of every month. The balance of the annuity after five years, correct to the nearest cent, is',
    ['$220 989.57', '$150 000.00', '$215 472.18', '$238 110.42', '$390 979.14'],
    'Financial solver: N = 60, I% = 5.4, PV = −300 000, PMT = 2500 gives FV = 220 989.57. $150 000 ignores interest.'),
  mc(RF, 'proficient',
    'The recurrence relation V₀ = 350 000, Vₙ₊₁ = 1.004Vₙ − 1400 models the balance of an account after n months. This account is',
    ['a perpetuity', 'a reducing balance loan that will be repaid in 250 months', 'an investment whose balance increases each month', 'depreciating by the flat rate method', 'an annuity that will run out in 350 months'],
    'Each month the interest is 0.004 × 350 000 = $1400, exactly the amount paid out, so the balance never changes: a perpetuity.'),
  mc(RF, 'developing',
    'The price of a coffee is $4.50 and increases by 3% each year. The price after 10 years, correct to the nearest cent, is',
    ['$6.05', '$5.85', '$5.87', '$4.64', '$13.50'],
    '4.50 × 1.03¹⁰ = 6.05. Adding 3% of $4.50 each year gives $5.85, which treats the increase as linear.'),

  // ════════════════ Examination 1 — Matrices (8) ════════════════
  mc(MX, 'developing',
    'A matrix has 12 elements. Its order cannot be',
    ['5 × 2', '2 × 6', '3 × 4', '4 × 3', '12 × 1'],
    'A matrix of order m × n has mn elements, and 5 × 2 = 10.'),
  mc(MX, 'proficient',
    'Matrix A is shown below, and B is the column matrix with elements 4 (top) and 9 (bottom). The solution of the matrix equation AX = B, where X is the column matrix with elements x (top) and y (bottom), is',
    ['x = 0.5, y = 3', 'x = 2, y = 3', 'x = 0.5, y = 9', 'x = 3, y = 0.5', 'x = 2, y = 1.5'],
    'The second row gives 3y = 9, so y = 3. The first row gives 2x + y = 4, so x = 0.5.',
    { diagram: { kind: 'matrix', name: 'A =', rows: [[2, 1], [0, 3]] } }),
  mc(MX, 'proficient',
    'The determinant of matrix M below is',
    ['13', '−11', '1', '7', '11'],
    'Expanding along the first row: 1 × (1 × 1 − 3 × 0) − 2 × (0 × 1 − 3 × 2) + 0 = 1 + 12 = 13.',
    { diagram: { kind: 'matrix', name: 'M =', rows: [[1, 2, 0], [0, 1, 3], [2, 0, 1]] } }),
  mc(MX, 'advanced',
    'Four teams play a round robin. In the dominance matrix D below, a 1 in row i and column j means team i defeated team j. Ranking the teams by the sum of their one-step and two-step dominances gives, from first to last,',
    ['A, B, D, C', 'A, B, C, D', 'B, A, D, C', 'A, D, B, C', 'D, A, B, C'],
    'One-step totals: A 2, B 2, C 1, D 1. Two-step totals (row sums of D²): A 3, B 2, C 1, D 2. Sums: A 5, B 4, D 3, C 2.',
    { diagram: { kind: 'matrix', name: 'D =', rows: [[0, 1, 1, 0], [0, 0, 1, 1], [0, 0, 0, 1], [1, 0, 0, 0]], rowLabels: ['A', 'B', 'C', 'D'], colLabels: ['A', 'B', 'C', 'D'] } }),
  mc(MX, 'proficient',
    'Each week, 1000 commuters choose between two ferries, A and B, according to the transition matrix T below (columns: this week, rows: next week). This week 600 commuters use ferry A and 400 use ferry B. The number using ferry A in two weeks’ time is',
    ['696', '600', '640', '660', '680'],
    'Next week: A = 0.9 × 600 + 0.3 × 400 = 660 and B = 340. The week after: A = 0.9 × 660 + 0.3 × 340 = 594 + 102 = 696.',
    { diagram: ferryMatrix }),
  mc(MX, 'proficient',
    'Using the transition matrix T below for the 1000 commuters, the number using ferry A in the long run is',
    ['750', '600', '696', '700', '900'],
    'At steady state, the 10% of A users moving to B balances the 30% of B users moving to A: 0.1A = 0.3B with A + B = 1000, so A = 750.',
    { diagram: ferryMatrix }),
  mc(MX, 'advanced',
    'Two colonies of birds, A and B, are modelled by Sₙ₊₁ = TSₙ + R, where T has first row 0.8, 0.1 and second row 0.2, 0.9, and R has elements −20 (top) and 30 (bottom). Initially each colony has 500 birds. After one year, the numbers in colonies A and B are',
    ['430 and 580', '450 and 550', '470 and 520', '430 and 520', '410 and 610'],
    'A: 0.8 × 500 + 0.1 × 500 − 20 = 430. B: 0.2 × 500 + 0.9 × 500 + 30 = 580. Leaving out R gives 450 and 550.'),
  mc(MX, 'developing',
    'The elements of matrix A are given by aᵢⱼ = i × j. The element a₃₂ is',
    ['6', '5', '3', '2', '9'],
    'a₃₂ is in row 3 and column 2: 3 × 2 = 6.'),

  // ════════════════ Examination 1 — Networks and decision mathematics (8) ════════════════
  mc(NW, 'developing',
    'A connected graph has 6 vertices and 6 edges. Which one of the following statements must be true?',
    ['The graph contains at least one cycle.', 'The graph is a tree.', 'The graph has an Eulerian circuit.', 'The graph has a vertex of degree 1.', 'The graph is a complete graph.'],
    'A connected graph with 6 vertices and no cycles is a tree with 5 edges. With 6 edges, at least one cycle must exist.'),
  mc(NW, 'proficient',
    'The adjacency matrix below represents a graph with vertices A, B, C and D. The degree of vertex C is',
    ['6', '3', '4', '5', '7'],
    'Row C shows one edge to A, two edges to B, a loop at C and one edge to D. A loop adds 2 to the degree: 1 + 2 + 2 + 1 = 6.',
    { diagram: { kind: 'matrix', rows: [[0, 1, 1, 0], [1, 0, 2, 0], [1, 2, 1, 1], [0, 0, 1, 0]], rowLabels: ['A', 'B', 'C', 'D'], colLabels: ['A', 'B', 'C', 'D'] } }),
  mc(NW, 'developing',
    'The weighted graph below shows cycle paths between locations, with distances in kilometres. The length of the shortest path from S to T, in kilometres, is',
    ['20', '15', '17', '18', '19'],
    'Dijkstra’s algorithm: A 4, B 6, C 11, D 13, E 17, T 20. Three different routes, such as S–A–C–D–T, all have length 20.',
    { diagram: routeNetwork }),
  mc(NW, 'proficient',
    'For the weighted graph of cycle paths below, the total length of the minimum spanning tree, in kilometres, is',
    ['21', '24', '25', '26', '28'],
    'Kruskal’s algorithm: CD 2, AB 3, ET 3, SA 4, DE 4, BC 5. Total 2 + 3 + 3 + 4 + 4 + 5 = 21 km.',
    { diagram: routeNetwork }),
  mc(NW, 'advanced',
    'The directed network below shows the capacities, in litres per minute, of pipes from a source S to a sink T. The capacity of the cut that separates {S, A} from {B, T} is',
    ['16', '9', '13', '14', '18'],
    'Count only the pipes that flow from the source side to the sink side: S → B (7), A → B (3) and A → T (6), total 16. The pipe B → A flows the other way and is not counted. The maximum flow is 14, set by a different cut.',
    { diagram: { kind: 'network_graph', title: 'Pipe capacities (L/min)', directed: true, vertices: [{ id: 'S', x: 5, y: 50 }, { id: 'A', x: 45, y: 86 }, { id: 'B', x: 45, y: 14 }, { id: 'T', x: 95, y: 50 }], edges: [{ from: 'S', to: 'A', weight: 9 }, { from: 'S', to: 'B', weight: 7 }, { from: 'A', to: 'B', weight: 3 }, { from: 'B', to: 'A', weight: 2 }, { from: 'A', to: 'T', weight: 6 }, { from: 'B', to: 'T', weight: 8 }] } }),
  mc(NW, 'advanced',
    'Three teams, X, Y and Z, are each to be allocated one project. The table below shows the profit, in thousands of dollars, each team would make on each project. The maximum total profit, in thousands of dollars, is',
    ['43', '31', '42', '45', '46'],
    'Checking the six allocations (or applying the Hungarian algorithm to the profits subtracted from 16): X P3, Y P2, Z P1 gives 16 + 14 + 13 = 43. 46 would need X and Z both on P3.',
    { diagram: { kind: 'data_table', title: 'Profit ($ thousands)', columns: ['Team', 'Project 1', 'Project 2', 'Project 3'], rowHeader: true, rows: [['X', 12, 9, 16], ['Y', 10, 14, 11], ['Z', 13, 8, 16]] } }),
  mc(NW, 'proficient',
    'For the project in the table below, the latest start time for activity D, in days, is',
    ['4', '3', '5', '6', '10'],
    'The project takes 16 days along A–C–F–G. E’s latest start is 10 (G starts by 12), so D must finish by day 10 and start by 10 − 6 = 4. Its earliest start is 3.',
    { diagram: gardenTable }),
  mc(NW, 'proficient',
    'For the project in the table below, the number of activities with zero float time is',
    ['4', '3', '5', '6', '8'],
    'A, C, F and G lie on the critical path A–C–F–G. B, D and E each have one day of float.',
    { diagram: gardenTable }),

  // ════════════════ Examination 2 — Data analysis (24 marks) ════════════════
  ext(DA, 'proficient',
    'The parallel box plots below show the one-way commuting times, in minutes, of a sample of workers who drive to work and a sample who catch the train.',
    [
      ['a', 'Find the difference between the median commuting times of the two groups.', 1, '11 minutes', 'Train median 44 − drive median 33 = 11.'],
      ['b', 'Find the interquartile range for each group.', 1, 'Drive 15 minutes; train 10 minutes', 'Drive: 41 − 26 = 15. Train: 48 − 38 = 10.'],
      ['c', 'Show that the commuting time of 75 minutes for the drive group is an outlier.', 2, 'Upper fence = 41 + 1.5 × 15 = 63.5; 75 > 63.5, so it is an outlier.', 'One mark for the fence, one for the comparison.'],
      ['d', 'Compare the two distributions in terms of their centre and spread, quoting values.', 2, 'The train group has the higher median (44 v 33 minutes) but is less variable (IQR 10 v 15 minutes; range 26 v 57 minutes).', 'One mark for comparing medians, one for comparing a measure of spread.'],
    ],
    { diagram: { kind: 'box_plot', title: 'One-way commuting time', axisLabel: 'time (minutes)', min: 10, max: 80, step: 10, boxes: [{ label: 'Drive', min: 18, q1: 26, median: 33, q3: 41, max: 58, outliers: [75] }, { label: 'Train', min: 30, q1: 38, median: 44, q3: 48, max: 56 }] } }),
  ext(DA, 'proficient',
    'The table below shows the hours of training per week and the time, in minutes, to run 5 km for seven runners. Run time is to be predicted from hours of training.',
    [
      ['a', 'Find the equation of the least squares line. Write the coefficients correct to two decimal places.', 2, 'run time = 33.47 − 1.06 × training', 'Using a CAS: intercept 33.4714, slope −1.0571. One mark for each coefficient.'],
      ['b', 'Find the correlation coefficient r, correct to three decimal places.', 1, 'r = −0.997', 'A very strong negative linear association.'],
      ['c', 'Find the residual for the runner who trains for 5 hours per week, correct to two decimal places.', 1, '−0.29 minutes', 'Predicted = 33.4714 − 1.0571 × 5 = 28.19, and 27.9 − 28.19 = −0.29.'],
      ['d', 'Interpret the coefficient of determination in the context of this data.', 1, 'r² = 0.994: 99.4% of the variation in run time is explained by the variation in hours of training.', 'r² = (−0.9972)².'],
      ['e', 'Use the line to predict the run time of a runner who trains for 12 hours per week, and comment on the reliability of this prediction.', 1, 'About 20.8 minutes; unreliable, because 12 hours is an extrapolation beyond the data (2 to 8 hours).', '33.4714 − 1.0571 × 12 = 20.79.'],
    ],
    { diagram: { kind: 'data_table', title: 'Training and 5 km run time', columns: ['Training (hours per week)', '2', '3', '4', '5', '6', '7', '8'], rowHeader: true, rows: [['Run time (minutes)', 31.5, 30.2, 29.4, 27.9, 27.1, 26.0, 25.2]] } }),
  ext(DA, 'proficient',
    'The lengths of snapper caught in a bay are approximately normally distributed with a mean of 36 cm and a standard deviation of 5 cm.',
    [
      ['a', 'Using the 68–95–99.7% rule, find the percentage of snapper with a length between 26 cm and 46 cm.', 1, '95%', '26 and 46 are two standard deviations either side of the mean.'],
      ['b', 'Of 600 snapper caught, how many would be expected to be shorter than 31 cm?', 1, '96', '31 cm is one standard deviation below the mean, and 16% of values lie below it: 0.16 × 600 = 96.'],
      ['c', 'The legal minimum length is 31 cm. Find the standardised score of a snapper of this length.', 1, 'z = −1', '(31 − 36) ÷ 5 = −1.'],
      ['d', 'A snapper has a standardised score of 2.4. Find its length.', 1, '48 cm', '36 + 2.4 × 5 = 48.'],
      ['e', 'Flathead in the same bay have lengths that are approximately normally distributed with a mean of 45 cm and a standard deviation of 4 cm. A snapper of 44 cm and a flathead of 52 cm are caught. Which fish is longer relative to its own species? Justify your answer.', 2, 'The flathead: z = 1.75 compared with z = 1.6 for the snapper.', 'Snapper: (44 − 36) ÷ 5 = 1.6. Flathead: (52 − 45) ÷ 4 = 1.75. One mark for both z-scores, one for the conclusion.'],
    ]),
  ext(DA, 'advanced',
    'The table below shows a household’s quarterly electricity bills, in dollars, over two years.',
    [
      ['a', 'Describe the main feature of this time series.', 1, 'Seasonality: bills are highest in Quarter 3 (winter) and lowest in Quarter 2 each year.', 'A slight increase from Year 1 to Year 2 is also acceptable as a second feature.'],
      ['b', 'Show that the seasonal index for Quarter 3, correct to two decimal places, is 1.31.', 2, '(520 ÷ 400 + 560 ÷ 425) ÷ 2 = (1.3 + 1.3176) ÷ 2 = 1.31', 'The yearly means are (420 + 310 + 520 + 350) ÷ 4 = 400 and (440 + 330 + 560 + 370) ÷ 4 = 425. One mark for the yearly means, one for averaging the ratios.'],
      ['c', 'The seasonal index for Quarter 2 is 0.78. Deseasonalise the Year 2, Quarter 2 bill, correct to the nearest dollar.', 1, '$423', '330 ÷ 0.78 = 423.08.'],
      ['d', 'A least squares line fitted to the deseasonalised bills is deseasonalised bill = 395 + 4.2t, where t = 1 is Quarter 1 of Year 1. Forecast the actual bill for Quarter 3 of Year 3, correct to the nearest dollar.', 2, '$578', 'Quarter 3 of Year 3 is t = 11. Deseasonalised forecast = 395 + 4.2 × 11 = 441.2. Actual = 441.2 × 1.31 = 577.97. One mark for the trend value, one for reseasonalising.'],
    ],
    { diagram: { kind: 'data_table', title: 'Quarterly electricity bills ($)', columns: ['', 'Quarter 1', 'Quarter 2', 'Quarter 3', 'Quarter 4'], rowHeader: true, rows: [['Year 1', 420, 310, 520, 350], ['Year 2', 440, 330, 560, 370]] } }),

  // ════════════════ Examination 2 — Recursion and financial modelling (12 marks) ════════════════
  ext(RF, 'proficient',
    'A boat bought for $45 000 is depreciated by the reducing balance method. After one year its value is $38 250.',
    [
      ['a', 'Find the annual rate of depreciation.', 1, '15%', '38 250 ÷ 45 000 = 0.85, so the value falls by 15% each year.'],
      ['b', 'Write down a recurrence relation for the value Vₙ, in dollars, of the boat after n years.', 1, 'V₀ = 45 000, Vₙ₊₁ = 0.85Vₙ', 'Each year the value is 85% of the previous value.'],
      ['c', 'Find the value of the boat after five years, correct to the nearest dollar.', 1, '$19 967', '45 000 × 0.85⁵ = 19 966.74.'],
      ['d', 'After how many years will the value of the boat first be less than $15 000?', 1, '7 years', 'After 6 years: $16 971.73. After 7 years: $14 425.97.'],
    ]),
  ext(RF, 'advanced',
    'Tom borrows $32 000 to buy a car. Interest is charged at 7.2% per annum, compounding monthly, and Tom repays $750 at the end of each month.',
    [
      ['a', 'Find the balance of the loan after one year, correct to the nearest cent.', 1, '$25 078.55', 'Financial solver: N = 12, I% = 7.2, PV = 32 000, PMT = −750 gives FV = −25 078.55.'],
      ['b', 'Find the number of monthly repayments needed to repay the loan.', 1, '50', 'Solving for N with FV = 0 gives 49.43: 49 full repayments and a smaller 50th.'],
      ['c', 'Find the amount of the final repayment, correct to the nearest cent.', 1, '$325.61', 'After 49 repayments the balance is $323.67. With one more month of interest at 0.6%: 323.67 × 1.006 = 325.61.'],
      ['d', 'Find the total interest paid over the life of the loan, correct to the nearest cent.', 1, '$5075.61', '49 × 750 + 325.61 − 32 000 = 5075.61.'],
    ]),
  ext(RF, 'advanced',
    'A school invests $150 000 in an account paying 4.5% per annum, compounding monthly, to fund a monthly scholarship payment.',
    [
      ['a', 'Find the monthly payment if the investment is to act as a perpetuity.', 1, '$562.50', 'The monthly interest is 0.00375 × 150 000 = 562.50.'],
      ['b', 'Instead, the school pays $1000 at the end of each month. Find the number of full payments that can be made before the fund runs out.', 1, '220', 'Solving for N with PV = −150 000, PMT = 1000 and FV = 0 gives 220.86.'],
      ['c', 'With payments of $1000 per month, find the balance of the fund after ten years, correct to the nearest cent.', 1, '$83 850.84', 'N = 120 gives FV = 83 850.84.'],
      ['d', 'Find the amount that would need to be invested at the same rate for the fund to pay $1000 per month as a perpetuity, correct to the nearest cent.', 1, '$266 666.67', '1000 ÷ 0.00375 = 266 666.67.'],
    ]),

  // ════════════════ Examination 2 — Matrices (12 marks) ════════════════
  ext(MX, 'advanced',
    'A library has 4000 books. Each week a book is on the shelf (S), on loan (L) or lost (X). The transition matrix T below shows how the status of the books changes from one week (columns) to the next (rows). At the start, all 4000 books are on the shelf.',
    [
      ['a', 'Explain the meaning of the element 0.05 in matrix T.', 1, 'Each week, 5% of the books on loan are lost.', 'Column L is this week; row X is next week.'],
      ['b', 'Find the number of books in each state after one week.', 1, 'S 2800, L 1200, X 0', '0.7 × 4000 = 2800 and 0.3 × 4000 = 1200.'],
      ['c', 'Find the number of books lost after three weeks.', 1, '123', 'After two weeks: S 2680, L 1260, X 60. After three weeks: X = 60 + 0.05 × 1260 = 123.'],
      ['d', 'Describe what this model predicts for the books in the long run, and explain why.', 1, 'Eventually all the books will be lost, because a lost book stays lost (the element in row X, column X is 1) while books keep moving into X.', 'X is an absorbing state.'],
    ],
    { diagram: { kind: 'matrix', name: 'T =', rows: [[0.7, 0.6, 0], [0.3, 0.35, 0], [0, 0.05, 1]], colLabels: ['S', 'L', 'X'], rowLabels: ['S', 'L', 'X'] } }),
  ext(MX, 'proficient',
    'Matrix Q below shows the numbers of adult, child and concession tickets sold at three cinemas on one night. The prices are $18 for an adult, $12 for a child and $14 for a concession, recorded in the column matrix P with elements 18, 12 and 14.',
    [
      ['a', 'State the order of the matrix product QP.', 1, '3 × 1', 'Q is 3 × 3 and P is 3 × 1.'],
      ['b', 'Find QP.', 1, 'The column matrix with elements 3680, 4120 and 3360', 'Cinema 1: 120 × 18 + 80 × 12 + 40 × 14 = 3680. Cinema 2: 4120. Cinema 3: 3360.'],
      ['c', 'Which cinema had the highest ticket revenue that night?', 1, 'Cinema 2', '$4120 is the largest element of QP.'],
      ['d', 'All prices increase by 5%. Find the total revenue from the same ticket sales at the new prices.', 1, '$11 718', '1.05 × (3680 + 4120 + 3360) = 1.05 × 11 160.'],
    ],
    { diagram: { kind: 'matrix', name: 'Q =', rows: [[120, 80, 40], [150, 60, 50], [90, 110, 30]], rowLabels: ['Cinema 1', 'Cinema 2', 'Cinema 3'], colLabels: ['Adult', 'Child', 'Concession'] } }),
  ext(MX, 'advanced',
    'A simple code turns each pair of letters into numbers (A = 1, B = 2, …, Z = 26), writes them as a column matrix M, and sends the encoded matrix EM, where E has first row 2, 1 and second row 1, 1.',
    [
      ['a', 'Find the determinant of E and the inverse matrix E⁻¹.', 1, 'det(E) = 1; E⁻¹ has first row 1, −1 and second row −1, 2', 'det(E) = 2 × 1 − 1 × 1 = 1.'],
      ['b', 'Encode the letters H and I (8 and 9).', 1, 'The column matrix with elements 25 and 17', '2 × 8 + 9 = 25 and 8 + 9 = 17.'],
      ['c', 'The encoded message received is the column matrix with elements 29 and 22. Decode it.', 1, 'GO', 'E⁻¹ times the message gives 29 − 22 = 7 and −29 + 44 = 15, which are G and O.'],
      ['d', 'Explain why the matrix with first row 2, 4 and second row 1, 2 could not be used as the encoding matrix.', 1, 'Its determinant is 2 × 2 − 4 × 1 = 0, so it has no inverse and messages could not be decoded.', 'Decoding requires the inverse matrix.'],
    ]),

  // ════════════════ Examination 2 — Networks and decision mathematics (12 marks) ════════════════
  ext(NW, 'advanced',
    'The directed network below shows the capacities, in kilolitres per hour, of the pipes carrying water from a reservoir S to a town T.',
    [
      ['a', 'Find the capacity of the cut that separates {S, A} from {B, C, D, T}.', 1, '23 kL/h', 'S → B (10), A → B (5) and A → C (8).'],
      ['b', 'Find the maximum flow from S to T.', 1, '19 kL/h', 'The minimum cut crosses C → T (10) and D → T (9).'],
      ['c', 'Explain how you know that the flow in part b cannot be exceeded.', 1, 'Every unit of water must pass through C → T or D → T, whose total capacity is 19.', 'This cut has the smallest capacity of all cuts.'],
      ['d', 'The pipe from C to T is upgraded to a capacity of 14 kL/h. Find the new maximum flow.', 1, '20 kL/h', 'Water into C is now limited to A → C (8) plus D → C (4), and D can pass on at most the 12 it receives from B. The new minimum cut, {S, A, B} against the rest, has capacity 8 + 12 = 20.'],
    ],
    { diagram: { kind: 'network_graph', title: 'Pipe capacities (kL/h)', directed: true, vertices: [{ id: 'S', x: 5, y: 50 }, { id: 'A', x: 32, y: 86 }, { id: 'B', x: 32, y: 14 }, { id: 'C', x: 66, y: 80 }, { id: 'D', x: 66, y: 20 }, { id: 'T', x: 95, y: 50 }], edges: [{ from: 'S', to: 'A', weight: 15 }, { from: 'S', to: 'B', weight: 10 }, { from: 'A', to: 'B', weight: 5 }, { from: 'A', to: 'C', weight: 8 }, { from: 'B', to: 'D', weight: 12 }, { from: 'C', to: 'T', weight: 10 }, { from: 'D', to: 'C', weight: 4 }, { from: 'D', to: 'T', weight: 9 }] } }),
  ext(NW, 'proficient',
    'The weighted graph below shows the roads, with lengths in kilometres, between six farms, A to F.',
    [
      ['a', 'Using Prim’s algorithm starting at A, write down the order in which the edges of the minimum spanning tree are chosen.', 1, 'AC, BC, BD, DE, DF', 'From A the shortest edge is AC (5); then BC (4), BD (6), DE (3) and DF (5).'],
      ['b', 'Find the total length of the minimum spanning tree.', 1, '23 km', '5 + 4 + 6 + 3 + 5 = 23.'],
      ['c', 'Find the length of the shortest path from A to F.', 1, '18 km', 'A–C–E–F: 5 + 7 + 6 = 18. The routes through D are 19 km or more.'],
      ['d', 'A new road of length 9 km is built directly between C and F. Find the new length of the shortest path from A to F.', 1, '14 km', 'A–C–F: 5 + 9 = 14.'],
    ],
    { diagram: { kind: 'network_graph', title: 'Roads between farms (km)', vertices: [{ id: 'A', x: 5, y: 50 }, { id: 'B', x: 35, y: 86 }, { id: 'C', x: 35, y: 14 }, { id: 'D', x: 66, y: 86 }, { id: 'E', x: 66, y: 14 }, { id: 'F', x: 95, y: 50 }], edges: [{ from: 'A', to: 'B', weight: 8 }, { from: 'A', to: 'C', weight: 5 }, { from: 'B', to: 'C', weight: 4 }, { from: 'B', to: 'D', weight: 6 }, { from: 'C', to: 'D', weight: 9 }, { from: 'C', to: 'E', weight: 7 }, { from: 'D', to: 'E', weight: 3 }, { from: 'D', to: 'F', weight: 5 }, { from: 'E', to: 'F', weight: 6 }] } }),
  ext(NW, 'advanced',
    'The table below shows the activities needed to launch a website, their durations in days and their immediate predecessors.',
    [
      ['a', 'Find the earliest start time for activity E.', 1, 'Day 7', 'E needs B (finishes on day 5) and C (finishes on day 3 + 4 = 7).'],
      ['b', 'Find the minimum time to complete the project, and write down the critical path.', 1, '16 days; A–C–E–G', '3 + 4 + 6 + 3 = 16.'],
      ['c', 'Find the float time for activity D.', 1, '3 days', 'F’s latest start is 13 − 5 = 8, so D must finish by day 8 and start by day 6. Its earliest start is 3.'],
      ['d', 'Activity C can be reduced by up to 2 days at $250 per day, and activity E by up to 3 days at $400 per day. Find the minimum cost of completing the project in 13 days.', 1, '$900', 'Reduce C by 2 days ($500) and E by 1 day ($400). Then A–C–E–G, B–E–G and A–D–F–G all take 13 days. Reducing E alone by 3 days would cost $1200.'],
    ],
    { diagram: { kind: 'data_table', title: 'Launching a website', columns: ['Activity', 'Duration (days)', 'Immediate predecessor(s)'], rowHeader: true, rows: [['A', 3, '–'], ['B', 5, '–'], ['C', 4, 'A'], ['D', 2, 'A'], ['E', 6, 'B, C'], ['F', 5, 'D'], ['G', 3, 'E, F']] } }),
]
