// VCE Mathematical Methods Unit 3 & 4 — Practice set 5.
// Examination 1: 9 technology-free questions, 40 marks.
// Examination 2: Section A 20 multiple choice; Section B 4 extended questions, 60 marks.
const FN = 'mm_functions', AL = 'mm_algebra', CA = 'mm_calculus', PR = 'mm_probability'
const S = 5
const code = { [FN]: 'VCE-MM-U34-AOS1', [AL]: 'VCE-MM-U34-AOS2', [CA]: 'VCE-MM-U34-AOS3', [PR]: 'VCE-MM-U34-AOS4' }
const ex1 = (t, d, q, p, extra = {}) => ({ t, s: S, d, calc: false, q, p, code: code[t], ...extra })
const mc = (t, d, q, o, e, extra = {}) => ({ t, s: S, d, calc: true, q, o, e, code: code[t], ...extra })
const ex2 = (t, d, q, p, extra = {}) => ({ t, s: S, d, calc: true, q, p, code: code[t], ...extra })

const sample = (f, a, b, n) => Array.from({ length: n + 1 }, (_, i) => {
  const x = a + ((b - a) * i) / n
  return [Math.round(x * 1000) / 1000, Math.round(f(x) * 1000) / 1000]
})

export const ITEMS = [
  // ════════════════ Examination 1 — technology-free (40 marks) ════════════════
  ex1(CA, 'developing', 'Let f: R → R, f(x) = x/(x² + 1).', [
    ['a', 'Use the quotient rule to show that f′(x) = (1 − x²)/(x² + 1)².', 2, 'f′(x) = ((x² + 1) − x × 2x)/(x² + 1)² = (1 − x²)/(x² + 1)²', 'One mark for applying the quotient rule, one for simplifying.'],
    ['b', 'Find the coordinates and nature of the stationary points of the graph of f.', 2, 'Local maximum (1, 1/2); local minimum (−1, −1/2)', 'f′(x) = 0 when x = ±1. f′ changes from positive to negative at x = 1 and from negative to positive at x = −1. One mark for the coordinates, one for the nature.'],
  ]),
  ex1(CA, 'developing', 'This question is about antiderivatives of circular, reciprocal and logarithmic functions.', [
    ['a', 'Find ∫(sin(2x) + 1/(2x + 1)) dx, where x > −1/2.', 2, '−(1/2)cos(2x) + (1/2)logₑ(2x + 1) + c', 'One mark for each term. The constant of integration is expected.'],
    ['b', 'Evaluate ∫ cos(3x) dx from x = 0 to x = π/6.', 1, '1/3', '[(1/3)sin(3x)] from 0 to π/6 = (1/3)sin(π/2) − 0 = 1/3.'],
    ['c', 'Given that d/dx(xlogₑ(x)) = logₑ(x) + 1, find an antiderivative of logₑ(x).', 1, 'xlogₑ(x) − x', 'Integrating both sides gives xlogₑ(x) = ∫logₑ(x) dx + x, so ∫logₑ(x) dx = xlogₑ(x) − x + c.'],
  ]),
  ex1(FN, 'proficient', 'Let f: R \\ {1} → R, f(x) = 3/(x − 1)² − 1.', [
    ['a', 'Write down the equations of the asymptotes of the graph of f.', 1, 'x = 1 and y = −1', 'The vertical asymptote is where x − 1 = 0; the horizontal asymptote is the constant term.'],
    ['b', 'Find the coordinates of the points where the graph of f meets the axes.', 3, '(0, 2), (1 − √3, 0) and (1 + √3, 0)', 'f(0) = 3 − 1 = 2. For the x-intercepts, (x − 1)² = 3, so x = 1 ± √3. One mark for the y-intercept, two for the x-intercepts.'],
    ['c', 'State the range of f.', 1, '(−1, ∞)', '3/(x − 1)² takes every positive value but never 0.'],
  ]),
  ex1(FN, 'proficient', 'Let h: R → R, h(x) = 3sin(πx/2) + 1.', [
    ['a', 'State the period and the range of h.', 2, 'Period 4; range [−2, 4]', 'The period is 2π ÷ (π/2) = 4. The amplitude is 3 about the line y = 1. One mark each.'],
    ['b', 'Solve h(x) = 5/2 for x ∈ [0, 4].', 2, 'x = 1/3 or x = 5/3', 'sin(πx/2) = 1/2 gives πx/2 = π/6 or 5π/6. One mark for each solution.'],
    ['c', 'Find the number of solutions of h(x) = 1 for x ∈ [0, 8].', 1, '5', 'sin(πx/2) = 0 when x = 0, 2, 4, 6 or 8.'],
  ]),
  ex1(AL, 'proficient', 'This question is about equations involving indices and logarithms.', [
    ['a', 'Solve 2²ˣ − 3 × 2ˣ⁺¹ + 8 = 0 for x.', 2, 'x = 1 or x = 2', 'Let u = 2ˣ. Then 2ˣ⁺¹ = 2u and the equation is u² − 6u + 8 = 0, so u = 2 or u = 4. One mark for the quadratic in u, one for both solutions.'],
    ['b', 'Solve logₑ(x) + logₑ(x − 3) = logₑ(4) for x.', 2, 'x = 4', 'x(x − 3) = 4 gives x² − 3x − 4 = (x − 4)(x + 1) = 0. x = −1 is rejected because logₑ(x) is undefined there. One mark for the quadratic, one for rejecting x = −1.'],
  ]),
  ex1(PR, 'proficient', 'On each school day Mia either walks to school or catches the bus. If she walks on one day, the probability that she walks the next day is 0.6. If she catches the bus on one day, the probability that she walks the next day is 0.3. Mia walks on Monday.', [
    ['a', 'Find the probability that Mia walks on Wednesday.', 2, '0.48', 'Walk–walk: 0.6 × 0.6 = 0.36. Bus–walk: 0.4 × 0.3 = 0.12. The total is 0.48. One mark for the two paths, one for the answer.'],
    ['b', 'Find the probability that Mia catches the bus on exactly one of Tuesday and Wednesday.', 1, '0.36', 'Walk then bus: 0.6 × 0.4 = 0.24. Bus then walk: 0.4 × 0.3 = 0.12.'],
    ['c', 'Given that Mia walks on Wednesday, find the probability that she walked on Tuesday.', 2, '3/4', 'Pr(walk Tuesday and Wednesday) ÷ Pr(walk Wednesday) = 0.36 ÷ 0.48. One mark for the conditional probability set-up, one for the answer.'],
  ]),
  ex1(PR, 'proficient', 'The continuous random variable X has probability density function f(x) = 1/x for 1 ≤ x ≤ e, and f(x) = 0 elsewhere.', [
    ['a', 'Show that f is a probability density function.', 1, 'f(x) ≥ 0 on [1, e] and ∫ (1/x) dx from 1 to e = logₑ(e) − logₑ(1) = 1', 'Both conditions are needed.'],
    ['b', 'Find Pr(X < 2).', 1, 'logₑ(2)', '∫ (1/x) dx from 1 to 2.'],
    ['c', 'Find E(X).', 1, 'e − 1', '∫ x × (1/x) dx from 1 to e = e − 1.'],
    ['d', 'Find the median of X.', 1, '√e', 'logₑ(m) = 1/2 gives m = e^(1/2).'],
  ]),
  ex1(PR, 'proficient', 'The random variable X has a binomial distribution with n = 4 and p = 1/3.', [
    ['a', 'Find Pr(X = 2).', 1, '8/27', '⁴C₂(1/3)²(2/3)² = 6 × 4/81 = 24/81.'],
    ['b', 'Find Pr(X ≥ 1).', 1, '65/81', '1 − (2/3)⁴ = 1 − 16/81.'],
    ['c', 'Find the mean and variance of X.', 1, 'Mean 4/3; variance 8/9', 'E(X) = np and Var(X) = np(1 − p).'],
    ['d', 'Find the smallest number of independent trials, each with success probability 1/3, needed for the probability of at least one success to exceed 0.8.', 1, '4', '(2/3)ⁿ < 0.2. (2/3)³ = 8/27 ≈ 0.30, which is too large, but (2/3)⁴ = 16/81 ≈ 0.198.'],
  ]),
  ex1(CA, 'advanced', 'The graphs of y = √x and y = x/2 meet at the origin O and at the point A.', [
    ['a', 'Find the coordinates of A.', 1, 'A(4, 2)', '√x = x/2 gives x = x²/4, so x = 0 or x = 4.'],
    ['b', 'Find the area of the region enclosed by the two graphs.', 2, '4/3', '∫ (√x − x/2) dx from 0 to 4 = [(2/3)x^(3/2) − x²/4] = 16/3 − 4. One mark for the integral, one for the value.'],
    ['c', 'Find the coordinates of the point on y = √x at which the tangent is parallel to y = x/2.', 1, '(1, 1)', '1/(2√x) = 1/2 gives x = 1.'],
    ['d', 'Find the maximum vertical distance between the two graphs for 0 ≤ x ≤ 4.', 1, '1/2', 'd(x) = √x − x/2 has d′(x) = 0 at x = 1, where d(1) = 1 − 1/2.'],
  ]),

  // ════════════════ Examination 2 — Section A (20 multiple choice) ════════════════
  mc(FN, 'developing',
    'The range of the function f: (0, ∞) → R, f(x) = 3 − 2e⁻ˣ is',
    ['(1, 3)', '[1, 3)', '(−∞, 3)', '(1, ∞)', '(3, 5)'],
    'e⁻ˣ takes every value in (0, 1) on this domain, so 3 − 2e⁻ˣ takes every value between 3 − 2 = 1 and 3, with neither endpoint reached.'),
  mc(FN, 'developing',
    'Which one of the following functions has an inverse function?',
    ['f: [2, 5] → R, f(x) = (x − 2)²', 'f: [0, π] → R, f(x) = sin(x)', 'f: R → R, f(x) = x² − 4', 'f: [−1, 1] → R, f(x) = x⁴', 'f: R → R, f(x) = x³ − 3x'],
    'Only (x − 2)² on [2, 5] is one-to-one: it is strictly increasing there. Each of the others takes some value twice.'),
  mc(FN, 'proficient',
    'The transformation T: R² → R², T(x, y) = (3 − x, 2y + 1) maps the graph of y = √x onto the graph of',
    ['y = 2√(3 − x) + 1', 'y = 2√(x − 3) + 1', 'y = 2√(x + 3) + 1', 'y = (1/2)√(3 − x) + 1', 'y = 2√(3 − x) − 1'],
    'Let (x′, y′) be the image. Then x = 3 − x′ and y = (y′ − 1)/2. Substituting into y = √x gives (y′ − 1)/2 = √(3 − x′), so y′ = 2√(3 − x′) + 1.'),
  mc(FN, 'developing',
    'The solutions of 2cos(x) + √3 = 0 for x ∈ [0, 2π] are',
    ['x = 5π/6 and x = 7π/6', 'x = π/6 and x = 11π/6', 'x = 2π/3 and x = 4π/3', 'x = π/3 and x = 5π/3', 'x = 7π/6 and x = 11π/6'],
    'cos(x) = −√3/2. The related angle is π/6, and cosine is negative in the second and third quadrants: π − π/6 and π + π/6.'),
  mc(FN, 'proficient',
    'The graph of y = alogₑ(x − b) passes through the points (3, 0) and (e + 2, 4). The values of a and b are',
    ['a = 4 and b = 2', 'a = 2 and b = 4', 'a = 4 and b = −2', 'a = 4 and b = 3', 'a = e and b = 2'],
    'y = 0 requires x − b = 1, so b = 2. Then alogₑ(e) = 4 gives a = 4.'),
  mc(AL, 'developing',
    'If 3ˣ = 5, then 9ˣ⁺¹ is equal to',
    ['225', '45', '75', '50', '250'],
    '9ˣ⁺¹ = 9 × (3ˣ)² = 9 × 25.'),
  mc(AL, 'proficient',
    'Newton’s method is used to find an approximate solution of eˣ − 3 = 0, with an initial estimate of x₀ = 1. The value of x₁ is',
    ['3/e', '1 − 3/e', 'e − 3', '1 + 3/e', 'logₑ(3)'],
    'x₁ = x₀ − f(x₀)/f′(x₀) = 1 − (e − 3)/e = 3/e ≈ 1.104. logₑ(3) ≈ 1.099 is the exact solution, not the first estimate.'),
  mc(AL, 'advanced',
    'The sum of all real solutions of the equation logₑ(x²) = 2logₑ(3) is',
    ['0', '3', '6', '−3', '9'],
    'x² = 9 gives x = 3 or x = −3, and logₑ(x²) is defined for both. Rewriting logₑ(x²) as 2logₑ(x) loses the negative solution.'),
  mc(CA, 'developing',
    'If y = (2x + 1)/(x − 1), then dy/dx is equal to',
    ['−3/(x − 1)²', '3/(x − 1)²', '−1/(x − 1)²', '(4x − 1)/(x − 1)²', '2'],
    'Quotient rule: (2(x − 1) − (2x + 1))/(x − 1)² = −3/(x − 1)².'),
  mc(CA, 'developing',
    'The function f: R → R, f(x) = x³ − 3x² − 9x + 1 is strictly decreasing on the interval',
    ['[−1, 3]', '(−∞, −1]', '[3, ∞)', '[−3, 1]', 'R'],
    'f′(x) = 3x² − 6x − 9 = 3(x − 3)(x + 1), which is negative between −1 and 3.'),
  mc(CA, 'proficient',
    'Given that ∫ 2e²ˣ dx from x = 0 to x = a is equal to 8, the value of a is',
    ['logₑ(3)', 'logₑ(9)', 'logₑ(4)', '(1/2)logₑ(8)', '3'],
    '[e²ˣ] from 0 to a = e²ᵃ − 1 = 8, so e²ᵃ = 9 and a = (1/2)logₑ(9) = logₑ(3).'),
  mc(CA, 'proficient',
    'The function f is differentiable, with f(2) = 3 and f′(2) = −1. If g(x) = xf(x), then g′(2) is equal to',
    ['1', '−2', '5', '3', '−1'],
    'g′(x) = f(x) + xf′(x), so g′(2) = 3 + 2 × (−1) = 1.'),
  mc(CA, 'developing',
    'The tangent to the graph of y = logₑ(x) at the point where x = e passes through the point',
    ['(0, 0)', '(0, 1)', '(1, 0)', '(e, 0)', '(0, −1)'],
    'The gradient is 1/e, so the tangent is y − 1 = (1/e)(x − e), which simplifies to y = x/e.'),
  mc(CA, 'developing',
    'Given that f′(x) = 3x² − 2 and the graph of y = f(x) passes through the point (1, 4), the value of f(2) is',
    ['9', '4', '10', '5', '8'],
    'f(x) = x³ − 2x + c, and f(1) = −1 + c = 4 gives c = 5. So f(2) = 8 − 4 + 5.'),
  mc(CA, 'proficient',
    'Four rectangles of equal width, using left endpoints, are used to approximate the area under the graph of y = x² + 1 between x = 0 and x = 2. The approximation is',
    ['3.75', '4.67', '4.75', '5.75', '7.5'],
    'The width is 0.5 and the heights are f(0), f(0.5), f(1) and f(1.5): 0.5(1 + 1.25 + 2 + 3.25) = 3.75. Right endpoints give 5.75, and the exact area is 14/3 ≈ 4.67.'),
  mc(PR, 'proficient',
    'The random variable X is normally distributed with a mean of 100 and a standard deviation of 15. Pr(X > 120 | X > 100), correct to four decimal places, is',
    ['0.1824', '0.0456', '0.0912', '0.5000', '0.9088'],
    'Pr(X > 120) = Pr(Z > 4/3) = 0.0912, and Pr(X > 100) = 0.5, so the conditional probability is 0.0912 ÷ 0.5 = 0.1824.'),
  mc(PR, 'advanced',
    'An approximate 95% confidence interval for a population proportion, calculated from one random sample, is (0.25, 0.35). The size of the sample is closest to',
    ['323', '81', '84', '1291', '35'],
    'p̂ = 0.3 and the margin of error is 0.05, so 1.96√(0.3 × 0.7 ÷ n) = 0.05, which gives n = 1.96² × 0.21 ÷ 0.05² ≈ 322.7.'),
  mc(PR, 'proficient',
    'The random variable X has a binomial distribution with n = 8 and p = 0.4. Pr(X ≥ 6), correct to four decimal places, is',
    ['0.0498', '0.0085', '0.0413', '0.1737', '0.9915'],
    'Pr(X = 6) + Pr(X = 7) + Pr(X = 8) = 0.04129 + 0.00786 + 0.00066 = 0.0498. 0.0085 is Pr(X > 6), and 0.1737 is Pr(X ≥ 5).'),
  mc(PR, 'developing',
    'The random variable X has variance 1.5. The variance of 3 − 2X is',
    ['6', '−3', '0', '3', '4.5'],
    'Var(aX + b) = a²Var(X), so Var(3 − 2X) = 4 × 1.5. The constant does not affect the spread.'),
  mc(PR, 'proficient',
    'The continuous random variable X has probability density function f(x) = 3(1 − x)² for 0 ≤ x ≤ 1, and f(x) = 0 elsewhere. E(X) is equal to',
    ['1/4', '1/12', '1/3', '1/2', '3/4'],
    'E(X) = ∫ 3x(1 − x)² dx from 0 to 1 = 3(1/2 − 2/3 + 1/4) = 3 × 1/12 = 1/4.'),

  // ════════════════ Examination 2 — Section B (60 marks) ════════════════
  ex2(FN, 'proficient',
    'A conservation program begins on an island. The population of a native bird species on the island, P thousand, t years after the program begins is modelled by P: [0, ∞) → R, P(t) = 12/(1 + 3e^(−0.4t)). The graph of y = P(t) is shown below.',
    [
      ['a', 'Find the population of the species when the program begins.', 1, '3 thousand', 'P(0) = 12/(1 + 3) = 3.'],
      ['b', 'State the population that the model predicts in the long run.', 1, '12 thousand', 'e^(−0.4t) → 0 as t → ∞, so P(t) → 12.'],
      ['c', 'Find the population after 5 years as a percentage of the long-run population, correct to one decimal place.', 1, '71.1%', 'P(5) = 8.535 thousand, and 8.535 ÷ 12 = 0.711.'],
      ['d', 'Find the exact time at which the population reaches 6 thousand, and give this time correct to two decimal places.', 2, 't = (5/2)logₑ(3) ≈ 2.75 years', '1 + 3e^(−0.4t) = 2 gives e^(−0.4t) = 1/3, so t = logₑ(3) ÷ 0.4. One mark for the equation, one for the value.'],
      ['e', 'Show that P′(t) = 14.4e^(−0.4t)/(1 + 3e^(−0.4t))².', 1, 'P′(t) = −12(1 + 3e^(−0.4t))⁻² × (−1.2e^(−0.4t)) = 14.4e^(−0.4t)/(1 + 3e^(−0.4t))²', 'Chain rule.'],
      ['f', 'Find the time at which the population is growing fastest, and the rate of growth at that time.', 2, 't ≈ 2.75 years; 1.2 thousand birds per year', 'P′(t) is maximised when P = 6, at t = (5/2)logₑ(3). P′ there is 14.4 × (1/3) ÷ 2² = 1.2. One mark for the time, one for the rate.'],
      ['g', 'Find the rule for t in terms of P, and state the set of values of P for which it applies.', 2, 't = (5/2)logₑ(3P/(12 − P)), for 3 ≤ P < 12', '1 + 3e^(−0.4t) = 12/P gives e^(−0.4t) = (12 − P)/(3P). Taking logarithms and dividing by −0.4 gives the rule. The domain is the range of P. One mark for the rule, one for the domain.'],
      ['h', 'Hence find the exact time taken for the population to grow from 4 thousand to 8 thousand.', 1, '5logₑ(2) ≈ 3.47 years', '(5/2)(logₑ(6) − logₑ(3/2)) = (5/2)logₑ(4).'],
      ['i', 'Find the average population over the first 10 years of the program, in thousands, correct to two decimal places.', 2, '8.00 thousand', '(1/10)∫ P(t) dt from 0 to 10 = 8.0016. One mark for the integral, one for the value.'],
      ['j', 'On a second island, the population of the species, Q thousand, is modelled by Q(t) = 1 + t. Find the time after which the second island has the larger population, correct to two decimal places.', 2, 't = 10.48 years', 'Solve 12/(1 + 3e^(−0.4t)) = 1 + t with a CAS. The first island has the larger population until then. One mark for the equation, one for the value.'],
    ],
    { diagram: { kind: 'function_graph', title: 'Bird population', xMin: 0, xMax: 16, yMin: 0, yMax: 14, xStep: 2, yStep: 2, xLabel: 't (years)', yLabel: 'P (thousand)', curves: [{ points: sample(t => 12 / (1 + 3 * Math.exp(-0.4 * t)), 0, 16, 64), label: 'y = P(t)' }, { points: [[0, 12], [16, 12]], dashed: true, label: 'P = 12' }] } }),
  ex2(CA, 'advanced',
    'Town A is 3 km from a straight coastline and town B is 5 km from it, on the same side. The points on the coastline nearest to A and B are 12 km apart. A pipeline is to run in a straight line from A to a pumping station P on the coastline, then in a straight line from P to B. Let x km be the distance from the point on the coastline nearest A to P, where 0 ≤ x ≤ 12, and let L(x) km be the total length of the pipeline. The graph of y = L(x) is shown below.',
    [
      ['a', 'Show that L(x) = √(x² + 9) + √(x² − 24x + 169).', 1, 'AP = √(x² + 3²) and PB = √((12 − x)² + 5²) = √(x² − 24x + 169)', 'Pythagoras’ theorem in each right-angled triangle.'],
      ['b', 'Find L′(x).', 2, 'L′(x) = x/√(x² + 9) + (x − 12)/√(x² − 24x + 169)', 'Chain rule on each term. One mark for each term.'],
      ['c', 'Show that the minimum length occurs when x = 9/2, and find the exact minimum length.', 3, 'x = 9/2; minimum length 4√13 km', 'L′(x) = 0 gives x/√(x² + 9) = (12 − x)/√((12 − x)² + 25). Squaring and simplifying gives 25x² = 9(12 − x)², so 5x = 3(12 − x) and x = 9/2. Then L = (√117 + √325)/2 = (3√13 + 5√13)/2 = 4√13. One mark for the equation, one for x, one for the length.'],
      ['d', 'The section from A to P costs $40 000 per km to build and the section from P to B costs $60 000 per km. Find the value of x that minimises the total cost, correct to two decimal places, and the minimum cost, correct to the nearest dollar.', 3, 'x = 8.00; minimum cost $725 948', 'C(x) = 40 000√(x² + 9) + 60 000√(x² − 24x + 169). Solving C′(x) = 0 with a CAS gives x = 8.0045. The dearer section is shortened by moving P towards B. One mark for C(x), one for x, one for the cost.'],
      ['e', 'Find the values of x for which the pipeline is shorter than 15 km, correct to two decimal places.', 2, '1.46 < x < 8.16', 'Solve L(x) = 15 with a CAS, then read off the interval between the solutions. One mark for each endpoint.'],
      ['f', 'Show that when x = 9/2, the pipes AP and PB make equal angles with the coastline.', 2, 'The angle between AP and the coastline has tangent 3 ÷ (9/2) = 2/3, and the angle between PB and the coastline has tangent 5 ÷ (15/2) = 2/3.', 'The acute angles have equal tangents, so they are equal. One mark for each tangent.'],
      ['g', 'Let B′ be the reflection of B in the coastline. Explain why PB = PB′, and hence find the minimum length of the pipeline without calculus.', 2, 'The coastline is the perpendicular bisector of BB′, so PB = PB′. AP + PB′ is least when A, P and B′ are collinear: √(12² + 8²) = √208 = 4√13 km.', 'B′ is 5 km on the other side of the coastline, so A and B′ are 8 km apart across the coastline and 12 km apart along it. One mark for the reason, one for the length.'],
    ],
    { diagram: { kind: 'function_graph', title: 'Total pipeline length', xMin: 0, xMax: 12, yMin: 12, yMax: 18, xStep: 2, yStep: 1, xLabel: 'x (km)', yLabel: 'L (km)', curves: [{ points: sample(x => Math.sqrt(x * x + 9) + Math.sqrt((12 - x) ** 2 + 25), 0, 12, 48), label: 'y = L(x)' }] } }),
  ex2(PR, 'advanced',
    'The lifetime, X years, of a brand of rechargeable battery is a continuous random variable with probability density function f(x) = (3/32)x(4 − x) for 0 ≤ x ≤ 4, and f(x) = 0 elsewhere. The graph of y = f(x) is shown below.',
    [
      ['a', 'Show that f is a probability density function.', 1, 'f(x) ≥ 0 on [0, 4] and ∫ (3/32)(4x − x²) dx from 0 to 4 = (3/32)(32 − 64/3) = 1', 'Both conditions are needed.'],
      ['b', 'Write down E(X).', 1, '2', 'The graph is symmetric about x = 2.'],
      ['c', 'Find Var(X).', 2, '0.8', 'E(X²) = (3/32)∫ (4x³ − x⁴) dx from 0 to 4 = (3/32)(256 − 204.8) = 4.8, so Var(X) = 4.8 − 2² = 0.8. One mark for E(X²), one for the variance.'],
      ['d', 'Find Pr(X > 3).', 1, '5/32', '(3/32)[2x² − x³/3] from 3 to 4 = (3/32)(32/3 − 9) = 5/32.'],
      ['e', 'Explain why Pr(X < 1) = Pr(X > 3).', 1, 'The density is symmetric about x = 2, and x = 1 and x = 3 are the same distance from 2.', 'f(2 − h) = f(2 + h) for every h.'],
      ['f', 'Find Pr(X > 3 | X > 2).', 1, '5/16', '(5/32) ÷ (1/2).'],
      ['g', 'A pack contains 10 of these batteries, with independent lifetimes. Find the probability that at least 2 of them last more than 3 years, correct to four decimal places.', 2, '0.4785', 'The number lasting more than 3 years is binomial with n = 10 and p = 5/32. 1 − Pr(0) − Pr(1) = 0.4785. One mark for the distribution, one for the value.'],
      ['h', 'The manufacturer wants to offer a warranty of a years, where 90% of batteries fail within a years. Find a, correct to three decimal places.', 2, '3.217', 'Solve (3/32)(2a² − a³/3) = 0.9 for 0 ≤ a ≤ 4 with a CAS. One mark for the equation, one for the value.'],
      ['i', 'A new model has lifetime Y years, which is normally distributed with a mean of 2.5 years and a standard deviation of 0.4 years. Find Pr(Y > 3), correct to four decimal places.', 1, '0.1056', 'z = (3 − 2.5) ÷ 0.4 = 1.25.'],
      ['j', 'In a random sample of 200 of the new batteries, 34 lasted more than 3 years. Find an approximate 95% confidence interval for the proportion of new batteries that last more than 3 years, with the endpoints correct to four decimal places.', 2, '(0.1179, 0.2221)', 'p̂ = 0.17 and 1.96√(0.17 × 0.83 ÷ 200) = 0.0521. One mark for the margin of error, one for the interval.'],
      ['k', 'One battery of each model is chosen, independently. Find the probability that both last more than 3 years, correct to four decimal places.', 1, '0.0165', '(5/32) × 0.1056.'],
    ],
    { diagram: { kind: 'function_graph', title: 'Battery lifetime density', xMin: 0, xMax: 4, yMin: 0, yMax: 0.5, xStep: 1, yStep: 0.1, xLabel: 'x (years)', yLabel: 'f(x)', curves: [{ points: sample(x => (3 / 32) * x * (4 - x), 0, 4, 40), label: 'y = f(x)' }] } }),
  ex2(AL, 'advanced',
    'Let f: R → R, f(x) = e^(x − 1) and g: (0, ∞) → R, g(x) = 1 + logₑ(x). The graphs of y = f(x), y = g(x) and y = x are shown below.',
    [
      ['a', 'Show that g is the inverse function of f.', 1, 'x = e^(y − 1) gives y − 1 = logₑ(x), so f⁻¹(x) = 1 + logₑ(x) = g(x), with domain the range of f, (0, ∞).', 'Swap x and y, then solve for y.'],
      ['b', 'Show that the line y = x is a tangent to both graphs at the point (1, 1).', 2, 'f(1) = g(1) = 1, and f′(1) = e⁰ = 1 and g′(1) = 1/1 = 1', 'Both graphs pass through (1, 1) with gradient 1. One mark for each graph.'],
      ['c', 'Find the exact area of the region enclosed by the graph of f, the line y = x and the y-axis.', 2, '1/2 − 1/e', '∫ (e^(x − 1) − x) dx from 0 to 1 = (1 − e⁻¹) − 1/2. One mark for the integral, one for the value.'],
      ['d', 'Hence find the exact area of the region enclosed by the graphs of f and g and the coordinate axes.', 1, '1 − 2/e', 'The region is symmetric about y = x, because f and g are inverses, so its area is twice the answer to part c.'],
      ['e', 'Let hₖ(x) = e^(x − k), where k is a real constant. Find the values of k for which the graph of y = hₖ(x) meets the line y = x at exactly two points.', 2, 'k > 1', 'The line is a tangent when e^(x − k) = x and e^(x − k) = 1, which gives x = 1 and k = 1. Increasing k translates the graph to the right, so it then crosses the line twice. One mark for the tangent case, one for the answer.'],
      ['f', 'For k = 2, find the x-coordinates of the points where y = h₂(x) meets y = x, correct to three decimal places.', 2, 'x = 0.159 and x = 3.146', 'Solve e^(x − 2) = x with a CAS. One mark for each value.'],
      ['g', 'Find the area of the region enclosed by y = h₂(x) and y = x, correct to three decimal places.', 2, '1.949', '∫ (x − e^(x − 2)) dx between the solutions in part f. One mark for the integral, one for the value.'],
      ['h', 'Find the equation of the tangent to the graph of f at x = 0, and the x-intercept of this tangent.', 2, 'y = (x + 1)/e; x-intercept (−1, 0)', 'f(0) = e⁻¹ and f′(0) = e⁻¹. One mark for the equation, one for the intercept.'],
      ['i', 'Find the exact average value of g over the interval [1, e].', 1, 'e/(e − 1)', '(1/(e − 1))∫ (1 + logₑ(x)) dx from 1 to e = (1/(e − 1))[x + xlogₑ(x) − x] from 1 to e = e/(e − 1).'],
    ],
    { diagram: { kind: 'function_graph', title: 'y = f(x), y = g(x) and y = x', xMin: -2, xMax: 4, yMin: -2, yMax: 4, xStep: 1, yStep: 1, curves: [{ points: sample(x => Math.exp(x - 1), -2, 2.38, 44), label: 'y = f(x)' }, { points: sample(x => 1 + Math.log(x), 0.05, 4, 60), dashed: true, label: 'y = g(x)' }, { points: [[-2, -2], [4, 4]], dotted: true, label: 'y = x' }], points: [{ x: 1, y: 1, label: '(1, 1)' }] } }),
]
