// VCE Mathematical Methods Unit 3 & 4 — Practice set 4.
// Examination 1: 9 technology-free questions, 40 marks.
// Examination 2: Section A 20 multiple choice; Section B 4 extended questions, 60 marks.
// Numeric answers are checked in scripts/authoring/vce/check-mm-set4.mjs.
const FN = 'mm_functions', AL = 'mm_algebra', CA = 'mm_calculus', PR = 'mm_probability'
const S = 4
const code = { [FN]: 'VCE-MM-U34-AOS1', [AL]: 'VCE-MM-U34-AOS2', [CA]: 'VCE-MM-U34-AOS3', [PR]: 'VCE-MM-U34-AOS4' }
const ex1 = (t, d, q, p, extra = {}) => ({ t, s: S, d, calc: false, q, p, code: code[t], ...extra })
const mc = (t, d, q, o, e, extra = {}) => ({ t, s: S, d, calc: true, q, o, e, code: code[t], ...extra })
const ex2 = (t, d, q, p, extra = {}) => ({ t, s: S, d, calc: true, q, p, code: code[t], ...extra })

const sample = (f, a, b, n) => Array.from({ length: n + 1 }, (_, i) => {
  const x = a + ((b - a) * i) / n
  return [Math.round(x * 1000) / 1000, Math.round(f(x) * 1000) / 1000]
})

export const ITEMS = [
  // ════════════════ Examination 1 — technology-free (40 marks) ════════════════
  ex1(CA, 'developing', 'This question is about the chain and product rules.', [
    ['a', 'Let y = (3x − 1)⁴. Find dy/dx.', 1, 'dy/dx = 12(3x − 1)³', 'Chain rule: 4(3x − 1)³ × 3.'],
    ['b', 'Let f(x) = x²logₑ(x), where x > 0. Evaluate f′(e).', 2, 'f′(e) = 3e', 'Product rule: f′(x) = 2xlogₑ(x) + x² × (1/x) = 2xlogₑ(x) + x. At x = e: 2e × 1 + e = 3e. One mark for the derivative, one for the value.'],
    ['c', 'Let g(x) = e^(sin(x)). Evaluate g′(π).', 1, 'g′(π) = −1', 'g′(x) = cos(x)e^(sin(x)). At x = π: cos(π)e⁰ = −1.'],
  ]),
  ex1(CA, 'developing', 'This question is about antiderivatives of exponential, reciprocal and power functions.', [
    ['a', 'Find ∫(4e²ˣ − 3/x) dx, where x > 0.', 2, '2e²ˣ − 3logₑ(x) + c', 'One mark for each term. The constant of integration is expected.'],
    ['b', 'Given that f′(x) = 3√x and f(4) = 20, find f(x).', 1, 'f(x) = 2x^(3/2) + 4', 'An antiderivative of 3x^(1/2) is 2x^(3/2). Then f(4) = 2 × 8 + c = 20 gives c = 4.'],
  ]),
  ex1(FN, 'proficient', 'Let f: R \\ {−1} → R, f(x) = 2 − 3/(x + 1).', [
    ['a', 'Write down the equations of the asymptotes of the graph of f.', 1, 'x = −1 and y = 2', 'The vertical asymptote is where x + 1 = 0; the horizontal asymptote is the constant term.'],
    ['b', 'Find the coordinates of the points where the graph of f meets the axes.', 2, '(0, −1) and (1/2, 0)', 'f(0) = 2 − 3 = −1. For the x-intercept, 3/(x + 1) = 2 gives x + 1 = 3/2, so x = 1/2. One mark for each intercept.'],
    ['c', 'Find the rule and domain of the inverse function f⁻¹.', 2, 'f⁻¹(x) = 3/(2 − x) − 1, domain R \\ {2}', 'Swap x and y: x = 2 − 3/(y + 1), so 3/(y + 1) = 2 − x and y = 3/(2 − x) − 1. The domain of f⁻¹ is the range of f, R \\ {2}. One mark for the rule, one for the domain.'],
  ]),
  ex1(FN, 'proficient', 'Let f: [0, 2π] → R, f(x) = 1 − 2cos(x).', [
    ['a', 'State the range of f.', 1, '[−1, 3]', 'cos(x) takes every value in [−1, 1] on this domain, so 1 − 2cos(x) runs from 1 − 2 = −1 to 1 + 2 = 3.'],
    ['b', 'Solve f(x) = 2 for x.', 2, 'x = 2π/3 or x = 4π/3', '1 − 2cos(x) = 2 gives cos(x) = −1/2, so x = π − π/3 = 2π/3 or x = π + π/3 = 4π/3. One mark for each solution.'],
    ['c', 'State the x-intercepts of the graph of f.', 1, 'x = π/3 and x = 5π/3', 'cos(x) = 1/2 gives x = π/3 or x = 2π − π/3 = 5π/3.'],
  ]),
  ex1(PR, 'proficient', 'A game costs $2 to play. The player rolls a fair six-sided die and wins $5 for a six, $2 for a four or a five, and nothing otherwise. Let X be the player’s net gain, in dollars, from one game.', [
    ['a', 'Write down the probability distribution of X.', 1, 'Pr(X = 3) = 1/6, Pr(X = 0) = 1/3, Pr(X = −2) = 1/2', 'A six gives 5 − 2 = 3; a four or five gives 2 − 2 = 0; otherwise the player loses the $2.'],
    ['b', 'Find E(X).', 1, '−1/2', 'E(X) = 3 × 1/6 + 0 × 1/3 − 2 × 1/2 = 1/2 − 1 = −1/2.'],
    ['c', 'Find Var(X).', 2, '13/4', 'E(X²) = 9 × 1/6 + 0 + 4 × 1/2 = 3/2 + 2 = 7/2. Var(X) = 7/2 − (−1/2)² = 7/2 − 1/4 = 13/4. One mark for E(X²), one for the variance.'],
    ['d', 'The game is played twice. Find the probability that the player’s total net gain is positive.', 1, '11/36', 'Positive totals come from (3, 3), (3, 0), (0, 3), (3, −2) and (−2, 3): 1/36 + 2 × 1/18 + 2 × 1/12 = 1/36 + 4/36 + 6/36 = 11/36.'],
  ]),
  ex1(PR, 'proficient', 'The continuous random variable X has probability density function f(x) = kx² for 0 ≤ x ≤ 2, and f(x) = 0 elsewhere.', [
    ['a', 'Show that k = 3/8.', 1, 'k × 8/3 = 1, so k = 3/8', '∫ kx² dx from 0 to 2 = k[x³/3] = 8k/3, which must equal 1.'],
    ['b', 'Find Pr(X > 1).', 1, '7/8', 'Pr(X ≤ 1) = (3/8)(1/3) = 1/8, so Pr(X > 1) = 7/8.'],
    ['c', 'Find the median of X.', 1, '∛4', 'Solve (3/8)(m³/3) = 1/2, so m³/8 = 1/2 and m³ = 4, giving m = ∛4.'],
    ['d', 'Find Pr(X < 1 | X < 3/2).', 1, '8/27', 'Pr(X < a) = a³/8. Pr(X < 1) = 1/8 and Pr(X < 3/2) = 27/64, so the conditional probability is (1/8) ÷ (27/64) = 8/27.'],
  ]),
  ex1(AL, 'proficient', 'This question is about logarithms and exponentials.', [
    ['a', 'Solve logₑ(2x + 1) = 2logₑ(x − 1) for x.', 2, 'x = 4', '2x + 1 = (x − 1)², so x² − 4x = 0 and x = 0 or x = 4. The logarithms need x > 1, so x = 4. One mark for the quadratic, one for rejecting x = 0.'],
    ['b', 'Solve e^(2x − 1) = 5 for x.', 1, 'x = (1 + logₑ(5))/2', '2x − 1 = logₑ(5).'],
    ['c', 'Given logₐ(3) = p and logₐ(5) = q, express logₐ(45) in terms of p and q.', 1, '2p + q', '45 = 3² × 5, so logₐ(45) = 2logₐ(3) + logₐ(5).'],
  ]),
  ex1(CA, 'proficient', 'Let f: R → R, f(x) = x³ − 3x + 2. The graph of f touches the x-axis at x = 1 and crosses it at x = −2.', [
    ['a', 'Find the coordinates of the stationary points of f and state their nature.', 2, '(−1, 4) local maximum; (1, 0) local minimum', 'f′(x) = 3x² − 3 = 0 when x = ±1. f(−1) = −1 + 3 + 2 = 4 and f(1) = 0. The cubic has a positive leading coefficient, so the left stationary point is the maximum. One mark for the coordinates, one for the nature.'],
    ['b', 'Find the area of the region enclosed by the graph of f and the x-axis.', 2, '27/4', '∫ (x³ − 3x + 2) dx from −2 to 1 = [x⁴/4 − 3x²/2 + 2x] = (1/4 − 3/2 + 2) − (4 − 6 − 4) = 3/4 + 6 = 27/4. One mark for the integral with correct terminals, one for the value.'],
    ['c', 'Find the values of k for which the equation f(x) = k has three solutions.', 1, '0 < k < 4', 'A horizontal line meets the graph three times strictly between the local minimum value 0 and the local maximum value 4.'],
  ]),
  ex1(CA, 'advanced', 'Let P(a, 1/a) be a point on the graph of y = 1/x, where a > 0. The tangent to the graph at P meets the x-axis at A and the y-axis at B. Let O be the origin.', [
    ['a', 'Show that the equation of the tangent at P is y = −x/a² + 2/a.', 2, 'dy/dx = −1/a² at P; y − 1/a = −(1/a²)(x − a), so y = −x/a² + 2/a.', 'One mark for the gradient, one for forming and simplifying the equation.'],
    ['b', 'Find the coordinates of A and B in terms of a.', 1, 'A(2a, 0) and B(0, 2/a)', 'Set y = 0 to get x = 2a, and set x = 0 to get y = 2/a.'],
    ['c', 'Show that the area of triangle OAB does not depend on a.', 1, 'Area = (1/2)(2a)(2/a) = 2', 'The area is 2 square units for every a > 0.'],
    ['d', 'Find the value of a for which the length AB is a minimum, and state this minimum length.', 2, 'a = 1; AB = 2√2', 'AB² = 4a² + 4/a². d/da(AB²) = 8a − 8/a³ = 0 when a⁴ = 1, so a = 1 (a > 0), which gives AB² = 8 and AB = 2√2. One mark for a, one for the length.'],
  ]),

  // ════════════════ Examination 2 — Section A (20 multiple choice) ════════════════
  mc(FN, 'developing',
    'The function f: [a, ∞) → R, f(x) = x² − 6x + 5 has an inverse function. The smallest possible value of a is',
    ['3', '−3', '0', '1', '5'],
    'f(x) = (x − 3)² − 4 has its turning point at x = 3. The function is one-to-one, so it has an inverse, only on a domain that starts at or to the right of x = 3.'),
  mc(FN, 'developing',
    'The equation of the vertical asymptote of the graph of y = logₑ(4 − 2x) + 1 is',
    ['x = 2', 'x = 4', 'x = −2', 'x = 1', 'y = 1'],
    'The logarithm is undefined when 4 − 2x = 0, that is x = 2, and the graph approaches this line.'),
  mc(FN, 'proficient',
    'The graph of y = f(x) is reflected in the x-axis and then translated 2 units in the positive direction of the x-axis. The rule of the image is',
    ['y = −f(x − 2)', 'y = −f(x + 2)', 'y = f(2 − x)', 'y = −f(x) − 2', 'y = f(−x − 2)'],
    'Reflecting in the x-axis gives y = −f(x). Translating 2 units right replaces x with x − 2, giving y = −f(x − 2).'),
  mc(AL, 'proficient',
    'The simultaneous linear equations kx + 3y = 6 and 3x + ky = k + 3, where k is a real constant, have infinitely many solutions when',
    ['k = 3', 'k = −3', 'k = 3 or k = −3', 'k = 0', 'k = 9'],
    'The determinant k² − 9 is zero when k = ±3. When k = 3 both equations are 3x + 3y = 6, so there are infinitely many solutions. When k = −3 they become −x + y = 2 and x − y = 0, which contradict each other, so there is no solution.'),
  mc(CA, 'developing',
    'If y = e³ˣcos(2x), then dy/dx is equal to',
    ['e³ˣ(3cos(2x) − 2sin(2x))', 'e³ˣ(3cos(2x) + 2sin(2x))', '−6e³ˣsin(2x)', '3e³ˣcos(2x)', 'e³ˣ(cos(2x) − 2sin(2x))'],
    'Product rule: 3e³ˣcos(2x) + e³ˣ(−2sin(2x)) = e³ˣ(3cos(2x) − 2sin(2x)).'),
  mc(CA, 'developing',
    'The gradient of the tangent to the graph of y = logₑ(x² + 3) at the point where x = 1 is',
    ['1/2', '1/4', '1/3', '2', 'logₑ(4)'],
    'dy/dx = 2x/(x² + 3). At x = 1 this is 2/4 = 1/2.'),
  mc(CA, 'proficient',
    'A function f has derivative f′(x) = (x − 2)²(x + 1). The graph of y = f(x) has',
    ['a local minimum at x = −1 and a stationary point of inflection at x = 2', 'a local maximum at x = −1 and a local minimum at x = 2', 'a local maximum at x = −1 and a stationary point of inflection at x = 2', 'a stationary point of inflection at x = −1 and a local minimum at x = 2', 'a local minimum at x = 2 only'],
    'f′(x) < 0 for x < −1 and f′(x) > 0 for −1 < x < 2, so there is a local minimum at x = −1. f′(x) > 0 on both sides of x = 2 because (x − 2)² does not change sign, so x = 2 is a stationary point of inflection.'),
  mc(CA, 'proficient',
    'The total area of the regions enclosed by the graph of y = sin(x), the x-axis and the lines x = 0 and x = 3π/2 is',
    ['3', '0', '1', '2', '4'],
    '∫ sin(x) dx from 0 to π = 2, and the region from π to 3π/2 lies below the axis with area |∫ sin(x) dx| = 1. The total area is 2 + 1 = 3. The signed integral from 0 to 3π/2 is 1, a common wrong answer.'),
  mc(CA, 'advanced',
    'The volume of a spherical balloon is increasing at a rate of 20 cm³ per second. When the radius is 5 cm, the rate at which the radius is increasing, in cm per second, is',
    ['1/(5π)', '1/(20π)', '1/(100π)', '4π/5', '5π'],
    'V = (4/3)πr³, so dV/dt = 4πr² × dr/dt. With dV/dt = 20 and r = 5: 20 = 100π × dr/dt, so dr/dt = 1/(5π).'),
  mc(PR, 'developing',
    'The random variable X has a binomial distribution with n = 12 and p = 0.25. Pr(X = 3), correct to four decimal places, is',
    ['0.2581', '0.0012', '0.2323', '0.6093', '0.6488'],
    'Pr(X = 3) = ¹²C₃(0.25)³(0.75)⁹ = 220 × 0.015625 × 0.07508 = 0.2581. 0.6488 is Pr(X ≤ 3) and 0.6093 is Pr(X ≥ 3).'),
  mc(PR, 'developing',
    'The random variable X is normally distributed with a mean of 50 and a standard deviation of 5. Pr(X < 42), correct to four decimal places, is',
    ['0.0548', '0.0228', '0.1151', '0.4452', '0.9452'],
    'z = (42 − 50) ÷ 5 = −1.6, and Pr(Z < −1.6) = 0.0548.'),
  mc(PR, 'proficient',
    'The random variable X is normally distributed with a standard deviation of 4. Given that Pr(X > 30) = 0.05, the mean of X, correct to two decimal places, is',
    ['23.42', '22.16', '25.00', '26.00', '36.58'],
    'Pr(X > 30) = 0.05 means 30 is at z = 1.6449. So μ = 30 − 1.6449 × 4 = 23.42. Using z = 1.96 gives 22.16, and adding instead of subtracting gives 36.58.'),
  mc(PR, 'advanced',
    'In a large population, 20% of people are left-handed. Random samples of 64 people are taken and P̂ is the proportion of left-handed people in a sample. Using a normal approximation, Pr(P̂ > 0.25), correct to four decimal places, is',
    ['0.1587', '0.0228', '0.0500', '0.3085', '0.8413'],
    'The standard deviation of P̂ is √(0.2 × 0.8 ÷ 64) = 0.05, so z = (0.25 − 0.2) ÷ 0.05 = 1, and Pr(Z > 1) = 0.1587.'),
  mc(PR, 'proficient',
    'An approximate 95% confidence interval for a population proportion p, calculated from one random sample, is (0.42, 0.56). Which one of the following statements is correct?',
    ['If many samples of the same size were taken, about 95% of the intervals calculated from them would contain p.', 'There is a 95% probability that p lies between 0.42 and 0.56.', 'About 95% of the population has a value between 0.42 and 0.56.', 'The sample proportion is 0.56.', 'The margin of error is 0.14.'],
    'The 95% describes the method: about 95% of intervals built this way capture p. A particular interval either contains p or it does not. The sample proportion is the midpoint, 0.49, and the margin of error is 0.07.'),
  mc(PR, 'proficient',
    'The continuous random variable X has probability density function f(x) = (1/2)e^(−x/2) for x ≥ 0, and f(x) = 0 elsewhere. Pr(X > 2) is equal to',
    ['e⁻¹', '1 − e⁻¹', 'e⁻²', 'e^(−1/2)', '1/2'],
    '∫ (1/2)e^(−x/2) dx from 2 to ∞ = [−e^(−x/2)] from 2 to ∞ = 0 − (−e⁻¹) = e⁻¹.'),
  mc(PR, 'advanced',
    'For events A and B, Pr(A) = 0.6, Pr(B | A) = 0.3 and Pr(B | A′) = 0.5. Pr(A | B) is equal to',
    ['9/19', '0.18', '0.3', '0.38', '10/19'],
    'Pr(A ∩ B) = 0.6 × 0.3 = 0.18 and Pr(A′ ∩ B) = 0.4 × 0.5 = 0.2, so Pr(B) = 0.38. Pr(A | B) = 0.18 ÷ 0.38 = 9/19.'),
  mc(AL, 'advanced',
    'Let f(x) = 2x + 1 and g(x) = x² − 3. The number of real solutions of the equation f(g(x)) = g(f(x)) is',
    ['0', '1', '2', '3', '4'],
    'f(g(x)) = 2x² − 5 and g(f(x)) = (2x + 1)² − 3 = 4x² + 4x − 2. Equating gives 2x² + 4x + 3 = 0, whose discriminant is 16 − 24 = −8 < 0, so there are no real solutions.'),
  mc(FN, 'developing',
    'The maximum value of the function f(x) = 3 − 2sin(2x − π/3) is',
    ['5', '1', '2', '3', '7'],
    'sin(2x − π/3) has minimum value −1, which gives the maximum value 3 − 2(−1) = 5.'),
  mc(CA, 'proficient',
    'The maximum value of the function f: R → R, f(x) = xe⁻ˣ is',
    ['1/e', '2/e²', '0', '1', 'e'],
    'f′(x) = e⁻ˣ(1 − x) = 0 when x = 1, which is a maximum since f′ changes from positive to negative. f(1) = e⁻¹ = 1/e.'),
  mc(PR, 'proficient',
    'A biased coin is tossed three times. The probability of obtaining at least one head is 0.973. The probability of obtaining a head on a single toss is',
    ['0.7', '0.3', '0.324', '0.9', '0.973'],
    'Pr(no heads) = (1 − p)³ = 1 − 0.973 = 0.027, so 1 − p = 0.3 and p = 0.7.'),

  // ════════════════ Examination 2 — Section B (60 marks) ════════════════
  ex2(FN, 'proficient',
    'The temperature, in degrees Celsius, in city A t hours after midnight on a spring day is modelled by T: [0, 24] → R, T(t) = 18 − 6cos(πt/12). The graph of y = T(t) is shown below.',
    [
      ['a', 'State the maximum and minimum temperatures, and the times at which they occur.', 2, 'Maximum 24 °C at noon (t = 12); minimum 12 °C at midnight (t = 0 and t = 24).', 'cos(πt/12) = −1 at t = 12 and 1 at t = 0 and 24. One mark for the values, one for the times.'],
      ['b', 'Find the temperature at 8 am.', 1, '21 °C', 'T(8) = 18 − 6cos(2π/3) = 18 + 3 = 21.'],
      ['c', 'Find the times at which the temperature is 21 °C.', 2, '8 am and 4 pm', 'cos(πt/12) = −1/2 gives πt/12 = 2π/3 or 4π/3, so t = 8 or t = 16. One mark for each time.'],
      ['d', 'For how many hours of the day is the temperature at least 21 °C?', 1, '8 hours', 'From t = 8 to t = 16.'],
      ['e', 'Find T′(t), and hence find the maximum rate of increase of the temperature and the time at which it occurs.', 3, 'T′(t) = (π/2)sin(πt/12); maximum rate π/2 °C per hour at 6 am', 'T′(t) = 6 × (π/12)sin(πt/12). Its maximum is π/2 ≈ 1.57, when sin(πt/12) = 1, that is t = 6. One mark each for the derivative, the rate and the time.'],
      ['f', 'Find the average rate of change of the temperature between 6 am and noon.', 1, '1 °C per hour', '(T(12) − T(6)) ÷ 6 = (24 − 18) ÷ 6 = 1.'],
      ['g', 'On the same day, the temperature in city B is modelled by S(t) = 20 − 4cos(π(t − 2)/12). Find the times, t, when the two cities have the same temperature. Give your answers correct to two decimal places.', 2, 't = 6 and t = 12.90', 'Solve T(t) = S(t) on [0, 24] with a CAS: t = 6 (both 18 °C) and t = 12.8984. One mark for each.'],
      ['h', 'For what percentage of the 24-hour period is city A warmer than city B? Give your answer correct to one decimal place.', 2, '28.7%', 'City A is warmer between the crossings, for 12.8984 − 6 = 6.8984 hours. 6.8984 ÷ 24 = 0.2874, or 28.7%. One mark for the interval, one for the percentage.'],
      ['i', 'Find the average temperature in city A over the 24 hours.', 1, '18 °C', 'The cosine term averages to zero over a full period, so the average is 18.'],
    ],
    { diagram: { kind: 'function_graph', title: 'Temperature in city A', xMin: 0, xMax: 24, yMin: 0, yMax: 28, xStep: 4, yStep: 4, xLabel: 't (hours after midnight)', yLabel: 'T (°C)', curves: [{ points: sample(t => 18 - 6 * Math.cos((Math.PI * t) / 12), 0, 24, 48), label: 'y = T(t)' }], points: [{ x: 0, y: 12 }, { x: 12, y: 24, label: '(12, 24)' }, { x: 24, y: 12 }] } }),
  ex2(AL, 'advanced',
    'Let f: R → R, f(x) = x(x − a)², where a is a positive real constant.',
    [
      ['a', 'Show that f′(x) = (x − a)(3x − a).', 1, 'f′(x) = (x − a)² + 2x(x − a) = (x − a)(3x − a)', 'Product rule, then factorise out (x − a).'],
      ['b', 'Find the coordinates of the stationary points of the graph of f, in terms of a.', 2, '(a, 0) and (a/3, 4a³/27)', 'f′(x) = 0 when x = a or x = a/3. f(a/3) = (a/3)(−2a/3)² = 4a³/27. One mark for each point.'],
      ['c', 'Find the area of the region enclosed by the graph of f and the x-axis, in terms of a.', 2, 'a⁴/12', '∫ (x³ − 2ax² + a²x) dx from 0 to a = a⁴/4 − 2a⁴/3 + a⁴/2 = a⁴/12. One mark for the integral, one for the result.'],
      ['d', 'Find the value of a for which this area is 27/4.', 1, 'a = 3', 'a⁴/12 = 27/4 gives a⁴ = 81, so a = 3 (a > 0).'],
      ['e', 'Let a = 3. Find the equation of the tangent to the graph of f at the point where x = 4.', 2, 'y = 9x − 32', 'f(4) = 4 × 1² = 4 and f′(4) = (4 − 3)(12 − 3) = 9. So y − 4 = 9(x − 4), or y = 9x − 32. One mark for the gradient, one for the equation.'],
      ['f', 'Find the coordinates of the other point where this tangent meets the graph of f.', 2, '(−2, −50)', 'x(x − 3)² = 9x − 32 simplifies to x³ − 6x² + 32 = 0, which factorises as (x − 4)²(x + 2) = 0. So x = −2 and y = 9(−2) − 32 = −50. One mark for the equation, one for the point.'],
      ['g', 'Find the area of the region bounded by the tangent and the graph of f.', 2, '108', 'On (−2, 4) the curve lies above the tangent: ∫ (x³ − 6x² + 32) dx from −2 to 4 = [x⁴/4 − 2x³ + 32x] = 64 − (−44) = 108. One mark for the integral, one for the value.'],
      ['h', 'Show that, for every a > 0, the local maximum of the graph of f lies on the curve y = 4x³.', 1, 'At x = a/3, y = 4a³/27 = 4(a/3)³.', 'Substituting x = a/3 into y = 4x³ gives 4a³/27, the y-coordinate of the maximum.'],
      ['i', 'Let a = 3. Find the values of k for which the equation f(x) = k has three distinct solutions.', 2, '0 < k < 4', 'The local minimum is (3, 0) and the local maximum is (1, 4), so a horizontal line y = k meets the graph three times for 0 < k < 4. One mark for each endpoint with correct inequalities.'],
    ],
    { diagram: { kind: 'function_graph', title: 'y = x(x − 3)², the case a = 3', xMin: -1, xMax: 5, yMin: -6, yMax: 22, xStep: 1, yStep: 4, curves: [{ points: sample(x => x * (x - 3) ** 2, -0.6, 4.9, 44), label: 'y = f(x)' }], points: [{ x: 1, y: 4, label: '(1, 4)' }, { x: 3, y: 0, label: '(3, 0)' }] } }),
  ex2(PR, 'advanced',
    'The time, T minutes, taken by students to complete a puzzle is normally distributed with a mean of 12 minutes and a standard deviation of 2.5 minutes.',
    [
      ['a', 'Find Pr(T > 15), correct to four decimal places.', 1, '0.1151', 'z = (15 − 12) ÷ 2.5 = 1.2, and Pr(Z > 1.2) = 0.1151.'],
      ['b', 'Find Pr(10 < T < 15), correct to four decimal places.', 1, '0.6731', 'Pr(−0.8 < Z < 1.2) = 0.8849 − 0.2119 = 0.6731.'],
      ['c', 'Find the time within which 90% of students complete the puzzle, correct to two decimal places.', 1, '15.20 minutes', '12 + 2.5 × 1.2816 = 15.20.'],
      ['d', 'Given that a student takes more than 10 minutes, find the probability that the student takes more than 15 minutes, correct to four decimal places.', 1, '0.1460', 'Pr(T > 15) ÷ Pr(T > 10) = 0.1151 ÷ 0.7881 = 0.1460.'],
      ['e', 'Twenty students attempt the puzzle independently. Find the probability that exactly three of them take more than 15 minutes, correct to three decimal places.', 2, '0.217', 'The number who take more than 15 minutes is binomial with n = 20 and p = 0.1151: ²⁰C₃p³(1 − p)¹⁷ = 0.217. One mark for identifying the distribution, one for the value.'],
      ['f', 'Find the probability that at least one of the twenty students takes more than 15 minutes, correct to four decimal places.', 1, '0.9133', '1 − (1 − 0.1151)²⁰ = 0.9133.'],
      ['g', 'In a random sample of 150 students, 27 took more than 15 minutes. Find an approximate 95% confidence interval for the proportion of all students who take more than 15 minutes. Give the endpoints correct to four decimal places.', 2, '(0.1185, 0.2415)', 'p̂ = 27 ÷ 150 = 0.18 and the standard error is √(0.18 × 0.82 ÷ 150) = 0.0314, so 0.18 ± 1.96 × 0.0314 gives (0.1185, 0.2415). One mark for p̂ and the standard error, one for the interval.'],
      ['h', 'Does this interval support the normal model’s value of 0.1151 for this proportion? Give a reason.', 1, 'No — 0.1151 lies outside the interval.', 'The whole interval lies above 0.1151, which suggests the proportion of students taking more than 15 minutes is higher than the model predicts.'],
      ['i', 'Using p̂ = 0.18, find the smallest sample size for which the margin of error of an approximate 95% confidence interval is at most 0.04.', 2, '355', 'n ≥ 1.96² × 0.18 × 0.82 ÷ 0.04² = 354.4, so n = 355. One mark for the inequality, one for rounding up.'],
      ['j', 'Students earn 3 points for finishing in under 10 minutes, 2 points for finishing in 10 to 15 minutes and 0 points otherwise. Find the expected number of points per student, correct to two decimal places, and the variance, correct to three decimal places.', 3, 'E = 1.98; Var = 0.672', 'Pr(T < 10) = 0.2119 and Pr(10 < T < 15) = 0.6731. E = 3 × 0.2119 + 2 × 0.6731 = 1.98. E(X²) = 9 × 0.2119 + 4 × 0.6731 = 4.599, so Var = 4.599 − 1.9817² = 0.672. One mark for the distribution, one each for E and Var.'],
    ]),
  ex2(CA, 'advanced',
    'The concentration of a medication in a patient’s blood, C mg/L, t hours after a dose is taken is modelled by C(t) = 20te^(−0.5t), t ≥ 0. The graph of y = C(t) is shown below.',
    [
      ['a', 'Show that C′(t) = 10e^(−0.5t)(2 − t).', 1, 'C′(t) = 20e^(−0.5t) − 10te^(−0.5t) = 10e^(−0.5t)(2 − t)', 'Product rule.'],
      ['b', 'Find the maximum concentration, correct to three decimal places, and the time at which it occurs.', 2, '14.715 mg/L at t = 2 hours', 'C′(t) = 0 at t = 2, and C(2) = 40e⁻¹ = 14.715. One mark for the time, one for the value.'],
      ['c', 'The medication is effective when the concentration is at least 8 mg/L. Find, correct to three decimal places, the times between which the medication is effective.', 2, 't = 0.518 to t = 5.085 hours', 'Solve 20te^(−0.5t) = 8 with a CAS: t = 0.518 and t = 5.085. One mark for each time.'],
      ['d', 'Find the average concentration over the first 6 hours, correct to three decimal places.', 2, '10.678 mg/L', '(1/6)∫ 20te^(−0.5t) dt from 0 to 6 = (80 − 320e⁻³) ÷ 6 = 10.678. One mark for the integral, one for the value.'],
      ['e', 'Find the rate of change of the concentration 4 hours after the dose, correct to three decimal places.', 1, '−2.707 mg/L per hour', 'C′(4) = 10e⁻²(2 − 4) = −20e⁻² = −2.707: the concentration is falling.'],
      ['f', 'A second, identical dose is taken 4 hours after the first, so that for t ≥ 4 the concentration is D(t) = C(t) + C(t − 4). Find D(4), correct to three decimal places.', 1, '10.827 mg/L', 'D(4) = C(4) + C(0) = 80e⁻² + 0 = 10.827.'],
      ['g', 'Show that the maximum of D occurs at t = (6e² + 2)/(e² + 1), and find the maximum concentration, correct to two decimal places.', 3, 't = 5.523 hours; maximum 21.20 mg/L', 'D′(t) = 10e^(−0.5t)(2 − t) + 10e^(−0.5(t − 4))(6 − t) = 0. Dividing by 10e^(−0.5t) gives (2 − t) + e²(6 − t) = 0, so t = (6e² + 2)/(e² + 1) = 5.523, and D(5.523) = 21.20. One mark for the derivative, one for solving, one for the value.'],
      ['h', 'Find, correct to two decimal places, the time at which the total concentration falls back below 8 mg/L.', 2, 't = 9.74 hours', 'Solve C(t) + C(t − 4) = 8 for t > 5.523 with a CAS: t = 9.74. One mark for the equation, one for the value.'],
      ['i', 'Explain why a single dose never produces a concentration higher than 15 mg/L.', 1, 'The maximum of C is 40e⁻¹ ≈ 14.72 mg/L, which is less than 15.', 'The only stationary point, at t = 2, is the global maximum for t ≥ 0.'],
    ],
    { diagram: { kind: 'function_graph', title: 'Concentration after one dose', xMin: 0, xMax: 14, yMin: 0, yMax: 16, xStep: 2, yStep: 2, xLabel: 't (hours)', yLabel: 'C (mg/L)', curves: [{ points: sample(t => 20 * t * Math.exp(-0.5 * t), 0, 14, 56), label: 'y = C(t)' }], points: [{ x: 2, y: 14.715, label: '(2, 14.715)' }] } }),
]
