// VCE Specialist Mathematics Unit 3 & 4 — Practice set 5.
import { SM, sample } from './sm-common.mjs'
const { ex1, mc, ex2, PF, FG, CX, CA, VE, ST } = SM(5)

export const ITEMS = [
  // ════════════════ Examination 1 — technology-free (40 marks) ════════════════
  ex1(PF, 'advanced', 'This question is about divisibility and proof by induction.', [
    ['a', 'Prove that n³ − n is divisible by 6 for every integer n.', 2, 'n³ − n = (n − 1)n(n + 1), a product of three consecutive integers, so it has a factor divisible by 2 and a factor divisible by 3.', 'One mark for the factorisation, one for the divisibility argument.'],
    ['b', 'Prove by mathematical induction that 1 × 2 + 2 × 3 + … + n(n + 1) = n(n + 1)(n + 2)/3 for all n ∈ N.', 2, 'Base: 2 = 1 × 2 × 3/3. Step: k(k + 1)(k + 2)/3 + (k + 1)(k + 2) = (k + 1)(k + 2)(k + 3)/3.', 'One mark for the base case and assumption, one for the inductive step.'],
  ]),
  ex1(CX, 'proficient', 'Let z = 2cis(π/6) and w = cis(π/4).', [
    ['a', 'Find zw in polar form.', 1, '2cis(5π/12)', 'Multiply moduli, add arguments.'],
    ['b', 'Find z/w in polar form.', 1, '2cis(−π/12)', 'Divide moduli, subtract arguments.'],
    ['c', 'Show that z³ is purely imaginary, and find it.', 2, 'z³ = 8cis(π/2) = 8i', 'De Moivre’s theorem gives argument 3 × π/6 = π/2. One mark for the method, one for the value.'],
  ]),
  ex1(FG, 'proficient', 'Let f: R \\ {0} → R, f(x) = (x² + 4)/x².', [
    ['a', 'Write down the equations of the asymptotes of the graph of f.', 2, 'x = 0 and y = 1', 'f(x) = 1 + 4/x². One mark for each asymptote.'],
    ['b', 'State the range of f.', 1, '(1, ∞)', '4/x² takes every positive value and never 0.'],
    ['c', 'Describe the symmetry of the graph of f.', 1, 'It is symmetric about the y-axis, because f(−x) = f(x).', 'f is an even function.'],
  ]),
  ex1(CA, 'proficient', 'This question is about integration.', [
    ['a', 'Use integration by parts to find ∫ x cos(x) dx.', 2, 'x sin(x) + cos(x) + c', 'u = x, dv = cos(x) dx: x sin(x) − ∫ sin(x) dx. One mark for the set-up, one for the answer.'],
    ['b', 'Evaluate ∫ eˣ/(1 + eˣ) dx from x = 0 to x = logₑ(2).', 2, 'logₑ(3/2)', 'An antiderivative is logₑ(1 + eˣ): logₑ(3) − logₑ(2). One mark for the antiderivative, one for the value.'],
  ]),
  ex1(CA, 'proficient', 'Consider the differential equation dy/dx = (y − 1)², where y(0) = 2.', [
    ['a', 'Solve the differential equation for y in terms of x.', 3, 'y = 1 + 1/(1 − x)', '∫ (y − 1)⁻² dy = ∫ dx gives −1/(y − 1) = x + c; y(0) = 2 gives c = −1, so y − 1 = 1/(1 − x). One mark each for separating, integrating and the constant.'],
    ['b', 'State the value of x at which the solution is undefined.', 1, 'x = 1', 'The denominator 1 − x is zero.'],
  ]),
  ex1(VE, 'proficient', 'Consider the points A(1, 0, −1), B(3, 2, 1) and C(0, −1, −2).', [
    ['a', 'Show that A, B and C are collinear.', 2, 'AB = 2i + 2j + 2k and AC = −i − j − k = −(1/2)AB, with the common point A.', 'One mark for the vectors, one for the conclusion.'],
    ['b', 'Find the vector of magnitude 6 in the direction of 2i − j + 2k.', 2, '4i − 2j + 4k', '|2i − j + 2k| = 3, so multiply by 6/3 = 2. One mark for the unit vector, one for the answer.'],
  ]),
  ex1(ST, 'proficient', 'A random variable X takes the values 0 and 2, each with probability 1/2. Random samples of 25 independent values of X are taken.', [
    ['a', 'Find the mean and standard deviation of the sample mean X̄.', 2, 'Mean 1, sd 1/5', 'E(X) = 1 and Var(X) = E(X²) − 1 = 2 − 1 = 1, so sd(X̄) = 1/√25. One mark each.'],
    ['b', 'Using a normal approximation and Pr(Z < 1.5) ≈ 0.933, estimate Pr(X̄ > 1.3).', 1, '0.067', 'z = 0.3/0.2 = 1.5, so the probability is about 1 − 0.933.'],
    ['c', 'Name the result that justifies using a normal approximation for X̄.', 1, 'The central limit theorem', 'X itself is far from normal, but the mean of a large sample is approximately normal.'],
  ]),
  ex1(CA, 'proficient', 'A particle oscillates in a straight line with position x(t) = 2sin(3t) metres at time t seconds.', [
    ['a', 'Find the velocity and acceleration, and show that the acceleration is −9x.', 2, 'v = 6cos(3t), a = −18sin(3t) = −9x', 'One mark for the derivatives, one for relating a to x.'],
    ['b', 'Find the maximum speed of the particle.', 1, '6 m/s', 'The amplitude of 6cos(3t).'],
    ['c', 'Find the first time after t = 0 at which the particle is at rest.', 1, 't = π/6', 'cos(3t) = 0 first when 3t = π/2.'],
  ]),
  ex1(CX, 'proficient', 'This question is about the solutions of z³ + 8 = 0.', [
    ['a', 'Factorise z³ + 8 into a linear factor and a real quadratic factor.', 1, '(z + 2)(z² − 2z + 4)', 'Sum of cubes.'],
    ['b', 'Hence find all solutions of z³ + 8 = 0.', 2, 'z = −2 and z = 1 ± √3i', 'z² − 2z + 4 = 0 gives z = 1 ± √(−3). One mark for each part of the solution set.'],
    ['c', 'Show that the solutions lie on a circle centred at the origin.', 1, '|−2| = |1 ± √3i| = 2', 'All three have modulus 2.'],
  ]),
  ex1(CA, 'proficient', 'Let R be the region enclosed by the graphs of y = x and y = x².', [
    ['a', 'Find the area of R.', 1, '1/6', '∫ (x − x²) dx from 0 to 1.'],
    ['b', 'R is rotated about the x-axis. Find the volume of the solid formed.', 2, '2π/15', 'V = π∫ (x² − x⁴) dx from 0 to 1 = π(1/3 − 1/5). One mark for the integral, one for the value.'],
    ['c', 'Show that sin⁻¹(x) + cos⁻¹(x) is constant for −1 < x < 1.', 1, 'Its derivative is 1/√(1 − x²) − 1/√(1 − x²) = 0.', 'The constant is π/2.'],
  ]),

  // ════════════════ Examination 2 — Section A (20 multiple choice) ════════════════
  mc(PF, 'developing', 'The implication "if P then Q" is false exactly when',
    ['P is true and Q is false', 'P is false and Q is true', 'P and Q are both false', 'P and Q are both true', 'Q is false'],
    'An implication only fails when the hypothesis holds and the conclusion does not.'),
  mc(PF, 'developing', 'A proof by contradiction that √3 is irrational begins by assuming that',
    ['√3 = p/q for integers p and q with no common factor', '√3 is irrational', '√3 is an integer', '3 is not prime', '√3 = p/q where p and q are both even'],
    'A proof by contradiction assumes the opposite of what is to be proved and derives a contradiction.'),
  mc(FG, 'proficient', 'The oblique asymptote of the graph of y = (x² − 1)/(x + 2) has equation',
    ['y = x − 2', 'y = x + 2', 'y = x', 'y = x − 1', 'y = 1'],
    'x² − 1 = (x + 2)(x − 2) + 3.'),
  mc(FG, 'developing', 'The number of vertical asymptotes of the graph of y = 1/(x³ − x) is',
    ['3', '0', '1', '2', '4'],
    'x³ − x = x(x − 1)(x + 1) is zero at x = 0, 1 and −1.'),
  mc(FG, 'proficient', 'For real constants a and b, the range of the function y = 1/(x − a)² + b, x ≠ a, is',
    ['(b, ∞)', '[b, ∞)', 'R \\ {b}', '(a, ∞)', 'R'],
    '1/(x − a)² takes every positive value but never 0, so y takes every value greater than b.'),
  mc(CX, 'developing', 'The set {z : |z − 1 + i| = 2} is a circle with centre',
    ['1 − i', '−1 + i', '1 + i', '2', '−1 − i'],
    '|z − (1 − i)| = 2 is the circle of radius 2 centred at 1 − i.'),
  mc(CX, 'developing', 'The real part of 1/(1 + i) is',
    ['1/2', '1', '−1/2', '0', '√2/2'],
    '1/(1 + i) = (1 − i)/2.'),
  mc(CX, 'developing', 'If z = cis(π/8), then z⁴ is equal to',
    ['i', '1', '−1', '−i', 'cis(π/32)'],
    'z⁴ = cis(π/2) = i.'),
  mc(CA, 'developing', 'For −3 < x < 3, an antiderivative of 1/√(9 − x²) is',
    ['sin⁻¹(x/3)', '(1/3)sin⁻¹(x/3)', '3sin⁻¹(x/3)', 'cos⁻¹(x/3)', 'tan⁻¹(x/3)'],
    'd/dx(sin⁻¹(x/a)) = 1/√(a² − x²).'),
  mc(CA, 'proficient', '∫ x sin(x) dx from x = 0 to x = π is equal to',
    ['π', '0', '2', '−π', 'π/2'],
    'By parts, an antiderivative is sin(x) − x cos(x), which gives (0 + π) − 0.'),
  mc(CA, 'proficient', 'The derivative of cos³(2x) with respect to x is',
    ['−6cos²(2x)sin(2x)', '3cos²(2x)', '−3cos²(2x)sin(2x)', '6cos²(2x)sin(2x)', '−6sin²(2x)cos(2x)'],
    'Chain rule: 3cos²(2x) × (−sin(2x)) × 2.'),
  mc(CA, 'proficient', 'The solution of dy/dx = −y/x, x > 0, whose graph passes through (1, 2) is',
    ['y = 2/x', 'y = 2x', 'y = −2x + 4', 'y = 2e⁻ˣ⁺¹', 'y = x + 1'],
    '∫ (1/y) dy = −∫ (1/x) dx gives logₑ(y) = −logₑ(x) + c, so y = A/x with A = 2.'),
  mc(CA, 'developing', 'A particle moves in a straight line with velocity v = 3 − 2t m/s, and its position at t = 0 is 1 m. Its position when t = 2 is',
    ['3 m', '1 m', '2 m', '5 m', '−1 m'],
    'x(t) = 1 + 3t − t², so x(2) = 1 + 6 − 4 = 3.'),
  mc(CA, 'proficient', 'The region under the graph of y = 1/x for 1 ≤ x ≤ 2 is rotated about the x-axis. The volume of the solid formed is',
    ['π/2', 'πlogₑ(2)', 'π', 'π/4', '2π'],
    'V = π∫ x⁻² dx from 1 to 2 = π(1 − 1/2).'),
  mc(VE, 'developing', 'For any vectors a and b, a · (a × b) is equal to',
    ['0', '|a|²|b|', 'a × b', '|a||b|', '1'],
    'a × b is perpendicular to a, so its dot product with a is zero.'),
  mc(VE, 'proficient', 'Vectors a and b have |a| = 3, |b| = 4 and an angle of 60° between them. |a + b| is equal to',
    ['√37', '7', '5', '√13', '37'],
    '|a + b|² = 9 + 16 + 2 × 3 × 4 × cos(60°) = 37.'),
  mc(VE, 'developing', 'The line r(t) = (i + 2k) + t(i + j + k) meets the plane z = 0 at the point',
    ['(−1, −2, 0)', '(1, 0, 0)', '(3, 2, 0)', '(−2, −1, 0)', '(0, −1, 0)'],
    'z = 2 + t = 0 gives t = −2, so the point is (1 − 2, 0 − 2, 0).'),
  mc(VE, 'developing', 'A particle has position vector r(t) = t³i + 2tj + sin(t)k. Its velocity at t = 0 is',
    ['2j + k', '0', 'i + 2j + k', '2j', '3i + 2j + k'],
    'ṙ(t) = 3t²i + 2j + cos(t)k, which is 2j + k at t = 0.'),
  mc(ST, 'proficient', 'X is normally distributed with mean 50 and variance 9. For random samples of 16, Pr(X̄ < 49.25), correct to four decimal places, is',
    ['0.1587', '0.0228', '0.3085', '0.4013', '0.8413'],
    'sd(X̄) = 3/4 = 0.75, so Pr(X̄ < 49.25) = Pr(Z < −1) = 0.1587. Using variance 9 as if it were the sd gives the wrong spread.'),
  mc(ST, 'developing', 'A hypothesis test is carried out at the 1% level of significance. The probability of a type I error is',
    ['0.01', '0.05', '0.99', '0.10', 'unknown without the sample size'],
    'The significance level is the probability of rejecting H₀ when it is true.'),

  // ════════════════ Examination 2 — Section B (60 marks) ════════════════
  ex2(CX, 'advanced', 'Let P(z) = z³ − (2 + i)z² + (1 + 2i)z − i, where z ∈ C.', [
    ['a', 'Show that z = i is a solution of P(z) = 0.', 1, '−i + (2 + i) + (1 + 2i)i − i = −i + 2 + i + i − 2 − i = 0', 'i² = −1 and i³ = −i.'],
    ['b', 'Hence express P(z) as a product of linear factors.', 3, 'P(z) = (z − i)(z − 1)²', 'Dividing by z − i gives z² − 2z + 1 = (z − 1)². One mark for the division, one for the quadratic, one for factorising it.'],
    ['c', 'Explain why the conjugate of i is not a solution of P(z) = 0.', 1, 'The conjugate root theorem needs real coefficients, and P has non-real coefficients.', 'Direct check: P(−i) ≠ 0.'],
    ['d', 'Find the area of the triangle with vertices 0, 1 and i in the complex plane.', 1, '1/2', 'A right triangle with legs 1 and 1.'],
    ['e', 'Solve z⁴ = −4 for z ∈ C, giving the solutions in Cartesian form.', 2, 'z = ±1 ± i', '−4 = 4cis(π), so z = √2cis(π/4 + kπ/2). One mark for the polar method, one for the solutions.'],
    ['f', 'Find the area of the square whose vertices are the solutions in part e.', 2, '4', 'The vertices (±1, ±1) form a square of side 2. One mark for the side length, one for the area.'],
  ]),
  ex2(CA, 'advanced', 'A tank holds 100 L of water in which 20 kg of salt is dissolved. Pure water flows in at 5 L per minute and the well-mixed solution flows out at 5 L per minute. Let Q kg be the amount of salt in the tank after t minutes.', [
    ['a', 'Explain why dQ/dt = −Q/20.', 2, 'Salt leaves at (Q/100 kg per L) × 5 L per min = Q/20 kg per min, and no salt enters.', 'The volume stays at 100 L. One mark for the concentration, one for the rate.'],
    ['b', 'Solve the differential equation.', 2, 'Q = 20e^(−t/20)', 'Exponential decay with Q(0) = 20. One mark for the form, one for the constant.'],
    ['c', 'Find the time taken for the amount of salt to fall to 5 kg, correct to two decimal places.', 1, '27.73 minutes', 't = 20logₑ(4).'],
    ['d', 'Instead, brine containing 0.1 kg of salt per litre flows in at 5 L per minute. Show that dQ/dt = 0.5 − Q/20 and solve it, given Q(0) = 20.', 3, 'Q = 10 + 10e^(−t/20)', 'Salt now enters at 0.1 × 5 = 0.5 kg per minute. dQ/dt = (10 − Q)/20, so ∫ dQ/(10 − Q) = ∫ dt/20 gives −logₑ|10 − Q| = t/20 + c, that is Q − 10 = Ae^(−t/20), and Q(0) = 20 gives A = 10. One mark for the equation, one for solving, one for the constant.'],
    ['e', 'State the amount of salt in the tank in the long run.', 1, '10 kg', 'e^(−t/20) → 0; the concentration approaches that of the incoming brine.'],
    ['f', 'Find the time at which the tank holds 15 kg of salt, correct to two decimal places.', 1, '13.86 minutes', '10e^(−t/20) = 5 gives t = 20logₑ(2).'],
  ]),
  ex2(VE, 'advanced', 'A ball is kicked from ground level with speed 20 m/s at an angle of 30° to the horizontal. Its acceleration is −9.8j m/s², where i and j are unit vectors horizontally forward and vertically up.', [
    ['a', 'Write down the initial velocity vector.', 1, '10√3i + 10j', '20cos(30°) = 10√3 and 20sin(30°) = 10.'],
    ['b', 'Show that the position vector of the ball is r(t) = 10√3ti + (10t − 4.9t²)j.', 2, 'Integrate the acceleration twice, using the initial velocity and r(0) = 0.', 'One mark for the velocity, one for the position.'],
    ['c', 'Find the time of flight, correct to two decimal places.', 1, '2.04 s', '10t − 4.9t² = 0 gives t = 10/4.9.'],
    ['d', 'Find the horizontal distance travelled, correct to two decimal places.', 1, '35.35 m', '10√3 × 10/4.9.'],
    ['e', 'Find the maximum height, correct to two decimal places.', 1, '5.10 m', 'At t = 10/9.8, the height is 100/19.6.'],
    ['f', 'Find the speed of the ball as it lands.', 1, '20 m/s', 'By symmetry of the trajectory, the vertical velocity is −10 at landing, so the speed is again √(300 + 100).'],
    ['g', 'A fence 2 m high stands 30 m from the kicking point. Show that the ball clears the fence and find by how much, correct to two decimal places.', 2, 'Height at the fence ≈ 2.62 m, clearing it by 0.62 m', 'x = 30 when t = √3, and then y = 10√3 − 4.9 × 3 = 2.62. One mark for the time, one for the height and conclusion.'],
    ['h', 'Find the angle the velocity makes with the horizontal when t = 1, correct to two decimal places.', 1, '0.66° above the horizontal', 'ṙ(1) = 10√3i + 0.2j, so tan(θ) = 0.2/(10√3).'],
  ]),
  ex2(VE, 'advanced', 'The planes Π₁: x + y + z = 6, Π₂: x − y + 3z = 8 and Π₃: 2x + y − z = 1 are given.', [
    ['a', 'Show that the three planes meet at a single point, and find it.', 3, '(1, 2, 3)', 'Solving the system (for example by elimination or with a matrix on a CAS) gives x = 1, y = 2, z = 3, and the normals are not coplanar (the determinant is 8 ≠ 0), so the point is unique. One mark for method, one for the point, one for uniqueness.'],
    ['b', 'Find the acute angle between Π₁ and Π₂, correct to two decimal places.', 2, '58.52°', 'cos(θ) = (1 − 1 + 3)/(√3 × √11) = 3/√33. One mark for the method, one for the angle.'],
    ['c', 'Find a vector equation of the line of intersection of Π₁ and Π₃.', 2, 'r(t) = (i + 2j + 3k) + t(−2i + 3j − k)', 'The direction is (1, 1, 1) × (2, 1, −1) = (−2, 3, −1), and (1, 2, 3) lies on both planes. One mark for the direction, one for the equation.'],
    ['d', 'Find the distance from the origin to Π₁.', 1, '2√3', '6/√3.'],
    ['e', 'Find the volume of the tetrahedron bounded by Π₁ and the three coordinate planes.', 2, '36', 'Π₁ meets the axes at 6, so V = (1/6) × 6 × 6 × 6. One mark for the intercepts, one for the volume.'],
  ]),
  ex2(ST, 'advanced', 'Sam’s journey to work is a bus ride followed by a walk. The bus time X is normally distributed with mean 35 minutes and standard deviation 5 minutes, and the walking time Y is independently normally distributed with mean 10 minutes and standard deviation 2 minutes.', [
    ['a', 'State the distribution of the total journey time T = X + Y, including its mean and standard deviation correct to three decimal places.', 2, 'T ~ N(45, 29): mean 45 min, sd 5.385 min', 'Means add and variances add: 25 + 4 = 29. One mark for the mean, one for the sd.'],
    ['b', 'Find Pr(T > 50), correct to four decimal places.', 1, '0.1766', 'z = 5/√29.'],
    ['c', 'Find the probability that Sam’s total travel time over five independent days exceeds 240 minutes, correct to four decimal places.', 2, '0.1064', 'The weekly total has mean 225 and variance 5 × 29 = 145, so Pr(Z > 15/√145) = 0.1064. One mark for the distribution, one for the value.'],
    ['d', 'A new bus route is claimed to be faster. Over 20 days the mean bus time is 33.1 minutes. Assuming σ = 5, find the p-value for a test of H₀: μ = 35 against H₁: μ < 35, correct to four decimal places.', 2, '0.0446', 'z = (33.1 − 35)/(5/√20) = −1.699. One mark for the statistic, one for the p-value.'],
    ['e', 'State the conclusion at the 5% level of significance.', 1, 'Reject H₀: there is evidence the new route is faster on average.', 'p < 0.05.'],
    ['f', 'Find an approximate 99% confidence interval for the mean bus time on the new route, correct to two decimal places.', 2, '(30.22, 35.98)', '33.1 ± 2.5758 × 5/√20. One mark for the z value, one for the interval.'],
  ]),
  ex2(CA, 'advanced', 'Let f: R → R, f(x) = e^(−x²/2). The graph of y = f(x) is shown below.', [
    ['a', 'Find f′(x) and f″(x).', 2, 'f′(x) = −xe^(−x²/2); f″(x) = (x² − 1)e^(−x²/2)', 'Chain rule, then product rule. One mark each.'],
    ['b', 'Find the coordinates of the points of inflection.', 1, '(±1, e^(−1/2))', 'f″ changes sign at x = ±1.'],
    ['c', 'Find the area of the region under the graph of f between x = −1 and x = 1, correct to four decimal places.', 1, '1.7112', 'Numerical integration.'],
    ['d', 'The region under the graph of f between x = 0 and x = 1 is rotated about the x-axis. Find the volume of the solid formed, correct to three decimal places.', 2, '2.346', 'V = π∫ e^(−x²) dx from 0 to 1 = π × 0.7468. One mark for the integral, one for the value.'],
    ['e', 'Find the length of the curve from x = 0 to x = 1, correct to three decimal places.', 2, '1.089', '∫ √(1 + x²e^(−x²)) dx from 0 to 1. One mark for the integral, one for the value.'],
    ['f', 'Find the equation of the tangent at x = 1 and the point where it meets the x-axis.', 2, 'y = e^(−1/2)(2 − x); it meets the x-axis at (2, 0)', 'f(1) = e^(−1/2) and f′(1) = −e^(−1/2). One mark for the equation, one for the intercept.'],
  ], { diagram: { kind: 'function_graph', title: 'y = e^(−x²/2)', xMin: -3, xMax: 3, yMin: 0, yMax: 1.1, xStep: 1, yStep: 0.2, curves: [{ points: sample(x => Math.exp(-x * x / 2), -3, 3, 60) }] } }),
]
