// VCE Specialist Mathematics Unit 3 & 4 — Practice set 4.
import { SM, sample } from './sm-common.mjs'
const { ex1, mc, ex2, PF, FG, CX, CA, VE, ST } = SM(4)

export const ITEMS = [
  // ════════════════ Examination 1 — technology-free (40 marks) ════════════════
  ex1(PF, 'advanced', 'This question is about induction and the contrapositive.', [
    ['a', 'Prove by mathematical induction that n! ≥ 2ⁿ⁻¹ for all n ∈ N.', 3, 'Base: 1! = 1 = 2⁰. Step: (k + 1)! = (k + 1)k! ≥ (k + 1)2ᵏ⁻¹ ≥ 2 × 2ᵏ⁻¹ = 2ᵏ, since k + 1 ≥ 2.', 'One mark for the base case, one for using the assumption, one for the inequality k + 1 ≥ 2 and the conclusion.'],
    ['b', 'Write down the contrapositive of the statement "If n is a prime number greater than 2, then n is odd".', 1, 'If n is even, then n is not a prime number greater than 2.', 'Negate and swap: not Q ⇒ not P.'],
  ]),
  ex1(CX, 'proficient', 'This question is about square roots of complex numbers.', [
    ['a', 'Find the square roots of −5 + 12i, in Cartesian form.', 3, '2 + 3i and −2 − 3i', '(a + bi)² = −5 + 12i gives a² − b² = −5 and ab = 6, so a = 2, b = 3 (or both negative). One mark for the two equations, one for solving, one for both roots.'],
    ['b', 'Hence solve z² − 2z + 6 − 12i = 0 for z ∈ C.', 1, 'z = 3 + 3i or z = −1 − 3i', '(z − 1)² = −5 + 12i, so z = 1 ± (2 + 3i).'],
  ]),
  ex1(FG, 'proficient', 'Let f(x) = 2x/(x² − 4), x ≠ ±2.', [
    ['a', 'Write down the equations of the asymptotes of the graph of f.', 2, 'x = 2, x = −2 and y = 0', 'One mark for the vertical asymptotes, one for the horizontal.'],
    ['b', 'Show that the graph of f has no stationary points.', 1, 'f′(x) = −2(x² + 4)/(x² − 4)², which is never zero.', 'The numerator −2x² − 8 is always negative.'],
    ['c', 'Explain why the graph is symmetric about the origin.', 1, 'f(−x) = −2x/(x² − 4) = −f(x), so f is odd.', 'An odd function has rotational symmetry about the origin.'],
  ]),
  ex1(CA, 'proficient', 'This question is about partial fractions and a trigonometric integral.', [
    ['a', 'Express (3x + 1)/((x − 1)(x + 1)) in partial fractions.', 1, '2/(x − 1) + 1/(x + 1)', '3x + 1 = A(x + 1) + B(x − 1); x = 1 gives A = 2 and x = −1 gives B = 1.'],
    ['b', 'Hence evaluate ∫ (3x + 1)/((x − 1)(x + 1)) dx from x = 2 to x = 3, expressing the answer as a single logarithm.', 2, 'logₑ(16/3)', '[2logₑ(x − 1) + logₑ(x + 1)] from 2 to 3 = 2logₑ(2) + logₑ(4) − logₑ(3). One mark for the antiderivative, one for simplifying.'],
    ['c', 'Find ∫ sec²(3x) dx.', 1, '(1/3)tan(3x) + c', 'd/dx(tan(3x)) = 3sec²(3x).'],
  ]),
  ex1(CA, 'proficient', 'This question is about differential equations.', [
    ['a', 'Verify that y = xeˣ satisfies dy/dx − y = eˣ.', 2, 'dy/dx = eˣ + xeˣ, so dy/dx − y = eˣ.', 'One mark for the derivative, one for the verification.'],
    ['b', 'Solve dy/dx = y cos(x), given that y(0) = 1.', 2, 'y = e^(sin(x))', '∫ (1/y) dy = ∫ cos(x) dx gives logₑ(y) = sin(x) + c, and c = 0. One mark for separating and integrating, one for the solution.'],
  ]),
  ex1(VE, 'proficient', 'Let a = i + mj + 3k and b = 2i − j + mk, where m is a real constant.', [
    ['a', 'Find the value of m for which a and b are perpendicular.', 1, 'm = −1', 'a · b = 2 − m + 3m = 2 + 2m = 0.'],
    ['b', 'For this value of m, find a × b.', 2, '4i + 7j + k', 'a = (1, −1, 3) and b = (2, −1, −1): ((−1)(−1) − 3(−1), 3 × 2 − 1 × (−1), 1 × (−1) − (−1) × 2) = (4, 7, 1). One mark for method, one for the vector.'],
    ['c', 'Hence find the area of the parallelogram with sides a and b.', 1, '√66', '|a × b| = √(16 + 49 + 1).'],
  ]),
  ex1(ST, 'proficient', 'The masses of eggs are independent with mean 60 g and standard deviation 4 g. An empty carton has a fixed mass of 30 g and holds 12 eggs.', [
    ['a', 'Find the mean and standard deviation of the mass of a full carton.', 2, 'Mean 750 g, sd 8√3 g', 'Mean 12 × 60 + 30. The variance is 12 × 16 = 192, so the sd is √192 = 8√3; the fixed 30 g adds no variance. One mark each.'],
    ['b', 'Find the standard deviation of the mean mass of a random sample of 100 eggs.', 1, '0.4 g', '4/√100.'],
    ['c', 'State the approximate distribution of the sample mean in part b, and the theorem that justifies it.', 1, 'Approximately normal, by the central limit theorem.', 'For a large sample the sample mean is approximately normal whatever the distribution of egg mass.'],
  ]),
  ex1(CA, 'advanced', 'A particle moving in a straight line slows down so that dv/dt = −v², where v m/s is its velocity at time t seconds. Initially v = 2.', [
    ['a', 'Find v in terms of t.', 2, 'v = 2/(2t + 1)', '∫ −v⁻² dv = ∫ dt gives 1/v = t + c, and c = 1/2. One mark for integrating, one for the rule.'],
    ['b', 'Find the distance travelled in the first second.', 2, 'logₑ(3) m', '∫ 2/(2t + 1) dt from 0 to 1 = logₑ(3). One mark for the integral, one for the value.'],
  ]),
  ex1(CX, 'proficient', 'Let S = {z : |z| ≤ 2, 0 ≤ Arg(z) ≤ π/3}.', [
    ['a', 'Find the area of the region S.', 2, '2π/3', 'S is a sector of radius 2 and angle π/3: (1/2)(2²)(π/3). One mark for identifying the sector, one for the area.'],
    ['b', 'Find the complex number in S with the largest imaginary part.', 2, '1 + √3i', 'The imaginary part is |z|sin(Arg z), which is largest at |z| = 2 and Arg(z) = π/3: 2cis(π/3). One mark for the argument, one for the number.'],
  ]),
  ex1(CA, 'proficient', 'This question is about areas and volumes involving circular functions.', [
    ['a', 'Find the area of the region bounded by the graph of y = 1/√(4 − x²), the coordinate axes and the line x = 1.', 2, 'π/6', '∫ 1/√(4 − x²) dx from 0 to 1 = sin⁻¹(1/2) = π/6. One mark for the antiderivative, one for the value.'],
    ['b', 'The region bounded by the graph of y = sec(x), the coordinate axes and the line x = π/4 is rotated about the x-axis. Find the volume of the solid formed.', 2, 'π', 'V = π∫ sec²(x) dx from 0 to π/4 = π tan(π/4). One mark for the integral, one for the value.'],
  ]),

  // ════════════════ Examination 2 — Section A (20 multiple choice) ════════════════
  mc(PF, 'proficient', 'The statement "n² − n + 41 is prime for every natural number n" is shown to be false by taking n equal to',
    ['41', '1', '2', '10', '40'],
    'For n = 41 the expression is 41² − 41 + 41 = 41², which is not prime. For n = 1, 2, 10 and 40 it gives the primes 41, 43, 131 and 1601.'),
  mc(PF, 'developing', 'Given that the statement "If it is raining, then the ground is wet" is true, which one of the following must also be true?',
    ['If the ground is not wet, then it is not raining.', 'If the ground is wet, then it is raining.', 'If it is not raining, then the ground is not wet.', 'It is raining.', 'The ground is wet.'],
    'A true statement always has a true contrapositive. The converse and inverse can fail (the ground might be wet from a sprinkler).'),
  mc(FG, 'developing', 'The graph of y = 1/(x² + 2x + 2) has a maximum at the point',
    ['(−1, 1)', '(1, 1/5)', '(0, 1/2)', '(−1, 1/2)', '(−2, 1/2)'],
    'x² + 2x + 2 = (x + 1)² + 1 is least, with value 1, at x = −1.'),
  mc(FG, 'proficient', 'The oblique asymptote of the graph of y = (2x² + 3x − 1)/(x + 1) has equation',
    ['y = 2x + 1', 'y = 2x + 3', 'y = 2x − 1', 'y = 2x', 'y = x + 1'],
    '2x² + 3x − 1 = (x + 1)(2x + 1) − 2, so y = 2x + 1 − 2/(x + 1).'),
  mc(FG, 'proficient', 'In partial fractions, 1/(x(x + 2)) is equal to',
    ['1/(2x) − 1/(2(x + 2))', '1/x − 1/(x + 2)', '1/(2x) + 1/(2(x + 2))', '2/x − 2/(x + 2)', '1/(x + 2) − 1/x'],
    '1 = A(x + 2) + Bx: x = 0 gives A = 1/2 and x = −2 gives B = −1/2.'),
  mc(CX, 'proficient', 'If z = 1 + √3i, then z̄/z is equal to',
    ['−1/2 − (√3/2)i', '−1/2 + (√3/2)i', '1/2 − (√3/2)i', '1', '−1'],
    'z = 2cis(π/3) and z̄ = 2cis(−π/3), so z̄/z = cis(−2π/3).'),
  mc(CX, 'developing', 'The set of points {z : Arg(z − 1) = π/4} in the complex plane is',
    ['a ray starting at (1, 0), not including it, making an angle of π/4 with the positive real axis', 'the line y = x − 1', 'a circle with centre 1', 'a ray starting at the origin making an angle of π/4 with the positive real axis', 'the line y = x'],
    'Arg(z − 1) measures the direction from the point 1 to z, and Arg is undefined at z = 1 itself. Only half of the line y = x − 1 is included.'),
  mc(CX, 'proficient', 'Let z = 2cis(π/5). The smallest positive integer n for which zⁿ is a real number is',
    ['5', '2', '3', '4', '10'],
    'zⁿ = 2ⁿcis(nπ/5) is real when nπ/5 is a multiple of π.'),
  mc(CA, 'developing', 'An antiderivative of 2/(4 + x²) is',
    ['tan⁻¹(x/2)', '2tan⁻¹(x/2)', '(1/2)tan⁻¹(x/2)', 'logₑ(4 + x²)', 'tan⁻¹(2x)'],
    '∫ 2/(4 + x²) dx = 2 × (1/2)tan⁻¹(x/2).'),
  mc(CA, 'proficient', 'An antiderivative of logₑ(x), for x > 0, is',
    ['xlogₑ(x) − x', '1/x', 'xlogₑ(x)', '(logₑ(x))²/2', 'xlogₑ(x) + x'],
    'By parts with u = logₑ(x), dv = dx: xlogₑ(x) − ∫ 1 dx.'),
  mc(CA, 'developing', 'The derivative of x²e⁻ˣ is',
    ['e⁻ˣ(2x − x²)', 'e⁻ˣ(2x + x²)', '−2xe⁻ˣ', '2xe⁻ˣ', 'e⁻ˣ(x² − 2x)'],
    'Product rule: 2xe⁻ˣ − x²e⁻ˣ.'),
  mc(CA, 'proficient', 'Every function of the form y = Ae⁻²ˣ + 3, where A is a real constant, is a solution of the differential equation',
    ['dy/dx = 6 − 2y', 'dy/dx = −2y', 'dy/dx = 2y − 6', 'dy/dx = −2y − 3', 'dy/dx = y − 3'],
    'dy/dx = −2Ae⁻²ˣ = −2(y − 3).'),
  mc(CA, 'proficient', 'Euler’s method with a step size of 0.2 is applied to dy/dx = 2y, y(0) = 1. The approximation to y(0.4) is',
    ['1.96', '1.4', '1.8', '2.23', '2.4'],
    'y(0.2) ≈ 1 + 0.2 × 2 = 1.4 and y(0.4) ≈ 1.4 + 0.2 × 2.8 = 1.96. The exact value is e^0.8 ≈ 2.23.'),
  mc(CA, 'advanced', 'A particle moves in a straight line with acceleration a = −2x m/s², where x m is its position. It is at rest when x = 3. Its speed when it passes through the origin is',
    ['3√2 m/s', '3 m/s', '6 m/s', '√6 m/s', '18 m/s'],
    'v dv/dx = −2x gives v²/2 = −x² + c, and v = 0 at x = 3 gives c = 9. So v² = 18 − 2x², and at x = 0, v = √18.'),
  mc(VE, 'developing', 'A vector equation of the line through (2, 0, −1) parallel to i − 2k is',
    ['r(t) = (2i − k) + t(i − 2k)', 'r(t) = (i − 2k) + t(2i − k)', 'r(t) = (2i − k) + t(i − 2j)', 'r(t) = t(2i − k)', 'r(t) = (2i + k) + t(i + 2k)'],
    'Position vector of a point on the line, plus t times the direction.'),
  mc(VE, 'developing', 'The points A(1, 2, 3), B(2, 4, 6) and C(3, 6, k) are collinear when k is equal to',
    ['9', '6', '7', '8', '12'],
    'AB = (1, 2, 3), so C = A + 2AB = (3, 6, 9).'),
  mc(VE, 'proficient', 'A particle has position vector r(t) = eᵗi + e⁻ᵗj, t ≥ 0. The Cartesian equation of its path is',
    ['xy = 1, x ≥ 1', 'y = x, x ≥ 1', 'x² + y² = 1', 'y = −x, x ≥ 1', 'xy = −1, x ≥ 1'],
    'x = eᵗ and y = e⁻ᵗ = 1/x; for t ≥ 0, x ≥ 1.'),
  mc(VE, 'proficient', 'The angle between the line with direction vector k and the plane x + y = 0 is',
    ['0°', '30°', '45°', '60°', '90°'],
    'The plane’s normal (1, 1, 0) is perpendicular to k, so the line is parallel to the plane.'),
  mc(ST, 'developing', 'X and Y are independent with E(X) = 2, Var(X) = 1, E(Y) = 5 and Var(Y) = 4. Var(3X − Y + 7) is equal to',
    ['13', '5', '9', '12', '20'],
    'Var(3X − Y + 7) = 9Var(X) + Var(Y) = 9 + 4; the constant adds no variance.'),
  mc(ST, 'proficient', 'For a test of H₀: μ = 100 against H₁: μ > 100 at the 5% level, with σ = 15 and a sample of 25, H₀ is rejected if the sample mean exceeds c. Correct to two decimal places, c is',
    ['104.93', '103.00', '104.20', '105.88', '124.67'],
    'c = 100 + 1.6449 × 15/√25 = 100 + 4.93. 105.88 uses the two-tailed value 1.96.'),

  // ════════════════ Examination 2 — Section B (60 marks) ════════════════
  ex2(CX, 'advanced', 'This question uses the solutions of z⁵ = 32 to find the exact value of cos(2π/5).', [
    ['a', 'Write down the five solutions of z⁵ = 32 in polar form.', 2, '2, 2cis(±2π/5), 2cis(±4π/5)', 'z = 2cis(2kπ/5) for k = 0, ±1, ±2. One mark for the modulus, one for the arguments.'],
    ['b', 'Show that z⁵ − 32 = (z − 2)(z⁴ + 2z³ + 4z² + 8z + 16).', 1, 'Expanding the right side gives z⁵ − 32.', 'All the middle terms cancel.'],
    ['c', 'Explain why the sum of the five solutions is 0.', 1, 'The coefficient of z⁴ in z⁵ − 32 is 0, and the sum of the roots is minus that coefficient.', 'Equivalently, the roots are equally spaced around a circle centred at the origin.'],
    ['d', 'Show that (z − 2cis(2π/5))(z − 2cis(−2π/5)) = z² − 4cos(2π/5)z + 4.', 2, 'The sum of the conjugate roots is 4cos(2π/5) and their product is |2cis(2π/5)|² = 4.', 'One mark for the sum, one for the product.'],
    ['e', 'Let c₁ = cos(2π/5) and c₂ = cos(4π/5). By writing z⁴ + 2z³ + 4z² + 8z + 16 = (z² − 4c₁z + 4)(z² − 4c₂z + 4) and comparing coefficients, show that c₁ = (√5 − 1)/4.', 4, 'Comparing z³: −4(c₁ + c₂) = 2, so c₁ + c₂ = −1/2. Comparing z²: 8 + 16c₁c₂ = 4, so c₁c₂ = −1/4. So c₁ and c₂ solve t² + t/2 − 1/4 = 0, t = (−1 ± √5)/4, and c₁ > 0 gives c₁ = (√5 − 1)/4.', 'One mark each for the sum, the product, the quadratic, and choosing the positive root.'],
  ]),
  ex2(CA, 'advanced', 'The region R is bounded by the graph of y = 2sin(x), for 0 ≤ x ≤ π, and the line y = 1, above the line.', [
    ['a', 'Find the x-coordinates of the points where the line meets the curve.', 1, 'x = π/6 and x = 5π/6', 'sin(x) = 1/2.'],
    ['b', 'Find the exact area of R.', 2, '2√3 − 2π/3', '∫ (2sin(x) − 1) dx from π/6 to 5π/6 = [−2cos(x) − x] = (√3 − 5π/6) − (−√3 − π/6). One mark for the integral, one for the value.'],
    ['c', 'R is rotated about the x-axis. Find the exact volume of the solid formed.', 3, 'π(2π/3 + √3)', 'V = π∫ (4sin²(x) − 1) dx = π∫ (1 − 2cos(2x)) dx from π/6 to 5π/6 = π[x − sin(2x)] = π(2π/3 + √3). One mark for the integral of outer² − inner², one for the identity, one for the value.'],
    ['d', 'Find the length of the curve y = 2sin(x) from x = 0 to x = π, correct to three decimal places.', 2, '5.270', 'Length = ∫ √(1 + 4cos²(x)) dx from 0 to π = 5.270. One mark for the integral, one for the value.'],
    ['e', 'Find the average value of 2sin(x) over [0, π].', 2, '4/π', '(1/π)∫ 2sin(x) dx from 0 to π = 4/π. One mark for the integral, one for the value.'],
  ]),
  ex2(VE, 'advanced', 'Two robots move across a warehouse floor. Their position vectors, in metres, t seconds after starting are rₐ(t) = 2ti + (4 − t)j and r_b(t) = (7 − t)i + (t − 1)j, t ≥ 0.', [
    ['a', 'Find the velocity of each robot.', 1, 'vₐ = 2i − j, v_b = −i + j', 'Differentiate.'],
    ['b', 'Show that the paths of the robots cross at the point (4, 2), and find when each robot is there.', 2, 'Robot A: t = 2; robot B: t = 3', 'rₐ(2) = 4i + 2j and r_b(3) = 4i + 2j. One mark for each time.'],
    ['c', 'Explain why the robots do not collide.', 1, 'They reach the crossing point at different times.', 'A collision needs rₐ(t) = r_b(t) for the same t.'],
    ['d', 'Show that the distance between the robots at time t is √(13t² − 62t + 74).', 2, 'r_b − rₐ = (7 − 3t)i + (2t − 5)j, and (7 − 3t)² + (2t − 5)² = 13t² − 62t + 74.', 'One mark for the difference vector, one for the expansion.'],
    ['e', 'Find the minimum distance between the robots and the time at which it occurs.', 2, '1/√13 ≈ 0.277 m at t = 31/13 s', 'The quadratic is least at t = 62/26 = 31/13, where it equals 1/13. One mark for the time, one for the distance.'],
    ['f', 'Find the angle between the velocities of the robots, correct to two decimal places.', 2, '161.57°', 'cos(θ) = (−2 − 1)/(√5 × √2) = −3/√10. One mark for the dot product, one for the angle.'],
  ]),
  ex2(VE, 'advanced', 'A cube has vertices O(0, 0, 0), A(2, 0, 0), C(0, 2, 0), D(0, 0, 2) and G(2, 2, 2), the vertex opposite O.', [
    ['a', 'Find the angle between the diagonal OG and the base of the cube (the plane z = 0), correct to two decimal places.', 2, '35.26°', 'sin(θ) = (OG · k)/|OG| = 2/(2√3) = 1/√3. One mark for the method, one for the angle.'],
    ['b', 'Find the Cartesian equation of the plane through A, C and D.', 2, 'x + y + z = 2', 'By symmetry a normal is (1, 1, 1), and A gives d = 2. One mark for the normal, one for the equation.'],
    ['c', 'Find the distance from G to the plane ACD.', 2, '4/√3', '|2 + 2 + 2 − 2|/√3. One mark for the formula, one for the value.'],
    ['d', 'Find the point where the diagonal OG meets the plane ACD.', 2, '(2/3, 2/3, 2/3)', 'Points on OG are (2t, 2t, 2t); 6t = 2 gives t = 1/3. One mark for the parametrisation, one for the point.'],
    ['e', 'Find the acute angle between the plane ACD and the base of the cube, correct to two decimal places.', 2, '54.74°', 'cos(θ) = |(1, 1, 1) · (0, 0, 1)|/√3 = 1/√3. One mark for the normals, one for the angle.'],
  ]),
  ex2(ST, 'advanced', 'The number of emails a help desk receives per hour, X, has mean 12 and standard deviation 4. X is not normally distributed.', [
    ['a', 'Random samples of 64 hours are taken. State the mean and standard deviation of the sample mean X̄.', 1, 'Mean 12, sd 0.5', '4/√64.'],
    ['b', 'Find, approximately, Pr(X̄ > 12.8), correct to four decimal places.', 2, '0.0548', 'By the central limit theorem X̄ is approximately N(12, 0.5²), so Pr(Z > 1.6) = 0.0548. One mark for invoking the CLT, one for the value.'],
    ['c', 'Find, approximately, the probability that more than 800 emails arrive in total over 64 hours, correct to four decimal places.', 2, '0.1587', 'The total has mean 768 and sd 4√64 = 32, so Pr(Z > 1) = 0.1587. One mark for the mean and sd, one for the value.'],
    ['d', 'After a spam filter is installed, a random sample of 64 hours has a mean of 11.2 emails per hour. Find the p-value for a test of H₀: μ = 12 against H₁: μ < 12, correct to four decimal places.', 2, '0.0548', 'z = (11.2 − 12)/0.5 = −1.6. One mark for the statistic, one for the p-value.'],
    ['e', 'State the conclusion at the 5% level of significance.', 1, 'Do not reject H₀: there is not enough evidence that the filter reduced the mean.', 'p > 0.05.'],
    ['f', 'Find the smallest sample size for which a sample mean of 11.2 would give a significant result at the 5% level.', 2, '68', 'Need (11.2 − 12)/(4/√n) ≤ −1.6449, so √n ≥ 8.2245 and n ≥ 67.6. One mark for the inequality, one for n.'],
  ]),
  ex2(FG, 'advanced', 'Let f: R → R, f(x) = 2tan⁻¹(x) − x. The graph of y = f(x) is shown below.', [
    ['a', 'Find f′(x).', 1, 'f′(x) = 2/(1 + x²) − 1 = (1 − x²)/(1 + x²)', 'd/dx(tan⁻¹(x)) = 1/(1 + x²).'],
    ['b', 'Find the exact coordinates of the stationary points and state their nature.', 2, '(1, π/2 − 1) local maximum; (−1, 1 − π/2) local minimum', 'f′(x) = 0 at x = ±1. One mark for the coordinates, one for the nature.'],
    ['c', 'Show that f is an odd function.', 1, 'f(−x) = 2tan⁻¹(−x) + x = −(2tan⁻¹(x) − x) = −f(x)', 'tan⁻¹ is odd.'],
    ['d', 'Find the x-intercepts of the graph of f, correct to three decimal places where appropriate.', 2, 'x = 0 and x = ±2.331', 'Solve 2tan⁻¹(x) = x with a CAS. One mark for 0, one for the other two.'],
    ['e', 'Find the area of the region enclosed by the graph of f and the x-axis for x ≥ 0, correct to three decimal places.', 2, '0.855', '∫ (2tan⁻¹(x) − x) dx from 0 to 2.331 = 0.855. One mark for the integral with correct terminals, one for the value.'],
    ['f', 'Find the values of k for which the equation f(x) = k has three real solutions.', 2, '1 − π/2 < k < π/2 − 1', 'Strictly between the local minimum and local maximum values. One mark for each endpoint.'],
  ], { diagram: { kind: 'function_graph', title: 'y = 2tan⁻¹(x) − x', xMin: -4, xMax: 4, yMin: -1.5, yMax: 1.5, xStep: 1, yStep: 0.5, curves: [{ points: sample(x => 2 * Math.atan(x) - x, -4, 4, 64) }], points: [{ x: 1, y: 0.571, label: '(1, π/2 − 1)' }, { x: -1, y: -0.571, label: '(−1, 1 − π/2)' }] } }),
]
