// VCE Specialist Mathematics Unit 3 & 4 — Practice set 1.
// Examination 1: 10 technology-free questions, 40 marks.
// Examination 2: Section A 20 multiple choice; Section B 6 extended questions, 60 marks.
import { SM, sample } from './sm-common.mjs'
const { ex1, mc, ex2, PF, FG, CX, CA, VE, ST } = SM(1)

export const ITEMS = [
  // ════════════════ Examination 1 — technology-free (40 marks) ════════════════
  ex1(PF, 'proficient', 'Prove by mathematical induction that 1 + 3 + 5 + … + (2n − 1) = n² for all n ∈ N.', [
    ['a', 'Show that the statement is true for n = 1.', 1, 'Left side = 1, right side = 1² = 1.', 'Both sides equal 1, so the statement holds for n = 1.'],
    ['b', 'Assume the statement is true for n = k. Show that it is then true for n = k + 1, and hence complete the proof.', 2, '1 + 3 + … + (2k − 1) + (2k + 1) = k² + 2k + 1 = (k + 1)².', 'Add the next term, 2(k + 1) − 1 = 2k + 1, to both sides of the assumption. The result is (k + 1)², so the statement is true for n = k + 1 whenever it is true for n = k; with part a, it is true for all n ∈ N by induction. One mark for using the assumption, one for the conclusion.'],
  ]),
  ex1(CX, 'proficient', 'Let z = 1 − √3i.', [
    ['a', 'Write z in polar form.', 1, 'z = 2cis(−π/3)', '|z| = √(1 + 3) = 2 and Arg(z) = −π/3 because z is in the fourth quadrant with tan⁻¹(√3) = π/3.'],
    ['b', 'Find z⁶.', 1, '64', 'By De Moivre’s theorem, z⁶ = 2⁶cis(−2π) = 64.'],
    ['c', 'Find the square roots of z, in polar form.', 2, '√2cis(−π/6) and √2cis(5π/6)', 'Square roots have modulus √2 and arguments (−π/3)/2 = −π/6 and −π/6 + π = 5π/6. One mark for each root.'],
  ]),
  ex1(FG, 'proficient', 'Let f(x) = (x² + 1)/(x − 1), x ≠ 1.', [
    ['a', 'Express f(x) in the form x + a + b/(x − 1), where a and b are integers.', 1, 'f(x) = x + 1 + 2/(x − 1)', 'x² + 1 = (x − 1)(x + 1) + 2.'],
    ['b', 'Write down the equations of the asymptotes of the graph of f.', 2, 'x = 1 and y = x + 1', 'The vertical asymptote comes from x − 1 = 0; as x → ±∞, 2/(x − 1) → 0, so y = x + 1 is an oblique asymptote. One mark for each.'],
    ['c', 'Find the coordinates of the stationary points of the graph of f.', 2, '(1 + √2, 2 + 2√2) and (1 − √2, 2 − 2√2)', 'f′(x) = 1 − 2/(x − 1)² = 0 gives (x − 1)² = 2, so x = 1 ± √2. Then f(1 + √2) = 2 + √2 + 2/√2 = 2 + 2√2 and f(1 − √2) = 2 − 2√2. One mark for the x-values, one for the coordinates.'],
  ]),
  ex1(CA, 'proficient', 'This question is about integration techniques.', [
    ['a', 'Using the substitution u = cos(x), evaluate ∫ sin(x)cos³(x) dx from x = 0 to x = π/2.', 2, '1/4', 'du = −sin(x) dx, and the terminals become u = 1 and u = 0: ∫ u³ du from 0 to 1 = 1/4. One mark for the transformed integral, one for the value.'],
    ['b', 'Use integration by parts to find ∫ xe²ˣ dx.', 2, '(x/2)e²ˣ − (1/4)e²ˣ + c', 'Let u = x and dv = e²ˣ dx, so v = (1/2)e²ˣ. Then ∫ xe²ˣ dx = (x/2)e²ˣ − ∫ (1/2)e²ˣ dx. One mark for the set-up, one for the answer.'],
  ]),
  ex1(CA, 'proficient', 'Consider the differential equation dy/dx = 2xy, where y(0) = 3.', [
    ['a', 'Solve the differential equation, expressing y in terms of x.', 3, 'y = 3e^(x²)', 'Separate: ∫ (1/y) dy = ∫ 2x dx, so logₑ|y| = x² + c and y = Ae^(x²). y(0) = 3 gives A = 3. One mark for separating, one for integrating, one for the constant.'],
    ['b', 'Find y when x = √(logₑ(2)).', 1, '6', 'y = 3e^(logₑ(2)) = 3 × 2 = 6.'],
  ]),
  ex1(VE, 'proficient', 'Let a = 2i − j + 2k and b = i + 2j − 2k.', [
    ['a', 'Find a · b.', 1, '−4', '2 × 1 + (−1) × 2 + 2 × (−2) = 2 − 2 − 4 = −4.'],
    ['b', 'Find the angle between a and b, in terms of an inverse circular function.', 1, 'cos⁻¹(−4/9)', '|a| = |b| = 3, so cos(θ) = −4/9.'],
    ['c', 'Find a × b.', 2, '−2i + 6j + 5k', 'a × b = ((−1)(−2) − 2 × 2)i − (2 × (−2) − 2 × 1)j + (2 × 2 − (−1) × 1)k = −2i + 6j + 5k. Check: it is perpendicular to a and b (dot products −4 − 6 + 10 = 0 and −2 + 12 − 10 = 0). One mark for method, one for the vector.'],
  ]),
  ex1(ST, 'proficient', 'The independent random variables X and Y have E(X) = 5, Var(X) = 4, E(Y) = 3 and Var(Y) = 9.', [
    ['a', 'Find E(2X − 3Y).', 1, '1', '2 × 5 − 3 × 3 = 10 − 9 = 1.'],
    ['b', 'Find Var(2X − 3Y).', 2, '97', 'For independent variables, Var(aX + bY) = a²Var(X) + b²Var(Y): 4 × 4 + 9 × 9 = 16 + 81 = 97. One mark for squaring the coefficients, one for adding the variances.'],
    ['c', 'Random samples of 16 values of X are taken. Find the standard deviation of the sample mean X̄.', 1, '1/2', 'sd(X̄) = σ/√n = 2/√16 = 1/2.'],
  ]),
  ex1(CA, 'proficient', 'The curve with equation x² + xy + y² = 7 passes through the point (1, 2).', [
    ['a', 'Use implicit differentiation to find dy/dx at the point (1, 2).', 3, '−4/5', '2x + y + x(dy/dx) + 2y(dy/dx) = 0, so dy/dx = −(2x + y)/(x + 2y). At (1, 2): −4/5. One mark for differentiating xy, one for rearranging, one for the value.'],
    ['b', 'Find the equation of the tangent to the curve at (1, 2).', 1, 'y = −(4/5)x + 14/5', 'y − 2 = −(4/5)(x − 1).'],
  ]),
  ex1(CX, 'proficient', 'Let P(z) = z³ − 2z² + 9z − 18, where z ∈ C.', [
    ['a', 'Show that z − 2 is a factor of P(z).', 1, 'P(2) = 8 − 8 + 18 − 18 = 0', 'By the factor theorem.'],
    ['b', 'Solve P(z) = 0 for z ∈ C.', 2, 'z = 2, 3i, −3i', 'P(z) = (z − 2)(z² + 9), and z² + 9 = 0 gives z = ±3i. One mark for the quadratic factor, one for the roots.'],
    ['c', 'The roots of P(z) = 0 are plotted in the complex plane. Find the area of the triangle with these points as vertices.', 1, '6', 'The vertices are 2, 3i and −3i: the base along the imaginary axis is 6 and the height is 2, so the area is 6.'],
  ]),
  ex1(CA, 'proficient', 'This question is about areas and volumes.', [
    ['a', 'The region bounded by the graph of y = √x, the x-axis and the line x = 4 is rotated about the x-axis. Find the volume of the solid formed.', 2, '8π', 'V = π∫ x dx from 0 to 4 = π × 8 = 8π. One mark for the integral, one for the value.'],
    ['b', 'Find the area of the region bounded by the graph of y = 1/(1 + x²), the x-axis and the lines x = 0 and x = 1.', 2, 'π/4', '∫ 1/(1 + x²) dx from 0 to 1 = tan⁻¹(1) − tan⁻¹(0) = π/4. One mark for the antiderivative, one for the value.'],
  ]),

  // ════════════════ Examination 2 — Section A (20 multiple choice) ════════════════
  mc(PF, 'developing', 'The contrapositive of the statement "If n² is even, then n is even" is',
    ['If n is odd, then n² is odd.', 'If n is even, then n² is even.', 'If n² is odd, then n is odd.', 'If n is odd, then n² is even.', 'n² is even and n is odd.'],
    'The contrapositive of "if P then Q" is "if not Q then not P". "If n is even, then n² is even" is the converse and "If n² is odd, then n is odd" is the inverse.'),
  mc(PF, 'developing', 'Which one of the following is a counterexample to the statement "for all real numbers x, x² > x"?',
    ['x = 1/2', 'x = 2', 'x = −1', 'x = 3', 'x = −1/2'],
    'A counterexample makes the statement false. For x = 1/2, x² = 1/4, which is not greater than 1/2. For each of the other values, x² > x is true.'),
  mc(FG, 'developing', 'The graph of y = (2x + 1)/(x − 3) has a horizontal asymptote with equation',
    ['y = 2', 'y = 0', 'y = 1/3', 'y = −1/3', 'x = 3'],
    '(2x + 1)/(x − 3) = 2 + 7/(x − 3), which approaches 2 as x → ±∞. x = 3 is the vertical asymptote.'),
  mc(FG, 'proficient', 'Given that 5x/((x − 1)(x + 4)) = A/(x − 1) + B/(x + 4), the values of A and B are',
    ['A = 1 and B = 4', 'A = 4 and B = 1', 'A = 1 and B = −4', 'A = −1 and B = 4', 'A = 5 and B = 0'],
    '5x = A(x + 4) + B(x − 1). Setting x = 1 gives 5 = 5A, so A = 1; setting x = −4 gives −20 = −5B, so B = 4.'),
  mc(FG, 'proficient', 'The maximum value of the function f(x) = 1/(x² − 4x + 5) is',
    ['1', '1/4', '1/5', '2', '5'],
    'x² − 4x + 5 = (x − 2)² + 1 has minimum value 1 at x = 2, so its reciprocal has maximum value 1.'),
  mc(CX, 'developing', 'If z = 2cis(π/3) and w = 3cis(π/6), then zw is equal to',
    ['6i', '6', '−6i', '5cis(π/2)', '6cis(π/18)'],
    'Multiply the moduli and add the arguments: zw = 6cis(π/2) = 6i.'),
  mc(CX, 'proficient', 'The set of points in the complex plane satisfying |z − 2i| = |z + 2| is the line with equation',
    ['y = −x', 'y = x', 'x = −1', 'y = 1', 'y = x + 2'],
    'The points are equidistant from 2i and −2, so they lie on the perpendicular bisector of the segment joining (0, 2) and (−2, 0). Algebraically, x² + (y − 2)² = (x + 2)² + y² simplifies to y = −x.'),
  mc(CX, 'proficient', 'The solutions of z⁴ = −16 are',
    ['2cis(±π/4) and 2cis(±3π/4)', '±2 and ±2i', '2cis(±π/2) and 2cis(π)', '4cis(±π/4) and 4cis(±3π/4)', '√2 ± √2i only'],
    '−16 = 16cis(π), so the solutions are 2cis((π + 2kπ)/4) for k = 0, 1, 2, 3: arguments π/4, 3π/4, −3π/4 and −π/4.'),
  mc(CA, 'developing', 'An antiderivative of 1/(x² + 9) is',
    ['(1/3)tan⁻¹(x/3)', 'tan⁻¹(x/3)', '(1/9)tan⁻¹(x/9)', '3tan⁻¹(3x)', 'logₑ(x² + 9)'],
    'Using ∫ a/(a² + x²) dx = tan⁻¹(x/a) with a = 3: ∫ 1/(x² + 9) dx = (1/3)tan⁻¹(x/3) + c.'),
  mc(CA, 'developing', 'For −1/2 < x < 1/2, the derivative of sin⁻¹(2x) with respect to x is',
    ['2/√(1 − 4x²)', '1/√(1 − 4x²)', '2/√(1 − 2x²)', '−2/√(1 − 4x²)', '2/(1 + 4x²)'],
    'd/dx(sin⁻¹(u)) = u′/√(1 − u²) with u = 2x and u′ = 2.'),
  mc(CA, 'proficient', 'Euler’s method with a step size of 0.1 is used to approximate the solution of dy/dx = x + y, y(0) = 1. The approximation to y(0.2) is',
    ['1.22', '1.1', '1.2', '1.242', '1.32'],
    'y₁ = 1 + 0.1(0 + 1) = 1.1, then y₂ = 1.1 + 0.1(0.1 + 1.1) = 1.22. The exact value is about 1.243.'),
  mc(CA, 'proficient', 'A particle moves in a straight line with velocity v(t) = 3t² − 12 m/s, t ≥ 0. The displacement of the particle, in metres, from t = 0 to t = 3 is',
    ['−9', '7', '9', '16', '23'],
    '∫ (3t² − 12) dt from 0 to 3 = 27 − 36 = −9. The particle reverses at t = 2, so the distance travelled is 16 + 7 = 23 m, which is a different quantity.'),
  mc(CA, 'proficient', 'The region under the graph of y = eˣ for 0 ≤ x ≤ 1 is rotated about the x-axis. The volume of the solid formed is',
    ['(π/2)(e² − 1)', 'π(e − 1)', 'π(e² − 1)', '(π/2)(e − 1)', '2π(e² − 1)'],
    'V = π∫ e²ˣ dx from 0 to 1 = (π/2)(e² − 1).'),
  mc(CA, 'proficient', 'A population P grows according to dP/dt = 0.2P(1 − P/500). The population is growing most rapidly when P is equal to',
    ['250', '100', '125', '400', '500'],
    'dP/dt = 0.2P − 0.0004P² is a quadratic in P with its maximum at P = 250, half the carrying capacity.'),
  mc(VE, 'developing', 'The vectors 2i + mj − k and i − 3j + 4k are perpendicular when m is equal to',
    ['−2/3', '2/3', '2', '−2', '6'],
    'The dot product 2 − 3m − 4 must be zero, so m = −2/3.'),
  mc(VE, 'proficient', 'The vector resolute of a = 3i + 4j in the direction of b = i + j is',
    ['(7/2)(i + j)', '7(i + j)', '(7/√2)(i + j)', '(1/2)(i + j)', '(7/25)(3i + 4j)'],
    'a · b = 7 and |b|² = 2, so the vector resolute is (a · b/|b|²)b = (7/2)(i + j).'),
  mc(VE, 'developing', 'The line with vector equation r(t) = (i + 2j + 3k) + t(2i − j + k), t ∈ R, passes through the point',
    ['(3, 1, 4)', '(2, −1, 1)', '(3, 3, 4)', '(1, 3, 2)', '(5, 0, 4)'],
    't = 1 gives (1 + 2, 2 − 1, 3 + 1) = (3, 1, 4). None of the other points gives a single consistent value of t.'),
  mc(VE, 'proficient', 'The Cartesian equation of the plane that passes through the point (1, 0, 3) and is perpendicular to the vector i + 2j − 2k is',
    ['x + 2y − 2z = −5', 'x + 2y − 2z = 5', 'x + 2y − 2z = 7', 'x − 2y + 2z = 7', 'x + 3z = 10'],
    'The plane is x + 2y − 2z = d, and substituting (1, 0, 3) gives d = 1 + 0 − 6 = −5.'),
  mc(ST, 'proficient', 'The masses of apples are normally distributed with mean 150 g and standard deviation 10 g. For random samples of 25 apples, Pr(X̄ > 154), correct to four decimal places, is',
    ['0.0228', '0.0456', '0.1587', '0.3446', '0.9772'],
    'sd(X̄) = 10/√25 = 2, so Pr(X̄ > 154) = Pr(Z > 2) = 0.0228. Using the population standard deviation gives Pr(Z > 0.4) = 0.3446.'),
  mc(ST, 'advanced', 'A random sample of 36 is used to test H₀: μ = 50 against H₁: μ > 50, where the population standard deviation is known to be 8. The sample mean is 52.4. The p-value, correct to four decimal places, is',
    ['0.0359', '0.0500', '0.0718', '0.3829', '0.9641'],
    'z = (52.4 − 50)/(8/√36) = 2.4/(4/3) = 1.8, and for a one-sided test p = Pr(Z > 1.8) = 0.0359. 0.0718 is the two-sided value.'),

  // ════════════════ Examination 2 — Section B (60 marks) ════════════════
  ex2(CX, 'advanced', 'Let u = 1 + i.', [
    ['a', 'Write u in polar form.', 1, 'u = √2cis(π/4)', '|u| = √2 and Arg(u) = π/4.'],
    ['b', 'Find u⁸.', 1, '16', '(√2)⁸cis(2π) = 16.'],
    ['c', 'Solve z³ = 8i for z ∈ C, giving the solutions in Cartesian form.', 3, 'z = √3 + i, −√3 + i, −2i', '8i = 8cis(π/2), so z = 2cis(π/6 + 2kπ/3): 2cis(π/6) = √3 + i, 2cis(5π/6) = −√3 + i and 2cis(−π/2) = −2i. One mark for the polar form of 8i, one for the arguments, one for converting.'],
    ['d', 'Find the area of the triangle whose vertices are the solutions to part c.', 2, '3√3', 'The solutions are equally spaced on a circle of radius 2, forming an equilateral triangle with side 2√3. Area = (√3/4)(2√3)² = 3√3. One mark for the side length, one for the area.'],
    ['e', 'Find the point on the circle |z| = 2 that is closest to u.', 1, '√2 + √2i', 'It lies on the ray from the origin through u: 2 × u/|u| = 2(1 + i)/√2.'],
    ['f', 'Show that u is a solution of z² − 2z + 2 = 0 and find the other solution.', 2, '(1 + i)² − 2(1 + i) + 2 = 2i − 2 − 2i + 2 = 0; the other solution is 1 − i.', 'A real quadratic has conjugate roots. One mark for the verification, one for the other root.'],
  ]),
  ex2(CA, 'advanced', 'A hot drink cools according to Newton’s law of cooling, dT/dt = −k(T − 20), where T °C is its temperature t minutes after it is poured and k is a positive constant. Initially T = 90, and after 10 minutes T = 55.', [
    ['a', 'Show that T = 20 + 70e^(−kt).', 2, 'Separating: ∫ 1/(T − 20) dT = −∫ k dt, so T − 20 = Ae^(−kt), and T(0) = 90 gives A = 70.', 'One mark for separating and integrating, one for the constant.'],
    ['b', 'Find the exact value of k.', 1, 'k = logₑ(2)/10', '55 = 20 + 70e^(−10k) gives e^(−10k) = 1/2.'],
    ['c', 'Find the time taken for the drink to cool to 30 °C, correct to two decimal places.', 2, '28.07 minutes', '70e^(−kt) = 10 gives t = logₑ(7)/k = 10logₑ(7)/logₑ(2) = 28.07. One mark for the equation, one for the value.'],
    ['d', 'Use Euler’s method with a step size of 5 minutes to estimate T when t = 5, correct to two decimal places.', 2, '65.74 °C', 'T(5) ≈ 90 + 5 × (−k)(90 − 20) = 90 − 350logₑ(2)/10 = 65.74. One mark for the gradient, one for the estimate.'],
    ['e', 'The exact value of T when t = 5 is about 69.50 °C. Explain why Euler’s method gives an underestimate here.', 1, 'The solution curve is concave up, so the tangent at t = 0 lies below the curve.', 'd²T/dt² = k²(T − 20) > 0, so the curve bends upward away from its tangent line.'],
    ['f', 'Find the time at which the drink is cooling at a rate of 1 °C per minute, correct to two decimal places.', 2, '22.79 minutes', 'k(T − 20) = 1 gives T − 20 = 1/k, so 70e^(−kt) = 10/logₑ(2) and t = 22.79. One mark for the equation, one for the value.'],
  ]),
  ex2(VE, 'advanced', 'The position vector of a ball, in metres, t seconds after it is hit is r(t) = 2ti + (4t − t²)j, 0 ≤ t ≤ 4, where i is a unit vector horizontally forward and j is a unit vector vertically up. The path of the ball is shown below.', [
    ['a', 'Find the velocity vector of the ball.', 1, 'ṙ(t) = 2i + (4 − 2t)j', 'Differentiate each component.'],
    ['b', 'Find the speed of the ball when t = 1.', 1, '2√2 m/s', '|2i + 2j| = √8 = 2√2.'],
    ['c', 'Find the maximum height reached by the ball and the time at which it occurs.', 2, '4 m at t = 2 s', 'The vertical velocity 4 − 2t is zero at t = 2, when the height is 8 − 4 = 4. One mark for the time, one for the height.'],
    ['d', 'Find the Cartesian equation of the path of the ball.', 2, 'y = 2x − x²/4', 'x = 2t gives t = x/2, and y = 4(x/2) − (x/2)². One mark for eliminating t, one for the equation.'],
    ['e', 'Find the horizontal distance travelled by the ball before it lands.', 1, '8 m', 'y = 0 again when t = 4, at x = 8.'],
    ['f', 'Find the angle between the initial direction of motion and the horizontal, correct to the nearest tenth of a degree.', 1, '63.4°', 'tan(θ) = 4/2 = 2, so θ = tan⁻¹(2) = 63.4°.'],
    ['g', 'Find the distance travelled by the ball along its path, correct to two decimal places.', 2, '11.83 m', 'Distance = ∫ |ṙ(t)| dt from 0 to 4 = ∫ √(4 + (4 − 2t)²) dt = 11.83. One mark for the integral, one for the value.'],
  ], { diagram: { kind: 'function_graph', title: 'Path of the ball', xMin: 0, xMax: 9, yMin: 0, yMax: 5, xStep: 1, yStep: 1, xLabel: 'x (m)', yLabel: 'y (m)', curves: [{ points: sample(x => 2 * x - (x * x) / 4, 0, 8, 32) }], points: [{ x: 4, y: 4, label: '(4, 4)' }, { x: 8, y: 0, label: '(8, 0)' }] } }),
  ex2(VE, 'advanced', 'The points A(1, 0, 2), B(3, 1, 1), C(2, 3, 4) and D(4, −1, 5) are the vertices of a tetrahedron.', [
    ['a', 'Find the vectors AB and AC.', 1, 'AB = 2i + j − k, AC = i + 3j + 2k', 'Subtract the position vector of A.'],
    ['b', 'Find AB × AC.', 2, '5i − 5j + 5k', '(1 × 2 − (−1) × 3)i − (2 × 2 − (−1) × 1)j + (2 × 3 − 1 × 1)k = 5i − 5j + 5k. One mark for method, one for the vector.'],
    ['c', 'Find the area of triangle ABC.', 1, '5√3/2', 'Area = (1/2)|AB × AC| = (1/2)(5√3).'],
    ['d', 'Find the Cartesian equation of the plane containing A, B and C.', 2, 'x − y + z = 3', 'A normal vector is i − j + k, and substituting A gives d = 1 − 0 + 2 = 3. (Check B: 3 − 1 + 1 = 3; C: 2 − 3 + 4 = 3.) One mark for the normal, one for the equation.'],
    ['e', 'Find the shortest distance from D to the plane ABC.', 2, '7√3/3', '|4 − (−1) + 5 − 3|/√3 = 7/√3 = 7√3/3. One mark for the formula, one for the value.'],
    ['f', 'Find the volume of the tetrahedron ABCD.', 2, '35/6', 'AD = 3i − j + 3k and AD · (AB × AC) = 15 + 5 + 15 = 35, so V = 35/6. (Equivalently (1/3) × area × height.) One mark for the scalar triple product, one for the volume.'],
  ]),
  ex2(ST, 'advanced', 'The masses of bags of rice labelled 1 kg are normally distributed with mean 1.02 kg and standard deviation 0.03 kg.', [
    ['a', 'Find the probability that a randomly chosen bag weighs less than 1 kg, correct to four decimal places.', 1, '0.2525', 'Pr(X < 1) = Pr(Z < −2/3) = 0.2525.'],
    ['b', 'Two bags are chosen at random. State the distribution of their total mass T, including its mean and standard deviation.', 2, 'T ~ N(2.04, 0.0424²): mean 2.04 kg, sd 0.03√2 ≈ 0.0424 kg', 'For independent bags, means add and variances add: Var(T) = 2 × 0.03² = 0.0018. One mark for the mean, one for the standard deviation.'],
    ['c', 'Find Pr(T > 2.1), correct to four decimal places.', 1, '0.0786', 'z = 0.06/0.0424 = 1.414, and Pr(Z > 1.414) = 0.0786.'],
    ['d', 'Random samples of 9 bags are taken. State the mean and standard deviation of the sample mean X̄.', 1, 'Mean 1.02 kg, sd 0.01 kg', 'sd(X̄) = 0.03/√9 = 0.01.'],
    ['e', 'After a new machine is installed, a random sample of 25 bags has a mean mass of 1.008 kg. Assuming the standard deviation is still 0.03 kg, test H₀: μ = 1.02 against H₁: μ < 1.02 by finding the p-value, correct to four decimal places.', 2, 'p = 0.0228', 'z = (1.008 − 1.02)/(0.03/5) = −2, so p = Pr(Z < −2) = 0.0228. One mark for the test statistic, one for the p-value.'],
    ['f', 'State the conclusion of the test at the 5% level of significance.', 1, 'Reject H₀: there is evidence that the mean mass has decreased.', 'p = 0.0228 < 0.05.'],
    ['g', 'Find an approximate 95% confidence interval for the new mean mass, correct to four decimal places.', 2, '(0.9962, 1.0198)', '1.008 ± 1.96 × 0.006. One mark for the standard error, one for the interval.'],
  ]),
  ex2(FG, 'advanced', 'Let f: R → R, f(x) = x/(x² + 1). The graph of y = f(x) is shown below.', [
    ['a', 'Show that f′(x) = (1 − x²)/(x² + 1)².', 1, 'Quotient rule: ((x² + 1) − 2x²)/(x² + 1)²', 'Simplify the numerator to 1 − x².'],
    ['b', 'Find the coordinates of the stationary points of the graph of f and state their nature.', 2, '(1, 1/2) maximum; (−1, −1/2) minimum', 'f′(x) = 0 when x = ±1. One mark for the coordinates, one for the nature.'],
    ['c', 'Given that f″(x) = 2x(x² − 3)/(x² + 1)³, find the coordinates of the points of inflection.', 2, '(0, 0), (√3, √3/4) and (−√3, −√3/4)', 'f″ changes sign at x = 0 and x = ±√3. One mark for the x-values, one for the coordinates.'],
    ['d', 'Find the area of the region bounded by the graph of f, the x-axis and the line x = 2.', 1, '(1/2)logₑ(5)', '∫ x/(x² + 1) dx from 0 to 2 = (1/2)logₑ(5).'],
    ['e', 'The region bounded by the graph of f, the x-axis and the line x = 1 is rotated about the x-axis. Find the exact volume of the solid formed.', 2, 'π²/8 − π/4', 'V = π∫ x²/(x² + 1)² dx from 0 to 1. Since d/dx(tan⁻¹(x) − x/(x² + 1)) = 2x²/(x² + 1)², V = (π/2)(π/4 − 1/2). One mark for the integral, one for the value.'],
    ['f', 'Find the area of the region between the line y = x and the graph of f for 0 ≤ x ≤ 1.', 2, '1/2 − (1/2)logₑ(2)', '∫ (x − x/(x² + 1)) dx from 0 to 1 = 1/2 − (1/2)logₑ(2) ≈ 0.153. One mark for the integral, one for the value.'],
  ], { diagram: { kind: 'function_graph', title: 'y = x/(x² + 1)', xMin: -4, xMax: 4, yMin: -0.8, yMax: 0.8, xStep: 1, yStep: 0.2, curves: [{ points: sample(x => x / (x * x + 1), -4, 4, 64) }], points: [{ x: 1, y: 0.5, label: '(1, 1/2)' }, { x: -1, y: -0.5, label: '(−1, −1/2)' }] } }),
]
