// VCE Specialist Mathematics Unit 3 & 4 — Practice set 2.
import { SM, sample } from './sm-common.mjs'
const { ex1, mc, ex2, PF, FG, CX, CA, VE, ST } = SM(2)

export const ITEMS = [
  // ════════════════ Examination 1 — technology-free (40 marks) ════════════════
  ex1(PF, 'proficient', 'This question is about direct proof and proof by induction.', [
    ['a', 'Prove that the sum of any two consecutive odd integers is divisible by 4.', 2, '(2k + 1) + (2k + 3) = 4k + 4 = 4(k + 1)', 'Write the integers as 2k + 1 and 2k + 3 for an integer k. The sum is 4 times the integer k + 1. One mark for the general form, one for the conclusion.'],
    ['b', 'Prove by mathematical induction that 5ⁿ − 1 is divisible by 4 for all n ∈ N.', 3, 'Base: 5 − 1 = 4. Step: 5ᵏ⁺¹ − 1 = 5(5ᵏ − 1) + 4, which is divisible by 4 if 5ᵏ − 1 is.', 'One mark for the base case, one for rewriting 5ᵏ⁺¹ − 1 in terms of 5ᵏ − 1, one for the conclusion.'],
  ]),
  ex1(CX, 'advanced', 'Consider the set of points z = x + yi in the complex plane that satisfy |z − 1| = 2|z + 1|.', [
    ['a', 'Show that these points satisfy (x + 5/3)² + y² = 16/9.', 3, '(x − 1)² + y² = 4((x + 1)² + y²) simplifies to 3x² + 10x + 3 + 3y² = 0, that is (x + 5/3)² + y² = 16/9.', 'One mark for squaring both moduli, one for expanding and collecting, one for completing the square.'],
    ['b', 'State the centre and radius of the circle.', 1, 'Centre −5/3 (the point (−5/3, 0)), radius 4/3', 'Read from the equation in part a.'],
  ]),
  ex1(FG, 'proficient', 'Let f(x) = 1/(x² − 1), x ≠ ±1.', [
    ['a', 'Write down the equations of the asymptotes of the graph of f.', 2, 'x = 1, x = −1 and y = 0', 'The denominator is zero at x = ±1, and f(x) → 0 as x → ±∞. One mark for the vertical asymptotes, one for the horizontal.'],
    ['b', 'Find the coordinates of the stationary point of the graph of f and state its nature.', 1, '(0, −1), a local maximum', 'f′(x) = −2x/(x² − 1)², which is zero only at x = 0; f′ changes from positive to negative there.'],
    ['c', 'State the range of f.', 1, '(−∞, −1] ∪ (0, ∞)', 'Between the asymptotes the graph reaches its maximum −1; outside them f takes every positive value.'],
  ]),
  ex1(CA, 'proficient', 'This question is about partial fractions and integration.', [
    ['a', 'Express 2/(x² − 1) in partial fractions.', 1, '1/(x − 1) − 1/(x + 1)', '2 = A(x + 1) + B(x − 1); x = 1 gives A = 1 and x = −1 gives B = −1.'],
    ['b', 'Evaluate ∫ 2/(x² − 1) dx from x = 2 to x = 3.', 2, 'logₑ(3/2)', '[logₑ|x − 1| − logₑ|x + 1|] from 2 to 3 = (logₑ(2) − logₑ(4)) − (0 − logₑ(3)) = logₑ(3/2). One mark for the antiderivative, one for the value.'],
    ['c', 'Find the derivative of x tan⁻¹(x).', 1, 'tan⁻¹(x) + x/(1 + x²)', 'Product rule.'],
  ]),
  ex1(CA, 'proficient', 'Consider the differential equation dy/dx = 1 + y², where y(0) = 0.', [
    ['a', 'Solve the differential equation for y in terms of x.', 3, 'y = tan(x)', '∫ 1/(1 + y²) dy = ∫ 1 dx gives tan⁻¹(y) = x + c, and y(0) = 0 gives c = 0. One mark for separating, one for integrating, one for the solution.'],
    ['b', 'State the largest interval containing x = 0 on which the solution is defined.', 1, '(−π/2, π/2)', 'tan(x) is continuous between its asymptotes at ±π/2.'],
  ]),
  ex1(VE, 'proficient', 'The line L passes through the points A(2, −1, 3) and B(4, 0, 1).', [
    ['a', 'Write down a vector equation of L.', 1, 'r(t) = (2i − j + 3k) + t(2i + j − 2k), t ∈ R', 'A direction vector is AB = 2i + j − 2k.'],
    ['b', 'Find the point where L meets the plane x + y + z = 1.', 2, '(−4, −4, 9)', '(2 + 2t) + (−1 + t) + (3 − 2t) = 1 gives 4 + t = 1, so t = −3. One mark for the equation in t, one for the point.'],
    ['c', 'Explain why L is not parallel to this plane.', 1, 'Its direction vector is not perpendicular to the normal: (2, 1, −2) · (1, 1, 1) = 1 ≠ 0.', 'A line is parallel to a plane exactly when its direction is perpendicular to the plane’s normal.'],
  ]),
  ex1(ST, 'proficient', 'The lengths of bolts made by a machine have mean 20 mm and standard deviation 0.4 mm. Nuts are made separately, with thickness mean 5 mm and standard deviation 0.3 mm.', [
    ['a', 'Random samples of 64 bolts are taken. Find the mean and standard deviation of the sample mean length X̄.', 1, 'Mean 20 mm, sd 0.05 mm', 'sd(X̄) = 0.4/√64 = 0.05.'],
    ['b', 'Given that Pr(Z < 2) ≈ 0.977, find the approximate value of Pr(X̄ > 20.1).', 1, '0.023', '(20.1 − 20)/0.05 = 2, so Pr(X̄ > 20.1) ≈ 1 − 0.977.'],
    ['c', 'A bolt and a nut are chosen independently. Find the mean and standard deviation of their combined length.', 2, 'Mean 25 mm, sd 0.5 mm', 'Means add; variances add: 0.16 + 0.09 = 0.25, so the sd is 0.5. One mark for the variance, one for the sd.'],
  ]),
  ex1(CA, 'proficient', 'A particle moves in a straight line with acceleration a = 6t − 4 m/s² at time t seconds. Initially its velocity is 2 m/s and its position is 0 m.', [
    ['a', 'Find the velocity v(t).', 1, 'v(t) = 3t² − 4t + 2', 'Antidifferentiate and use v(0) = 2.'],
    ['b', 'Find the position x(t).', 1, 'x(t) = t³ − 2t² + 2t', 'Antidifferentiate and use x(0) = 0.'],
    ['c', 'Show that the particle is never at rest.', 1, 'The discriminant of 3t² − 4t + 2 is 16 − 24 < 0, so v(t) ≠ 0.', 'v(t) is always positive.'],
    ['d', 'Find the position of the particle when t = 2.', 1, '4 m', '8 − 8 + 4 = 4.'],
  ]),
  ex1(CX, 'proficient', 'Given that z = 1 + 2i is a solution of z³ − 3z² + 7z − 5 = 0,', [
    ['a', 'find the other two solutions.', 2, '1 − 2i and 1', 'Coefficients are real, so 1 − 2i is also a solution. (z − 1 − 2i)(z − 1 + 2i) = z² − 2z + 5, and the product of the three roots is 5, so the third is 1. One mark for each.'],
    ['b', 'write the polynomial as a product of a linear factor and a real quadratic factor.', 1, '(z − 1)(z² − 2z + 5)', 'Expanding checks: z³ − 3z² + 7z − 5.'],
    ['c', 'show that the non-real solutions lie on the circle |z − 1| = 2.', 1, '|(1 ± 2i) − 1| = |±2i| = 2', 'Both are 2 units from 1.'],
  ]),
  ex1(CA, 'proficient', 'The part of the graph of y = x² for 0 ≤ x ≤ 2 is rotated about the y-axis.', [
    ['a', 'Find the volume of the solid formed by rotating the region bounded by the curve, the y-axis and the line y = 4 about the y-axis.', 2, '8π', 'x² = y, so V = π∫ y dy from 0 to 4 = 8π. One mark for the integral in y, one for the value.'],
    ['b', 'Find the area of the region bounded by the curve, the y-axis and the line y = 4.', 1, '16/3', '∫ √y dy from 0 to 4 = (2/3)(8) = 16/3.'],
  ]),

  // ════════════════ Examination 2 — Section A (20 multiple choice) ════════════════
  mc(PF, 'developing', 'The negation of the statement "for all real numbers x, x² ≥ 0" is',
    ['there exists a real number x such that x² < 0', 'for all real numbers x, x² < 0', 'there exists a real number x such that x² ≥ 0', 'for all real numbers x, x² ≤ 0', 'there is no real number x with x² ≥ 0'],
    'The negation of "for all x, P(x)" is "there exists x such that not P(x)".'),
  mc(PF, 'developing', 'Which one of the following is logically equivalent to "If a triangle is equilateral, then it is isosceles"?',
    ['If a triangle is not isosceles, then it is not equilateral.', 'If a triangle is isosceles, then it is equilateral.', 'If a triangle is not equilateral, then it is not isosceles.', 'A triangle is equilateral if and only if it is isosceles.', 'If a triangle is isosceles, then it is not equilateral.'],
    'A statement is equivalent to its contrapositive. The converse (isosceles ⇒ equilateral) and inverse are not equivalent to it.'),
  mc(FG, 'developing', 'The graph of y = (x² − 4)/(x² − 1) has asymptotes with equations',
    ['x = −1, x = 1 and y = 1', 'x = −2, x = 2 and y = 1', 'x = −1, x = 1 and y = 4', 'x = 1 and y = 0', 'x = −1, x = 1 and y = 0'],
    'The denominator is zero at x = ±1, and (x² − 4)/(x² − 1) = 1 − 3/(x² − 1) → 1 as x → ±∞.'),
  mc(FG, 'developing', 'The range of the function f: R → R, f(x) = |x − 2| − 3 is',
    ['[−3, ∞)', '[2, ∞)', '(−3, ∞)', 'R', '[−2, ∞)'],
    '|x − 2| ≥ 0, with equality at x = 2, so f(x) ≥ −3.'),
  mc(FG, 'proficient', 'Let f(x) = x² − 2x − 3. The graph of y = 1/f(x) has vertical asymptotes at',
    ['x = −1 and x = 3', 'x = 1 and x = −3', 'x = 1 only', 'x = −1, x = 1 and x = 3', 'x = 3 only'],
    'f(x) = (x − 3)(x + 1) is zero at x = 3 and x = −1, where 1/f(x) is undefined.'),
  mc(CX, 'developing', 'If z = 3 − 4i, then 1/z is equal to',
    ['(3 + 4i)/25', '(3 − 4i)/25', '(3 + 4i)/5', '1/3 − (1/4)i', '−3 + 4i'],
    'Multiply by the conjugate: 1/z = z̄/|z|² = (3 + 4i)/25.'),
  mc(CX, 'developing', 'The principal argument of (1 + i)/(1 − i) is',
    ['π/2', '0', 'π/4', '−π/2', 'π'],
    '(1 + i)/(1 − i) = (1 + i)²/2 = 2i/2 = i, whose argument is π/2.'),
  mc(CX, 'developing', 'The complex number with modulus 3 and principal argument −2π/3 is',
    ['−3/2 − (3√3/2)i', '−3/2 + (3√3/2)i', '3/2 − (3√3/2)i', '−(3√3/2) − (3/2)i', '(3√3/2) − (3/2)i'],
    '3cis(−2π/3) = 3(cos(2π/3) − i sin(2π/3)) = 3(−1/2 − (√3/2)i).'),
  mc(CA, 'developing', 'An antiderivative of x/(x² + 1) is',
    ['(1/2)logₑ(x² + 1)', 'logₑ(x² + 1)', '2logₑ(x² + 1)', 'tan⁻¹(x)', '(1/2)tan⁻¹(x²)'],
    'The numerator is half the derivative of the denominator.'),
  mc(CA, 'proficient', 'For −2 < x < 2, the derivative of cos⁻¹(x/2) is',
    ['−1/√(4 − x²)', '1/√(4 − x²)', '−2/√(4 − x²)', '−1/(2√(4 − x²))', '−1/√(1 − x²)'],
    'd/dx(cos⁻¹(u)) = −u′/√(1 − u²) with u = x/2: −(1/2)/√(1 − x²/4) = −1/√(4 − x²).'),
  mc(CA, 'developing', 'In the slope field for the differential equation dy/dx = y − x, the gradient of the line segment at the point (1, 3) is',
    ['2', '−2', '1', '3', '4'],
    'Substitute x = 1 and y = 3: 3 − 1 = 2.'),
  mc(CA, 'proficient', '∫ tan(x) dx from x = 0 to x = π/4 is equal to',
    ['(1/2)logₑ(2)', 'logₑ(2)', '1', '√2 − 1', '−(1/2)logₑ(2)'],
    'An antiderivative of tan(x) is −logₑ(cos(x)). The value is −logₑ(1/√2) + logₑ(1) = (1/2)logₑ(2).'),
  mc(CA, 'developing', 'A ball is thrown vertically upwards at 19.6 m/s and moves under gravity alone (acceleration −9.8 m/s²). The maximum height reached, in metres, is',
    ['19.6', '9.8', '2', '39.2', '4'],
    'Using v² = u² + 2as with v = 0: 0 = 19.6² − 2 × 9.8 × s, so s = 19.6.'),
  mc(CA, 'proficient', 'The length of the curve y = (2/3)x^(3/2) from x = 0 to x = 3 is',
    ['14/3', '2', '8', '16/3', '7/3'],
    'dy/dx = √x, so the length is ∫ √(1 + x) dx from 0 to 3 = (2/3)(4^(3/2) − 1) = 14/3.'),
  mc(VE, 'developing', 'The magnitude of the vector 2i − 3j + 6k is',
    ['7', '5', '11', '√13', '49'],
    '√(4 + 9 + 36) = √49 = 7.'),
  mc(VE, 'developing', 'The angle between the vectors i + j and j + k is',
    ['60°', '30°', '45°', '90°', '120°'],
    'The dot product is 1 and each vector has length √2, so cos(θ) = 1/2.'),
  mc(VE, 'proficient', 'A particle moves with position vector r(t) = cos(2t)i + sin(2t)j. The magnitude of its acceleration is',
    ['4', '1', '2', '8', '4t'],
    'r̈(t) = −4cos(2t)i − 4sin(2t)j = −4r(t), which has magnitude 4.'),
  mc(VE, 'advanced', 'The Cartesian equation of the plane containing the points (0, 0, 0), (1, 0, 1) and (0, 1, 1) is',
    ['x + y − z = 0', 'x + y + z = 0', 'x − y + z = 0', 'x + y − z = 1', 'x + y + z = 2'],
    'A normal is (1, 0, 1) × (0, 1, 1) = (−1, −1, 1), and the plane passes through the origin.'),
  mc(ST, 'proficient', 'X and Y are independent, with X ~ N(30, 4²) and Y ~ N(20, 3²). Pr(X − Y > 15), correct to four decimal places, is',
    ['0.1587', '0.0228', '0.0668', '0.3085', '0.8413'],
    'X − Y is normal with mean 10 and variance 16 + 9 = 25, so Pr(X − Y > 15) = Pr(Z > 1) = 0.1587. Subtracting the variances is the common error.'),
  mc(ST, 'proficient', 'A random sample of 36 is taken from a population with standard deviation 12, and the sample mean is 50. An approximate 95% confidence interval for the population mean is',
    ['(46.08, 53.92)', '(48.04, 51.96)', '(26.48, 73.52)', '(47.00, 53.00)', '(46.71, 53.29)'],
    'The standard error is 12/√36 = 2, so the interval is 50 ± 1.96 × 2.'),

  // ════════════════ Examination 2 — Section B (60 marks) ════════════════
  ex2(CX, 'advanced', 'Let w = −2 + 2√3i.', [
    ['a', 'Write w in polar form.', 1, 'w = 4cis(2π/3)', '|w| = √(4 + 12) = 4 and w is in the second quadrant with Arg(w) = π − π/3.'],
    ['b', 'Find w³.', 1, '64', '4³cis(2π) = 64.'],
    ['c', 'Find the three cube roots of w, in polar form.', 2, '∛4 cis(2π/9), ∛4 cis(8π/9), ∛4 cis(−4π/9)', 'Modulus 4^(1/3); arguments (2π/3 + 2kπ)/3 for k = 0, 1, −1. One mark for the modulus, one for the arguments.'],
    ['d', 'Find the maximum value of |z| for z in the set S = {z : |z − 2i| ≤ 2}.', 1, '4', 'S is a disc of radius 2 centred at 2i, so the farthest point from the origin is 4i.'],
    ['e', 'The line Im(z) = √3 Re(z) meets the circle |z − 2i| = 2 at the origin and at a point P. Find P.', 3, 'P = √3 + 3i', 'With z = x + √3xi: x² + (√3x − 2)² = 4 gives 4x² − 4√3x = 0, so x = 0 or x = √3. One mark for the substitution, one for solving, one for P.'],
    ['f', 'Find the area of the triangle with vertices 0, P and 4i.', 2, '2√3', 'With vertices (0, 0), (√3, 3) and (0, 4), the area is (1/2)|√3 × 4 − 0 × 3| = 2√3. One mark for method, one for the value.'],
  ]),
  ex2(CA, 'advanced', 'The number of fish, P, in a lake t years after they are introduced satisfies dP/dt = 0.4P(1 − P/2000), with P(0) = 200.', [
    ['a', 'Verify that P(t) = 2000/(1 + 9e^(−0.4t)) satisfies the differential equation and the initial condition.', 2, 'P(0) = 2000/10 = 200; P′(t) = 7200e^(−0.4t)/(1 + 9e^(−0.4t))², which equals 0.4P(1 − P/2000).', 'One mark for the initial condition, one for showing the derivative matches.'],
    ['b', 'Find the number of fish after 5 years, correct to the nearest whole number.', 1, '902', '2000/(1 + 9e⁻²) = 901.7.'],
    ['c', 'Find the time taken for the population to reach 1500, correct to two decimal places.', 2, '8.24 years', '1 + 9e^(−0.4t) = 4/3 gives e^(−0.4t) = 1/27, so t = logₑ(27)/0.4 = 8.24. One mark for the equation, one for the value.'],
    ['d', 'Find the maximum rate of growth of the population and the time at which it occurs, correct to two decimal places.', 2, '200 fish per year, at t = 5.49 years', 'dP/dt is greatest when P = 1000, giving 0.4 × 1000 × 0.5 = 200. P = 1000 when 9e^(−0.4t) = 1, t = logₑ(9)/0.4. One mark each.'],
    ['e', 'Use Euler’s method with a step size of 1 year to estimate P(1), and compare it with the exact value.', 2, 'Euler: 272; exact: 284.38', '200 + 1 × 0.4 × 200 × 0.9 = 272. Exact: 2000/(1 + 9e^(−0.4)) = 284.38. One mark for each.'],
    ['f', 'State the population in the long run.', 1, '2000', 'As t → ∞, e^(−0.4t) → 0.'],
  ]),
  ex2(CA, 'advanced', 'A car starts from rest and moves in a straight line. Its velocity v m/s at time t seconds satisfies dv/dt = 5 − 0.25v, with v(0) = 0.', [
    ['a', 'Show that v = 20(1 − e^(−0.25t)).', 3, '∫ 1/(5 − 0.25v) dv = ∫ 1 dt gives −4logₑ|5 − 0.25v| = t + c; v(0) = 0 then gives 5 − 0.25v = 5e^(−0.25t).', 'One mark for separating, one for integrating, one for using the initial condition.'],
    ['b', 'State the terminal velocity of the car.', 1, '20 m/s', 'As t → ∞, v → 20.'],
    ['c', 'Find the time taken to reach 15 m/s, correct to two decimal places.', 2, '5.55 s', 'e^(−0.25t) = 1/4 gives t = 4logₑ(4) = 5.545. One mark for the equation, one for the value.'],
    ['d', 'Find the distance travelled in the first 10 seconds, correct to two decimal places.', 2, '126.57 m', '∫ 20(1 − e^(−0.25t)) dt from 0 to 10 = 20(6 + 4e^(−2.5)) = 126.57. One mark for the integral, one for the value.'],
    ['e', 'Find the acceleration when v = 12, and the time at which the acceleration is half its initial value, correct to two decimal places.', 2, '2 m/s²; t = 2.77 s', 'a = 5 − 0.25 × 12 = 2. a = 5e^(−0.25t) = 2.5 gives t = 4logₑ(2) = 2.77. One mark each.'],
  ]),
  ex2(VE, 'advanced', 'The lines L₁ and L₂ have vector equations r₁(s) = (i + 2j) + s(i − j + 2k) and r₂(t) = (4i + 3k) + t(2i + j − k).', [
    ['a', 'Explain why L₁ and L₂ are not parallel.', 1, 'Their direction vectors (1, −1, 2) and (2, 1, −1) are not scalar multiples of each other.', 'Parallel lines have parallel direction vectors.'],
    ['b', 'Show that L₁ and L₂ do not intersect.', 2, 'The i and j components give s = 7/3 and t = −1/3, but then the k components are 14/3 and 10/3, which differ.', 'One mark for solving two component equations, one for showing the third fails. The lines are skew.'],
    ['c', 'Find a vector perpendicular to both lines.', 2, '−i + 5j + 3k', '(1, −1, 2) × (2, 1, −1) = (1 − 2, 4 + 1, 1 + 2) = (−1, 5, 3). One mark for method, one for the vector.'],
    ['d', 'Find the shortest distance between the lines, correct to three decimal places.', 2, '0.676', 'Project the vector between the given points, (3, −2, 3), onto the common perpendicular: |(3, −2, 3) · (−1, 5, 3)|/√35 = 4/√35 = 0.676. One mark for the method, one for the value.'],
    ['e', 'Find the acute angle between the directions of the lines, correct to the nearest tenth of a degree.', 2, '80.4°', 'cos(θ) = |2 − 1 − 2|/(√6 × √6) = 1/6. One mark for the dot product, one for the angle.'],
    ['f', 'Find the point on L₁ where s = 1.', 1, '(2, 1, 2)', 'Substitute s = 1.'],
  ]),
  ex2(ST, 'advanced', 'A manufacturer claims its batteries last 40 hours on average, with a standard deviation of 5 hours. A consumer group tests a random sample of 50 batteries and finds a mean lifetime of 38.8 hours. It tests H₀: μ = 40 against H₁: μ < 40, assuming σ = 5.', [
    ['a', 'Find the p-value of the test, correct to four decimal places.', 2, '0.0448', 'z = (38.8 − 40)/(5/√50) = −1.697, and Pr(Z < −1.697) = 0.0448. One mark for the test statistic, one for the p-value.'],
    ['b', 'State the conclusion of the test at the 5% level of significance.', 1, 'Reject H₀: there is evidence that the mean lifetime is less than 40 hours.', 'p < 0.05.'],
    ['c', 'State the conclusion at the 1% level of significance.', 1, 'Do not reject H₀.', 'p > 0.01.'],
    ['d', 'Find the critical value of the sample mean for this test at the 5% level of significance, correct to two decimal places.', 2, '38.84 hours', '40 − 1.6449 × 5/√50 = 38.84. One mark for the z value, one for the critical mean.'],
    ['e', 'Explain what a type I error would mean in this context.', 1, 'Concluding the mean lifetime is less than 40 hours when it really is 40 hours.', 'A type I error rejects a true null hypothesis.'],
    ['f', 'Suppose the true mean lifetime is 38.5 hours. Find the probability of a type II error for this test at the 5% level, correct to four decimal places.', 2, '0.3169', 'A type II error occurs when X̄ ≥ 38.837 even though μ = 38.5: Pr(Z ≥ (38.837 − 38.5)/0.7071) = 0.3169. One mark for the set-up, one for the value.'],
    ['g', 'State the distribution of the sample mean if H₀ is true.', 1, 'X̄ ~ N(40, 0.7071²)', 'sd(X̄) = 5/√50 ≈ 0.7071.'],
  ]),
  ex2(CA, 'advanced', 'Let f: [0, ∞) → R, f(x) = xe⁻ˣ. The graph of y = f(x) is shown below.', [
    ['a', 'Find f′(x), and the coordinates and nature of the stationary point.', 2, 'f′(x) = (1 − x)e⁻ˣ; (1, 1/e), a maximum', 'Product rule; f′ changes from positive to negative at x = 1. One mark for the derivative, one for the point.'],
    ['b', 'Given that f″(x) = (x − 2)e⁻ˣ, find the coordinates of the point of inflection.', 1, '(2, 2/e²)', 'f″ changes sign at x = 2.'],
    ['c', 'Use integration by parts to find the exact area of the region bounded by the graph of f, the x-axis and the line x = 2.', 2, '1 − 3/e²', '∫ xe⁻ˣ dx = −(x + 1)e⁻ˣ, so the area is (−3e⁻²) − (−1) = 1 − 3/e². One mark for the antiderivative, one for the value.'],
    ['d', 'The region in part c is rotated about the x-axis. Find the exact volume of the solid formed.', 2, '(π/4)(1 − 13e⁻⁴)', 'V = π∫ x²e⁻²ˣ dx from 0 to 2. An antiderivative is −e⁻²ˣ(x²/2 + x/2 + 1/4), giving π(1/4 − (13/4)e⁻⁴). One mark for the integral, one for the value.'],
    ['e', 'Find the length of the curve y = f(x) from x = 0 to x = 2, correct to three decimal places.', 2, '2.102', 'Length = ∫ √(1 + (1 − x)²e⁻²ˣ) dx from 0 to 2 = 2.102. One mark for the integral, one for the value.'],
    ['f', 'Explain why f(x) ≤ 1/e for all x ≥ 0.', 1, 'The only stationary point, at x = 1, is a maximum with value 1/e, and f(0) = 0 and f(x) → 0 as x → ∞.', 'So 1/e is the global maximum.'],
  ], { diagram: { kind: 'function_graph', title: 'y = xe⁻ˣ', xMin: 0, xMax: 6, yMin: 0, yMax: 0.45, xStep: 1, yStep: 0.1, curves: [{ points: sample(x => x * Math.exp(-x), 0, 6, 60) }], points: [{ x: 1, y: 0.368, label: '(1, 1/e)' }, { x: 2, y: 0.271, label: '(2, 2/e²)' }] } }),
]
