// VCE Specialist Mathematics Unit 3 & 4 — Practice set 3.
import { SM, sample } from './sm-common.mjs'
const { ex1, mc, ex2, PF, FG, CX, CA, VE, ST } = SM(3)

export const ITEMS = [
  // ════════════════ Examination 1 — technology-free (40 marks) ════════════════
  ex1(PF, 'proficient', 'This question is about proof by contradiction and counterexample.', [
    ['a', 'Prove by contradiction that √2 is irrational.', 3, 'Suppose √2 = p/q in lowest terms. Then p² = 2q², so p is even, p = 2m, and q² = 2m², so q is even too — contradicting lowest terms.', 'One mark for the assumption, one for deducing p even, one for the contradiction.'],
    ['b', 'Give a counterexample to the statement "for all real numbers a and b, if a² = b² then a = b".', 1, 'a = 1, b = −1', '1² = (−1)² but 1 ≠ −1.'],
  ]),
  ex1(CX, 'proficient', 'This question is about complex numbers.', [
    ['a', 'Solve z² + 4z + 13 = 0 for z ∈ C.', 1, 'z = −2 ± 3i', '(z + 2)² = −9.'],
    ['b', 'Let u = −2 + 3i. Find uū and u + ū.', 1, 'uū = 13, u + ū = −4', 'uū = |u|² = 4 + 9; u + ū = 2Re(u).'],
    ['c', 'Express (1 + i)¹⁰ in the form a + bi.', 2, '32i', '(1 + i)¹⁰ = (√2)¹⁰cis(10π/4) = 32cis(5π/2) = 32cis(π/2) = 32i. One mark for De Moivre, one for the answer.'],
  ]),
  ex1(FG, 'proficient', 'Let f: R \\ {0} → R, f(x) = x + 4/x.', [
    ['a', 'Write down the equations of the asymptotes of the graph of f.', 2, 'x = 0 and y = x', 'f is undefined at x = 0, and 4/x → 0 as x → ±∞. One mark for each.'],
    ['b', 'Find the coordinates of the stationary points and state their nature.', 2, '(2, 4) local minimum; (−2, −4) local maximum', 'f′(x) = 1 − 4/x² = 0 at x = ±2. One mark for the coordinates, one for the nature.'],
  ]),
  ex1(CA, 'proficient', 'This question is about techniques of integration.', [
    ['a', 'Using a suitable substitution, evaluate ∫ x√(x² + 1) dx from x = 0 to x = 1.', 2, '(2√2 − 1)/3', 'Let u = x² + 1: (1/2)∫ √u du from 1 to 2 = (1/3)(2^(3/2) − 1). One mark for the substitution, one for the value.'],
    ['b', 'Find ∫ cos²(x) dx.', 2, 'x/2 + sin(2x)/4 + c', 'Use cos²(x) = (1 + cos(2x))/2. One mark for the identity, one for the antiderivative.'],
  ]),
  ex1(CA, 'proficient', 'Consider the differential equation dy/dx = x/y, where y > 0 and y(0) = 2.', [
    ['a', 'Solve the differential equation, giving y in terms of x.', 3, 'y = √(x² + 4)', '∫ y dy = ∫ x dx gives y²/2 = x²/2 + c; y(0) = 2 gives y² = x² + 4, and y > 0. One mark each for separating, integrating and the constant.'],
    ['b', 'Find y when x = √5.', 1, '3', '√(5 + 4) = 3.'],
  ]),
  ex1(VE, 'proficient', 'Let a = i + 2j + 2k and b = 3i + 4k.', [
    ['a', 'Find the unit vector in the direction of b.', 1, '(3i + 4k)/5', '|b| = 5.'],
    ['b', 'Find the scalar resolute of a in the direction of b.', 1, '11/5', 'a · b̂ = (3 + 8)/5.'],
    ['c', 'Find the vector resolute of a perpendicular to b.', 2, '−(8/25)i + 2j + (6/25)k', 'a − (11/25)(3i + 4k). (Check: its dot product with b is −24/25 + 24/25 = 0.) One mark for the parallel component, one for subtracting.'],
  ]),
  ex1(ST, 'proficient', 'The random variable X has mean 10 and standard deviation 3.', [
    ['a', 'Let Y = 2X + 5. Find E(Y) and sd(Y).', 2, 'E(Y) = 25, sd(Y) = 6', 'E(aX + b) = aE(X) + b and sd(aX + b) = |a| sd(X). One mark each.'],
    ['b', 'Let S = X₁ + X₂ + X₃ + X₄ be the sum of four independent observations of X. Find E(S) and sd(S), and explain why sd(S) is not equal to sd(4X).', 2, 'E(S) = 40, sd(S) = 6; sd(4X) = 12 because the four observations are independent and their variances add (4 × 9 = 36), whereas 4X scales one variance by 16.', 'One mark for E(S) and sd(S), one for the explanation.'],
  ]),
  ex1(CA, 'advanced', 'A particle moves in a straight line so that its velocity v m/s when it is x m from the origin is v = 2x + 1. Initially the particle is at the origin.', [
    ['a', 'Find the acceleration of the particle when x = 1.', 2, '6 m/s²', 'a = v(dv/dx) = (2x + 1) × 2 = 6 at x = 1. One mark for a = v dv/dx, one for the value.'],
    ['b', 'Find x in terms of t.', 2, 'x = (e²ᵗ − 1)/2', 'dx/dt = 2x + 1 gives (1/2)logₑ(2x + 1) = t, using x(0) = 0. One mark for integrating, one for the rule.'],
  ]),
  ex1(CX, 'proficient', 'This question is about sets of points in the complex plane.', [
    ['a', 'Describe the set {z : |z − 3| ≤ |z + 1|} and give its Cartesian description.', 2, 'The half-plane Re(z) ≥ 1, that is x ≥ 1', 'Points at least as close to 3 as to −1 lie on or to the right of the perpendicular bisector x = 1. One mark for the boundary, one for the correct side.'],
    ['b', 'Find the complex numbers z that satisfy |z| = 2 and Re(z) = 1.', 2, 'z = 1 ± √3i', '1 + y² = 4 gives y = ±√3. One mark for the equation, one for both solutions.'],
  ]),
  ex1(CA, 'advanced', 'Let y = x²/4 − (1/2)logₑ(x), for x > 0.', [
    ['a', 'Show that 1 + (dy/dx)² = (x/2 + 1/(2x))².', 2, 'dy/dx = x/2 − 1/(2x), so 1 + (dy/dx)² = x²/4 + 1/2 + 1/(4x²) = (x/2 + 1/(2x))².', 'One mark for the derivative, one for the expansion.'],
    ['b', 'Hence find the length of the curve from x = 1 to x = e.', 2, '(e² + 1)/4', '∫ (x/2 + 1/(2x)) dx from 1 to e = (e²/4 + 1/2) − 1/4. One mark for the integral, one for the value.'],
  ]),

  // ════════════════ Examination 2 — Section A (20 multiple choice) ════════════════
  mc(PF, 'developing', 'The converse of the statement "If x > 2, then x² > 4" is',
    ['If x² > 4, then x > 2.', 'If x ≤ 2, then x² ≤ 4.', 'If x² ≤ 4, then x ≤ 2.', 'x > 2 and x² ≤ 4.', 'If x > 2, then x² ≤ 4.'],
    'The converse swaps hypothesis and conclusion. (It is false: x = −3 is a counterexample.)'),
  mc(PF, 'proficient', 'To prove that 2ⁿ > n for all n ∈ N by induction, the inductive step assumes that 2ᵏ > k and must then show that',
    ['2ᵏ⁺¹ > k + 1', '2ᵏ > k + 1', '2ᵏ⁺¹ > 2k', '2k > k', '2ᵏ⁺¹ > k'],
    'The inductive step shows that the statement for n = k implies the statement for n = k + 1.'),
  mc(FG, 'proficient', 'For x ≠ ±1, (x + 1)/(x² − 1) = 1/(x − 1). The graph of y = (x + 1)/(x² − 1) has',
    ['a vertical asymptote at x = 1 and a hole at x = −1', 'vertical asymptotes at x = 1 and x = −1', 'a vertical asymptote at x = −1 only', 'no vertical asymptotes', 'a hole at x = 1 and a vertical asymptote at x = −1'],
    'The factor x + 1 cancels, so x = −1 is a removable discontinuity; x = 1 still makes the denominator zero.'),
  mc(FG, 'proficient', 'The maximum value of the function f(x) = x/(x² + 4) is',
    ['1/4', '1/2', '1/8', '2', '4'],
    'f′(x) = (4 − x²)/(x² + 4)² is zero at x = 2, where f(2) = 2/8 = 1/4.'),
  mc(FG, 'proficient', 'Let f(x) = 3/(x − 1) + 2, x ≠ 1. The rule for the inverse function f⁻¹ is',
    ['f⁻¹(x) = 3/(x − 2) + 1', 'f⁻¹(x) = 3/(x − 1) + 2', 'f⁻¹(x) = (x − 1)/3 + 2', 'f⁻¹(x) = 3/(x + 2) − 1', 'f⁻¹(x) = 2/(x − 3) + 1'],
    'Swap x and y: x = 3/(y − 1) + 2, so y − 1 = 3/(x − 2).'),
  mc(CX, 'developing', 'If z = cis(θ), then z + 1/z is equal to',
    ['2cos(θ)', '2i sin(θ)', '1', '2', 'cis(2θ)'],
    '1/z = cis(−θ), and cis(θ) + cis(−θ) = 2cos(θ).'),
  mc(CX, 'developing', 'The sum of the six solutions of z⁶ = 1 is',
    ['0', '1', '6', '−1', '2'],
    'The solutions are equally spaced around the unit circle, so they sum to zero (the coefficient of z⁵ in z⁶ − 1 is 0).'),
  mc(CX, 'proficient', 'If z = 2 − 2i, then z⁴ is equal to',
    ['−64', '64', '−64i', '16', '64i'],
    'z = 2√2cis(−π/4), so z⁴ = 64cis(−π) = −64.'),
  mc(CA, 'developing', 'An antiderivative of sin³(x)cos(x) is',
    ['sin⁴(x)/4', 'cos⁴(x)/4', '−sin⁴(x)/4', '3sin²(x)cos²(x)', 'sin⁴(x)'],
    'Let u = sin(x): ∫ u³ du = u⁴/4.'),
  mc(CA, 'developing', '∫ xeˣ dx from x = 0 to x = 1 is equal to',
    ['1', 'e', 'e − 1', '2e − 1', '1/2'],
    'By parts, an antiderivative is (x − 1)eˣ, so the value is 0 − (−1) = 1.'),
  mc(CA, 'proficient', 'For x > 0, the derivative of tan⁻¹(1/x) is',
    ['−1/(1 + x²)', '1/(1 + x²)', '−1/x²', 'x²/(1 + x²)', '1/(x² − 1)'],
    'Chain rule: (1/(1 + 1/x²)) × (−1/x²) = −1/(x² + 1).'),
  mc(CA, 'proficient', 'Euler’s method with a step size of 0.5 is applied to dy/dx = x², y(1) = 2. The approximation to y(2) is',
    ['3.625', '2.5', '3.125', '4.333', '4.625'],
    'y(1.5) ≈ 2 + 0.5 × 1 = 2.5, then y(2) ≈ 2.5 + 0.5 × 2.25 = 3.625. The exact value is 13/3 ≈ 4.333.'),
  mc(CA, 'proficient', 'A particle moves in a straight line with velocity v(t) = 4 − t² m/s, for 0 ≤ t ≤ 3. The distance travelled, in metres, is',
    ['23/3', '3', '7/3', '16/3', '9'],
    'The particle stops at t = 2. Distance = ∫ (4 − t²) dt from 0 to 2 + |∫ (4 − t²) dt from 2 to 3| = 16/3 + 7/3. The displacement is only 3 m.'),
  mc(CA, 'developing', 'The solution of dy/dx = 3y with y(0) = 2 is',
    ['y = 2e³ˣ', 'y = 3e²ˣ', 'y = e³ˣ + 1', 'y = 2 + 3x', 'y = 6x'],
    'dy/dx = ky gives y = Ae^(kx), with A = y(0) = 2.'),
  mc(VE, 'developing', 'For the vectors a = 2i + j and b = i − 2j, which one of the following is true?',
    ['a and b are perpendicular.', 'a and b are parallel.', 'a · b = 4', '|a| = 5', 'a × b = 0'],
    'a · b = 2 − 2 = 0, so the vectors are perpendicular. |a| = √5.'),
  mc(VE, 'proficient', 'A unit vector perpendicular to both i + j and j + k is',
    ['(i − j + k)/√3', '(i + j + k)/√3', 'i − j + k', '(i + k)/√2', '(−i + j + k)/√3'],
    '(i + j) × (j + k) = i − j + k, which has length √3.'),
  mc(VE, 'developing', 'A particle has position vector r(t) = t²i + 2tj. Its speed when t = 1 is',
    ['2√2', '2', '4', '√5', '8'],
    'ṙ(t) = 2ti + 2j, so the speed at t = 1 is |2i + 2j| = 2√2.'),
  mc(VE, 'proficient', 'The distance from the point (1, 2, 3) to the plane 2x − y + 2z = 1 is',
    ['5/3', '1', '5', '6', '7/3'],
    '|2 − 2 + 6 − 1|/√(4 + 1 + 4) = 5/3.'),
  mc(ST, 'proficient', 'A random sample of 25 is taken from a population with standard deviation 10, and the sample mean is 70. An approximate 90% confidence interval for the population mean is',
    ['(66.71, 73.29)', '(66.08, 73.92)', '(68.36, 71.64)', '(67.44, 72.56)', '(53.55, 86.45)'],
    'The standard error is 10/√25 = 2 and z = 1.645 for 90% confidence, giving 70 ± 3.29. (66.08, 73.92) is the 95% interval.'),
  mc(ST, 'proficient', 'In a two-tailed test of a population mean, the test statistic is z = −2.2. The p-value, correct to four decimal places, is',
    ['0.0278', '0.0139', '0.0500', '0.4722', '0.9861'],
    'p = 2 × Pr(Z < −2.2) = 2 × 0.0139 = 0.0278.'),

  // ════════════════ Examination 2 — Section B (60 marks) ════════════════
  ex2(CX, 'advanced', 'Let P(z) = z⁴ − 2z³ + 6z² − 8z + 8, where z ∈ C.', [
    ['a', 'Show that 2i is a solution of P(z) = 0.', 1, '16 + 16i − 24 − 16i + 8 = 0', '(2i)⁴ = 16, (2i)³ = −8i and (2i)² = −4.'],
    ['b', 'Find all solutions of P(z) = 0.', 3, 'z = ±2i and z = 1 ± i', '±2i are roots, so z² + 4 is a factor; dividing gives z² − 2z + 2, with roots 1 ± i. One mark for the conjugate, one for the quadratic factor, one for its roots.'],
    ['c', 'Find the distance between the points representing 2i and 1 + i.', 1, '√2', '|2i − (1 + i)| = |−1 + i|.'],
    ['d', 'The four solutions lie on a circle. Find its equation in the form |z − a| = r.', 3, '|z + 1| = √5', 'By symmetry the centre (a, 0) is on the real axis. Equal distances to 2i and 1 + i: a² + 4 = (1 − a)² + 1 gives a = −1, and r² = 5. One mark for the symmetry argument, one for the centre, one for the radius.'],
    ['e', 'Find the value of (1 + i)⁸ + (2i)⁴.', 2, '32', '(1 + i)⁸ = ((1 + i)²)⁴ = (2i)⁴ = 16, and (2i)⁴ = 16. One mark for each term.'],
  ]),
  ex2(CA, 'advanced', 'Water drains from a tank so that the depth h metres after t minutes satisfies dh/dt = −0.2√h. Initially the depth is 16 m.', [
    ['a', 'Show that h = (4 − 0.1t)².', 3, '∫ h^(−1/2) dh = −0.2∫ dt gives 2√h = −0.2t + c; h(0) = 16 gives c = 8, so √h = 4 − 0.1t.', 'One mark each for separating, integrating and the constant.'],
    ['b', 'Find the time taken for the tank to empty.', 1, '40 minutes', '4 − 0.1t = 0.'],
    ['c', 'Find the depth after 10 minutes.', 1, '9 m', '(4 − 1)² = 9.'],
    ['d', 'Find the rate at which the depth is decreasing when h = 9.', 1, '0.6 m per minute', 'dh/dt = −0.2 × 3 = −0.6.'],
    ['e', 'Use Euler’s method with a single step of 10 minutes to estimate the depth after 10 minutes, and compare with part c.', 2, '8 m, an underestimate of 1 m', '16 + 10 × (−0.2 × 4) = 8. The rate of draining slows as h falls, so one long step overestimates the fall. One mark for the estimate, one for the comparison.'],
    ['f', 'Find the time at which the water drains at half its initial rate.', 2, '20 minutes', 'Initial rate 0.8; half is 0.4, so √h = 2 and h = 4, which happens when 4 − 0.1t = 2. One mark for h, one for t.'],
  ]),
  ex2(VE, 'advanced', 'A drone flies along a helix. Its position vector, in metres, t seconds after take-off is r(t) = 3cos(πt/6)i + 3sin(πt/6)j + (t/2)k, where k points vertically upwards.', [
    ['a', 'Find the velocity vector of the drone.', 1, 'ṙ(t) = −(π/2)sin(πt/6)i + (π/2)cos(πt/6)j + (1/2)k', 'Differentiate each component.'],
    ['b', 'Show that the drone flies at a constant speed, and find this speed correct to three decimal places.', 2, '(1/2)√(π² + 1) ≈ 1.648 m/s', '|ṙ|² = π²/4 (sin² + cos²) + 1/4, which does not depend on t. One mark for showing it is constant, one for the value.'],
    ['c', 'Find the acceleration vector and show that it is perpendicular to the velocity.', 2, 'r̈(t) = −(π²/12)cos(πt/6)i − (π²/12)sin(πt/6)j; ṙ · r̈ = 0', 'The i and j terms cancel in the dot product and r̈ has no k component. One mark each.'],
    ['d', 'Find the height gained in one complete revolution.', 1, '6 m', 'One revolution takes 12 seconds, and the height increases by t/2.'],
    ['e', 'Find the distance flown in one complete revolution, correct to two decimal places.', 2, '19.78 m', 'Constant speed × 12 = 6√(π² + 1). One mark for the method, one for the value.'],
    ['f', 'Find the angle between the drone’s velocity and the vertical, correct to two decimal places.', 2, '72.34°', 'cos(θ) = (1/2)/((1/2)√(π² + 1)) = 1/√(π² + 1). One mark for the dot product with k, one for the angle.'],
  ]),
  ex2(VE, 'advanced', 'The planes Π₁ and Π₂ have equations x + y + z = 6 and 2x − y + z = 3 respectively. The point A has coordinates (1, 1, 1).', [
    ['a', 'Find the acute angle between the planes, correct to two decimal places.', 2, '61.87°', 'The angle between the planes equals the angle between their normals: cos(θ) = (2 − 1 + 1)/(√3 × √6) = √2/3. One mark for the method, one for the angle.'],
    ['b', 'Find a vector equation of the line of intersection of the planes.', 3, 'r(t) = (3i + 3j) + t(2i + j − 3k)', 'The direction is (1, 1, 1) × (2, −1, 1) = (2, 1, −3). Setting z = 0 gives x + y = 6 and 2x − y = 3, so (3, 3, 0) is on both planes. One mark for the direction, one for the point, one for the equation.'],
    ['c', 'Find the shortest distance from A to Π₁.', 1, '√3', '|1 + 1 + 1 − 6|/√3 = 3/√3.'],
    ['d', 'Find the coordinates of the point on Π₁ closest to A.', 2, '(2, 2, 2)', 'Move from A along the normal: (1 + s, 1 + s, 1 + s) lies on Π₁ when 3 + 3s = 6. One mark for the parametric line, one for the point.'],
    ['e', 'Find the reflection of A in Π₁.', 1, '(3, 3, 3)', 'Go the same distance again beyond the foot of the perpendicular.'],
    ['f', 'Show that the line of intersection is perpendicular to the normal of Π₁.', 1, '(2, 1, −3) · (1, 1, 1) = 0', 'The line lies in Π₁, so its direction is perpendicular to Π₁’s normal.'],
  ]),
  ex2(ST, 'advanced', 'A café’s coffee machine dispenses volumes V mL that are normally distributed with standard deviation 8 mL. The supplier claims the mean volume is 250 mL.', [
    ['a', 'A random sample of 16 cups has a mean volume of 246 mL. Find the p-value for a test of H₀: μ = 250 against H₁: μ ≠ 250, correct to four decimal places.', 2, '0.0455', 'z = (246 − 250)/(8/4) = −2, and p = 2Pr(Z < −2) = 0.0455. One mark for the test statistic, one for the two-tailed p-value.'],
    ['b', 'State the conclusion at the 5% level of significance.', 1, 'Reject H₀: there is evidence the mean volume is not 250 mL.', 'p < 0.05.'],
    ['c', 'Find an approximate 95% confidence interval for μ, correct to two decimal places.', 2, '(242.08, 249.92)', '246 ± 1.96 × 2. One mark for the standard error, one for the interval.'],
    ['d', 'Explain how the confidence interval is consistent with the conclusion in part b.', 1, '250 lies outside the 95% interval, which matches rejecting H₀ at the 5% level in a two-tailed test.', 'A two-tailed test at level α rejects exactly the values outside the (1 − α) interval.'],
    ['e', 'Large cups L are normally distributed with mean 400 mL and standard deviation 10 mL, independent of small cups S (mean 250 mL, sd 8 mL). Find Pr(L > 1.5S), correct to four decimal places.', 2, '0.9453', 'L − 1.5S has mean 400 − 375 = 25 and variance 100 + 2.25 × 64 = 244, so Pr(L − 1.5S > 0) = Pr(Z > −25/√244) = 0.9453. One mark for the mean and variance, one for the probability.'],
    ['f', 'How many cups should be sampled so that the margin of error of an approximate 95% confidence interval for μ is at most 2 mL?', 2, '62', 'n ≥ (1.96 × 8/2)² = 61.5, so 62. One mark for the inequality, one for rounding up.'],
  ]),
  ex2(FG, 'advanced', 'Let f(x) = (x² − 3)/(x − 2), x ≠ 2. The graph of y = f(x) is shown below.', [
    ['a', 'Show that f(x) = x + 2 + 1/(x − 2), and write down the equations of the asymptotes.', 2, 'x² − 3 = (x − 2)(x + 2) + 1; asymptotes x = 2 and y = x + 2', 'One mark for the division, one for the asymptotes.'],
    ['b', 'Find the coordinates and nature of the stationary points.', 2, '(1, 2) local maximum; (3, 6) local minimum', 'f′(x) = 1 − 1/(x − 2)² = 0 at x = 1 and x = 3. One mark for the points, one for their nature.'],
    ['c', 'Find the axis intercepts.', 1, '(±√3, 0) and (0, 3/2)', 'x² = 3 and f(0) = −3/−2.'],
    ['d', 'Find the area of the region between the graph of f and its oblique asymptote for 3 ≤ x ≤ 5.', 2, 'logₑ(3)', '∫ 1/(x − 2) dx from 3 to 5 = logₑ(3) − logₑ(1). One mark for the integral, one for the value.'],
    ['e', 'State the range of f.', 1, '(−∞, 2] ∪ [6, ∞)', 'From the local maximum and minimum.'],
    ['f', 'Find the values of k for which the equation f(x) = k has no real solutions.', 2, '2 < k < 6', 'Horizontal lines strictly between the local maximum value and the local minimum value miss the graph. One mark for each endpoint with correct inequalities.'],
  ], { diagram: { kind: 'function_graph', title: 'y = (x² − 3)/(x − 2)', xMin: -3, xMax: 7, yMin: -6, yMax: 12, xStep: 1, yStep: 2, curves: [{ points: sample(x => (x * x - 3) / (x - 2), -3, 1.8, 48) }, { points: sample(x => (x * x - 3) / (x - 2), 2.12, 7, 49) }, { points: [[-3, -1], [7, 9]], dashed: true, label: 'y = x + 2' }], points: [{ x: 1, y: 2, label: '(1, 2)' }, { x: 3, y: 6, label: '(3, 6)' }] } }),
]
